refactor(cluster): update cluster to utilize two layers
Canadian-Geospatial-Platform/geoview pull request #1041
Opened 2023-05-02 20:59 UTC by DamonU2

Closes #1026
Closes #1000 

# Description

Clustering updated to be two separate layers.
Clusters automatically split at set zoom level (default 8).
Clusters keep same colours as their individual Points, LineStrings, or Polygons.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested on cluster.html with layers panel added. Checked toggle fuctionality and colour cohesion on all layers.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2023-05-03 20:31 UTC, jolevesq requested changes
We will need a twist for the legend. sub item visibility are not working and the clucster sub item visibility are toggling everything

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-:-NUY6dde3MNjoXw7QJnQ:b-woja1r)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/schema.json` line 1075 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUY5hUC6e-E4sSMLo8S:-NUY5hUC6e-E4sSMLo8T:b-o0s1aq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8235c6e3ba6d1ce5e5feb7be41c9f267115a7c0c/packages/geoview-core/schema.json#L1075)):*
> ```JSON
>       "minItems": 1,
>       "additionalProperties": false,
>       "items": { "anyOf": [{ "$ref": "#/definitions/TypeLayerGroupEntryConfig" }, { "$ref": "#/definitions/TypeOgcWmsLayerEntryConfig" }] }
> ```

Have you modified the format? Please run rush build... it should do preittier on the whole viewer files
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 343 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUY6r2NBbCj5MeiURJ-:-NUY6r2NBbCj5MeiURJ0:b810kvk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8235c6e3ba6d1ce5e5feb7be41c9f267115a7c0c/packages/geoview-core/src/core/components/legend/legend-item.tsx#L343)):*
> ```XML
>           (api.map(mapId).layer.registeredLayers[clusterLayerId].source as TypeVectorSourceInitialConfig)!.cluster!.splitZoom || 8;
>         if ((payload as NumberPayload).value >= splitZoom) setCanCluster(false);
>         if ((payload as NumberPayload).value < splitZoom) setCanCluster(true);
> ```

Set maybe zoom level 6 by default
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 448 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUYJ0hD325ZE1-2x73D:-NUYJ0hD325ZE1-2x73E:b-uplx8f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd2c937db9b851d870f941cb260e1bca4baa986e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L448)):*
> ```XML
>    * @param {string | TypeLayerEntryConfig | null} layerPathOrConfig Optional layer path or configuration.
>    */
>   toggleCluster(layerPathOrConfig: string | TypeLayerEntryConfig | null = this.activeLayer) {
> ```

Where is this located now?


<!-- Sent from Reviewable.io -->

2023-05-03 20:35 UTC, jolevesq reviewed
Details does not work as well, click on cluster or single send empty result. Click on item when zoomed in does not work

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-:-NUYJVKn3rfUuXTzShnk:bs214r6)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2023-05-05 20:33 UTC, DamonU2 reviewed
Sub items not showing was apparently a long running issue, looks like it goes back to at least March. I will open an issue for that. Cluster sub item can no longer be toggled, check box removed. Sub item visibility fixed, and persists between clustered and unclustered layers, as does opacity.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-:-NUh_aAe7BvCNcnjtsBg:b-ye8jcd)* status: 2 of 17 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 343 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUY6r2NBbCj5MeiURJ-:-NUhabEODcifV2grTcj-:b5tzd1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8235c6e3ba6d1ce5e5feb7be41c9f267115a7c0c/packages/geoview-core/src/core/components/legend/legend-item.tsx#L343)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Set maybe zoom level 6 by default
</blockquote></details>

Trying 7, 6 seemed low. Thoughts?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 448 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUYJ0hD325ZE1-2x73D:-NUhbV38CxJZrWzHtqYD:bhx0gzz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd2c937db9b851d870f941cb260e1bca4baa986e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L448)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Where is this located now?
</blockquote></details>

It is all done with the legend button handler.


<!-- Sent from Reviewable.io -->

2023-05-05 20:34 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041)* status: 2 of 17 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 1075 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUY5hUC6e-E4sSMLo8S:-NUhbp3T6INIk9_JiFRy:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8235c6e3ba6d1ce5e5feb7be41c9f267115a7c0c/packages/geoview-core/schema.json#L1075)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Have you modified the format? Please run rush build... it should do preittier on the whole viewer files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-08 11:42 UTC, jolevesq approved these changes
> Reviewed 11 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 343 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041#-NUY6r2NBbCj5MeiURJ-:-NUv7Qz665rqeuo3OX8n:bcncxq0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8235c6e3ba6d1ce5e5feb7be41c9f267115a7c0c/packages/geoview-core/src/core/components/legend/legend-item.tsx#L343)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Trying 7, 6 seemed low. Thoughts?
</blockquote></details>

Lets go with 7


<!-- Sent from Reviewable.io -->

2023-05-08 11:42 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2023-05-08 14:38 UTC, merged