feat(details-panel): More cleaning and adding more new feature to details
Canadian-Geospatial-Platform/geoview pull request #1298
Opened 2023-09-14 04:11 UTC by amir-azma

…ning

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1277 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2023-09-27 17:41 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMijyf18mPlRD0BFrn:-NfMijyf18mPlRD0BFro:bf15892) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L24)):*
> ```XML
>     noWrap: true,
>     '& .MuiListItemText-primary': {
>       font: 'normal normal 600 20px/27px Roboto, Helvetica, Arial, sans-serif',
> ```

Is this something we can move to the theme?


<!-- Sent from Reviewable.io -->

2023-09-27 17:47 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMjwqL5Etm7zZQk2D5:-NfMjwqM0pLlCZ-TIq8a:bjjyr9b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L60)):*
> ```XML
>   const { t } = useTranslation<string>();
>   const [checked, setChecked] = useState<boolean>(false);
>   const [checkedFeatures, setCheckedFeatures] = useState<TypeArrayOfFeatureInfoEntries>([]);
> ```

OPTIONAL: I think this should move to a store. @jolevesq what do you think?


<!-- Sent from Reviewable.io -->

2023-09-27 17:52 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMkRH92lpP45v7mqKw:-NfMkRH92lpP45v7mqKx:bwwqaih) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L102)):*
> ```XML
>     if (checkedFeatures.length !== 0) {
>       checkedFeatures.forEach((checkedFeature: TypeFeatureInfoEntry) => {
>         api.event.emit(featureHighlightPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_FEATURE, mapId, checkedFeature));
> ```

Since we are trying to get rid of `api.event.emit` from out code I suggest we move checkFeatured to a store. 
In that case we wont need to fire this event.
We can create IDetailsPanelState and use it to track the state of this panel.. including the selectedFeatures, checkedFeatures, checked**

Then if we want external users to know if anything happened then we can use eventProcessors to emit to the external world


<!-- Sent from Reviewable.io -->

2023-09-27 17:53 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMlMM93O_26uwmQbht:-NfMlMM93O_26uwmQbhu:b1p974g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L129)):*
> ```XML
>         if (index !== currentFeatureIndex) {
>           api.event.emit(
>             clearHighlightsPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_CLEAR, mapId, getUid(singleFeature.geometry))
> ```

api.event.emit is no longer wanted in the components code


<!-- Sent from Reviewable.io -->

2023-09-27 17:54 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-table.tsx` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMlasd3wnmj6fhZ3vw:-NfMlasd3wnmj6fhZ3vx:b-wjtgsg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-table.tsx#L28)):*
> ```XML
>     },
>     featureTableRow: {
>       ...(isOdd && { backgroundColor: '#F1F2F5' }),
> ```

Use backgroundColor: `primary.main`. (this is because the purple color is only for when using Vlad's template).

Just make sure to set the theme to `royal` in the map configurations.


<!-- Sent from Reviewable.io -->

2023-09-27 17:56 UTC, DamonU2 requested changes
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: all files reviewed, 16 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMg-l_1q-wINocWf7u:-NfMg-l_1q-wINocWf7v:b7o75jj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/public/locales/en/translation.json#L74)):*
> ```JSON
>     "nextFeatureBtn": "Next feature",
>     "previousFeatureBtn": "Previous feature",
>     "clearAllfeatures": "Clear all features",
> ```

"Clear all feature highlights" makes more sense to me here.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMgo__A_MwOCmMewIw:-NfMgo__A_MwOCmMewIx:bjw1pv4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L102)):*
> ```XML
>     if (checkedFeatures.length !== 0) {
>       checkedFeatures.forEach((checkedFeature: TypeFeatureInfoEntry) => {
>         api.event.emit(featureHighlightPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_FEATURE, mapId, checkedFeature));
> ```

This may be problematic as it could be re-highlighting the same feature repeatedly. We'll need an issue to add a check for this to the highlighting functions.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMSolS8qKnHcnZ6GuO:-NfMSolS8qKnHcnZ6GuP:bf61y0e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L129)):*
> ```XML
>         if (index !== currentFeatureIndex) {
>           api.event.emit(
>             clearHighlightsPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_CLEAR, mapId, getUid(singleFeature.geometry))
> ```

Could use: 
if (checkedFeatures.length === 0) api.event.emit(clearHighlightsPayload(EVENT\_NAMES.FEATURE\_HIGHLIGHT.EVENT\_HIGHLIGHT\_CLEAR, mapId, 'all'));
if you move this above  api.event.emit(featureHighlightPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_FEATURE, mapId, feature));
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 95 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMjT9X26LS9fniJaA0:-NfMjT9X26LS9fniJaA1:b-ts91tn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L95)):*
> ```XML
>           (feature.geometry as TypeGeometry)?.ol_uid
>         ) {
>           api.event.emit(clearHighlightsPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_CLEAR, mapId, getUid(feature.geometry)));
> ```

Better to clear all highlights and re-highlight the current one, at least until we make sure to not duplicate highlights


<!-- Sent from Reviewable.io -->

2023-09-27 17:57 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 128 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmRVj8IyUan38kB7J:-NfMmRVj8IyUan38kB7K:bik3apy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L128)):*
> ```XML
> 
>   useEffect(() => {
>     api.event.on(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_FEATURE, highlightCallbackFunction, mapId);
> ```

If we use state we wont need these events. 


<!-- Sent from Reviewable.io -->

2023-09-27 17:59 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmm9vCSWw6F6Ll98f:-NfMmm9vCSWw6F6Ll98g:bol1fge) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L220)):*
> ```XML
>                         sx={{ marginLeft: '20px' }}
>                         aria-label="clear-all-features"
>                         tooltip="details.clearAllfeatures"
> ```

Havent tried this, does it automatcally translate the text?


<!-- Sent from Reviewable.io -->

2023-09-27 18:03 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: all files reviewed, 18 unresolved discussions (waiting on @amir-azma and @cphelefu)

___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMijyf18mPlRD0BFrn:-NfMns1UAi7pE3m8lKLq:b-8ayu6x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L24)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Is this something we can move to the theme?
</blockquote></details>

Agree
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMjwqL5Etm7zZQk2D5:-NfMnkvJ9H5RwrrylXp5:bw6cmmp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L60)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

OPTIONAL: I think this should move to a store. @jolevesq what do you think?
</blockquote></details>

Yes this should move we need an issue for this
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMlMM93O_26uwmQbht:-NfMnSWH2ZZvYpPbhc_y:b-j47pp6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L129)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

api.event.emit is no longer wanted in the components code
</blockquote></details>

I will update the store for the highlight events and like you said it can be removed from the component.
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 128 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmRVj8IyUan38kB7J:-NfMnDEB63LoblTM2y03:blt6b71) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L128)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

If we use state we wont need these events.
</blockquote></details>

This will part of migration that I am working on.


<!-- Sent from Reviewable.io -->

2023-09-27 18:22 UTC, kaminderpal requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: all files reviewed, 20 unresolved discussions (waiting on @amir-azma and @cphelefu)

___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmm9vCSWw6F6Ll98f:-NfMrq4CCdujC59bJ_V3:bwtb2sw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L220)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Havent tried this, does it automatcally translate the text?
</blockquote></details>

it should be `tooltip={ t("details.clearAllfeatures") }`
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 232 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMsBc-DRZFuLOMaQ7D:-NfMsBc-DRZFuLOMaQ7E:bia5m04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L232)):*
> ```XML
>                       <IconButton
>                         aria-label="backward"
>                         tooltip="details.previousFeatureBtn"
> ```

it should be `tooltip={ t("details.previousFeatureBtn") }`
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 242 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMs4Z--uwfkdPMHbT7:-NfMs4Z--uwfkdPMHbT8:b-jiffx4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L242)):*
> ```XML
>                         sx={{ marginLeft: '20px' }}
>                         aria-label="forward"
>                         tooltip="details.nextFeatureBtn"
> ```

it should be `tooltip={ t("details.nextFeatureBtn") }`


<!-- Sent from Reviewable.io -->

2023-09-27 19:15 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: 6 of 11 files reviewed, 20 unresolved discussions (waiting on @cphelefu, @DamonU2, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMF5dkCrAVAIbhRb02:-NfMlzwa-9wGdB7hCZ34:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/public/locales/fr/translation.json#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Item suivant
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMF72n3lYivrfFDjqj:-NfMm6qHEnIk-Jtjt_wo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/public/locales/fr/translation.json#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Item précédent
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMFVic7rdNbAC4P66x:-NfMmO4rD2VNMbiJc3Sj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use paper from ui component not material
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMijyf18mPlRD0BFrn:-NfMmYVQAkN4mEpe6VxI:bcmio51) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L24)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Is this something we can move to the theme?
</blockquote></details>

I have this issue related to refactor and fix some style https://github.com/Canadian-Geospatial-Platform/geoview/issues/1334
I will make this change in that issue.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMjwqL5Etm7zZQk2D5:-NfMmllo0aDZ5uSgg7VS:b-spzpg4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L60)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

OPTIONAL: I think this should move to a store. @jolevesq what do you think?
</blockquote></details>

I think in this issue we don't use the new store we use with zustand, since I started this issue before we implement stores, I am implementing the existing states that used to be there before, but for future issue I will use it
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMkRH92lpP45v7mqKw:-NfMnm7M0CD7Y8WEsbuG:balhhym) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L102)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Since we are trying to get rid of `api.event.emit` from out code I suggest we move checkFeatured to a store. 
In that case we wont need to fire this event.
We can create IDetailsPanelState and use it to track the state of this panel.. including the selectedFeatures, checkedFeatures, checked**

Then if we want external users to know if anything happened then we can use eventProcessors to emit to the external world
</blockquote></details>

Not sure if we want to use store in this issue, @jolevesq  I think we wanted to merge this issue then we can enhance it later with stores
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMgo__A_MwOCmMewIw:-NfMoETy6vnx5FK0g-RE:bn3d2fh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L102)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This may be problematic as it could be re-highlighting the same feature repeatedly. We'll need an issue to add a check for this to the highlighting functions.
</blockquote></details>

I Agree, thanks
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMdZhX9xCeW-9JEBJd:-NfMoQ1E0ZLWcFhL2PA_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Double ss in comments to featuress
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMlMM93O_26uwmQbht:-NfMoVHV1yosmovdH4Qa:b9vojot) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I will update the store for the highlight events and like you said it can be removed from the component.
</blockquote></details>

I agree, thanks
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMSolS8qKnHcnZ6GuO:-NfMp1Dc0TND4nIOpwzM:b-6w3mhc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L129)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Could use: 
if (checkedFeatures.length === 0) api.event.emit(clearHighlightsPayload(EVENT\_NAMES.FEATURE\_HIGHLIGHT.EVENT\_HIGHLIGHT\_CLEAR, mapId, 'all'));
if you move this above  api.event.emit(featureHighlightPayload(EVENT_NAMES.FEATURE_HIGHLIGHT.EVENT_HIGHLIGHT_FEATURE, mapId, feature));
</blockquote></details>

I will connect with you about this to make sure.
___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 153 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMdTDY3fmDJeBEjEYK:-NfMosFCAU8TAX0NcTU4:bxoxqa2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L153)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this fixed? Do we have an issue?
</blockquote></details>

Good point, I will remove the comment, it's fixed.
___
*[`packages/geoview-core/src/core/compon [...]

2023-09-27 19:34 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: 5 of 11 files reviewed, 20 unresolved discussions (waiting on @cphelefu, @DamonU2, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMg-l_1q-wINocWf7u:-NfN5Ijs-yWjJdYMEgx-:b-pju9lb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/public/locales/en/translation.json#L74)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

"Clear all feature highlights" makes more sense to me here.
</blockquote></details>

Sure, I will use "Clear all feature highlights" 
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMFAxo5rNGovozuGzp:-NfN5o_c-0dFecCtm338:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/public/locales/fr/translation.json#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Déselctionner tout les items
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 14:17 UTC, DamonU2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-:-NfR8HOWBDhDIO6tACGt:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @amir-azma, @cphelefu, and @jolevesq)



<!-- Sent from Reviewable.io -->

2023-09-28 14:22 UTC, jolevesq approved these changes
> Reviewed 1 of 10 files at r1, 2 of 5 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMkRH92lpP45v7mqKw:-NfQaW7FELRApGayNqTI:b-wg7bja) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L102)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Not sure if we want to use store in this issue, @jolevesq  I think we wanted to merge this issue then we can enhance it later with stores
</blockquote></details>

Yew we merge first, store will be later


<!-- Sent from Reviewable.io -->

2023-09-28 14:23 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/feature-info-new.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMjwqL5Etm7zZQk2D5:-NfR9jjE44UEuobkyt5C:b6monce) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/feature-info-new.tsx#L60)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I think in this issue we don't use the new store we use with zustand, since I started this issue before we implement stores, I am implementing the existing states that used to be there before, but for future issue I will use it
</blockquote></details>

I think we need to implement it so we remove api.events from this code. Unless if you already have a task to do that for the rest of this new component.


<!-- Sent from Reviewable.io -->

2023-09-28 14:24 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 128 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmRVj8IyUan38kB7J:-NfRAMEa2BQQ7wEC-Voi:b3krq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L128)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

K


<!-- Sent from Reviewable.io -->

2023-09-28 14:25 UTC, kaminderpal approved these changes

2023-09-28 14:26 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1298#-NfMmm9vCSWw6F6Ll98f:-NfRAkveC2UlrAhk0sTo:bmco3vl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79930788eaaa171e17da25e9b467ab8bcee46ab5/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L220)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Yes it's automatically translates, inside the IconButton, we already have t(...) 
![image.png](https://files.reviewableusercontent.io/images/reviewable/138072320/eMdRbyBQBLxwo8hJLPL3nFNm/image.png)
</blockquote></details>

This cetralization can be a problem in the 


<!-- Sent from Reviewable.io -->

2023-09-28 14:31 UTC, merged