89 sample pages layers
Canadian-Geospatial-Platform/GeoView pull request #130
Opened 2021-03-02 19:56 UTC by melzeiny1980

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

2021-03-02 19:57 UTC, melzeiny1980 commented
closes #89

2021-03-02 21:13 UTC, jolevesq requested changes
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 2 of 8 files reviewed, 31 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/layers.html, line 87 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojRSm03vLZHM6Wf4z:-MUojRSm03vLZHM6Wf5-:b74di4x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L87)):*
> ```HTML
>                     <tr>
>                         <td>
>                             <a href="./index.html">Main</a><br /><a href="#HLYR1">1. WMS Layer</a><br /><a href="#HLYR2"
> ```

Put each a tag on is own line
___
*[public/templates/layers.html, line 97 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojVLJCQjSTysmysnA:-MUojVLJCQjSTysmysnB:b2wezg0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L97)):*
> ```HTML
>                 <tbody>
>                     <tr>
>                         <td>This page is used to showcase how the viewer may show different basemaps</td>
> ```

Not basemaps, layers
___
*[public/templates/layers.html, line 103 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojKUx6IcO8w7QJ2aZ:-MUojKUx6IcO8w7QJ2a_:b-hfu771) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L103)):*
> ```HTML
>         </div>
>         <div>
>             <h3 id="HLYR1">1.Adding WMS Layer</h3>
> ```

Remove Adding, you dot have this for the 3 other layers
___
*[public/templates/layers.html, line 114 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUoj_qA5W5k9buS4yLW:-MUoj_qA5W5k9buS4yLX:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L114)):*
> ```HTML
>             ></div>
>             <p>This map has a wms layer added from configuration.</p>
>             <p><strong>Configuraion Snippet:</strong></p>
> ```

Typo
___
*[public/templates/layers.html, line 130 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojjCs0l77Se10YlDy:-MUojjCs0l77Se10YlDz:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L130)):*
> ```HTML
>             ></div>
>             <p>This map has a Esri dynamic layer added from configuration.</p>
>             <p><strong>Configuraion Snippet:</strong></p>
> ```

Typo
___
*[public/templates/layers.html, line 143 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojlri6uhZT6on5Kx8:-MUojlri6uhZT6on5Kx9:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L143)):*
> ```HTML
>             ></div>
>             <p>This map has a Esri feature layer added from configuration.</p>
>             <p><strong>Configuraion Snippet:</strong></p>
> ```

Typo
___
*[public/templates/layers.html, line 156 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojob32kRxm-K-lUaK:-MUojob32kRxm-K-lUaL:bkr3c9k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L156)):*
> ```HTML
>             ></div>
>             <p>
>                 This map has one GeoJSON layer added from configuration. and another geoJSON Layer that can be added/removed by clikcing the
> ```

Remove capital L to second Layer. Remove that in layer that can be added
___
*[public/templates/layers.html, line 161 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUok5WO3i55eT6oT_31:-MUok5WO3i55eT6oT_32:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L161)):*
> ```HTML
>             <button id="add-geojson">Add GeoJSON Layer</button><button id="remove-geojson">Remove GeoJSON Layer</button> <br />
>             <label id="new-layer-id-label"> Added Layer ID : </label><label id="new-layer-id"></label>
>             <p><strong>Configuraion Snippet:</strong></p>
> ```

Typo
___
*[public/templates/layers.html, line 181 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokAIgEXUDwjw3_uWo:-MUokAIgEXUDwjw3_uWp:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L181)):*
> ```HTML
>             cgpv.init(function () {
>                 console.log('api is ready');
>                 // inject cofiguration snippet inside panel
> ```

Typo
___
*[public/templates/layers.html, line 181 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokIjj75VKdCcgZ1uW:-MUokIjj75VKdCcgZ1uX:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L181)):*
> ```HTML
>             cgpv.init(function () {
>                 console.log('api is ready');
>                 // inject cofiguration snippet inside panel
> ```

Carriage return before comment
___
*[public/templates/layers.html, line 195 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokF6yAQXavVvBR0iM:-MUokF6yAQXavVvBR0iN:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L195)):*
> ```HTML
>                 }
>             });
>             // find the button element by ID
> ```

Carriage return before comment
___
*[public/templates/layers.html, line 197 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokK5m4hp7UaWHwHd1:-MUokK5m4hp7UaWHwHd2:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L197)):*
> ```HTML
>             // find the button element by ID
>             var addGeoJSONButton = document.getElementById('add-geojson');
>             // add an event listener when a button is clicked
> ```

Carriage return before comment
___
*[public/templates/layers.html, line 208 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokW2X24--LpY6R1x2:-MUokW2X24--LpY6R1x3:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L208)):*
> ```HTML
>                 document.getElementById('new-layer-id').innerText = layerID;
>             });
>             // find the button element by ID
> ```

Carriage return before comment
___
*[public/templates/layers.html, line 210 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokXcAC6ywL7Ug-KsU:-MUokXcAC6ywL7Ug-KsV:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L210)):*
> ```HTML
>             // find the button element by ID
>             var removeGeoJSONButton = document.getElementById('remove-geojson');
>             // add an event listener when a button is clicked
> ```

Carriage return before comment
___
*[src/common/layers/esri-dynamic.ts, line 21 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUoloGA0P600z-zXTG1:-MUoloGA0P600z-zXTG2:b-mlvd64) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-dynamic.ts#L21) [...]

2021-03-03 14:11 UTC, yass0016 requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 2 of 8 files reviewed, 37 unresolved discussions (waiting on @melzeiny1980)

___
*[src/common/layers/esri-dynamic.ts, line 29 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPKiq9YujFZxUSWzG:-MUsPKiq9YujFZxUSWzH:b75xrr1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-dynamic.ts#L29)):*
> ```XML
>             attribution: '',
>         });
>         const layerid = new Date().getTime().toString();
> ```

I have few comments for this

Can you try moving generating the ID in the layers.ts class for each function when creating the layers then pass it down as the first parameter

Also now we have a generateId function, can you try using it instead of generating it from date?
___
*[src/common/layers/esri-feature.ts, line 25 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPj6_Bx-EWBkcbeqv:-MUsPj6_Bx-EWBkcbeqw:bnj7hl0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-feature.ts#L25)):*
> ```XML
>             url: layer.url,
>         });
>         const layerid = new Date().getTime().toString();
> ```

same as above
___
*[src/common/layers/geojson.ts, line 37 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPlPS9hXtqFr4hhxD:-MUsPlPS9hXtqFr4hhxE:b-5kwr88) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/geojson.ts#L37)):*
> ```XML
>      */
>     add(map: Map, layer: LayerConfig, layers: Array<LayerData>): string {
>         const layerid = new Date().getTime().toString();
> ```

same above
___
*[src/common/layers/layer.ts, line 145 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPpOI7eRYK85R3hh9:-MUsPpOI7eRYK85R3hhA:b-pc173i) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L145)):*
> ```XML
>     createGeoJSONLayer = (layerConfig: LayerConfig): string => {
>         const layerid = this.geoJSON.add(this.map, layerConfig, this.layers);
>         return layerid;
> ```

are we able to return the full created layerdata? I would like them to have access directly to the full layerdata from outside which includes the id and the layer itself if they want to modify it. We currently don't have a function to getLayerById, maybe you can add that as an extra?
___
*[src/common/layers/layer.ts, line 165 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsQ8XKA8O8Z8rQBIlA:-MUsQ8XL3SRfJ5naTgtY:bnj7hl0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L165)):*
> ```XML
>     createFeatureLayer = (layerConfig: LayerConfig): string => {
>         const layerid = this.esriFeature.add(this.map, layerConfig, this.layers);
>         return layerid;
> ```

same as above
___
*[src/common/layers/layer.ts, line 175 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsQAt_BacQ74QuQt2P:-MUsQAt_BacQ74QuQt2Q:bnj7hl0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L175)):*
> ```XML
>     createDynamicLayer = (layerConfig: LayerConfig): string => {
>         const layerid = this.esriDynamic.add(this.map, layerConfig, this.layers);
>         return layerid;
> ```

same as above


<!-- Sent from Reviewable.io -->

2021-03-03 14:16 UTC, melzeiny1980 commented
___
*[src/components/map/map.tsx, line 106 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUomGO3A48gDh-mZri8:-MUsRV0R8OLy6i5TIoSS:bu6e824) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/components/map/map.tsx#L106)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this? Why do you have basemap stuff in your PR?
</blockquote></details>

if i remove it , the wms tile layer will not show as it will load under the basemap


<!-- Sent from Reviewable.io -->

2021-03-03 14:42 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 2 of 8 files reviewed, 37 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/components/map/map.tsx, line 106 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUomGO3A48gDh-mZri8:-MUsXEvm6L_Aba8Wkc5Y:b-m7fak3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/components/map/map.tsx#L106)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

if i remove it , the wms tile layer will not show as it will load under the basemap
</blockquote></details>

ok I remember... Can you put this in the basemap component / class instead?
___
*[src/components/map/map.tsx, line 142 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsXKW-9Idiu9ae7iab:-MUsXKW-9Idiu9ae7iac:bb752ax) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/components/map/map.tsx#L142)):*
> ```XML
>                                 attribution={attribution}
>                                 opacity={basemapLayer.opacity}
>                                 pane="basemapsPane" // send basemap layers to the basmap pane
> ```

Typo


<!-- Sent from Reviewable.io -->

2021-03-03 19:09 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 37 unresolved discussions (waiting on @jolevesq, @melzeiny1980, @return, and @yass0016)

___
*[public/templates/layers.html, line 87 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojRSm03vLZHM6Wf4z:-MUsOAQB1SqIi3HoIYVU:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put each a tag on is own line
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 97 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojVLJCQjSTysmysnA:-MUsOG4E0HYp_7H4KVF2:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not basemaps, layers
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 103 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojKUx6IcO8w7QJ2aZ:-MUsOKIk-6oatUlHcTYV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove Adding, you dot have this for the 3 other layers
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 114 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUoj_qA5W5k9buS4yLW:-MUsOVUk1ZRG0s1qlKMM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L114)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 130 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojjCs0l77Se10YlDy:-MUsOaDh4C0sjwReRhPZ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 143 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojlri6uhZT6on5Kx8:-MUsOasfBp_O7S4dTOgv:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 156 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUojob32kRxm-K-lUaK:-MUsOvipBE9A__pDPJrV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L156)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove capital L to second Layer. Remove that in layer that can be added
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 161 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUok5WO3i55eT6oT_31:-MUsOwoo4UygmARCsRrf:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 181 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokAIgEXUDwjw3_uWo:-MUsP3gF2jwj7SRl_UEC:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L181)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 195 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokF6yAQXavVvBR0iM:-MUsPCcc5BuseRZqy1UV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L195)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 197 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokK5m4hp7UaWHwHd1:-MUsPDwa8tZavPKQEQE6:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L197)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[src/common/layers/esri-dynamic.ts, line 29 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPKiq9YujFZxUSWzG:-MUsamh98a8n7j-8t7uo:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-dynamic.ts#L29)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I have few comments for this

Can you try moving generating the ID in the layers.ts class for each function when creating the layers then pass it down as the first parameter

Also now we have a generateId function, can you try using it instead of generating it from date?
</blockquote></details>

Done.
___
*[src/common/layers/esri-dynamic.ts, line 38 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUolqTw2z_9lphxAhzu:-MUsan-_-6PXELJjyCun:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-dynamic.ts#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before return
</blockquote></details>

Done.
___
*[src/common/layers/esri-feature.ts, line 21 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUolnHA9g5rL2UU1k_L:-MUsb2fE52OCUlZ1v6Xv:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-feature.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add return param string @return {string} the layer id to function JSDOC
</blockquote></details>

Done.
___
*[src/common/layers/esri-feature.ts, line 25 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPj6_Bx-EWBkcbeqv:-MUsb2SgEDBcpauZsVrb:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-feature.ts#L25)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[src/common/layers/esri-feature.ts, line 34 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUolDeu-O6qPJo7xhW-:-MUsb1hPCDDgbaQS5QfU:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-feature.ts#L34)): [...]

2021-03-03 19:11 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 37 unresolved discussions (waiting on @jolevesq, @return, and @yass0016)

___
*[public/templates/layers.html, line 181 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokIjj75VKdCcgZ1uW:-MUtUfLl5J57aKE4Bn5h:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L181)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 208 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokW2X24--LpY6R1x2:-MUtUgKOEwxFPIDiKYBD:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L208)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 210 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokXcAC6ywL7Ug-KsU:-MUtUgZj8Zv7vmCn6TZY:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[src/common/layers/esri-dynamic.ts, line 21 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUoloGA0P600z-zXTG1:-MUtUiSk9CxSKHxPYt-1:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/esri-dynamic.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add return param string @return {string} the layer id to function JSDOC
</blockquote></details>

Done.
___
*[src/common/layers/layer.ts, line 145 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPpOI7eRYK85R3hh9:-MUtUjlr1L5ZZHmdnV09:b-zbflo5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L145)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

are we able to return the full created layerdata? I would like them to have access directly to the full layerdata from outside which includes the id and the layer itself if they want to modify it. We currently don't have a function to getLayerById, maybe you can add that as an extra?
</blockquote></details>

sure, getLayerById would be very useful for more operations on the layers. should that  be part of this PR ? or should i create a new issue for it ?


<!-- Sent from Reviewable.io -->

2021-03-03 19:23 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 14 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/templates/layers.html, line 195 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUokF6yAQXavVvBR0iM:-MUtVkjA4M1hCtbv8hzi:b33ykl4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/public/templates/layers.html#L195)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Carriage return not done
___
*[src/common/basemap.ts, line 122 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW5g70lsg7OcTXej_:-MUtW5g70lsg7OcTXeja:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L122)):*
> ```XML
>         }
>     };
> ```

Carriage return before comment
___
*[src/common/basemap.ts, line 171 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW1WG1dwcaLifl23y:-MUtW1WG1dwcaLifl23z:b-zng5n) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L171)):*
> ```XML
>         const basemapLayers: BasemapLayer[] = [];
>         let mainBasemapOpacity = 1;
> ```

Carriage return before if
___
*[src/common/basemap.ts, line 212 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW8iWEDnTbqAfymP4:-MUtW8iWEDnTbqAfymP5:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L212)):*
> ```XML
>     loadDefaultBasemaps = (): void => {
>         const layers = this.getBasemapLayers();
> ```

Carriage return before comment
___
*[src/common/basemap.ts, line 225 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtWBN28j-rE_REVKwo:-MUtWBN28j-rE_REVKwp:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/84dac3df9fd9947ec27cb907886e90a2abfb5705/src/common/basemap.ts#L225)):*
> ```XML
> 
>     // createBasemapPane = (): string => {
> ```

Remove dead code
___
*[src/common/map-viewer.ts, line 84 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtWMn_8a5amSzs3tWM:-MUtWMn_8a5amSzs3tWN:b-qtgsd4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/84dac3df9fd9947ec27cb907886e90a2abfb5705/src/common/map-viewer.ts#L84)):*
> ```XML
>         this.buttonPanel = new ButtonPanel(mapInstance.map);
> 
>         // create newpane to host basemap layers
> ```

Space between new and pane
___
*[src/common/layers/layer.ts, line 145 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPpOI7eRYK85R3hh9:-MUtXAaV8-vJdQHUdA2M:bqfxvw7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L145)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

sure, getLayerById would be very useful for more operations on the layers. should that  be part of this PR ? or should i create a new issue for it ?
</blockquote></details>

If you can add it as part of this one would be nice. It need to be quick because it would be better you do not have to rebase and I have a PR standing. So if too long, create an issue for it.
___
*[src/components/map/map.tsx, line 142 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsXKW-9Idiu9ae7iab:-MUtXxF-5pMqq24P_llX:b-k1zlqh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/components/map/map.tsx#L142)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is this line still needed?


<!-- Sent from Reviewable.io -->

2021-03-03 19:43 UTC, melzeiny1980 commented
___
*[src/common/layers/layer.ts, line 145 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPpOI7eRYK85R3hh9:-MUtbLgg3LXdQdbBWulN:b2txedo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L145)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If you can add it as part of this one would be nice. It need to be quick because it would be better you do not have to rebase and I have a PR standing. So if too long, create an issue for it.
</blockquote></details>

if there is no differnce i would like to create a separate issue for this. i do not want to run the risk of rebasing again as this PR changes are in many files


<!-- Sent from Reviewable.io -->

2021-03-03 19:46 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 14 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/common/basemap.ts, line 122 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW5g70lsg7OcTXej_:-MUtapQqBgl0qz-SK7Ch:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L122)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 171 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW1WG1dwcaLifl23y:-MUtaowD-QZcjFLj5tNS:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L171)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before if
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 212 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtW8iWEDnTbqAfymP4:-MUtc6Bu8NUx9IDw9akn:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6cc63408a6a9714586a4e5355756234e651c25b4/src/common/basemap.ts#L212)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 225 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtWBN28j-rE_REVKwo:-MUtayXj3Kmw0xbE-CEh:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/84dac3df9fd9947ec27cb907886e90a2abfb5705/src/common/basemap.ts#L225)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.
___
*[src/common/map-viewer.ts, line 84 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtWMn_8a5amSzs3tWM:-MUtbEBG4c87ElC4eU4u:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/84dac3df9fd9947ec27cb907886e90a2abfb5705/src/common/map-viewer.ts#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space between new and pane
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 142 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsXKW-9Idiu9ae7iab:-MUtbx46AP53HjW6v3jt:bf8zygx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/components/map/map.tsx#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this line still needed?
</blockquote></details>

yes , this is where the layer adding happen. however this line should have changed now to 
pane={basemapLayer.basemapPaneName}


<!-- Sent from Reviewable.io -->

2021-03-03 19:53 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/common/layers/layer.ts, line 145 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUsPpOI7eRYK85R3hh9:-MUtdDzdEU9O8fJYAcKX:b-ktnne6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L145)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

if there is no differnce i would like to create a separate issue for this. i do not want to run the risk of rebasing again as this PR changes are in many files
</blockquote></details>

Perfect, can you create a new issue now so we do not loose track.


<!-- Sent from Reviewable.io -->

2021-03-03 19:54 UTC, yass0016 reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 20:03 UTC, jolevesq requested changes
> Reviewed 1 of 8 files at r1, 5 of 9 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 7 of 10 files reviewed, 9 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/layers/layer.ts, line 143 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtfy1IBtJcly_4tvuh:-MUtfy1IBtJcly_4tvui:bd0q7g2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L143)):*
> ```XML
>      * @param layerConfig the layer configuration
>      */
>     createGeoJSONLayer = (layerConfig: LayerConfig): string => {
> ```

Add JSDOC return param
___
*[src/common/layers/layer.ts, line 151 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtg0Ns2BAzUCFIuASA:-MUtg0Ns2BAzUCFIuASB:bd0q7g2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L151)):*
> ```XML
>      * Create a new WMS layer on the map
>      *
>      * @param layerConfig the layer configuration
> ```

Add JSDOC return param
___
*[src/common/layers/layer.ts, line 161 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtg1GT9EjUKRAPB0gG:-MUtg1GT9EjUKRAPB0gH:bd0q7g2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L161)):*
> ```XML
>      * Create a new feature layer on the map
>      *
>      * @param layerConfig the layer configuration
> ```

Add JSDOC return param
___
*[src/common/layers/layer.ts, line 171 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtg2My5H8KYsFI1EYm:-MUtg2My5H8KYsFI1EYn:bd0q7g2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/17c6c3c35f97722772ad1001288eb2866398f50e/src/common/layers/layer.ts#L171)):*
> ```XML
>      * Create a new dynamic layer on the map
>      *
>      * @param layerConfig the layer configuration
> ```

Add JSDOC return param


<!-- Sent from Reviewable.io -->

2021-03-03 20:05 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 7 of 10 files reviewed, 10 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 119 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130#-MUtgJtD5HPtfmTPYRm_:-MUtgJtEAEpWQ1Ffzx8w:b-65m55h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6629180b31282c0b7b0dfe32d8ae6966818dfdbc/src/common/basemap.ts#L119)):*
> ```XML
>      * @param {string} mapId the map id
>      */
>     init = (mapId: string, basemapsPaneName: string): void => {
> ```

Add JSDOC


<!-- Sent from Reviewable.io -->

2021-03-03 21:04 UTC, jolevesq reviewed
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 21:05 UTC, jolevesq approved these changes
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: all files reviewed, 5 unresolved discussions (waiting on @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 21:05 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: all files reviewed, 5 unresolved discussions (waiting on @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 21:05 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: all files reviewed, 5 unresolved discussions (waiting on @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 21:05 UTC, yass0016 reviewed
> Reviewed 1 of 8 files at r1, 6 of 9 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: all files reviewed, 5 unresolved discussions (waiting on @yass0016)



<!-- Sent from Reviewable.io -->

2021-03-03 21:07 UTC, yass0016 approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/130)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-03 21:07 UTC, merged