Using store for layers
Canadian-Geospatial-Platform/geoview pull request #1456
Opened 2023-11-02 17:53 UTC by cphelefu

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2023-11-03 19:58 UTC, jolevesq requested changes
> Reviewed 18 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 18 of 20 files reviewed, 23 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/layers/layers.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLh6kPCufPph6p-wbi:-NiLh6kPCufPph6p-wbj:bb5kmas) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/layers.tsx#L2)):*
> ```XML
> import { styled, useTheme } from '@mui/material';
> import React, { useEffect } from 'react';
> ```

React should come first, why do you import the whole React?
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgOaI44JPMPsnZP4y:-NiLgOaI44JPMPsnZP4z:b-gxrox4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/types.ts#L85)):*
> ```XML
>   children: TypeLegendLayer[];
> 
>   opacity?: number; // Does every layer have opacity?
> ```

Yes it should but we may want to restrict the usage so we can keep optional
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgajg849g8DPDxWXG:-NiLgajg849g8DPDxWXH:b-k7xkgp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx#L1)):*
> ```XML
> import { Button, useTheme } from '@mui/material';
> ```

useTheme is from ;@mui/material/styles I think. If not I have error in my code

Button should come from ui
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgjPY1fwr7tM6eCgV:-NiLgjPY1fwr7tM6eCgW:b-h0hzpn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx#L2)):*
> ```XML
> import { Button, useTheme } from '@mui/material';
> import React from 'react';
> ```

Always put react import first, then i18n then mui

Try to only import what you need from react.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhNBr4LTL9ihXbYKG:-NiLhNBs9TkstWW5_mzu:b-ab1grx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L1)):*
> ```XML
> import React from 'react';
> ```

Why whole react import?
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgyO9BK0fk8PRsWhv:-NiLgyO9BK0fk8PRsWhw:b-v4c6nn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L2)):*
> ```XML
> import React from 'react';
> import { useTheme } from '@mui/material';
> ```

Check if need /styles
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhT7S29m0JzLOi3AM:-NiLhT7S29m0JzLOi3AN:b-u6sthp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L11)):*
> ```XML
>   const theme = useTheme();
>   const sxClasses = getSxClasses(theme);
>   const legendLayers = useLayersList();
> ```

Add comment line where you get store value
// get store value(s)
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhbPyEFKeWVlHAqd2:-NiLhbPyEFKeWVlHAqd3:bl49ddw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L2)):*
> ```XML
> import { useState } from 'react';
> import { useTheme } from '@mui/material';
> ```

Think we should add /styles
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhfY60YJB8aqYpjLy:-NiLhfY7AyEZMiOFRn8p:bz7icxt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L15)):*
> ```XML
>   KeyboardArrowUpIcon,
>   GroupWorkOutlinedIcon,
>   KeyboardArrowRightIcon,
> ```

Try to put import in alphabetical order when there is many
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhm3-1R7ORlDae_6_:-NiLhm3-1R7ORlDae_6a:bgkpxmy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L39)):*
> ```XML
>   const sxClasses = getSxClasses(theme);
> 
>   const { toggleLayerVisibility, setSelectedLayerPath } = useLayerStoreActions();
> ```

Comment for store values
// get store value(s)
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLiZIDAkXhXTYDDmN5:-NiLiZIDAkXhXTYDDmN6:bryklzw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L1)):*
> ```XML
> import { useTheme, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
> ```

We should try to avoid table item. Use Grid instead from @/ui
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLiRdZEVZqmFV_BiR5:-NiLiRdZEVZqmFV_BiR6:b-a5mbtn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L2)):*
> ```XML
> import { useTheme, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
> import { useTranslation } from 'react-i18next';
> ```

react i18 import first and think useTheme needs import fomr ../styles
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLijOZ9hiLj6-7Xrh2:-NiLijOZ9hiLj6-7Xrh3:b-e5m5c9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L15)):*
> ```XML
>   const theme = useTheme();
>   const sxClasses = getSxClasses(theme);
>   const { t } = useTranslation<string>();
> ```

Always put props at the top, then translation, then thehe/sx, then usestate/useref (internal state), then store. This order should be consistent in all components tsx
___
*[`packages/geoview-core/src/core/component [...]

2023-11-03 20:41 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 18 of 20 files reviewed, 23 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/layers.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLh6kPCufPph6p-wbi:-NiLqzHSCJ3-buXd9tKm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/layers.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

React should come first, why do you import the whole React?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgOaI44JPMPsnZP4y:-NiLr0QZADqpwkWfF1A3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/types.ts#L85)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes it should but we may want to restrict the usage so we can keep optional
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgajg849g8DPDxWXG:-NiLs-za88IQ57bFLXDi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

useTheme is from ;@mui/material/styles I think. If not I have error in my code

Button should come from ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgjPY1fwr7tM6eCgV:-NiLs1Br2auK1iy8RdVH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Always put react import first, then i18n then mui

Try to only import what you need from react.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLgyO9BK0fk8PRsWhv:-NiLsRtgDMnpEDK7AmWo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Check if need /styles
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhbPyEFKeWVlHAqd2:-NiLsq4gAUlh9bPMBvOW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Think we should add /styles
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhfY60YJB8aqYpjLy:-NiLsrHe-W2Wi1MFE5Oc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Try to put import in alphabetical order when there is many
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhm3-1R7ORlDae_6_:-NiLss3t0Rpp6OVnVAj3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Comment for store values
// get store value(s)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLiRdZEVZqmFV_BiR5:-NiLugTfBGMd3FzhE_QU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

react i18 import first and think useTheme needs import fomr ../styles
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLizGaBDnwxAcBHYWa:-NiLuiE0DLF0IOTJn5QH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add comment
// get store values(s)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-06 01:34 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 12 of 20 files reviewed, 23 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhNBr4LTL9ihXbYKG:-NiXC6Lm98sj50N6bboM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why whole react import?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLhT7S29m0JzLOi3AM:-NiXC8J-5BRFG-wMYZc5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add comment line where you get store value
// get store value(s)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLiZIDAkXhXTYDDmN5:-NiXCEGwDgpboFtg7dVQ:b-ttcc0h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should try to avoid table item. Use Grid instead from @/ui
</blockquote></details>

Hmm, not sure if this is a good idea.
Grid is useful where you dont want a tabular structure
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLjNLQ19XP5-DFQP1C:-NiXEpWC34R-p9ZEkwKi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No hardcoded string, use translation
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLjYx6-f59kwcyWYaB:-NiXF20t6Y2ODe8iG-kk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add blank line between props - theme/sx, internal, store
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 71 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLjkXND3d0gwFlutEx:-NiXFMzOC9h0aF9KMdAb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/stores/geoview-store.ts#L71)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put between app and map in alphabetical order
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 145 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLkOmlBlAkTxfZmTih:-NiXFecN8JYa6KfOsJeu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L145)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Layer state selectors
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 149 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLkYCXBChb5dIiZXBH:-NiXFoX7AfjpSRBu2Hl-:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L149)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line before storeActions
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLkdtB2cPtf1mGf4aL:-NiXFttb7J27VrjisLgk:b-84vpq3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L151)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The whole selected layer should be an action or maybe a computed value and we would need a new section in the interface?
</blockquote></details>

Not sure I get the comment. Please explain.


<!-- Sent from Reviewable.io -->

2023-11-06 01:34 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-NiLjL4a-8YB9IlJ0crq:-NiXG4OE7_LL1xQRScFU:bf3lyqn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use Grid system
</blockquote></details>

I will do this in my next PR if thats okay with you.


<!-- Sent from Reviewable.io -->

2023-11-06 17:57 UTC, jolevesq requested changes
> Reviewed 1 of 20 files at r1, 1 of 6 files at r2, 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 13 of 21 files reviewed, 18 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456#-Ni_fzni3byx3S1nIDRG:-Ni_fznj8TJTQ1EnzckU:b-vc544o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/67501596dc216a19a996d7349afbd278950c9e99/packages/geoview-core/public/locales/fr/translation.json#L8)):*
> ```JSON
>     "add": "Ajouter",
>     "remove": "Retirer"
>   },
> ```

You miss the name propertie


<!-- Sent from Reviewable.io -->

2023-11-06 18:15 UTC, jolevesq reviewed
> Reviewed 1 of 6 files at r2, 2 of 9 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2023-11-06 18:16 UTC, jolevesq reviewed
> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2023-11-06 18:18 UTC, jolevesq approved these changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2023-11-06 18:21 UTC, merged