refactor(optional-theme): Make the theme properties to be optional in…
Canadian-Geospatial-Platform/geoview pull request #1657
Opened 2023-12-30 04:27 UTC by amir-azma

# Description

In UI components, we need to make the theme properties to be optional, since UI component references a 'theme' object which might not have been created the same way the map init has done it inside the core.

Fixes #1449 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
There is no functional changes in this PR, all the demo map should work as expected.

https://amir-azma.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2023-12-30 04:30 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`packages/geoview-core/src/ui/panel/panel-style.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-NmsyieJDIQdYT0Vuod8:-NmsyieK04ZBwEhvRRnH:bki782h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0189d7241de94dacb278280ef1f5817e6e29317/packages/geoview-core/src/ui/panel/panel-style.ts#L5)):*
> ```XML
> export const getSxClasses = (theme: Theme) => ({
>   panelContainer: {
>     // TODO because we are using ! in line below, we cannot make panel to be optional. Same scenarios for other lines.
> ```

I need to discuss with the team if it's safe to remove ! from line below if we are sure to receive the background from the panel in theme.


<!-- Sent from Reviewable.io -->

2024-01-05 14:02 UTC, jolevesq reviewed
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @amir-azma)

___
*[`packages/geoview-core/src/ui/panel/panel-style.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-NmsyieJDIQdYT0Vuod8:-NnOvRdC1h0MAN-7NW7_:b-3vljqh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0189d7241de94dacb278280ef1f5817e6e29317/packages/geoview-core/src/ui/panel/panel-style.ts#L5)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I need to discuss with the team if it's safe to remove ! from line below if we are sure to receive the background from the panel in theme.
</blockquote></details>

Please ask the question in GeoView Channel or at scrum and update


<!-- Sent from Reviewable.io -->

2024-01-05 22:51 UTC, Alex-NRCan requested changes
Based on the discussion today, I believe the `select-style.ts` file (for the Select ui component) should probably be cleaned up to remove unnecessary `?` as indicated by the red arrows here and be a part of this PR:

![image.png](https://files.reviewableusercontent.io/images/reviewable/94073946/EX1ePf2SbVedx_Xzszqgfmd4/image.png)

> Reviewed 1 of 15 files at r1, 14 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-:-NnQoEQfEPX_1FLYr2Yl:b-u4vzya)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @amir-azma and @jolevesq)

___
*[`packages/geoview-core/src/ui/panel/panel-style.ts` line 16 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-NnQnNB69aa1mpn2c888:-NnQnNB69aa1mpn2c889:b9a7lap) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b6ef49fa466e5c7c3d9b8108aec9b926bbca824/packages/geoview-core/src/ui/panel/panel-style.ts#L16)):*
> ```XML
>     '& .MuiCardHeader-root': {
>       backgroundColor: theme.panel?.background,
>       borderBottomColor: theme.panel.border!,
> ```

`theme.panel` here should likely be `theme.panel?`, no? If yes, probably good to do a "search all" in all components.

Also, maybe `border!` should be `border`?


<!-- Sent from Reviewable.io -->

2024-01-08 02:44 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/ui/panel/panel-style.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-NmsyieJDIQdYT0Vuod8:-Nnax3Io2tGxuyrDd7tO:b-qd8op8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0189d7241de94dacb278280ef1f5817e6e29317/packages/geoview-core/src/ui/panel/panel-style.ts#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Please ask the question in GeoView Channel or at scrum and update
</blockquote></details>

I had discussion with our team in GeoView channel.
___
*[`packages/geoview-core/src/ui/panel/panel-style.ts` line 16 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-NnQnNB69aa1mpn2c888:-NnaxFuE-6j230x3p0CI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b6ef49fa466e5c7c3d9b8108aec9b926bbca824/packages/geoview-core/src/ui/panel/panel-style.ts#L16)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

`theme.panel` here should likely be `theme.panel?`, no? If yes, probably good to do a "search all" in all components.

Also, maybe `border!` should be `border`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-08 02:45 UTC, amir-azma reviewed
I applied the changes.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657#-:-NnaxMsR4Aqbqn4Fbg4x:bwpbdi1)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)



<!-- Sent from Reviewable.io -->

2024-01-08 14:08 UTC, Alex-NRCan reviewed
> Reviewed 13 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @jolevesq)



<!-- Sent from Reviewable.io -->

2024-01-09 14:29 UTC, jolevesq approved these changes
> Reviewed 2 of 15 files at r2, 13 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1657)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amir-azma)



<!-- Sent from Reviewable.io -->

2024-01-09 14:29 UTC, merged