Layers add refactoring
Canadian-Geospatial-Platform/geoview pull request #1721
Opened 2024-01-24 19:30 UTC by ychoquet

# Description

Current Behavior
The add-new-layer.tsx file use an old method to validate and add new layers on a map. This cause code duplication and to a certain extent code discrepencies.

Expected Behavior
We want to use the geoview classes every time we need to create and add a new layer.

The code in add-new-layer.tsx is obsolete and must be replace with a new implementation.

Fixes #1720 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
By tracing the code using the Chrome Devtools and the raw-feature-info.html template

__Deploy URL__: https://ychoquet.github.io/GeoView/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-01-24 19:58 UTC, jolevesq requested changes
> Reviewed 14 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721)* status: 14 of 17 files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-Nowy-RyELeVjSJsnabg:-Nowy-RyELeVjSJsnabh:bez0qiv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/public/templates/raw-feature-info.html#L68)):*
> ```HTML
>         },
>         'listOfGeoviewLayerConfig': [
>           /*
> ```

Why this layer in comment?
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 293 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowylFc9V1IR6YsRo2c:-NowylFc9V1IR6YsRo2d:b-f3jiqu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L293)):*
> ```XML
>   const wfsValidation = async (): Promise<boolean> => {
>     try {
>       const wfsGeoviewLayerConfig = {
> ```

Does all these section should be elsewhere.... do they are needed when we load from the api function call or it is only for ui?

This is a lot of logic for the component...
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 355 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzNvk-MyYEJxjyIIE:-NowzNvk-MyYEJxjyIIF:bzgl1bn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L355)):*
> ```XML
>       }
> 
>       // ! Question: this type of query is not implemented in the ogc feature class. Should we add it to the code.
> ```

No, but we need to have a comment to explain what is currently supported and what is missing
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 406 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzYUE-uYiZYi1rgrC:-NowzYUE-uYiZYi1rgrD:b-soomc3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L406)):*
> ```XML
>       if (!isValid) throw new Error('err');
>       const geoCoreGeoviewLayerConfig = {
>         geoviewLayerId: generateId(),
> ```

For id can we use the geocore uuid provided or it is the layerURL value?

Is it later where you call geocore api to get config?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 562 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-Nox1yLNAKpjQ1fwHZIF:-Nox1yLNAKpjQ1fwHZIG:b-axw560) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L562)):*
> ```XML
>         }
>       } else {
>         console.log(`geoviewLayerType must be ${CONST_LAYER_TYPES.WMS}`);
> ```

use new logger warning instead of console.log


<!-- Sent from Reviewable.io -->

2024-01-24 20:22 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721)* status: 14 of 17 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-Nowy-RyELeVjSJsnabg:-Nox4HP_APNTkfaYuolp:b-36v5tm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/public/templates/raw-feature-info.html#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this layer in comment?
</blockquote></details>

I wanted to deactivate all the layers of the map at initialisation so I can easily see the layers added. I commented it in case we want to revert to what we had previously.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 293 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowylFc9V1IR6YsRo2c:-Nox55c-3cfZVZivxeLp:b-blpq7d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L293)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Does all these section should be elsewhere.... do they are needed when we load from the api function call or it is only for ui?

This is a lot of logic for the component...
</blockquote></details>

It could be. I've just replaced the old code with the new one. Old code was as big as the new one. Do you want to add a TODO?
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 355 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzNvk-MyYEJxjyIIE:-Nox5hTZ9oUKUS7sv8Jl:b-rcv7kj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L355)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No, but we need to have a comment to explain what is currently supported and what is missing
</blockquote></details>

We can add a TODO.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 406 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzYUE-uYiZYi1rgrC:-Nox5pznE2f4-OtOBnhO:b-bzqmgu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L406)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For id can we use the geocore uuid provided or it is the layerURL value?

Is it later where you call geocore api to get config?
</blockquote></details>

The code works only with the UUID.  The property layerURL is a variavle used to get user input. It can contain URLs but also other string like in htis case. The geocore api URL used to query the database is built later in the class instance.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 562 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-Nox1yLNAKpjQ1fwHZIF:-Nox7g5rAIFKVpS0qjOo:b-v812x7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L562)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

use new logger warning instead of console.log
</blockquote></details>

Done! Will be in my next push.


<!-- Sent from Reviewable.io -->

2024-01-25 18:37 UTC, jolevesq requested changes
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 293 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowylFc9V1IR6YsRo2c:-Np0uCcvDAXhsDyMSkfZ:b-62rkaa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L293)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It could be. I've just replaced the old code with the new one. Old code was as big as the new one. Do you want to add a TODO?
</blockquote></details>

Yeah, we should a TODO... maybe put in a utility add layer ts file on in layer inside geo
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 355 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzNvk-MyYEJxjyIIE:-Np0uMGdCOFXvTnIemy2:b9y1bfs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L355)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

We can add a TODO.
</blockquote></details>

Yes please


<!-- Sent from Reviewable.io -->

2024-01-26 23:18 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721)* status: 6 of 39 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 293 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowylFc9V1IR6YsRo2c:-Np72g6GAmoXCeGrEwQL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L293)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yeah, we should a TODO... maybe put in a utility add layer ts file on in layer inside geo
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 355 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1721#-NowzNvk-MyYEJxjyIIE:-Np73Bqg17e12toEHmi6:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e5d90730c78563d628363bd9dd70353ee7db9dc6/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L355)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 22:16 UTC, ychoquet commented
This PR is replaced by PR #1756

2024-02-05 22:16 UTC, closed without merging