Styling improvements forcolors across themes
Canadian-Geospatial-Platform/geoview pull request #1738
Opened 2024-01-29 16:14 UTC by cphelefu

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-01-29 18:26 UTC, jolevesq reviewed
> Reviewed 11 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 11 of 17 files reviewed, 7 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 156 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLQRLpDHU09o8tK7q9:-NpLQRLpDHU09o8tK7qA:bnf097o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/public/templates/raw-feature-info.html#L156)):*
> ```HTML
>         ]
>       },
>       'theme': 'dark',
> ```

We should keep geo.ca for this demo
___
*[`packages/geoview-core/src/core/components/details/feature-info-table.tsx` line 125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRaXR1Su3RJo05xzl:-NpLRaXS8WUmxsoGFurQ:b9uarfv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/details/feature-info-table.tsx#L125)):*
> ```XML
>       {featureInfoList.map((featureInfoItem, index) => (
>         // eslint-disable-next-line react/no-array-index-key
>         <Grid container spacing={5} sx={{ backgroundColor: index % 2 > 0 ? theme.palette.primary.main : '', marginBottom: '20px' }} key={index}>
> ```

Why it is not like the other 'geoviewColors....'
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRqt925qBEbwgVXJM:-NpLRqt925qBEbwgVXJN:b5qasc3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L30)):*
> ```XML
>     border: '1px solid',
>     borderColor: 'geoViewColors.bgColorDarker',
>     boxShadow: 'rgb(0 0 0 / 20%) 0px 3px 1px -2px, rgb(0 0 0 / 14%) 0px 2px 2px 0px, rgb(0 0 0 / 12%) 0px 1px 5px 0px',
> ```

Can we use the geoviewColor to replace the rgb...
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLS8cNBU2paYhvymHI:-NpLS8cNBU2paYhvymHJ:bo5fjfi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L31)):*
> ```XML
>     borderColor: 'geoViewColors.bgColorDarker',
>     boxShadow: 'rgb(0 0 0 / 20%) 0px 3px 1px -2px, rgb(0 0 0 / 14%) 0px 2px 2px 0px, rgb(0 0 0 / 12%) 0px 1px 5px 0px',
>     background: '#fff',
> ```

Can we use geoviewColors...
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRytEBteWc_bBuOVd:-NpLRytEBteWc_bBuOVe:bo5fjfi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L43)):*
> ```XML
>     width: 24,
>     height: 24,
>     background: '#fff',
> ```

Can we use geoviewColors...
___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLSd7s-4JakKO4DcXL:-NpLSd7s-4JakKO4DcXM:b-86wezj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts#L21)):*
> ```XML
> 
>     '& .layerItemContainer': {
>       background: `${theme.palette.geoViewColors.bgColorLight} 0% 0% no-repeat padding-box`,
> ```

Why theme.palette before geoviewColors.... somethimes it is theme.palette, somethimes just geoviewColors
___
*[`packages/geoview-core/src/ui/style/default.ts` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLTBKo9P6wDiJCN1Wa:-NpLTBKo9P6wDiJCN1Wb:b9ib79p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/ui/style/default.ts#L65)):*
> ```XML
>   },
>   typography: {
>     fontSize: 16,
> ```

If we have geoViewText, should the 16 be taken from that array?


<!-- Sent from Reviewable.io -->

2024-01-29 21:43 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLSd7s-4JakKO4DcXL:-NpMAHZI1f7QVD5mAxhe:b-z54bp4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why theme.palette before geoviewColors.... somethimes it is theme.palette, somethimes just geoviewColors
</blockquote></details>

For color and backgroundColor the short statements work. Otherwise you have to go this route.


<!-- Sent from Reviewable.io -->

2024-01-29 21:45 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/default.ts` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLTBKo9P6wDiJCN1Wa:-NpMAgLA9C58IaSeOjFR:bg4wk4j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/ui/style/default.ts#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If we have geoViewText, should the 16 be taken from that array?
</blockquote></details>

This is for the next round. First around am moving colors to the styles world.. them rearranging with style files


<!-- Sent from Reviewable.io -->

2024-01-29 21:46 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 6 of 25 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/feature-info-table.tsx` line 125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRaXR1Su3RJo05xzl:-NpMAC9762-5_VDaPf96:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/details/feature-info-table.tsx#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why it is not like the other 'geoviewColors....'
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLS8cNBU2paYhvymHI:-NpMAE6s-BWHVn1sSw4Y:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use geoviewColors...
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRytEBteWc_bBuOVd:-NpMAEjB-gOgNXKuIxSH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use geoviewColors...
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 156 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLQRLpDHU09o8tK7q9:-NpMAvJCE_tBeNbzoZj6:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/public/templates/raw-feature-info.html#L156)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should keep geo.ca for this demo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-29 21:52 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRqt925qBEbwgVXJM:-NpMB-wSAH6nqCvnP3SL:b-6atko8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use the geoviewColor to replace the rgb...
</blockquote></details>

Still working on this.We have 24 rgb colors. Working on centralizing them so we dont end up with 24 different colors. Basically have to find whats similar and replace accordingly. Will deliver shortly. Was thinking of doing it for next sprint


<!-- Sent from Reviewable.io -->

2024-01-31 20:54 UTC, jolevesq requested changes
> Reviewed 1 of 18 files at r2, 4 of 27 files at r3, 17 of 32 files at r4, 11 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 33 of 39 files reviewed, 26 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWC2j570jXmgNOsbhF:-NpWC2j570jXmgNOsbhG:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/attribution/attribution.tsx#L55)):*
> ```XML
>         tooltip="mapctrl.attribution.tooltip"
>         sx={{
>           color: 'geoViewColors.primary.light[300]',
> ```

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 72 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWCEqMCrUDVxVeh72b:-NpWCEqMCrUDVxVeh72c:b-3zqsro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/common/layer-list.tsx#L72)):*
> ```XML
>                   sx={{
>                     color: `${theme.palette.geoViewColors.primary.main} !important`,
>                     background: `${theme.palette.grey.A100} !important`,
> ```

Why there is color not in geoviewColors (grey).. some places it is theme.palette.common....
___
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 11 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDDkd3cAGcEr0Zm3m:-NpWDDkd3cAGcEr0Zm3n:b-18qnhu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L11)):*
> ```XML
>     border: '1px solid',
>     borderColor: theme.palette.grey[600],
>     boxShadow: theme.footerPanel.boxShadow,
> ```

Should it be higher in hierarchy and this box shadow re use everywhere we need a box shadow?
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 39 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWERSQ3KjKn0InkKJk:-NpWERSQ3KjKn0InkKJl:b-65xhw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/details/details-style.ts#L39)):*
> ```XML
>     borderRadius: 0,
>     border: '1px solid',
>     borderColor: theme.palette.grey[600],
> ```

Not in GEovicolors or common?
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 40 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDhv0E1U_u8szl2RB:-NpWDhv17YcgHgBvByUo:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/details/details-style.ts#L40)):*
> ```XML
>     border: '1px solid',
>     borderColor: theme.palette.grey[600],
>     boxShadow: theme.footerPanel.boxShadow,
> ```

Same as above
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 14 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDq1h-BoBpxegqsK8:-NpWDq1h-BoBpxegqsK9:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L14)):*
> ```XML
>     maxHeight: '35px',
>     backdropFilter: 'blur(5px)',
>     backgroundColor: 'geoViewColors.bgColor.dark[800]',
> ```

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 42 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDrL4Cd-zbjNuuH0w:-NpWDrL4Cd-zbjNuuH0x:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L42)):*
> ```XML
>     alignItems: 'center',
>     justifyContent: 'center',
>     color: 'geoViewColors.primary.light[300]',
> ```

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 60 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDsTEAqSXjTrQEnTu:-NpWDsTEAqSXjTrQEnTv:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L60)):*
> ```XML
>     width: '1.5em',
>     height: '1.5em',
>     color: 'geoViewColors.primary.light[300]',
> ```

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 18 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWE56s4x4UGlyuXlel:-NpWE56s4x4UGlyuXlem:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L18)):*
> ```XML
> const sxClasses = {
>   tooltipItem: {
>     color: 'geoViewColors.white',
> ```

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 19 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWEem81knXbAmsscfw:-NpWEem81knXbAmsscfx:b-op7mkb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L19)):*
> ```XML
>   tooltipItem: {
>     color: 'geoViewColors.white',
>     background: '#222',
> ```

hexadecimal color, use palette
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLS8cNBU2paYhvymHI:-NpWEv_CAHwMqC9K2Ypm:b-tgbsx8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L31)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should we always use theme.palette.... for standardization... because we need to use theme.palette sometimes
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRytEBteWc_bBuOVd:-NpWF-WV-KmhvXfHhcxK:b-tgo6re) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L43)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should we always use theme.palette.... for standardization
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 60 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWF326Af90iVPoifGx:-NpWF326Af90iVPoifGy:b-lt1s2m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L60)):*
> ```XML
>     padding: 0,
>     borderRadius: 0,
>     boxShadow: theme?.footerPanel.boxShadow,
> ```

 [...]

2024-01-31 21:03 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWC2j570jXmgNOsbhF:-NpWK7-T4UhCMGlBKR5Q:b2i9koj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/attribution/attribution.tsx#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Hmm, feels too long. am actually also thinking in the future we will reduce geoViewColors to something else. Maybe gvColors.. what do you think?


<!-- Sent from Reviewable.io -->

2024-01-31 21:37 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 42 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDrL4Cd-zbjNuuH0w:-NpWS4Ad55NpNqoNVwc8:b-vxldw3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Hmm, nope


<!-- Sent from Reviewable.io -->

2024-01-31 22:09 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts` line 10 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWFd2M8u2UDY5qb2T6:-NpWZWdZ2Mn2e4rip6-8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 22:10 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLSd7s-4JakKO4DcXL:-NpWZkr56pwrjNC96lnY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 22:11 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWC2j570jXmgNOsbhF:-NpWZxH82wkA1vjVGYnF:b-7ql1td) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/attribution/attribution.tsx#L55)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Hmm, feels too long. am actually also thinking in the future we will reduce geoViewColors to something else. Maybe gvColors.. what do you think?
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2024-01-31 23:39 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 8 of 52 files reviewed, 26 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 72 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWCEqMCrUDVxVeh72b:-NpWajDNCcNSDjj6lPW1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/common/layer-list.tsx#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why there is color not in geoviewColors (grey).. some places it is theme.palette.common....
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 39 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWERSQ3KjKn0InkKJk:-NpWay5h5sKIq5JnTr1_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/details/details-style.ts#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not in GEovicolors or common?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 40 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDhv0E1U_u8szl2RB:-NpWay_w4xb9o3m-QCfk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/details/details-style.ts#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 14 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDq1h-BoBpxegqsK8:-NpWZp9x6Y_rnoLggsy7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 60 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDsTEAqSXjTrQEnTu:-NpWb0PV0X8pU0V5xB6e:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 18 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWE56s4x4UGlyuXlel:-NpWb1xp3pwhHl114MS8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLS8cNBU2paYhvymHI:-NpWt3QpCqPsXck9NEM8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization... because we need to use theme.palette sometimes
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpLRytEBteWc_bBuOVd:-NpWt5QC9Jq7sfaZzPRN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1480e08a21cf0a3aadc1826af2e4b75daf59004/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts` line 46 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWFeop-x4nSRzsH0BZ:-NpWZVWn2fiLw02wmYoq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/containers/containers-style.ts` line 57 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWFxMj46t6OJP8hDvJ:-NpWZQ3hAFH66-NppNxb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/containers/containers-style.ts#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we always use theme.palette.... for standardization
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/types/material-ui.d.ts` line 152 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWG9S-6ZrUJknITYM6:-NpWZFVnCkKWnf1JW_XV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/types/material-ui.d.ts#L152)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 23:40 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 8 of 52 files reviewed, 26 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control-styles.ts` line 20 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWFjX228tQ_HiYi1S-:-NpWtGTA69ZFO4qfzCQv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control-styles.ts#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

theme.palette.geoviewText like in layer-details.ts ... we shuld standardize
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 23:40 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 8 of 52 files reviewed, 26 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/style/default.ts` line 22 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWGR8ZA4WFEWhE3f2o:-NpWtN3W-_ISCa4Qfm2K:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/default.ts#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this is not hexadecimal... if it is a background, can we use the bgColor to reduce amount of colors
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 23:41 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 252 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWI5XQ5pIhMxc7m8vQ:-NpWt_1X9kJnCpdadBJz:b-rmoi1h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L252)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All this should reuse our define color...
</blockquote></details>

Not sure. there is no color here


<!-- Sent from Reviewable.io -->

2024-01-31 23:42 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 8 of 52 files reviewed, 26 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/style/geoView.interface.ts` line 72 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWHFpa5B0VRMQ7Eny7:-NpWtfW4EDyDsAidKy6J:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/geoView.interface.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can the 3 next elements can reuse a variation of existing color we are supporting instead of crating a new one?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-31 23:43 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 11 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDDkd3cAGcEr0Zm3m:-NpWtu5b608CgkjJ8rCU:b-jakinx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be higher in hierarchy and this box shadow re use everywhere we need a box shadow?
</blockquote></details>

Will be cleaning up most of the themeOptions later on to remove the ones we dont need (or their props). Will be starting with footerPanel.


<!-- Sent from Reviewable.io -->

2024-01-31 23:44 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 42 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWDrL4Cd-zbjNuuH0w:-NpWu7133csXiGr4b7X3:b-886gsx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L42)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Hmm, nope
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-01-31 23:44 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 19 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWEem81knXbAmsscfw:-NpWu9l87K9NBPcIYbDZ:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

hexadecimal color, use palette
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-31 23:44 UTC, cphelefu commented
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts` line 60 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWF326Af90iVPoifGx:-NpWuD6sCKvvI-o0OmLB:bl24j6q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be higher in hierarchy because we use footerPanel shadow in a common component. We should have one shadow element reusable everywhere
</blockquote></details>

Will do this when I clean up the theme options. It may end up in a different place altogether.


<!-- Sent from Reviewable.io -->

2024-01-31 23:47 UTC, cphelefu commented
*[`packages/geoview-core/src/core/types/material-ui.d.ts` line 88 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWG1VJ-aMjxwlE43Gs:-NpWuus4CZ3vj7SGck4z:b12u6w2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/types/material-ui.d.ts#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be higher in hierarchy and not link to footer so it is reuse everywhere
</blockquote></details>

yep, for later


<!-- Sent from Reviewable.io -->

2024-01-31 23:48 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 73 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWHv7q7Grq7avju6GQ:-NpWv-db1S_6kTBhcimY:b401awm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we reuse color everywhre we are using new rgb color in this file?
</blockquote></details>

wasnt sure. Will clean remove when I clean the theme options.


<!-- Sent from Reviewable.io -->

2024-01-31 23:48 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 8 of 52 files reviewed, 26 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts` line 44 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWFNad5J2Crytuq5wH:-NpWuqLs6GNtGaYcW1oC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should come from the theme.palette.geoview....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-01 15:29 UTC, jolevesq requested changes
> Reviewed 1 of 13 files at r5, 32 of 43 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 48 of 53 files reviewed, 9 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 33 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_E36OBKt38kvXalGp:-Np_E36OBKt38kvXalGq:brqz4sz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L33)):*
> ```XML
>   } = useTheme();
> 
>   const sxClasses = {
> ```

The definition for sxClasses should be in hover-tooltip-style.ts
___
*[`packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-style.ts` line 15 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_FHlM0xhNip4Jybia:-Np_FHlM0xhNip4Jybib:b-d4id19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-style.ts#L15)):*
> ```XML
>     color: theme.palette.secondary.contrastText,
>     '&:hover': {
>       backgroundColor: '#dddddd',
> ```

Can we use geoviewColor
___
*[`packages/geoview-core/src/ui/slider/slider-style.ts` line 6 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_FPjo27ErVvWWIjtw:-Np_FPjo27ErVvWWIjtx:b-d4id19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/slider/slider-style.ts#L6)):*
> ```XML
>   slider: {
>     '& .MuiSlider-root': {
>       color: '#fff',
> ```

Can we use geoviewColor
___
*[`packages/geoview-core/src/ui/slider/slider-style.ts` line 26 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_F_Kj8YCv6Uhup5bF:-Np_F_Kk4teNPi4E67wa:b-d4id19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/slider/slider-style.ts#L26)):*
> ```XML
>     '& .MuiSlider-rail': {
>       opacity: 0.35,
>       color: 'rgba(0,0,0,0.87)',
> ```

Can we use geoviewColor
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 73 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWHv7q7Grq7avju6GQ:-Np_Geb_7HwKx-hEFcFX:bdicdmo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L73)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

wasnt sure. Will clean remove when I clean the theme options.
</blockquote></details>

We can merge with this inside but we should always reuse the palette.... 
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 252 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWI5XQ5pIhMxc7m8vQ:-Np_GvMI1qv5_CfCirp0:b-gm52eu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L252)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Not sure. there is no color here
</blockquote></details>

appBar.background #FFFFFFee,
appBar.btnActive: #000000e6,
....

All colors should came from our palette....nothing should be hardcoded
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 16 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_G62B0_konDMffAte:-Np_G62B0_konDMffAtf:b-uoei4e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L16)):*
> ```XML
>         white: '#fff',
>       },
>       primary: {
> ```

Is it a duplication....
theme.palette.primary.main vs theme.palette.geoViewColor.primary.main

Should we have only one place with colors? Always use geoviewColor or palette.primary is using geoviewColor


<!-- Sent from Reviewable.io -->

2024-02-01 15:56 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 16 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_G62B0_konDMffAte:-Np_Nc0h7c-qRL42mQjM:bq9ifql) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it a duplication....
theme.palette.primary.main vs theme.palette.geoViewColor.primary.main

Should we have only one place with colors? Always use geoviewColor or palette.primary is using geoviewColor
</blockquote></details>

Nope, it is not a duplication. This primary is used by components. It controls the primary color in components. We cant remove it.


<!-- Sent from Reviewable.io -->

2024-02-01 15:58 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 73 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWHv7q7Grq7avju6GQ:-Np_NpiS2O8CNoblydMv:b44koh9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can merge with this inside but we should always reuse the palette....
</blockquote></details>

Agreed, I believe this is just the initial work. We should be able to stabilize the colors in the next few days as we change themeOptions and also get feedback from team on how their components have changed.


<!-- Sent from Reviewable.io -->

2024-02-01 15:59 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 252 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWI5XQ5pIhMxc7m8vQ:-Np_O8yIAXPwodkbM9BL:bqshe4q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L252)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

appBar.background #FFFFFFee,
appBar.btnActive: #000000e6,
....

All colors should came from our palette....nothing should be hardcoded
</blockquote></details>

Yes, there is lots work to be done in the themeOptions itself. But i feel we can merge this PR and continue work on another one.


<!-- Sent from Reviewable.io -->

2024-02-01 16:01 UTC, cphelefu commented
*[`packages/geoview-core/src/ui/style/geoView.interface.ts` line 71 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-NpWH4WPET0zINSMkEv-:-Np_OPWl8q0W9QNH30t8:b2de87a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd0d08ea5ba1ed2e711e7c45eee1acad8bf7ec2/packages/geoview-core/src/ui/style/geoView.interface.ts#L71)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

he common color like grey, white, black .... should it be in one object?
white is in comon in the themeOptionsGenerator. Maybe combine white, grey and black in common....
</blockquote></details>

is it okay if i do this as part of themeOptions clean-up? I would like to see where the common colors are used.. maybe we dont need them.


<!-- Sent from Reviewable.io -->

2024-02-01 16:02 UTC, cphelefu reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 48 of 53 files reviewed, 8 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/slider/slider-style.ts` line 6 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_FPjo27ErVvWWIjtw:-Np_NWGv2sYgE3nAtLMS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/slider/slider-style.ts#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use geoviewColor
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/slider/slider-style.ts` line 26 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738#-Np_F_Kj8YCv6Uhup5bF:-Np_NVmH0yyS4qxKYioI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6cd28e826004685225f27d4fe25cae8392fc9c62/packages/geoview-core/src/ui/slider/slider-style.ts#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use geoviewColor
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-01 16:27 UTC, jolevesq reviewed
> Reviewed 4 of 43 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2024-02-01 19:20 UTC, jolevesq reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: 51 of 54 files reviewed, all discussions resolved (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2024-02-01 19:21 UTC, jolevesq approved these changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1738)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)



<!-- Sent from Reviewable.io -->

2024-02-01 19:21 UTC, merged