feat(guide-tab): Added new Guide tab
Canadian-Geospatial-Platform/geoview pull request #1750
Opened 2024-02-02 21:46 UTC by amir-azma

# Description

We have added a new tab called "Guide" to include help documentation about the map and different content including footer bar items and etc. The content can be fetched from a MD file.

Fixes #1441 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://amir-azma.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-02-06 21:51 UTC, jolevesq requested changes
> Reviewed 14 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 15 of 17 files reviewed, 12 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/package.json` line 177 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-IcyT-Y3v4X5UQSyG:-Nq-IcyT-Y3v4X5UQSyH:bwjzcy6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/package.json#L177)):*
> ```JSON
>     "zustand": "~4.4.1",
>     "simple-zustand-devtools": "^1.1.0",
>     "markdown-loader": "~8.0.0",
> ```

Why do we have 2 dependencies for markdown?
___
*[`packages/geoview-core/schema.json` line 1587 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-J0EiB3e6Kx4LOc2K:-Nq-J0EiB3e6Kx4LOc2L:b3slzjn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/schema.json#L1587)):*
> ```JSON
>                   "time-slider",
>                   "geochart",
>                   "guide"
> ```

Will see but this should always be there as soon as we have the footer created... this way we do not have to add it to all our config...
___
*[`packages/geoview-core/src/core/components/guide/custom-hook.tsx` line 17 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Jf_kC4EicQunQvyf:-Nq-Jf_l5g3-w2z8vxNZ:b-akixtn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/custom-hook.tsx#L17)):*
> ```XML
>         const sections = content.split(/=([^=]+)=/);
> 
>         if (sections[0].trim() === '') {
> ```

Why do you do this?
___
*[`packages/geoview-core/src/core/components/guide/custom-hook.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-JkIy-ER9nkcLG2vj:-Nq-JkIy-ER9nkcLG2vk:b-x7i0za) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/custom-hook.tsx#L24)):*
> ```XML
>         for (let i = 0; i < sections.length; i += 2) {
>           const heading = sections[i].trim();
>           const sectionContent = sections[i + 1].trim();
> ```

With the section content, it is were you can know how many subsection there is...
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-KKjnE6yDOBz2GAzd:-Nq-KKjnE6yDOBz2GAze:b-8h2ilw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L15)):*
> ```XML
> import { TypeFooterBarProps } from '@/geo/map/map-schema-types';
> 
> type coreTabsType = TypeFooterBarProps['tabs']['core'];
> ```

Should you use this type instead: https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/geo/map/map-schema-types.ts#L1443C13-L1443C45
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 58 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-KXSK3LTYxjK2RkO0:-Nq-KXSK3LTYxjK2RkO1:b-uwttsq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L58)):*
> ```XML
> 
>   // Custom hook for calculating the height of footer panel
>   const { leftPanelRef, rightPanelRef, panelTitleRef } = useFooterPanelHeight({ footerPanelTab: 'details' });
> ```

Why getting details may not be in the footer if not in config
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 60 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-LVXt83Zycy8NiYSq:-Nq-LVXt83Zycy8NiYSr:b-2w8j1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L60)):*
> ```XML
>   const { leftPanelRef, rightPanelRef, panelTitleRef } = useFooterPanelHeight({ footerPanelTab: 'details' });
> 
>   // get store config for footer tabs
> ```

footer bar
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 61 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-LXhg6ZwdfSeN1YSe:-Nq-LXhg6ZwdfSeN1YSf:b-p7fppp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L61)):*
> ```XML
> 
>   // get store config for footer tabs
>   const footerTabsConfig = useGeoViewConfig()?.footerBar;
> ```

footerBar
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 81 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lk55A1cG3AkgE5SK:-Nq-Lk55A1cG3AkgE5SL:b-b1wisk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L81)):*
> ```XML
>   const footerContentKeyValues: Record<string, string> = {};
>   if (sectionsOfFooters) {
>     if (sectionsOfFooters[0]?.trim() === '') {
> ```

Why this check?
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lzx062LvZprrcp_F:-Nq-Lzx062LvZprrcp_G:b-4xs74t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L84)):*
> ```XML
>       sectionsOfFooters.shift();
>     }
>     for (let i = 0; i < sectionsOfFooters.length; i += 2) {
> ```

Why += 2 for index?
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 96 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-M7TG1PoEHtN_5kId:-Nq-M7TG1PoEHtN_5kIe:bvl4di0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L96)):*
> ```XML
> 
>   leftPanelItemKeys?.forEach((item) => {
>     if (item !== 'Footer') {
> ```

Should not be specific for footer... the section should be dynamic and check if in the config object. Please add a TODO
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 134 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-NTNaAHFgce42Dyou:-Nq-NTNb4hN-DykcmPlB:b-9ciqts) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L134)):*
> ```XML
>       {helpItems.length ? (
>         <>
>           <ResponsiveGrid.Root sx={{ pt: 8, pb: 8 }} ref={panelTitleRef}>
> ```

Can you use https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/core/components/common/layout.tsx like in time-slider... less code and reuse the common at higher level


<!-- Sent from Reviewable.io -->

2024-02-06 21:52 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 15 of 17 files reviewed, 13 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/icon-stack/icon-stack.tsx` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-P-n5-ZLaB1AeUZil:-Nq-P-n5-ZLaB1AeUZim:b-xq3tra) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/icon-stack/icon-stack.tsx#L42)):*
> ```XML
>       )}
>     </IconButton>
>   ) : // eslint-disable-next-line no-nested-ternary
> ```

Is tehre a better way to test condition and do not ad d the eslitn disable?


<!-- Sent from Reviewable.io -->

2024-02-06 22:59 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 15 of 17 files reviewed, 13 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/package.json` line 177 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-IcyT-Y3v4X5UQSyG:-Nq-WZZhAvRGJVURK69F:b-c1jxju) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/package.json#L177)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do we have 2 dependencies for markdown?
</blockquote></details>

I hot error related to webpack that there is no loader configured, I found out we need to have html-loader
___
*[`packages/geoview-core/schema.json` line 1587 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-J0EiB3e6Kx4LOc2K:-Nq-Wpae0jwbElDfnkeO:bzy432) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/schema.json#L1587)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will see but this should always be there as soon as we have the footer created... this way we do not have to add it to all our config...
</blockquote></details>

You mean "guide" should be part of the default footer tabs?  I removed the tabs from config setting, if we don't include the tabs, then we won't have any tabs in footer, it seems we don't have default tabs, is that correct?
___
*[`packages/geoview-core/src/core/components/guide/custom-hook.tsx` line 17 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Jf_kC4EicQunQvyf:-Nq-XnnA4V0R_XJrZjow:bx32aty) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/custom-hook.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you do this?
</blockquote></details>

After parsing the md file content there is always the first element with empty content as the first element, this line and next shift() method removes the possible empty element from the "sections" array (that's the first element of array)
___
*[`packages/geoview-core/src/core/components/guide/custom-hook.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-JkIy-ER9nkcLG2vj:-Nq-YX75EbaVxOa9xW8D:b-ntewi3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/custom-hook.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

With the section content, it is were you can know how many subsection there is...
</blockquote></details>

This section is not the section inside each content, this is based on this  =some name here= , the sections are referring is based on  %my section%  (between % signs) , that's is different code , it's in line 70 here https://github.com/Canadian-Geospatial-Platform/geoview/pull/1750/files#diff-a6b4570b6a1e51b497bfb26e37f0fb3b68dd3839f85f96199c2bb783ab406029R70
I need to refactor logics because originally the regular content don't have sections like %my section% , because in MD file you can create your own section by adding ### my section that creates h3 tags, need to change the format of MD because right now %something% is only inside footer in MD file
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-KKjnE6yDOBz2GAzd:-Nq-aQ_d7etrVpWO19kx:beghmvc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should you use this type instead: https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/geo/map/map-schema-types.ts#L1443C13-L1443C45
</blockquote></details>

I think I got type error, but don't remember..., I will try that again
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 58 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-KXSK3LTYxjK2RkO0:-Nq-alSOEhX_PQb1CXaQ:b-8i0b8k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why getting details may not be in the footer if not in config
</blockquote></details>

Here it should be 'guide' , I will change that
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 60 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-LVXt83Zycy8NiYSq:-Nq-bTkB9maKOdZoezlo:bs7lqkl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

footer bar
</blockquote></details>

I will change it.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 61 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-LXhg6ZwdfSeN1YSe:-Nq-bdD37U26Ax5ypGve:b-4wp2id) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

footerBar
</blockquote></details>

I will change it to footerBarsConfig
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 81 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lk55A1cG3AkgE5SK:-Nq-bs9I-4RHgom24rch:b-th1878) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this check?
</blockquote></details>

The first element in array is empty string, I will double check again
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lzx062LvZprrcp_F:-Nq-c1x04FGJ2nVyoz4B:beemgaz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why += 2 for index?
</blockquote></details>

I need to get every other element of this array, the first one is section name, the second is content of that section, so need every other element 
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 96 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-M7TG1PoEHtN_5kId:-Nq-cMaj0e_SZaOpf5oe:b6prq4q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L96)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should not be specific for footer... the section should be dynamic and check if in the config ob [...]

2024-02-07 15:57 UTC, jolevesq requested changes
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 16 of 17 files reviewed, 12 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lzx062LvZprrcp_F:-Nq3GGGY35W7VcWXIQwA:brjw95h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L84)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I need to get every other element of this array, the first one is section name, the second is content of that section, so need every other element
</blockquote></details>

Why don't you split the content by crating an object header: and content: in the array so everything is packaged together?
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 96 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-M7TG1PoEHtN_5kId:-Nq3GoXq0xpUY6QLwdOh:b1dvsjq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L96)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

So how do we know if we are inside the footer section to match the sections with the array of footer tabs?  when we get inside the footer section in MD file, then we check the sections if it matches with the tab names, if we have tab A, B, C, then we display the sections for A, B, C , and don't display section D , because section D is not in footer in that map, but maybe section D will be in other map
</blockquote></details>

If we want it to be fully reusable, from section header id you find the content in the config object and test again it. So it can use appbar and footerbar without having to specify.... Let it like this for now...


<!-- Sent from Reviewable.io -->

2024-02-08 19:59 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 16 of 17 files reviewed, 12 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 134 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-NTNaAHFgce42Dyou:-Nq9Ap8363JMgqn5uIZS:b-w94jhs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L134)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I will check it
</blockquote></details>

I used the same layer structure we have in Details tab that works fine here, not sure which section you want me to change, I can review later


<!-- Sent from Reviewable.io -->

2024-02-09 13:40 UTC, jolevesq requested changes
> Reviewed 11 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/schema.json` line 1587 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-J0EiB3e6Kx4LOc2K:-NqD35xDA9f_fXordjTl:b-rvflc9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/schema.json#L1587)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

You mean "guide" should be part of the default footer tabs?  I removed the tabs from config setting, if we don't include the tabs, then we won't have any tabs in footer, it seems we don't have default tabs, is that correct?
</blockquote></details>

There is no default tabs but guide should be added automatically
___
*[`packages/geoview-core/public/locales/en/translation.json` line 204 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqD2qAr3BSv-lzfRNa9:-NqD2qAr3BSv-lzfRNaA:b-rqu93f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b4a8e10a520ce6c392281557b7e602fdd1de4f7/packages/geoview-core/public/locales/en/translation.json#L204)):*
> ```JSON
>     "title": "Guide",
>     "errorMessage": "Sorry, unable to find the help document!"
>   },
> ```

Wrong rebase should be  "footerBar": {
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 205 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqD2va517T7dwNAuOjr:-NqD2va517T7dwNAuOjs:bjwyy87) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b4a8e10a520ce6c392281557b7e602fdd1de4f7/packages/geoview-core/public/locales/fr/translation.json#L205)):*
> ```JSON
>     "errorMessage": "Désolé, impossible de trouver le document d'aide !"
>   },
>   "footerTabsContainer": {
> ```

 Wrong rebase should be "footerBar": {
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lzx062LvZprrcp_F:-NqD3v3eALZBH-hN3gvT:b-gfr9b3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L84)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

It's the same logic we have in custom hook, to get every other section, added todo in that file
</blockquote></details>

But if you create and object "sectionPath": { "header": ..., "content": ... } it will mimic layers array with layerPath object.... I see it is what you are doing later, maybe you should add comments in your code so we understand what you are trying to achieve
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 134 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-NTNaAHFgce42Dyou:-NqD4fBc8DXyu-qmoSA2:b8sx4uo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L134)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I used the same layer structure we have in Details tab that works fine here, not sure which section you want me to change, I can review later
</blockquote></details>

Details willl be refactored to reuse common component at an higher level... we can keep like this for now and refactor at the same time


<!-- Sent from Reviewable.io -->

2024-02-09 17:44 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 204 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqD2qAr3BSv-lzfRNa9:-NqDuThSEqYFOWgFSwtM:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b4a8e10a520ce6c392281557b7e602fdd1de4f7/packages/geoview-core/public/locales/en/translation.json#L204)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wrong rebase should be  "footerBar": {
</blockquote></details>

Done
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 205 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqD2va517T7dwNAuOjr:-NqDuSx45_hhldnUxBml:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b4a8e10a520ce6c392281557b7e602fdd1de4f7/packages/geoview-core/public/locales/fr/translation.json#L205)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wrong rebase should be "footerBar": {
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-Lzx062LvZprrcp_F:-NqDy42Z2dSFWYbFA17O:b-jv6h4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

But if you create and object "sectionPath": { "header": ..., "content": ... } it will mimic layers array with layerPath object.... I see it is what you are doing later, maybe you should add comments in your code so we understand what you are trying to achieve
</blockquote></details>

Added example of data we receive from MD file.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 134 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-NTNaAHFgce42Dyou:-NqDy96yBDKXrrnFIiWq:bb87ghg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L134)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Details willl be refactored to reuse common component at an higher level... we can keep like this for now and refactor at the same time
</blockquote></details>

ok sure


<!-- Sent from Reviewable.io -->

2024-02-09 17:45 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 1587 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-Nq-J0EiB3e6Kx4LOc2K:-NqDyCBQ6u38n2gRwlI2:b-9q22gn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b62df65a51ecc934433db17ee0ae6dda8ab53a6/packages/geoview-core/schema.json#L1587)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no default tabs but guide should be added automatically
</blockquote></details>

I have fixed this, we will always have guide tab even if we don't include it in the list of the tabs in config file.


<!-- Sent from Reviewable.io -->

2024-02-12 13:44 UTC, jolevesq requested changes
> Reviewed 8 of 10 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma)

___
*[`packages/geoview-core/schema.json` line 1608 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqSYpp_6VtNg7zBCtDB:-NqSYppa3_WlsdW1pmBp:bmth6yr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/41a3cdc1e8d3665cd65c7e08df9491f6ab242bf7/packages/geoview-core/schema.json#L1608)):*
> ```JSON
>                   "time-slider",
>                   "geochart",
>                   "guide"
> ```

Because guide is default and not settable, we should remove the value from accepted tabs in the schema


<!-- Sent from Reviewable.io -->

2024-02-12 17:22 UTC, amir-azma reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 1608 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750#-NqSYpp_6VtNg7zBCtDB:-NqTKrcs8jHIUhifgcn6:bj2g1c9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/41a3cdc1e8d3665cd65c7e08df9491f6ab242bf7/packages/geoview-core/schema.json#L1608)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because guide is default and not settable, we should remove the value from accepted tabs in the schema
</blockquote></details>

Done, I am pushing changes


<!-- Sent from Reviewable.io -->

2024-02-12 17:54 UTC, jolevesq approved these changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1750)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amir-azma)



<!-- Sent from Reviewable.io -->

2024-02-12 17:56 UTC, merged