See layer in Error #1774
Canadian-Geospatial-Platform/geoview pull request #1829
Opened 2024-02-20 15:34 UTC by ychoquet

# Description

This PR is a major restructuration of the layerSet class. Now, it has two sub classes: LegendsLayerSet and FeatureInfoLayerSet. The OO approch ease the understanding and coding of the layer sets.

Fixes #1774

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the Chrome Devtools for tracing and debugging the code verifying that everything works as expected.

__Deploy URL__: https://ychoquet.github.io/GeoView/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-02-21 13:20 UTC, jolevesq reviewed
> Reviewed 22 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 22 of 54 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 478 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAjA6Y6GqukRUV1We6:-NrAjA6ZBCHcmbjUChso:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/public/templates/layers/esri-feature.html#L478)):*
> ```HTML
> 
>       // LYR2 ===================================================================================================================
>       
> ```

Blank spaces
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrAocURBWxSLmS1qxlH:bwgpfj9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
> ```XML
> 
>       // Give it some time so that each layer has their chance to load on time
>       // await delay(LegendEventProcessor.timeDelayBeforeSelectingLayerInStore);
> ```

If not needed anymore, should we remove dead code and dead dependency


<!-- Sent from Reviewable.io -->

2024-02-21 13:32 UTC, jolevesq reviewed
> Reviewed 22 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 44 of 54 files reviewed, 14 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 872 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAppARAOkhk3nl9zcp:-NrAppARAOkhk3nl9zcq:bq2w4ix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L872)):*
> ```XML
>     /*
>     let message = '';
>     switch (geoviewLayerInstance?.layerPhase) {
> ```

Change to layerStatus
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 676 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqIzqCypvzrIlaT2m:-NrAqIzqCypvzrIlaT2n:b-ow8p1r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L676)):*
> ```XML
>     // When we get here, we know that the metadata (if the service provide some) are processed.
>     // We need to signal to the layer sets that the 'processed' phase is done.
>     layerConfig.layerStatus = 'processed';
> ```

Setting both status one after the other, is it really doing something?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 381 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqUp83gYhuwKEl2NE:-NrAqUp83gYhuwKEl2NF:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L381)):*
> ```XML
>       // When we get here, we know that the metadata (if the service provide some) are processed.
>       // We need to signal to the layer sets that the 'processed' phase is done.
>       layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 215 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqan68megJFB2pkBU:-NrAqan68megJFB2pkBV:bbli2sl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L215)):*
> ```XML
>           this.layerLoadError.push({
>             layer: layerPath,
>             consoleMessage: `Empty layer group (mapId:  ${this.mapId}, layerPath: ${layerPath})`,
> ```

Change console by logger
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 268 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqnO7AbetmO9bDnD8:-NrAqnO7AbetmO9bDnD9:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L268)):*
> ```XML
>         // When we get here, we know that the metadata (if the service provide some) are processed.
>         // We need to signal to the layer sets that the 'processed' phase is done.
>         layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 609 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqq46E6nljbjR0Bp6:-NrAqq46E6nljbjR0Bp7:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L609)):*
> ```XML
>       // When we get here, we know that the metadata (if the service provide some) are processed.
>       // We need to signal to the layer sets that the 'processed' phase is done.
>       layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 274 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqrdy0DsJ09F4TEHv:-NrAqrdy0DsJ09F4TEHw:b-16m8gn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L274)):*
> ```XML
>         // When we get here, we know that the metadata (if the service provide some) are processed.
>         // We need to signal to the layer sets that the 'processed' phase is done.
>         layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts` line 204 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqwxc-smSDfPX58I4:-NrAqwxc-smSDfPX58I5:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts#L204)):*
> ```XML
>       // When we get here, we know that the metadata (if the service provide some) are processed.
>       // We need to signal to the layer sets that the 'processed' phase is done.
>       layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 246 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqyXe30tagPHb9Zxv:-NrAqyXe30tagPHb9Zxw:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L246)):*
> ```XML
> 
>         // When we get here, we know that the metadata (if the service provide some) are processed.
>         // We need to signal to the layer sets that the 'processed' phase is done.
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 261 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAr3b_EF5iwjC_mPZx:-NrAr3b_EF5iwjC_mPZy:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L261)):*
> ```XML
>       // When we get here, we know that the metadata (if the service provide some) are processed.
>       // We need to signal to the layer sets that the 'processed' phase is done.
>       layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 315 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrArFKKE2OWSYDNaI3M:-NrArFKKE2OWSYDNaI3N:b1h68q1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L315)):*
> ```XML
>       // When we get here, we know that the metadata (if the service provide some) are processed.
>       // We need to signal to the layer sets that the 'processed' phase is done.
>       layerConfig.layerStatus = 'processed';
> ```

Same as above, do we need both?
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 756 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrArNbh3klLB_dWN5vK:-NrArNbh3klLB_dWN5vL:b7ikss1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/map/map-schema-types.ts#L756)):*
> ```XML
>   [...]

2024-02-21 13:41 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 44 of 54 files reviewed, 15 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 132 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAtTAQDFUOW8hK1U0W:-NrAtTAQDFUOW8hK1U0X:b-5ovy5l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L132)):*
> ```XML
>         if (payloadIsGetAllLayerFeatures(payload)) {
>           // Log
>           logger.logTraceDetailed('feature-info-layer-set on EVENT_NAMES.GET_FEATURE_INFO.QUERY_ALL_FEATURES', this.mapId);
> ```

Revert to loggerCoreApiEvent because it is trigger by event


<!-- Sent from Reviewable.io -->

2024-02-21 13:44 UTC, jolevesq reviewed
> Reviewed 1 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 45 of 54 files reviewed, 17 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 199 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAtvh73nYo-kbk09Zh:-NrAtvh73nYo-kbk09Zi:b-j400y2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L199)):*
> ```XML
>         if (payloadIsAMapMouseEvent(payload)) {
>           // Log
>           logger.logTraceDetailed('feature-info-layer-set on EVENT_NAMES.MAP.EVENT_MAP_SINGLE_CLICK', this.mapId, payload);
> ```

Revert to loggerCoreApiEvent because it is trigger by event
Is this a duplicate of above logger?
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAu93a9h7MsijETPLf:-NrAu93a9h7MsijETPLg:b-crqg6u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L220)):*
> ```XML
>         if (payloadIsAMapMouseEvent(payload)) {
>           // Log
>           logger.logTraceDetailed('feature-info-layer-set on EVENT_NAMES.MAP.EVENT_MAP_POINTER_MOVE', this.mapId, payload);
> ```

Is this a duplicate of previous logger?


<!-- Sent from Reviewable.io -->

2024-02-21 13:47 UTC, jolevesq reviewed
> Reviewed 1 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 46 of 54 files reviewed, 19 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAuU5eAxLu34LT0Spz:-NrAuU5eAxLu34LT0Sq-:b-5ovy5l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L79)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceDetailed('layer-set on EVENT_NAMES.LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

Revert to loggerCoreApiEvent because it is trigger by event
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-NrAv0mg1sp8BcDYt-Sq:b-5ovy5l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L64)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceDetailed('legend-layer-set on EVENT_NAMES.LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

Revert to loggerCoreApiEvent because it is trigger by event


<!-- Sent from Reviewable.io -->

2024-02-21 13:48 UTC, jolevesq reviewed
> Reviewed 5 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 51 of 54 files reviewed, 19 unresolved discussions (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-02-21 17:57 UTC, Alex-NRCan reviewed
In the future, if a change like a `resultsSet` to a `resultSet` must be made, they should be in a distinct PR to really facilitate review.

> Reviewed 9 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-:-NrBjafi6gv0tCoNqNZv:b-r2c9t4)* status: 53 of 54 files reviewed, 28 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrB0FxZ4mKKCWEG5uVx:b-e0yg28) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
> ```XML
>         try {
>           // Await for the Geoview layer in loaded state
>           const myLayer = api.maps[mapId].layer.geoviewLayers[layerPathNodes[0]];
> ```

In general: why remove the async for this function? Could we just leave it async and await where it's called instead? Here:

this.resultsSet\[layerPath\].data \= legendInfo;
**await** LegendEventProcessor.propagateLegendToStore(this.mapId, layerPath, this.resultsSet\[layerPath\]);
api.event.emit(
    GetLegendsPayload.createLegendsLayersetUpdatedPayload(\`${this.mapId}/LegendsLayerSet\`, layerPath, this.resultsSet)
);

Also, if we remove async, it should be `api.maps[mapId].layer.getGeoviewLayerById(layerPathNodes[0]);`?
And should rewrite the line-comment if not awaiting anymore.

Also, this try catch seems useless now, as calculateBounds() already have a main try catch and it returns undefined when it fails (bounds variable remaining `undefined`) OR when it crashes, so I'd either remove this try catch here or in calculateBounds().

If we put this function sync, what happens when this code is executed and the layer isn't ready for its bounds to be calculated (`calculateBounds()` uses `getBounds()` which uses `getSource()`, it seems that if we don't wait anymore the bounds will just be undefined? Add a `if (!bounds) logDebug('failed')` in ` calculateBounds()` to confirm.
You can also check all the errors in the console when navigating here: https://ychoquet.github.io/GeoView/all-layers.html

This modification tells me the whole bounds calculation thing should be moved elsewhere!?

Also, and the following is unrelated to this function being async or not.
When logging the calculateBounds() function, for the same template page, one can see that the function is called about 160 times with this PR (whereas before it was called about 20 times). Is that expected?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrB7g87BcDPWKOgvc1Y:bef0z5x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If not needed anymore, should we remove dead code and dead dependency
</blockquote></details>

Are we not selecting a layer by default when the map loads anymore!?

This modification will about always give a 'Couldn't select a layer as none were processed in time' warning message and never set a selected layer path in the store upon load.. so all the logic should probably be flushed or moved elsewhere if that's what we want.

Also, if removing, should remove `propagatedOnce` and `timeDelayBeforeSelectingLayerInStore` attributes.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB9rDs9l1NlgadhrLe:-NrB9rDs9l1NlgadhrLf:bhaaf9p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1327)):*
> ```XML
>           })
>         | undefined;
>       logger.logDebug('getLegend:layerConfig=', layerConfig);
> ```

Please don't git-push 'logDebug' lines unless it's really something major for the whole team to debug.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 246 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBH20m1PmXhINrnCDP:-NrBH20n0-HUmmOtkonk:b-y9vzqb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L246)):*
> ```XML
>    */
>   protected processLayerMetadata(layerConfig: TypeTileLayerEntryConfig): Promise<TypeLayerEntryConfig> {
>     const promiseOfExecution = new Promise<TypeLayerEntryConfig>((resolve) => {
> ```

For clarity (and possibly apply to other `processLayerMetadata` functions), should rewrite this function to get rid of the Promise that's actually doing sync code anyways to something like:
if (!this.metadata...) return Promise.resolve(layerConfig)
else
layerConfig.layerStatus = something
return Promise.resolve(layerConfig)
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 576 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBE6N75xVqhTnnAr9p:-NrBE6N75xVqhTnnAr9q:b-muhugb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L576)):*
> ```XML
>    */
>   protected processLayerMetadata(layerConfig: TypeLayerEntryConfig): Promise<TypeLayerEntryConfig> {
>     const promiseOfExecution = new Promise<TypeLayerEntryConfig>((resolve) => {
> ```

For clarity (and possibly apply to other `processLayerMetadata` functions), should rewrite this function to get rid of the Promise that's actually doing sync code anyways to something like:
if (geoviewEntry....)
layerConfig.layerStatus = something
return Promise.resolve(layerConfig)
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts` line 201 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBCC4N1mitYOBv0icZ:-NrBCC4N1mitYOBv0ic_:b-fekr6b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts#L201)):*
> ```XML
>    */
>   protected processLayerMetadata(layerConfig: TypeVectorLayerEntryConfig): Promise<TypeLayerEntryConfig> {
>     const promiseOfExecution = new Promise<TypeLayerEntryConfig>((resolve) => {
> ```

For clarity (and possibly apply to other `processLayerMetadata` functions), should rewrite this function to something like:



_Code snippet:_
```XML
layerConfig.layerStatus = 'something'
return Promise.resolve(layerConfig);
```
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBKScmBoc9WfzEzQhf:-NrBKScmBoc9WfzEzQhg:borbtoa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L109)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceDetailed('legend-layer-set on EVENT_NAMES.LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

I believe this should be using loggerCoreApiEvent because it is trigger by event by mother class, right?

Review all 'logTraceDetailed' in this `feature-info-layer-set` class and `layer-set` class, basically. Some seem  [...]

2024-02-23 07:29 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 30 of 61 files reviewed, 28 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 478 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAjA6Y6GqukRUV1We6:-NrJrQ2t2MsQR180jIqd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/public/templates/layers/esri-feature.html#L478)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrHM0y51bxzwW7NbRft:b-mlz1hw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

In general: why remove the async for this function? Could we just leave it async and await where it's called instead? Here:

this.resultsSet\[layerPath\].data \= legendInfo;
**await** LegendEventProcessor.propagateLegendToStore(this.mapId, layerPath, this.resultsSet\[layerPath\]);
api.event.emit(
    GetLegendsPayload.createLegendsLayersetUpdatedPayload(\`${this.mapId}/LegendsLayerSet\`, layerPath, this.resultsSet)
);

Also, if we remove async, it should be `api.maps[mapId].layer.getGeoviewLayerById(layerPathNodes[0]);`?
And should rewrite the line-comment if not awaiting anymore.

Also, this try catch seems useless now, as calculateBounds() already have a main try catch and it returns undefined when it fails (bounds variable remaining `undefined`) OR when it crashes, so I'd either remove this try catch here or in calculateBounds().

If we put this function sync, what happens when this code is executed and the layer isn't ready for its bounds to be calculated (`calculateBounds()` uses `getBounds()` which uses `getSource()`, it seems that if we don't wait anymore the bounds will just be undefined? Add a `if (!bounds) logDebug('failed')` in ` calculateBounds()` to confirm.
You can also check all the errors in the console when navigating here: https://ychoquet.github.io/GeoView/all-layers.html

This modification tells me the whole bounds calculation thing should be moved elsewhere!?

Also, and the following is unrelated to this function being async or not.
When logging the calculateBounds() function, for the same template page, one can see that the function is called about 160 times with this PR (whereas before it was called about 20 times). Is that expected?
</blockquote></details>

As I mentioned in a previous meeting, the calculateBounds function must be move in an other place which will cause less call. This will be done in the next PR. By the time I read your comment, I already had remove the try/catch and I'll improve the stability in the next PR.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrHUDct5uLIo-jN01N5:b-u22zxk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Are we not selecting a layer by default when the map loads anymore!?

This modification will about always give a 'Couldn't select a layer as none were processed in time' warning message and never set a selected layer path in the store upon load.. so all the logic should probably be flushed or moved elsewhere if that's what we want.

Also, if removing, should remove `propagatedOnce` and `timeDelayBeforeSelectingLayerInStore` attributes.
</blockquote></details>

I must adjust the code here for the selected layer. I'll do that in a quick and little PR right after this one.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 872 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAppARAOkhk3nl9zcp:-NrHY4wAB_QHXj3gsF4M:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L872)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Change to layerStatus
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 676 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqIzqCypvzrIlaT2m:-NrHY9lw0ZDb_lOaXVrI:brv6wgy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L676)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Setting both status one after the other, is it really doing something?
</blockquote></details>

Yes, the layerStatus is doing a lot of thins behind the scene. I added a comment to explaine what's going on here.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB9rDs9l1NlgadhrLe:-NrH_60O3QkwyFezMI3q:b-phjkgj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1327)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Please don't git-push 'logDebug' lines unless it's really something major for the whole team to debug.
</blockquote></details>

Yes, I know. By the time I read your comment, I already had cleaned up my code from useless logDebug.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 381 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqUp83gYhuwKEl2NE:-NrH_eAL1X4c-sMbqNhZ:b-4m5i21) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L381)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as above, do we need both?
</blockquote></details>

Absolutely, I improved the comment and moved the second affectation to processOneLayerEntry for less ambiguity.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 215 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAqan68megJFB2pkBU:-NrHaN79EGPCF4s3OI8m:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L215)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Change console by logger
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 246 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBH20m1PmXhINrnCDP:-NrHphqE94SWZzr16AoX:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geovie [...]

2024-02-23 13:02 UTC, jolevesq requested changes
> Reviewed 5 of 21 files at r2, 25 of 29 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 59 of 61 files reviewed, 22 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 777 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrKx3OK9wG6ePbUcpQi:-NrKx3OK9wG6ePbUcpQj:b-qdtxbc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L777)):*
> ```XML
>    */
>   protected processOneLayerEntry(layerConfig: TypeBaseLayerEntryConfig): Promise<BaseLayer | null> {
>     // ! IMPORTANT: The processOneLayerEntry method of all the childre must call this method to ensure that the flow of
> ```

Typo childre
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 244 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrKy4tyE9ntAfjxH0Im:-NrKy4tyE9ntAfjxH0In:b-p1hjj1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L244)):*
> ```XML
>   /** ***************************************************************************************************************************
>    * This method is used to process the layer's metadata. It will fill the empty fields of the layer's configuration (renderer,
>    * initial settings, fields and aliases). This routine must imperatively ends with layerConfig.layerStatus = 'processed' and
> ```

Here you say it must end with status to processed and loading but below at the end of the function, loading status has been removed
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 756 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrArNbh3klLB_dWN5vK:-NrL0FbJ9mRyZpnGXrdD:bta6eg1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/map/map-schema-types.ts#L756)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

LayerPhase is a debugging property that is intended to guide the developpers to the code that failed when an error occurs. It must not be used as operationnal property in the code. Since the arrival of the logger, I believe that we should completely eliminate it because I saw code using it to make a decision on what shoud be done in the viewer. The logger does a better job. I propose to delete it completely. If you aggree, let me know and I'll delete it in my next PR.
</blockquote></details>

Yes, I think we should delete
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 784 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0JFO7ZfLwdHH26o_:-NrL0JFO7ZfLwdHH26oa:b8zkbwv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L784)):*
> ```XML
>     if (!this.IsGreaterThanOrEqualTo(newLayerStatus)) {
>       this._layerStatus = newLayerStatus;
>       this.geoviewLayerInstance!.setLayerPhase(newLayerStatus, this.layerPath);
> ```

This setLayerPhase  is something that will be remove later (comment about still using layerPhase?)
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0yG5AuYFZa8nySbI:-NrL0yG5AuYFZa8nySbJ:bmsuwbb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-viewer.ts#L185)):*
> ```XML
>     if (this.layer === undefined) return false;
>     return !Object.keys(this.layer.geoviewLayers).find((geoviewLayerId) => {
>       return !this.layer.geoviewLayers[geoviewLayerId].allLayerStatusAreGreaterThanOrEqualTo('loaded');
> ```

Why use loaded instead of processed here?
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAu93a9h7MsijETPLf:-NrL1GoB-0jKZUdlm2ET:bygcfew) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L220)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we should keep the one outside of the so if payload is bad we will be able to see the value in console. If not we will nerve know the event has been triggered
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 110 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL1dzeAfyMKulqfj9E:-NrL1dzeAfyMKulqfj9F:b9os82k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L110)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceCoreAPIEvent('feature-info-layer-set on EVENT_NAMES.LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

Naming convention for the logger is the caller caps FEATURE-INFO_LAYER_SET on ....
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-NrL2A6_2Y0mNuFr7sN1:bfib36b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Logger is called in the callback function above.
</blockquote></details>

Because it checks the payload, logger may never be triggered. Would be better to have them outside the payload check so den can see payload result
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 79 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL1rg20HRtt8KNixJN:-NrL1rg20HRtt8KNixJO:b-axhvac) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/layer-set.ts#L79)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceCoreAPIEvent('layer-set on EVENT_NAMES.LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

Naming convention for logger is first param caps LAYER_SET on ...
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 67 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL2TU155g06boie3YG:-NrL2TU155g06boie3YH:b8gmeua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L67)):*
> ```XML
>     if (payloadIsLayerSetChangeLayerStatus(payload)) {
>       // Log
>       logger.logTraceCoreAPIEvent('legend-layer-set on LAYER_SET.CHANGE_LAYER_STATUS', this.mapId, payload);
> ```

Naming convention for logger, first param caps LEGEND-LAYER-SET on ...


<!-- Sent from Reviewable.io -->

2024-02-23 15:10 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 59 of 61 files reviewed, 24 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 317 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLVwunE0iRAWsenHJ1:-NrLVwunE0iRAWsenHJ2:b-b11cr6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L317)):*
> ```XML
>       // We need to signal to the layer sets that the 'processed' phase is done. Be aware that the
>       // layerStatus setter is doing a lot of things behind the scene.
>       layerConfig.layerStatus = 'processed';
> ```

It took me a while to understand the setter does not only set a value but apply a function. I think it would be cleaner to have areal function because it is not only a setter.


<!-- Sent from Reviewable.io -->

2024-02-23 15:18 UTC, Alex-NRCan requested changes
> Reviewed 1 of 29 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 18 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrLEsrO1l9zpws--UH9:bmozgts) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

As I mentioned in a previous meeting, the calculateBounds function must be move in an other place which will cause less call. This will be done in the next PR. By the time I read your comment, I already had remove the try/catch and I'll improve the stability in the next PR.
</blockquote></details>

If the cleaning up is immediately done in a following PR, okay. I'd suggest adding a TODO meanwhile. This can be resolved right now, as long as the overflowing calls to calculateBounds() aren't breaking anything.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrLEI-K5-YuRKUvSS-f:byooov8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I must adjust the code here for the selected layer. I'll do that in a quick and little PR right after this one.
</blockquote></details>

If the cleaning up is immediately done in a following PR, okay. I'd suggest adding a TODO, because, reading this, I was wondering why leaving useless code.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 772 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLS9da68zTUgaM9D3G:-NrLS9da68zTUgaM9D3H:b-dsw970) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L772)):*
> ```XML
>    * @param {string} newLayerStatus The new layerId value.
>    */
>   set layerStatus(newLayerStatus: TypeLayerStatus) {
> ```

This setter handles quite a bit of additional logic that goes beyond simply validating the `newLayerStatus`. For clarity and expectations, I'd recommend to refactor this setter in a method which processes the all the logic you want to implement here.
In any case, due to the amount of code relying on this, I'd suggest to comment the code a lot more. Every line.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-NrLH7qX8RUIuNcr_ACY:bn83atn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because it checks the payload, logger may never be triggered. Would be better to have them outside the payload check so den can see payload result
</blockquote></details>

(1) I'd log it before checking the payload indeed like Johann is suggesting
(2) You're right that it's being logged in the external function. Might as well fix that right away. The log call should be moved to where the event handle actually is (wheres I was expecting to read it) instead of inside another method. The reason for this is that the function might be repurposed eventually or worse it might not be the 'first' method called inside the handle anymore eventually.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-NrLIlDk95XNtjjvDVsK:bmk35o7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L64)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should move the logger call to the actual place where the event is handled (see other comment for details).


<!-- Sent from Reviewable.io -->

2024-02-23 15:32 UTC, Alex-NRCan requested changes
> Reviewed 22 of 54 files at r1, 2 of 29 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 20 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 387 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL_iN8BtgoEYE871Y4:-NrL_iN8BtgoEYE871Y5:b-j78rs1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L387)):*
> ```XML
>     } catch (error) {
>       layerConfig.layerStatus = 'error';
>       console.log(error);
> ```

Should use logger here
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 194 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL_qS93mc2YGR24DBG:-NrL_qS93mc2YGR24DBH:b-y01uqd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L194)):*
> ```XML
>       showError(this.mapId, `Error: vector tile layer (${layerConfig.layerId}) projection does not match map projection`);
>       // eslint-disable-next-line no-console
>       console.log(`Error: vector tile layer (${layerConfig.layerId}) projection does not match map projection`);
> ```

Should be logger here


<!-- Sent from Reviewable.io -->

2024-02-23 15:36 UTC, Alex-NRCan requested changes
> Reviewed 2 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 21 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 519 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLauGjEfv2BpbNd_Qi:-NrLauGjEfv2BpbNd_Qj:b40pno) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/layer.ts#L519)):*
> ```XML
>    * @throws an exception when the layer failed to become in processed phase before the timeout expired
>    */
>   waitForProcesseOrErrorStatus = async (
> ```

Should rename the function here to align with the new logic


<!-- Sent from Reviewable.io -->

2024-02-23 15:49 UTC, Alex-NRCan requested changes
> Reviewed 1 of 21 files at r2, 13 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 23 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 62 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLdqtX-8onvALXOxdI:-NrLdqtYDXVpXs_M1mYU:bs700q3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L62)):*
> ```XML
>     this.registrationConditionFunction = (layerPath: string): boolean => {
>       // Log
>       logger.logTraceCore('FeatureInfoLayerSet registration condition...', layerPath, Object.keys(this.resultSet));
> ```

Maybe we want to keep the standard elsewhere and capitalize this?
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 77 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLdwye5fwkE2nz_E_f:-NrLdwye5fwkE2nz_E_g:bs700q3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L77)):*
> ```XML
>     this.registrationUserInitialisation = (layerPath: string) => {
>       // Log
>       logger.logTraceCore('FeatureInfoLayerSet initializing layer path...', layerPath, Object.keys(this.resultSet));
> ```

Maybe we want to keep the standard elsewhere and capitalize this?


<!-- Sent from Reviewable.io -->

2024-02-23 15:51 UTC, Alex-NRCan requested changes
> Reviewed 1 of 54 files at r1, 1 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 24 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 233 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLeC5a2PNv1WLNIyNI:-NrLeC5a2PNv1WLNIyNJ:bq2xwge) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L233)):*
> ```XML
>       (payload) => {
>         // Log
>         logger.logTraceCoreAPIEvent('feature-info-layer-set - QUERY_RESULT', this.mapId, payload);
> ```

Capitalize?


<!-- Sent from Reviewable.io -->

2024-02-23 18:52 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 48 of 61 files reviewed, 24 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrLvmf85A7xoAT7p3qT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

If the cleaning up is immediately done in a following PR, okay. I'd suggest adding a TODO meanwhile. This can be resolved right now, as long as the overflowing calls to calculateBounds() aren't breaking anything.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrLw7vz5UhXsJ4tXpXb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

If the cleaning up is immediately done in a following PR, okay. I'd suggest adding a TODO, because, reading this, I was wondering why leaving useless code.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 519 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLauGjEfv2BpbNd_Qi:-NrLwedY583fsbA9zV2l:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/layer.ts#L519)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should rename the function here to align with the new logic
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 777 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrKx3OK9wG6ePbUcpQi:-NrLJTUlAXsmK7AtpRHz:b-896fja) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L777)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo childre
</blockquote></details>

Done!
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 387 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL_iN8BtgoEYE871Y4:-NrLxRt43RCXzyRSa8fm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L387)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should use logger here
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 194 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL_qS93mc2YGR24DBG:-NrMFUWFBKSx2-_Sr053:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L194)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should be logger here
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 244 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrKy4tyE9ntAfjxH0Im:-NrM2yXT-nz1XN8w2Zh0:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L244)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Here you say it must end with status to processed and loading but below at the end of the function, loading status has been removed
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 317 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLVwunE0iRAWsenHJ1:-NrM347M9QIiN-cL4rH1:b910er1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L317)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It took me a while to understand the setter does not only set a value but apply a function. I think it would be cleaner to have areal function because it is not only a setter.
</blockquote></details>

As I explained in the scrum, it was before and some developpers was not aware that they imperatively had to use the method in order that the viewer works properky. Using a setter to make sure the essential code execution is done is the safest way to do what must be done. This is not the first time we use a setter in this way.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 756 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrArNbh3klLB_dWN5vK:-NrLGcmU3sErp5hvbOV8:bvb6llh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/map/map-schema-types.ts#L756)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes, I think we should delete
</blockquote></details>

I'll do that in my next PR
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 772 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLS9da68zTUgaM9D3G:-NrM4Dbl4Ric83bl-DJx:bi0d9zt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L772)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This setter handles quite a bit of additional logic that goes beyond simply validating the `newLayerStatus`. For clarity and expectations, I'd recommend to refactor this setter in a method which processes the all the logic you want to implement here.
In any case, due to the amount of code relying on this, I'd suggest to comment the code a lot more. Every line.
</blockquote></details>

Documentation will be added, but as explained above, using a method to do the work is not the safest way. It happened in the past that developpers directly set the layerStatus to a new value without using the mandatory call to the method. Using this method enforce the rule. It is not the first time we use this strategy in our code.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 784 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0JFO7ZfLwdHH26o_:-NrLK4gd1X9jyJCXkqVE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L784)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This setLayerPhase  is something that will be remove later (comment about still using layerPhase?)
</blockquote></details>

Done.
___
*[`pack [...]

2024-02-23 20:32 UTC, Alex-NRCan requested changes
> Reviewed 2 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 48 of 61 files reviewed, 17 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrM_xAt7PhqY--Z5w6-:b-fdjqvk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The attribute `timeDelayBeforeSelectingLayerInStore` is still there, I'd suggest to remove it, because now nothing points to it at all and could easily be forgotten in a further refactor.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 772 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLS9da68zTUgaM9D3G:-NrMc-tI-ib_HNr_rBZP:bo5znra) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L772)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Documentation will be added, but as explained above, using a method to do the work is not the safest way. It happened in the past that developpers directly set the layerStatus to a new value without using the mandatory call to the method. Using this method enforce the rule. It is not the first time we use this strategy in our code.
</blockquote></details>

What I'm suggesting would still enforce people to use the method to enforce the rule..


<!-- Sent from Reviewable.io -->

2024-02-23 21:18 UTC, jolevesq requested changes
> Reviewed 9 of 13 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 57 of 61 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrMdB_PATGo6VNZ4vAR:b-ffacwp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For bounds.... I refresh the layer multiple times and bound are not always assign to the same layer. I have GEoJSON line undefined, then refresh and it is polygon. at the end of your loaded status, could it be a good place to set so it is not undefined by default? Can it be recall on highlight or zoom press if there were a a problem at the first place and if so inform user.

This can be done in a next PR with a comment
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 772 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLS9da68zTUgaM9D3G:-NrMeuJmE5Inbr_-CdBn:brem4cl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L772)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

What I'm suggesting would still enforce people to use the method to enforce the rule..
</blockquote></details>

Correct me Yves if I am wrong but we can make layerStatus a protected property that is only settable by the function processLayerStatus (because it is not just assigning, there other stuff). This would be clean and use cannot set layerStatus without using the function. I really do not like the set as function as it is not explicit. It was a function before and put the attribute private or protected. Using set and get like in config validation 154-162 is fine as it does what it means to do.

If we use the same strategy elsewhere I think we should put a TODO and revise later.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 786 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLMoQn2koJUo-PBeVm:-NrMj-ZA6RH_1NAi42lT:b-js5nt6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L786)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

When you trace an event's code, you'll realize that it's almost the same thing as a method call. What you need to know here is that the call to the listeners is not deferred far down the execution thread. All listeners are called immediately. The difference between a method and an event is that the method uses parameters and can be called directly if it's visible to the section of code you're executing. The event uses a callback and payload instead, and the call is made through an event emitter. Of course, it's possible to call the callback function directly if it's not coded as an anonymous function, but that's not what we want to do here. When you use an event, anyone interested in that event simply has to listen to it. There's no need to modify the code where the event occurs and make an additional direct call to the person interested in the event. So yes, we could do a pirouette and arrange a double flavor to propagate the layerStatus update to layerSet instances, but this would be at the cost of increased complexity that isn't necessary.
</blockquote></details>

Why other process would like to listen to this event? I think we should try to have a more direct link to the caller and the function who does the job. I get your point for a mouse move event that will be listen by multiple components but in this case it is targeted to something else more?

We will have to revise some of our events like, create panel, tabs, ... that can be manage in a more straightforward way. By doing so we will revise all of them. Events is a nice way to communicate easily but we will need to understand a little bit more who is/are the listener and the purpose.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0yG5AuYFZa8nySbI:-NrMnCg09TFzkbwQiuGA:byker6p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-viewer.ts#L185)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

allLayerStatusAreGreaterThanOrEqualTo('loaded'); returns true even if it finds layer in erro
</blockquote></details>

Yes but for layer stuck in prior status, UI hangs like in all-layer.html
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-NrMoHvjAd1Gu6beXOIw:b-cf5rgs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

1- It is outside. The listener is called after the logger.
2- We are in a parent class here, and this method is inherited by legendLayerSet and FeatureInfoLayerSet. In OO language, when a child do the same thing the parent does, it does not  create a copy of the code from the parent in its instance. It inherit it. Allso, the listener of the child class is doing things specific to him and call the parent method of the same name in the parent which does the things specific to the parent. I strongly suggest to leave things the way they are.
</blockquote></details>

We need the logger for the API event so this is the first call like in other API event. If we need other logger inside function once payload are validated, they can be traceCore or something else.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-NrMp4rmEVCgYLOV-bpA:b-8ki2zi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L64)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same answer as above. As discussed in the scrum, more documentation will be added to clearly explain what happens here
</blockquote></details>

This logger is not the API event, more a logTrace


<!-- Sent from Reviewable.io -->

2024-02-26 02:01 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 57 of 61 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrB0FxY7X-z9qei35vX:-NrSEv0qB8Smtu0ZF76O:bpbkoiu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For bounds.... I refresh the layer multiple times and bound are not always assign to the same layer. I have GEoJSON line undefined, then refresh and it is polygon. at the end of your loaded status, could it be a good place to set so it is not undefined by default? Can it be recall on highlight or zoom press if there were a a problem at the first place and if so inform user.

This can be done in a next PR with a comment
</blockquote></details>

When I write "Done, I mean I added the TODO in the code.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAocURBWxSLmS1qxlG:-NrN5jsr3sVRpapvBHkV:b-r46pt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L245)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

The attribute `timeDelayBeforeSelectingLayerInStore` is still there, I'd suggest to remove it, because now nothing points to it at all and could easily be forgotten in a further refactor.
</blockquote></details>

will be done in the next PR.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 772 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLS9da68zTUgaM9D3G:-NrN67FH91rac4EdHnso:b-d7cd5q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L772)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Correct me Yves if I am wrong but we can make layerStatus a protected property that is only settable by the function processLayerStatus (because it is not just assigning, there other stuff). This would be clean and use cannot set layerStatus without using the function. I really do not like the set as function as it is not explicit. It was a function before and put the attribute private or protected. Using set and get like in config validation 154-162 is fine as it does what it means to do.

If we use the same strategy elsewhere I think we should put a TODO and revise later.
</blockquote></details>

I think this is a good idea. An other thing to do in the next PR. I just hope I wont drop one.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 786 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLMoQn2koJUo-PBeVm:-NrN6aqP9KPMMuRSv3me:b-64cn5c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L786)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why other process would like to listen to this event? I think we should try to have a more direct link to the caller and the function who does the job. I get your point for a mouse move event that will be listen by multiple components but in this case it is targeted to something else more?

We will have to revise some of our events like, create panel, tabs, ... that can be manage in a more straightforward way. By doing so we will revise all of them. Events is a nice way to communicate easily but we will need to understand a little bit more who is/are the listener and the purpose.
</blockquote></details>

Your right, we can decide that the layerStatus is an internal property intended only for the viewer. I do not see a reason why a user would like to be inform that its vaue has changed.Should we create an issue or write a TODO that says it will be done in the next PR?
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0yG5AuYFZa8nySbI:-NrN8pOaBkPTtoJKA150:b-txzfw4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-viewer.ts#L185)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes but for layer stuck in prior status, UI hangs like in all-layer.html
</blockquote></details>

This should not happen if the sequence of values for this indicator is coded correctly. If the viewer stalls, then we haven't done our job properly. The "processed" value must imperatively be set in the processLayerMetadata method. You must ensure that it is called on every layerConfig that is not a group. The "loading" value must imperatively be assigned at the start of the processOneLayerEntry method, and you must ensure that it is called on every layerConfig that is not a group. Then, somewhere in the execution thread used by the processOneLayerEntry method, you must set up two Openlayers listeners (one for 'loaded' and one for 'error'; OL doesn't provide these listeners for GroupLayer). These two listeners will end the layerStatus sequence with 'loaded' or 'error'. A  setter olLayerAndLoadEndListeners has been created to do so. If you don't follow this logic, you're bound to run into problems. If you overwrite the methods from the parent, you must respect these rules. All this should be documented in our repo, but for the moment, all our energy goes to the implementation.

If you prefere, I can replace the olLayerAndLoadEndListeners with a method and make olLayer protected as we will do for the layerStatus.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-NrSFK7_B50XAXSwhDJx:b-pph68y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need the logger for the API event so this is the first call like in other API event. If we need other logger inside function once payload are validated, they can be traceCore or something else.
</blockquote></details>

Not sure I understand what you want here. There is a logger in the listener function right before the test on the payload is done so the child logs that its method was called. Then, when the child calls the parent method, the parent logs that its method was called before doing the test on the payload. I can add a log here saying that the mehtod that create the listener (the api.event.on) was executed if you want, but do not confuse the listener creation with the listener execution. If you do a search in all files in the project, there is no logger call to indicate that we have created a listener on a specific event.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-NrZ1sWFDS1Uze5xH2Pm:b-f9kpv8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e [...]

2024-02-26 14:58 UTC, jolevesq requested changes
> Reviewed 3 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 59 of 61 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 317 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLVwunE0iRAWsenHJ1:-Nr_ryY53EMoQ9mfyMyz:bee091) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L317)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

As I explained in the scrum, it was before and some developpers was not aware that they imperatively had to use the method in order that the viewer works properky. Using a setter to make sure the essential code execution is done is the safest way to do what must be done. This is not the first time we use a setter in this way.
</blockquote></details>

I will create an issue to revisit this approach
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 786 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLMoQn2koJUo-PBeVm:-Nr_sM7M32CNojTV9woK:buw948t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L786)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Your right, we can decide that the layerStatus is an internal property intended only for the viewer. I do not see a reason why a user would like to be inform that its vaue has changed.Should we create an issue or write a TODO that says it will be done in the next PR?
</blockquote></details>

You can add a TODO.... I will create an issue as well as part of some events rethinking
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0yG5AuYFZa8nySbI:-Nr_t4R74bdKyjr3mwh2:bx9po9b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-viewer.ts#L185)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This should not happen if the sequence of values for this indicator is coded correctly. If the viewer stalls, then we haven't done our job properly. The "processed" value must imperatively be set in the processLayerMetadata method. You must ensure that it is called on every layerConfig that is not a group. The "loading" value must imperatively be assigned at the start of the processOneLayerEntry method, and you must ensure that it is called on every layerConfig that is not a group. Then, somewhere in the execution thread used by the processOneLayerEntry method, you must set up two Openlayers listeners (one for 'loaded' and one for 'error'; OL doesn't provide these listeners for GroupLayer). These two listeners will end the layerStatus sequence with 'loaded' or 'error'. A  setter olLayerAndLoadEndListeners has been created to do so. If you don't follow this logic, you're bound to run into problems. If you overwrite the methods from the parent, you must respect these rules. All this should be documented in our repo, but for the moment, all our energy goes to the implementation.

If you prefere, I can replace the olLayerAndLoadEndListeners with a method and make olLayer protected as we will do for the layerStatus.
</blockquote></details>

Can you do what is needed for this to work. If it is to add a a time out on the splash screen, we can do it for now and revisit. It is working ok when we do not have the Natural Earth Geopackages layer.... We need to speed up the time required to show the map
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-Nr_tqkr6JijsnN7BNnv:b-wjoc9z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Not sure I understand what you want here. There is a logger in the listener function right before the test on the payload is done so the child logs that its method was called. Then, when the child calls the parent method, the parent logs that its method was called before doing the test on the payload. I can add a log here saying that the mehtod that create the listener (the api.event.on) was executed if you want, but do not confuse the listener creation with the listener execution. If you do a search in all files in the project, there is no logger call to indicate that we have created a listener on a specific event.
</blockquote></details>

You are right, the call is not for the listener, it is for the coreAPIEvent. Every API.on has a looger coreAPIEvent as its first line with the payload in param.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-Nr_uOKf9iEEO29gYARo:bdkwemd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L64)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I think this logger is an API event because it is in an event listener. If it is not the case, many of the event listeners (if not all) have the same problem. Moreover, In this PR you ased to move the logger call before the the payload test, but if you do a search, many of the event listeners (if not all) call the logger in the then section of the payload test.  I don't know what you consider the most important. Is it the fact that the listener was call and if the payload is rejected, you have no log infornation to warn you. Is it the fact that the payload was accepted and if it is rejected you have no log information to warn you. If you want both, we will have to modify the logger calls of all our event listener, because none of them is doing so.
</blockquote></details>

If they are in payload test, they will need to be fixed because it is wrong. We want to know when API is triggered. Then in the listener, if there info to log we can add a trace logger. Listener does not have to always have a logger inside... depends what they are doing.


<!-- Sent from Reviewable.io -->

2024-02-26 16:19 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 59 of 61 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 317 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLVwunE0iRAWsenHJ1:-Nr_xNYl1uj_gRKLUNTm:b2nhlkw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L317)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I will create an issue to revisit this approach
</blockquote></details>

Ok!
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 786 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrLMoQn2koJUo-PBeVm:-NraApHpAGBtcP9yHp0Q:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-schema-types.ts#L786)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can add a TODO.... I will create an issue as well as part of some events rethinking
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrL0yG5AuYFZa8nySbI:-NraBGEb-9wkBIzKWqMC:b-aca9r0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1a728bad3da684f30ce88f27fce06f0739827767/packages/geoview-core/src/geo/map/map-viewer.ts#L185)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you do what is needed for this to work. If it is to add a a time out on the splash screen, we can do it for now and revisit. It is working ok when we do not have the Natural Earth Geopackages layer.... We need to speed up the time required to show the map
</blockquote></details>

I think we should merge now even if we still have issues in some other area of the viewer. This PR resolve many issue in different part of it and doing repetitive rebase is not a good thing.  I'll look at the issue you refer to in priority in my next PR
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrBUkn04Zmbe9LoAqGh:-Nr_yLnE27uhiKR8p4G8:b2nhlkw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/layer-set.ts#L115)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are right, the call is not for the listener, it is for the coreAPIEvent. Every API.on has a looger coreAPIEvent as its first line with the payload in param.
</blockquote></details>

Ok!
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrAv0mg1sp8BcDYt-Sp:-Nr_yefj26uuwCax8ewO:b2nhlkw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63030bb1c1150a8636981d4ab983aee415ef940e/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If they are in payload test, they will need to be fixed because it is wrong. We want to know when API is triggered. Then in the listener, if there info to log we can add a trace logger. Listener does not have to always have a logger inside... depends what they are doing.
</blockquote></details>

Ok!


<!-- Sent from Reviewable.io -->

2024-02-27 17:28 UTC, jolevesq reviewed
> Reviewed 1 of 2 files at r6, 13 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: 59 of 61 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 94 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrfaMcwBQvTjMk1q4Gl:-NrfaMcwBQvTjMk1q4Gm:b-jixg4i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dfeb2eb9337aee694d370a77487cfbcda3df4a71/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L94)):*
> ```XML
>       (payload) => {
>         // Log
>         logger.logTraceCoreAPIEvent('legends-layer-set - GET_LEGENDS.LEGEND_INFO', this.mapId, payload);
> ```

This is suppose to be capitalize, please take a note for next PR
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 119 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829#-NrfaWCZ9hCLJVsBo_eY:-NrfaWCZ9hCLJVsBo_eZ:b-jixg4i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dfeb2eb9337aee694d370a77487cfbcda3df4a71/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L119)):*
> ```XML
>       (payload) => {
>         // Log
>         logger.logTraceCoreAPIEvent('legends-layer-set - LAYER_SET.UPDATED', this.mapId, payload);
> ```

This is suppose to be capitalize, please take a note for next PR


<!-- Sent from Reviewable.io -->

2024-02-27 17:49 UTC, jolevesq approved these changes
> Reviewed 1 of 54 files at r1, 2 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1829)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-02-27 17:55 UTC, DamonU2 approved these changes

2024-02-27 17:58 UTC, merged