clean(eslint): Clean global esLint comment to have them more inline
Canadian-Geospatial-Platform/geoview pull request #1865
Opened 2024-02-27 21:00 UTC by jolevesq

Closes #1859

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1859

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
https://jolevesq.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-02-27 21:19 UTC, Alex-NRCan requested changes
> Reviewed 53 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: 53 of 66 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 389 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOXh7CZF2PfR_2o23:-NrgOXh7CZF2PfR_2o24:b4q47bu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L389)):*
> ```XML
>  */
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export function parseJSONConfig(configObjStr: string): any {
> ```

Maybe return unknown? Not sure
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 585 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOKduD0vAwltXIYDO:-NrgOKduD0vAwltXIYDP:b712zpz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L585)):*
> ```XML
>   checkCallback: () => T,
>   doCallback: (value: T) => void,
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
> ```

Good example where an 'any' was missed.
I'd remove the eslint-disable and put 'unknown' instead.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 621 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOSpa9IOoOUmuXOXq:-NrgOSpa9IOoOUmuXOXr:b712zpz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L621)):*
> ```XML
>   checkCallback: () => T,
>   doCallback: (value: T) => void,
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
> ```

Good example where an 'any' was missed.
I'd remove the eslint-disable and put 'unknown' instead.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPA8oAM1ga29rhSXh:-NrgPA8oAM1ga29rhSXi:bd487b7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L3)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerConfig. We keep it global...
> // eslint-disable-next-line max-classes-per-file
> ```

Do we have a lot of max-classes-per-file global?
I'd personally like it if we could address them all at some point. To clarify and help when searching for stuff around the code.
Maybe a TODO for them or we just search for them later
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPahMBzX7okUnjhY4:-NrgPahMBzX7okUnjhY5:b4gvu7a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/geo/map/map-schema-types.ts#L2)):*
> ```XML
> /* eslint-disable no-underscore-dangle */
> // We use _ for layerPAtha nd olLayer all over the file. We keep it global...
> ```

Typos here
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPqN69BqyFmlfYzmK:-NrgPqN71XUmnID43MFq:bqhnbg6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/ui/panel/panel.tsx#L335)):*
> ```XML
>                 </>
>               ) : (
>                 // eslint-disable-next-line react/jsx-no-useless-fragment
> ```

Should remove the single-line comment from here, because it's part of the 'render' code and that's causing known issues with react in production setup (when it cleans the code and comments out for a production build). I've had it happen to me in the past and took a while to figure out.
It's a known issue, like here for example: https://github.com/facebook/create-react-app/issues/9507

It's hard to find, because it works locally, just doesn't work in a production deployment(!)
___
*[`packages/geoview-layers-panel/src/layers-list.tsx` line 342 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgQ_4gAaXsE1Vp-U6P:-NrgQ_4h8quj9LWfuVro:bhuuxy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-layers-panel/src/layers-list.tsx#L342)):*
> ```XML
>               </Box>
>               {(layerLegend[layer.geoviewLayerId] as TypeJsonArray).map((subLayer, index: number) => (
>                 // eslint-disable-next-line react/no-array-index-key
> ```

Should remove the single-line comments from here and the below 2 other lines (ref. see other comment)


<!-- Sent from Reviewable.io -->

2024-02-28 22:07 UTC, DamonU2 requested changes
> Reviewed 6 of 66 files at r1, 46 of 46 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 22 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrletrHAemwRfVPu-QU:-NrletrHAemwRfVPu-QV:b-2zlk1w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/config/config-validation.ts#L2)):*
> functions with dangle and many reassigns
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlfptq3xbTFqiT4AEG:-Nrlfptq3xbTFqiT4AEH:b-xfx9dh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerPath-layerConfig. We keep it global..
> ```

reassing > reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlfvg40uodWIDeNabc:-Nrlfvg40uodWIDeNabd:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerPath-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlg3C86OTizcxenq-L:-Nrlg3C86OTizcxenq-M:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerPath-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 272 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlhHac4Lb1fUf9VeSC:-NrlhHac4Lb1fUf9VeSD:be0ehs5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L272)):*
> ```XML
>     geometryFieldName: string,
>     fields: TypeJsonArray,
>     layerConfig: EsriFeatureLayerEntryConfig | TypeEsriDynamicLayerEntryConfig | TypeEsriImageLayerEntryConfig // TODO: see why we have dynamic and inage in a feature class...
> ```

This was just so that I could reuse common methods in the image layers
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlh_0E3COpKbf_ncKQ:-Nrlh_0E3COpKbf_ncKR:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerPath-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlj0439A88pRUMjXni:-Nrlj0439A88pRUMjXnj:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layer-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljEdD9bOp0_P0MjzK:-NrljEdD9bOp0_P0MjzL:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljJtX5MhrcFMs4XIf:-NrljJtX5MhrcFMs4XIg:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for sourceOptions-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljPodE-L4mnklWm0S:-NrljPoeAICxB1-Ms-gG:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for sourceOptions. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljS2o4dWatdR0urgM:-NrljS2o4dWatdR0urgN:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for sourceOptions-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljUco8SDjiHq2I7uR:-NrljUco8SDjiHq2I7uS:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for sourceOptions-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljX61DTD-KLLvh7xp:-NrljX61DTD-KLLvh7xq:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for sourceOptions-layerConfig. We keep it global...
> ```

*reassign
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljaTf2mubVXiFgsID:-NrljaTf2mubVXiFgsIE:b-5indy1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L2)):*
> ```XML
> /* eslint-disable no-param-reassign */
> // We have many reassing for source [...]

2024-02-28 22:10 UTC, ychoquet requested changes
> Reviewed 44 of 66 files at r1, 46 of 46 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 30 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/webpack.common.js` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrl_-Uo5OY3PDxcm_e-:-Nrl_-Uo5OY3PDxcm_e0:blyhn9i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/webpack.common.js#L5)):*
> ```JavaScript
> const webpack = require('webpack');
> const path = require('path');
> const HtmlWebpackPlugin = require('html-webpack-plugin');
> ```

Wouldn't it be better to mark every line that needs to disable no-var-requires as we said in the scrum. The idea is to clearly identify the targeted lines. If we define it globally, anyone could insert code that would normally be detected, but will go unnoticed because of the global definition.
___
*[`packages/geoview-core/webpack.dev.js` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlaem688voZr_HlMBA:-Nrlaem688voZr_HlMBB:bqfkdfx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/webpack.dev.js#L5)):*
> ```JavaScript
> const path = require('path');
> const { merge } = require('webpack-merge');
> const common = require('./webpack.common');
> ```

Same as mentioned above
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 388 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrldXpgBj4rHiIT_Uyb:-NrldXpgBj4rHiIT_Uyc:bzdzorc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/utilities.ts#L388)):*
> ```XML
>  * @returns {any} cleaned and parsed config object
>  */
> export function parseJSONConfig(configObjStr: string): unknown {
> ```

What is the purpose of sandbox.html. The function parseJSONConfig is only used by this HTML code, and if it is a place to test and play with code and ideas without using it in the viewer, maybe we should delete the function.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 610 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlfOAGEENBzRUc9W2U:-NrlfOAGEENBzRUc9W2V:b-t04s3n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/config/config-validation.ts#L610)):*
> ```XML
>       );
> 
>       // ? some validation are type as other are classes
> ```

This is normal, it is here that the JSON config is used to instanciate the classes. In the end, the new instance replace the JSON
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 38 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlgx1p76-l4XJq3fez:-Nrlgx1q1wsS07UeFJ54:b-4q604z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L38)):*
> ```XML
> export type TypeSourceVectorTilesInitialConfig = TypeSourceTileInitialConfig;
> 
> // export class TypeVectorTilesLayerEntryConfig extends TypeTileLayerEntryConfig {
> ```

Will we keep this dead code. Theoritically, it is supposed to be moved with the other classes?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 176 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlhY3N0VnB2Nq3a4zc:-NrlhY3N0VnB2Nq3a4zd:bnwwc9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L176)):*
> ```XML
>    */
>   protected processOneLayerEntry(layerConfig: VectorTilesLayerEntryConfig): Promise<TypeBaseRasterLayer | null> {
>     const promisedVectorLayer = new Promise<TypeBaseRasterLayer | null>((resolve) => {
> ```

Why do we get back to the old implementation. We lost here important code that resolved layerStatus progressive sequence of value. Also, the set visible flag must not be done here because it causes loading issues.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 242 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrliHn6A-zAlCMZttBV:-NrliHn6A-zAlCMZttBW:b-l9c9uy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L242)):*
> ```XML
>    */
>   protected processLayerMetadata(layerConfig: TypeTileLayerEntryConfig): Promise<TypeLayerEntryConfig> {
>     const promiseOfExecution = new Promise<TypeLayerEntryConfig>((resolve) => {
> ```

I have the feeling you restored an old version of the code. If so, you also restored the bugs that come with it.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 881 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljDeV8QeXDV-h8yh5:-NrljDeW3b7IvOjx-wlO:biujnky) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L881)):*
> ```XML
>         for (let i = 0; i < this.WMSStyles.length; i++) {
>           // TODO: refactor - does this await in a loop may haev an impact on performance?
>           // eslint-disable-next-line no-await-in-loop
> ```

I think this section of code should use a promise.all
It's a good idea to have a todo to revise it.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPA8oAM1ga29rhSXh:-NrljZ8z9ur1fr4CjdOH:b-kpwedl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L3)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Do we have a lot of max-classes-per-file global?
I'd personally like it if we could address them all at some point. To clarify and help when searching for stuff around the code.
Maybe a TODO for them or we just search for them later
</blockquote></details>

We want to move them in a central place with a directory structure that showd the inheritance. It is better to have one classe per file. That way, we are sure all the code in the file is related to a specific class. We should have an issue for this. however, Johann seems to have done a big part of that work.


<!-- Sent from Reviewable.io -->

2024-02-29 01:23 UTC, Alex-NRCan reviewed
> Reviewed 7 of 66 files at r1, 24 of 46 files at r2, 10 of 53 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: 62 of 105 files reviewed, 28 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPA8oAM1ga29rhSXh:-NrmR_cd4_iBwx0rR9Ci:bhmf4r9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L3)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

We want to move them in a central place with a directory structure that showd the inheritance. It is better to have one classe per file. That way, we are sure all the code in the file is related to a specific class. We should have an issue for this. however, Johann seems to have done a big part of that work.
</blockquote></details>

Yeah agreed, I wasn't too clear but yes. A directory structure and 1 class per file is what I'd suggest as well. I do think Johann is doing most (if not all?) of the work in this PR.


<!-- Sent from Reviewable.io -->

2024-02-29 01:54 UTC, Alex-NRCan reviewed
> Reviewed 42 of 53 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: 104 of 105 files reviewed, 28 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 881 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrljDeV8QeXDV-h8yh5:-NrmThso8EChG-4HnFB0:bun9zjm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L881)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I think this section of code should use a promise.all
It's a good idea to have a todo to revise it.
</blockquote></details>

Agreed, there's even an eslint warning usually for this as 90% of the time, you don't want to await in a loop. It can impact performance quite a bit indeed.

In this case here, when glancing at the code, the only reason to await would be if the order that the `styleLegend` get added to the `styleLegends` array MUST be the same order as they are in the WMSStyles array (as in they are 2 arrays with same indexes pointers). Without the await, WMSStyles[2] stuff could be associated with something in styleLegends[1] position for example (1<>2). If we remove the await, be mindful of that (maybe add this remark in the TODO?). In any case, I'd suggest to remove the await indeed, for performance, and rewrite the code to make it work (probably not 2 distinct arrays).

That being said, I'd also add a TODO here to never call an explicit function with an index counter. `this.WMSStyles[i]` should be sent to the ` getStyleLegend` function instead of doing the `this.WMSStyles[i]` in the latter. Would read a lot better and more easily reused.


<!-- Sent from Reviewable.io -->

2024-02-29 02:02 UTC, Alex-NRCan reviewed
> Reviewed 1 of 53 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 27 unresolved discussions (waiting on @jolevesq and @ychoquet)



<!-- Sent from Reviewable.io -->

2024-02-29 14:15 UTC, jolevesq reviewed
> Reviewed 20 of 66 files at r1, 13 of 46 files at r2, 36 of 53 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 27 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/webpack.common.js` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrl_-Uo5OY3PDxcm_e-:-NroxSPo6kPYcRcGxmka:bmyk4gb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/webpack.common.js#L5)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Wouldn't it be better to mark every line that needs to disable no-var-requires as we said in the scrum. The idea is to clearly identify the targeted lines. If we define it globally, anyone could insert code that would normally be detected, but will go unnoticed because of the global definition.
</blockquote></details>

This is not a file we run, it is only for the build and line 3 to 10 are in problem. Updated comment
___
*[`packages/geoview-core/webpack.dev.js` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlaem688voZr_HlMBA:-NroyVNU9e_uVvmaP1F2:bvksaah) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/webpack.dev.js#L5)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same as mentioned above
</blockquote></details>

This is not a file we run, it is only for the build and line all require lines are in problem. Updated comment
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 389 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOXh7CZF2PfR_2o23:-Nrga2Z68GZmRndsIOB3:bs7wumb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L389)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe return unknown? Not sure
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 585 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOKduD0vAwltXIYDO:-NrjlhhEBuLF5bB8yBqK:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L585)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Good example where an 'any' was missed.
I'd remove the eslint-disable and put 'unknown' instead.
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 621 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgOSpa9IOoOUmuXOXq:-NrmDq7Z3jBy98V3tdVE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/core/utils/utilities.ts#L621)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Good example where an 'any' was missed.
I'd remove the eslint-disable and put 'unknown' instead.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 388 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrldXpgBj4rHiIT_Uyb:-Nrp2Zfs84S_3__D5ULx:b-rerfrh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/utilities.ts#L388)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

What is the purpose of sandbox.html. The function parseJSONConfig is only used by this HTML code, and if it is a place to test and play with code and ideas without using it in the viewer, maybe we should delete the function.
</blockquote></details>

It is use by getValidConfigFromString who was previously a function in utilities. I will put a TODO
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrletrHAemwRfVPu-QU:-Nrp3_wf5lLT5tAwgYsu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/config/config-validation.ts#L2)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

> functions with dangle and many reassigns
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 610 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlfOAGEENBzRUc9W2U:-Nrp3h1M0-PNzgXXGlxD:boos1r5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/config/config-validation.ts#L610)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This is normal, it is here that the JSON config is used to instanciate the classes. In the end, the new instance replace the JSON
</blockquote></details>

I was not sure because it was Type.. and some were in the layer<type>.ts and some in schema. As I rearrange I saw it was all classes.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlfptq3xbTFqiT4AEG:-Nrp6QNo8XbUiKZvC0Ul:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L2)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

reassing > reassign
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlfvg40uodWIDeNabc:-Nrp6abfCHeFH62jgcs4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L2)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

*reassign
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlg3C86OTizcxenq-L:-Nrp6gNW4_hBW-G1rX35:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L2)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

*reassign
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 272 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlhHac4Lb1fUf9VeSC:-Nrp7Q172pECaw8KJuUr:b5fcxmd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L272)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This was just so that I could reuse common methods in the image layers
</blockquote></details>

Updated comment
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrlh_0E3COpKbf_ncKQ [...]

2024-02-29 14:30 UTC, Alex-NRCan approved these changes
> Reviewed 5 of 46 files at r2, 30 of 30 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 23 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 388 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrldXpgBj4rHiIT_Uyb:-NrpDttwBUgN8q1CyK2e:b-wkqa1s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/utilities.ts#L388)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is use by getValidConfigFromString who was previously a function in utilities. I will put a TODO
</blockquote></details>

I don't see the harm of having this function stay in utilities to be reused.
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrgPqN69BqyFmlfYzmK:-NrpFeKc3wwShKsVjsiK:bkezts3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/30c90261a31717bf15cc1fdabe59f85c8cd3426e/packages/geoview-core/src/ui/panel/panel.tsx#L335)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Added a TODO, will try to see if it works with latest react
</blockquote></details>

Sounds good. I mean if it works, we probably shouldn't keep the TODO there for nothing, I'm surprised sometimes comments in render section break react and sometimes not. All good.


<!-- Sent from Reviewable.io -->

2024-02-29 15:00 UTC, ychoquet requested changes
> Reviewed 51 of 53 files at r4, 30 of 30 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 16 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 388 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrldXpgBj4rHiIT_Uyb:-NrpJYXK-l7gdrHFqY9x:bfmb8ys) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/utilities.ts#L388)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I don't see the harm of having this function stay in utilities to be reused.
</blockquote></details>

Dead code doesn't harm, it is just that the refactor from leaflet to openlayers created dead section of code that polute the viewer. If we have section of code that is useless and will not be used anymore, we should delete it. It may be good to keep some code if we are absolutely sure to get back to it in a refactor phase, but when we already have a replacement I'm not sure it is pertinent. For example, the old marker code we keep. At the beginning i was updating it every time I did a modification that impact it, but at the end I stop doing that because the code is getting so far from where we are now that I now think we should not keep it.
___
*[`packages/geoview-core/src/core/utils/config/validationClasses/tile-layer-entry-config.ts` line 2 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrpN40h7bxeqnbhFUIn:-NrpN40h7bxeqnbhFUIo:bfs3tdk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/92425a26175a7e122c003fa5c38e4f25366c64d2/packages/geoview-core/src/core/utils/config/validationClasses/tile-layer-entry-config.ts#L2)):*
> ```XML
> // TODO: class
> ```

I would be more verbose on the work we have to do here. When I expand, I see the content is already a class. What task has to be done?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 272 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlhHac4Lb1fUf9VeSC:-NrpHwLdEvf7UDnvnAEC:b9cyg9y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L272)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Updated comment
</blockquote></details>

This layerConfig definition is corrected in my next PR on OSDP demo
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 176 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrlhY3N0VnB2Nq3a4zc:-NrpIsEt8407tH7ksfuA:bj06xaa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L176)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Tried to revert back
</blockquote></details>

Seems to be good now. We'll see at the testing phase.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 242 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrliHn6A-zAlCMZttBV:-NrpJ0yt2LC2k-d2Xcqo:bj06xaa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L242)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Tried to revert back
</blockquote></details>

Seems to be good now. We'll see at the testing phase.


<!-- Sent from Reviewable.io -->

2024-02-29 15:47 UTC, DamonU2 requested changes
> Reviewed 53 of 53 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 947 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrmM2vu44XeMpQHWQjv:-NrmM2vu44XeMpQHWQjw:b-qt18y9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/92425a26175a7e122c003fa5c38e4f25366c64d2/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L947)):*
> ```XML
>   protected getFeatureInfoUsingPolygon(location: Coordinate[], layerPath: string): Promise<TypeArrayOfFeatureInfoEntries> {
>     // Log
>     logger.logError(`getFeatureInfoUsingPolygon is not implemented! for ${layerPath} - ${location}`);
> ```

Move ! to the end?


<!-- Sent from Reviewable.io -->

2024-02-29 18:00 UTC, Alex-NRCan reviewed
> Reviewed 5 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: 100 of 106 files reviewed, all discussions resolved (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 388 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-NrldXpgBj4rHiIT_Uyb:-Nrq0O4M6qr1ufQ8XnVd:b-u344np) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/907edca001e442e0410b6600b31fd5ac2dcf470c/packages/geoview-core/src/core/utils/utilities.ts#L388)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Dead code doesn't harm, it is just that the refactor from leaflet to openlayers created dead section of code that polute the viewer. If we have section of code that is useless and will not be used anymore, we should delete it. It may be good to keep some code if we are absolutely sure to get back to it in a refactor phase, but when we already have a replacement I'm not sure it is pertinent. For example, the old marker code we keep. At the beginning i was updating it every time I did a modification that impact it, but at the end I stop doing that because the code is getting so far from where we are now that I now think we should not keep it.
</blockquote></details>

It's a utility function that's called by sandbox, not dead code.


<!-- Sent from Reviewable.io -->

2024-02-29 18:09 UTC, Alex-NRCan reviewed
> Reviewed 2 of 8 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: 103 of 106 files reviewed, all discussions resolved (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 2 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865#-Nrq1KOJ16kgzYFF2Ax6:-Nrq1KOJ16kgzYFF2Ax7:b-z2xs17) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/45e769b2f2741ff23c92dc2b1ae8e8b771f000f4/packages/geoview-core/src/geo/map/map-schema-types.ts#L2)):*
> ```XML
> /* eslint-disable no-underscore-dangle */
> // We use _ for layerPth and olLayer all over the file. We keep it global...
> ```

Typos?


<!-- Sent from Reviewable.io -->

2024-02-29 18:11 UTC, DamonU2 approved these changes
> Reviewed 1 of 8 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1865)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)



<!-- Sent from Reviewable.io -->

2024-02-29 18:13 UTC, merged