feat(guide): add guide subsections
Canadian-Geospatial-Platform/geoview pull request #2001
Opened 2024-04-10 19:56 UTC by DamonU2

Closes #1983

# Description

Added subsections to guide.md, and methods to turn it into an object in the app store. Guide sections replace instructions for most footer panels. App store updated to follow format of other stores. Currently, the guide does not have the subsections available, will be added later.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested throughout footer tabs.
https://damonu2.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-04-10 20:57 UTC, jolevesq requested changes
> Reviewed 27 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 27 of 37 files reviewed, 15 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8k3J3DQTHhbHI7Nba:-Nv8k3J3DQTHhbHI7Nbb:bt165x6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L26)):*
> ```Markdown
> Note that the map **must be** focused for key binding to work.
> 
> =2!overviewMap=
> ```

I do not see the overview map in the guide. Do  miss something? Does 2 before the section means in the other PR?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8lSVE1ChkZB-zPUI0:-Nv8lSVE1ChkZB-zPUI1:b-uthvqm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L120)):*
> ```XML
>    */
>   static async setGuide(mapId: string): Promise<void> {
>     const store = getGeoViewStore(mapId);
> ```

You can do this to access the state:  this.getAppState(mapId)
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8lkUo41tTPxpb-vup:-Nv8lkUo41tTPxpb-vuq:b-vpd9t8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L138)):*
> ```XML
>   }
> 
>   static async createGuideObject(mapId: string): Promise<TypeGuideObject | undefined> {
> ```

We should try to avoid too much logic in the event processor... We can have a utility function to return the guide in core.utilities who takes language as param so no leaking of api.maps
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mDgn1NYYRGM8G7FR:-Nv8mDgn1NYYRGM8G7FS:b-1hs1nr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L217)):*
> ```XML
>             <Box sx={sxClasses.guideBox}>
>               <Markdown options={{ wrapper: 'article' }}>
>                 {guide?.footerPanel?.children?.dataTable?.content || (t('dataTable.selectVisbleLayer') as string)}
> ```

We should not use the t(... value anymore and rely on the guide panel I think
___
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mMXW1IAfUNo9YPjJ:-Nv8mMXX1dFg9yRn3gp0:b-hsae7p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L78)):*
> ```XML
>     color: theme.palette.geoViewColor.textColor.main,
>   },
>   guideBox: {
> ```

The css should be move to common component so it is not repeated
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 452 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mVl0E2mtCDVGdHSR:-Nv8mVl0E2mtCDVGdHSS:b-1hs1nr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/details/details-panel.tsx#L452)):*
> ```XML
>                 <Box sx={sxClasses.guideBox}>
>                   <Markdown options={{ wrapper: 'article' }}>
>                     {guide?.footerPanel?.children?.details?.content || (t('details.selectVisbleLayer') as string)}
> ```

We should not use the t(... value anymore and rely on the guide panel I think
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mYE_90VGVIjwatbX:-Nv8mYEa1J_3k66_txQc:b-81njip) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/details/details-style.ts#L57)):*
> ```XML
>     alignItems: 'center',
>   },
>   guideBox: {
> ```

Reuse
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mkZdCNIt0VBXqrvu:-Nv8mkZdCNIt0VBXqrvv:b-1hs1nr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L61)):*
> ```XML
>       const markDown = (
>         <Markdown options={{ wrapper: 'article' }}>
>           {guide?.footerPanel?.children?.layers?.children?.remove?.content || (t('layers.removeLayerDescription') as string)}
> ```

We should not use the t(... value anymore and rely on the guide panel I think
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mlaF7kgDMO-V-ux7:-Nv8mlaF7kgDMO-V-ux8:b-1hs1nr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L73)):*
> ```XML
>       const markDown = (
>         <Markdown options={{ wrapper: 'article' }}>
>           {guide?.footerPanel?.children?.layers?.children?.sort?.content || (t('layers.sortingDescription') as string)}
> ```

We should not use the t(... value anymore and rely on the guide panel I think
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mmKWEs7ZfnmOxfi7:-Nv8mmKWEs7ZfnmOxfi8:b-1hs1nr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L85)):*
> ```XML
>       const markDown = (
>         <Markdown options={{ wrapper: 'article' }}>
>           {guide?.footerPanel?.children?.layers?.children?.add?.content || (t('layers.addingNewLayerDescription') as string)}
> ```

We should not use the t(... value anymore and rely on the guide panel I think
___
*[`packages/geoview-core/src/core/components/layers/layers-style.ts` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mnwwDQYTuylgHCIB:-Nv8mnwwDQYTuylgHCIC:b-81njip) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-style.ts#L18)):*
> ```XML
>     },
>   },
>   guideBox: {
> ```

Reuse
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 274 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8n7g-3pGMkeuNHL-W:-Nv8n7g-3pGMkeuNHL-X:b-z5cj90) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-geochart/src/geochart-panel.tsx#L274)):*
> ```XML
>                 <Markdown options={{ wrapper: 'article' }}>
>                   {guide?.footerPanel?.children?.chart?.content ||
>                     api.utilities.core.getLocalizedMessage('geochart.panel.clickMap', displayLanguage)}
> ```

We should not use the Message(... value anymore and rely on the guide panel I think
___
*[`p [...]

2024-04-10 21:59 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 27 of 37 files reviewed, 15 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8k3J3DQTHhbHI7Nba:-Nv8nYPrDoIA93JrPnz6:bj7ixsr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I do not see the overview map in the guide. Do  miss something? Does 2 before the section means in the other PR?
</blockquote></details>

Yep, anything with a 2 or 3 won't show up in the guide, but might be in the footer tabs
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8lSVE1ChkZB-zPUI0:-Nv8pNVb3zs3exBZ7-VJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L120)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can do this to access the state:  this.getAppState(mapId)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8lkUo41tTPxpb-vup:-Nv8pNsbEnjX-cfuSqij:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L138)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should try to avoid too much logic in the event processor... We can have a utility function to return the guide in core.utilities who takes language as param so no leaking of api.maps
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mDgn1NYYRGM8G7FR:-Nv8u0JPC3DqSG5PzRdo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L217)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the t(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mMXW1IAfUNo9YPjJ:-Nv8zRZPEhhHGviwWCrR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The css should be move to common component so it is not repeated
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 452 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mVl0E2mtCDVGdHSR:-Nv8tzSE0IerIXfaTkeW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/details/details-panel.tsx#L452)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the t(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mYE_90VGVIjwatbX:-Nv8zTaK0X6Byx80eYBV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/details/details-style.ts#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Reuse
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mkZdCNIt0VBXqrvu:-Nv8ttUm2LOcV7toC4Db:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the t(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mlaF7kgDMO-V-ux7:-Nv8tspnBDbSp7fcEyI8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the t(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mmKWEs7ZfnmOxfi7:-Nv8tsd1DJO6SZi2ZEhM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L85)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the t(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/layers-style.ts` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mnwwDQYTuylgHCIB:-Nv8zfgf5id18XmTCFRG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/layers/layers-style.ts#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Reuse
</blockquote></details>

Done.
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 274 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8n7g-3pGMkeuNHL-W:-Nv8tXV84Y6K4PduDlyw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-geochart/src/geochart-panel.tsx#L274)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use the Message(... value anymore and rely on the guide panel I think
</blockquote></details>

Done.
___
*[`packages/geoview-geochart/src/geochart-style.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8nBnpCXQXJhOGfyYx:-Nv9-qtoCqsme8c998lO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-geochart/src/geochart-style.ts#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summ [...]

2024-04-11 11:21 UTC, jolevesq requested changes
> Reviewed 2 of 37 files at r1, 16 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 42 of 43 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8k3J3DQTHhbHI7Nba:-NvBoTCUCmnVgszZdK_L:bz7irkf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L26)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Yep, anything with a 2 or 3 won't show up in the guide, but might be in the footer tabs
</blockquote></details>

Ok, but overview map should level 1 inside navigation control I think
___
*[`packages/geoview-core/public/locales/en/guide.md` line 36 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBpBu6BmDHeNPnYTjq:-NvBpBu78FnNB7B0q_j8:bbav8v2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L36)):*
> ```Markdown
> Click-hold on the box in the overview map and drag it to change the extent of the main map. Clicking on the toggle icon ![](img/guide/navigation/chevron_overview.png) in the top right corner of the overview map will expand or contract it.
> 
> =2!keyboardNavigation=
> ```

There is 2 section keyboard navigation with cross hair. Seems to have duplication between the 2 
___
*[`packages/geoview-core/public/locales/en/guide.md` line 97 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBpjG80q3QGpFcET0o:-NvBpjG80q3QGpFcET0p:b-4zchs0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L97)):*
> ```Markdown
> | <img src="img/guide/sidebar/about.svg" width="30"/>         | About Geoview | Display information about Geoview viewer                                                           |
> 
> =2!geolocator=
> ```

This duplication with the geolocator at the bottom, is this wanted? We should have geolocator only in side bar (or in the bigger Map Navigation section (instead of controls)???
___
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mMXW1IAfUNo9YPjJ:-NvBrMiH6bI2SRKXPsHd:b-d17una) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L78)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do you now why we have thing here like border who is not get from the common layout? All right panel should be the same
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 421 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBrye86HcuNz9SX3JH:-NvBrye86HcuNz9SX3JI:bz69au4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f36c7f1c1115e66dc51cd8d4da8c893170eeaf67/packages/geoview-core/src/core/utils/utilities.ts#L421)):*
> ```XML
> }
> 
> export function getSectionHeading(content: string): string {
> ```

This function is internal to the other, it does not have to be exported
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 431 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBsARWDfs-2A3CcQ_V:-NvBsARWDfs-2A3CcQ_W:bns96u5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f36c7f1c1115e66dc51cd8d4da8c893170eeaf67/packages/geoview-core/src/core/utils/utilities.ts#L431)):*
> ```XML
>     const content = await response.text();
>     const sections = content.split(/=(?=1!)(.*?)=/);
>     if (!sections[0].trim()) {
> ```

Can you put some comments and blank lines to help readability


<!-- Sent from Reviewable.io -->

2024-04-11 14:37 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 40 of 43 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8k3J3DQTHhbHI7Nba:-NvCT89m12lM2yXsZOne:b-3b2zi3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Ok, but overview map should level 1 inside navigation control I think
</blockquote></details>

Navigation control is level 1, so overview map is it's child
___
*[`packages/geoview-core/public/locales/en/guide.md` line 36 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBpBu6BmDHeNPnYTjq:-NvCUUS99mFLbYcUjPqB:bnzb6nq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is 2 section keyboard navigation with cross hair. Seems to have duplication between the 2
</blockquote></details>

I think it makes sense to have it in both places, so it can be found quickly going directly to the section, and it can be seen in the individual sections.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 97 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBpjG80q3QGpFcET0o:-NvCWjbxCNTcBTzmk8y6:b-4zx306) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/public/locales/en/guide.md#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This duplication with the geolocator at the bottom, is this wanted? We should have geolocator only in side bar (or in the bigger Map Navigation section (instead of controls)???
</blockquote></details>

Yeah, I was thinking the same thing. I think it was just Jeff overemphasizing the thing he was very familiar with. Moved to sidebar.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-style.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-Nv8mMXW1IAfUNo9YPjJ:-NvC_bHD1v_eZVar1yu3:b-yrdae4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f7c71bf69fecc66d8ba028d301fc0e19e9df349e/packages/geoview-core/src/core/components/data-table/data-table-style.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you now why we have thing here like border who is not get from the common layout? All right panel should be the same
</blockquote></details>

No idea, and I saw rightPanelContainer overrides in some of the others as well.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 421 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBrye86HcuNz9SX3JH:-NvCX-yi6KaiPUNLSdL1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f36c7f1c1115e66dc51cd8d4da8c893170eeaf67/packages/geoview-core/src/core/utils/utilities.ts#L421)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function is internal to the other, it does not have to be exported
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 431 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvBsARWDfs-2A3CcQ_V:-NvC_PjV8_lUyLtoD2V2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f36c7f1c1115e66dc51cd8d4da8c893170eeaf67/packages/geoview-core/src/core/utils/utilities.ts#L431)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put some comments and blank lines to help readability
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-12 10:50 UTC, jolevesq requested changes
> Reviewed 1 of 17 files at r2, 15 of 17 files at r3, 3 of 9 files at r4, 15 of 15 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 63 of 64 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 59 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGshp9AAoA_B_CTcHO:-NvGshp9AAoA_B_CTcHP:b6cgpyn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/components/common/layer-list.tsx#L59)):*
> ```XML
> 
>       default:
>         if (layer.content) return null;
> ```

Why doing this, can you add a comment. Feel weird that if optional content is there return null.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 38 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGtNrtE54cuMdBKdh1:-NvGtNrtE54cuMdBKdh2:b2o5b1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L38)):*
> ```XML
>         let { content } = guide[item];
>         if (guide[item].children) {
>           Object.keys(guide[item].children as TypeGuideObject).forEach((child: string) => {
> ```

Can you add comments to specify what you are doing here, maybe also blank space between if section so we see more what is going on
___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 71 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGtnwNBMMrVDwllcnu:-NvGtnwNBMMrVDwllcnv:b9ymn7s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L71)):*
> ```XML
>     if (displayState === 'remove') {
>       const markDown = (
>         <Markdown options={{ wrapper: 'article' }}>{guide!.footerPanel!.children!.layers!.children!.remove!.content}</Markdown>
> ```

Maybe not in this PR, but we should try to define the guide as not undefined so there is no need for all the !. If it can be done quick lets go if not we can wait
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 454 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGv6Vy2a-SuT_T5HtT:-NvGv6Vy2a-SuT_T5HtU:bg1m39k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/utils/utilities.ts#L454)):*
> ```XML
>       const fullSectionContent = sections[i + 1].trim();
>       const heading = getSectionHeading(fullSectionContent);
>       // Split by second level sections (Split with =2!<key>=)
> ```

We should put blank line before a comment unless it is the first line in a if or loop
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 493 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGuz-f3n4HTHJEpeDN:-NvGuz-f3n4HTHJEpeDO:b-ud3rs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/utils/utilities.ts#L493)):*
> ```XML
>     return guideObject;
>   } catch (error) {
>     logger.logError(mapId, error);
> ```

Can you add function name as parameter in logger


<!-- Sent from Reviewable.io -->

2024-04-12 13:19 UTC, Alex-NRCan approved these changes
> Reviewed 22 of 37 files at r1, 11 of 17 files at r2, 15 of 17 files at r3, 2 of 9 files at r4, 12 of 15 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-04-12 14:16 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: 61 of 64 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 59 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGshp9AAoA_B_CTcHO:-NvH_ddp8F4L4YbNeE6H:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/components/common/layer-list.tsx#L59)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why doing this, can you add a comment. Feel weird that if optional content is there return null.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 38 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGtNrtE54cuMdBKdh1:-NvHabXoCgU2NwZqH4Nd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add comments to specify what you are doing here, maybe also blank space between if section so we see more what is going on
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 454 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGv6Vy2a-SuT_T5HtT:-NvHcYI9ASwZt6olCYjV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/utils/utilities.ts#L454)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should put blank line before a comment unless it is the first line in a if or loop
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 493 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001#-NvGuz-f3n4HTHJEpeDN:-NvHcYf9CaHvWUNh0I9m:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c4339c339b5bba63dc1928ad6826245c67872370/packages/geoview-core/src/core/utils/utilities.ts#L493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add function name as parameter in logger
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-12 14:27 UTC, jolevesq reviewed
> Reviewed 1 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-04-12 14:27 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-04-12 14:28 UTC, merged