Input and internal schema validation plus  default maxExtent issue
Canadian-Geospatial-Platform/geoview pull request #2124
Opened 2024-05-10 16:42 UTC by ychoquet

# Description

This PR groups two issues:
- The creation and activation of two schemas (input/internal) that validate hte configuration provided by the user and the the structure of the internal representation of the map and layer instances.
- The correction of the default maxExtent according to the projection code used.

Fixes #2121, 2122

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace and debug the code.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-05-10 17:07 UTC, jolevesq requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 9 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124#-NxYSzhHDNhl3xZlTTd1:-NxYSzhHDNhl3xZlTTd2:b-3lq0ek) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44984533246bc6b0aa94f708a586440f7bb764a7/packages/geoview-core/src/api/config/types/config-constants.ts#L9)):*
> ```XML
>   TypeAppBarProps,
>   TypeBasemapId,
>   TypeBasemapOptions,
> ```

Why all those type diseapred from this file


<!-- Sent from Reviewable.io -->

2024-05-10 17:10 UTC, jolevesq requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124#-NxYTcSd6Qv6KlV6vQ6k:-NxYTcSd6Qv6KlV6vQ6l:b-m5iv22) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0e809d519cb91d8fe43931f4cd209975ea77043/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1125)):*
> ```JSON
>       },
>       "if": {
>         "properties": {
> ```

Because most property of all layer are similar, can we have a type defiition reusable and have one specific by source?


<!-- Sent from Reviewable.io -->

2024-05-10 21:19 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 9 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124#-NxYSzhHDNhl3xZlTTd1:-NxZL5AX0aiJ8QsFNU4S:b-t7dq34) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44984533246bc6b0aa94f708a586440f7bb764a7/packages/geoview-core/src/api/config/types/config-constants.ts#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why all those type diseapred from this file
</blockquote></details>

I used a trick proposed by Alex that minimize the as SomeOtherType usage. So, all these types I had to use before are not needed anymore. I use the Cast function which does basically a 'as unknown as newType'. The drawback of this methode is if The object in the Cast does not define a field in the targetted newType, you will not get an error flaged.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124#-NxYTcSd6Qv6KlV6vQ6k:-NxZMnF_7Lz_aYFwBgE0:bu7vb7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0e809d519cb91d8fe43931f4cd209975ea77043/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because most property of all layer are similar, can we have a type defiition reusable and have one specific by source?
</blockquote></details>

Yes we can, I will do that in my next PR.


<!-- Sent from Reviewable.io -->

2024-05-14 11:55 UTC, jolevesq approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2124)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-05-14 11:55 UTC, merged