2170-Schema cleanup and inheritance
Canadian-Geospatial-Platform/geoview pull request #2171
Opened 2024-05-23 21:48 UTC by ychoquet

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2170

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-05-24 14:24 UTC, jolevesq requested changes
> Reviewed 15 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: 15 of 23 files reviewed, 26 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyejvQlDOqD4afZL2Je:-NyejvQlDOqD4afZL2Jf:b-fe6b6f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a35601ffde444a69d24f7f99d678b1bf07418b46/packages/geoview-core/src/api/config/types/config-constants.ts#L28)):*
> ```XML
>  * Indeed, GeoCore is not an official Abstract Geoview Layer, but it can be used in schema types.
>  */
> export type TypeGeoviewLayerTypeWithGeoCore = TypeGeoviewLayerType | typeof CV_CONST_SUB_LAYER_TYPES.GEOCORE;
> ```

You cant remove the geocore from type and keep the same name ...TypeWithGeocore
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 155 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyekETb7Altf7uebj3U:-NyekETb7Altf7uebj3V:bvbhseo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L155)):*
> ```XML
>         enableRotation: true,
>         rotation: 0,
>         maxExtent: [-125, 30, -60, 89],
> ```

The extent will depend of the projection and it is not max extent but only extent
```
"initialView": {
        "extent": [-90, 45, -65, 70]
      },
```
Do not forget to test the demo pages to see if your modification does what it is expected to do
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 172 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyekoiyCncGeuDadoZ6:-NyekoiyCncGeuDadoZ7:bfcxv2u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L172)):*
> ```XML
>     extraOptions: {},
>   },
>   theme: 'dark',
> ```

Default theme is geo.ca
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 186 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyenWgtEiIV10m64zsw:-NyenWgtEiIV10m64zsx:b-68j2c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L186)):*
> ```XML
>   externalPackages: [],
>   serviceUrls: {
>     geocoreUrl: CV_CONFIG_GEOCORE_URL,
> ```

Add constant for geolocator and proxy url (value is in a comment below)
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyelCqB-Cg5f3k6uwsC:-NyelCqB-Cg5f3k6uwsD:b-hs2rw3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L88)):*
> ```JSON
>       "additionalProperties": false,
>       "enum": ["dark", "light", "geo.ca"],
>       "default": "dark"
> ```

default is geo.ca
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyelp9yCiMR9mniYOHr:-Nyelp9yCiMR9mniYOHs:b5swlz2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L245)):*
> ```JSON
>       "properties": {
>         "name": {
>           "description": "External Package name. The name must be ideintical to the window external package object to load.",
> ```

Typo identical
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 276 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyenMPF8Mvj_YCMMA_x:-NyenMPF8Mvj_YCMMA_y:bblmn6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L276)):*
> ```JSON
>         },
>         "proxyUrl": {
>           "description": "An optional proxy to be used for dealing with same-origin issues.  URL must either be a relative path on the same server or an absolute path on a server which sets CORS headers.",
> ```

default  "https://maps.canada.ca/wmsproxy/ws/wmsproxy/executeFromProxy"
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 280 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyem8o_-WomKQ6NohPM:-Nyem8o_-WomKQ6NohPN:bh11422) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L280)):*
> ```JSON
>         },
>         "geolocator": {
>           "description": "Service end point to access geo location of searched value.",
> ```

default: "https://geolocator.api.geo.ca?keys=geonames,nominatim,locate"
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 284 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeni9u-V-IMBNyPHBO:-Nyeni9v-M9mzrqIejWm:btk1oov) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L284)):*
> ```JSON
>         }
>       },
>       "required": ["geocoreUrl"]
> ```

Add the geolocator and proxy as required for the internal one
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 415 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyeoHbv0btwYXn2eGQA:-NyeoHbv0btwYXn2eGQB:b-39c06u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L415)):*
> ```JSON
>             "type": "number"
>           },
>           "default": [-125, 30, -60, 89]
> ```

Do not forget there 2 default, one for LCC and one for WM
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 627 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyesH2nCTuShJFggLK4:-NyesH2nCTuShJFggLK5:bh0o1rl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L627)):*
> ```JSON
>           "minimum": 0,
>           "maximum": 28,
>           "default": 3.5
> ```

I see 3.5 here but when we run the code it is 4.5 (as define in your constant file and below)
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 799 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyet1JMBBAEfQOG6zLR:-Nyet1JMBBAEfQOG6zLS:b-lhwmsw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L799)):*
> ```JSON
>           "properties": {
>             "source": {
>               "$ref": "#/definitions/TypeSourceImageEsriInitialConfig"
> ```

should be DynamicEsri.... because ImageEsri.... will be for image server. Below it is EsriFeature... here ImageEsri, We should have the same order... EsriFeatureInitial... and EsriDynamicInitial...
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1061 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeu47vEzQ38KZK [...]

2024-05-24 14:57 UTC, Alex-NRCan requested changes
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: all files reviewed, 27 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/type-guards.ts` line 10 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyf3UXG8SGg8_LWR4BZ:-Nyf3UXG8SGg8_LWR4B_:b-jhfgfl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/type-guards.ts#L10)):*
> ```XML
> import { CV_CONST_SUB_LAYER_TYPES, CV_CONST_LAYER_TYPES } from '@config/types/config-constants';
> import { TypeJsonObject } from '@config/types/config-types';
> import {
> ```

As a general note, type guards are, most of the time, unnecessary, as TypeScript automatically narrows down the type when performing conditional operations.

If we feel like we really need to, we can keep those custom type guards, but I'd probably just place them next to their Type definition (like where TypeBaseVectorConfig is defined). Having a specific file (which would serve for a bunch of type guards?) seems like overload.


<!-- Sent from Reviewable.io -->

2024-05-27 18:00 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: all files reviewed, 26 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyejvQlDOqD4afZL2Je:-NyfQI9eDqrSeZBgN-uc:b-3ws5ii) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a35601ffde444a69d24f7f99d678b1bf07418b46/packages/geoview-core/src/api/config/types/config-constants.ts#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You cant remove the geocore from type and keep the same name ...TypeWithGeocore
</blockquote></details>

This is not a constant. Also, this type does not exists in the new configuration
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 155 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyekETb7Altf7uebj3U:-NyukanY61KACAecbRbm:bb7gf4p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L155)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The extent will depend of the projection and it is not max extent but only extent
```
"initialView": {
        "extent": [-90, 45, -65, 70]
      },
```
Do not forget to test the demo pages to see if your modification does what it is expected to do
</blockquote></details>

The value here are used only if the user doesn't specify a projection code.
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 172 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyekoiyCncGeuDadoZ6:-NyfZ8my9jXrzGM1d-Iw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L172)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Default theme is geo.ca
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 186 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyenWgtEiIV10m64zsw:-NyvAZu45EfWHRcrIRcH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-constants.ts#L186)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add constant for geolocator and proxy url (value is in a comment below)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyelCqB-Cg5f3k6uwsC:-NyfZk5rAgALy5_EEW9q:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

default is geo.ca
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyelp9yCiMR9mniYOHr:-Nyf_WT3DmCwM0pLDG2J:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L245)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo identical
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 276 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyenMPF8Mvj_YCMMA_x:-NyfaQlY5XlQHdPE6cyw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L276)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

default  "https://maps.canada.ca/wmsproxy/ws/wmsproxy/executeFromProxy"
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 280 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyem8o_-WomKQ6NohPM:-NyfafEe7xUWVOYqRV_7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L280)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

default: "https://geolocator.api.geo.ca?keys=geonames,nominatim,locate"
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 284 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeni9u-V-IMBNyPHBO:-NyfeR02Bm2FYVnLM0wR:by7chkf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L284)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add the geolocator and proxy as required for the internal one
</blockquote></details>

The internal config validation doesn't have to make these properties as required because if the user doesn't provide them, the default values will be assigned to them. The question is: do we have to set geocoreUrl as required for the input schema?
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 415 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyeoHbv0btwYXn2eGQA:-Nyfg8sAC_l-apuhcCZD:bb3b7ad) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L415)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not forget there 2 default, one for LCC and one for WM
</blockquote></details>

The default specified here is used only if the user doesn't specify a projection code
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 627 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyesH2nCTuShJFggLK4:-Nyu8OFB5EniK4opNn0Q:b3hfb2z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L627)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I see 3.5 here but when we run the code it is 4.5 (as define in your constant file and below)
</blockquote></details>

Done. I've changed the value in config-constants to 4.5
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 799 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyet1JMBBAEfQOG6zLR:-Nyuau-T0SSEHcv7OpEn:bt9vj06) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L799)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

should be DynamicEsri.... because ImageEsri.... will be for image server. Below it is EsriFeature.. [...]

2024-05-28 13:04 UTC, jolevesq requested changes
> Reviewed 39 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: 43 of 47 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 284 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeni9u-V-IMBNyPHBO:-NyzAzh_3mrsvc1KiGg8:b-uujts8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L284)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The internal config validation doesn't have to make these properties as required because if the user doesn't provide them, the default values will be assigned to them. The question is: do we have to set geocoreUrl as required for the input schema?
</blockquote></details>

No , it can be only for the internal... geocore url is the same as the other. Only needed for the internal
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1061 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeu47vEzQ38KZKUCcp:-NyzBIw2AKinl4Q6ea6h:b-rys66c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1061)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Are you sure? I ask because ersiDynamic layers can call getAllFeatureInfo as we can do with esriFeature layers.
</blockquote></details>

We may have to do some testing, but the max record is use to query feature to display on the map.... Do we have an ESRI with thousand of features and max record?

Ok, on le garde pour Dynamic...
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyexoOlBWP6hYR14pTS:-NyzHJW60e0KFbFPOl3-:b-e82lct) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts#L11)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I do not agree with the interpretation you make here. All geoview layer has in the listOfLayerEntryConfig a ***tree*** structure that can have a height of 1 or more depending on the user's need. All intermediary nodes must be a GroupLayerEntryConfig object and all leaves must be objects of a type corresponding to the geoview layer in use. In the present context, EsriFeatureLayerConfig instances can only contain EsriFeatureLayerEntryConfig.
</blockquote></details>

Yeah but the esri-config cannot be a group it must be esri-feature config. Then the group is group-config.ts
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyez26S2p-uPNinU6ZD:-NyzHfEF7sETv2dozQks:b-yj5m9q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L47)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same question as before.
</blockquote></details>

Ok, we keep
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyzHqj0Ab_DUD6dNqTi:-NyzHqj0Ab_DUD6dNqTj:bi5kihm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/99a8907f04952d9b7c8b5397f882699d3bf5a9a1/packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts#L108)):*
> ```XML
>         get().uiState.setterActions.setActiveFooterBarTab(id);
>       },
>       setActiveAppBarTabId: (id: string) => {
> ```

Why have you changed this state file?
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyzHyCZ9HyidzmvxlP5:-NyzHyCZ9HyidzmvxlP6:b-xp0t46) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/99a8907f04952d9b7c8b5397f882699d3bf5a9a1/packages/geoview-core/src/core/utils/config/config-validation.ts#L10)):*
> ```XML
> import defaultsDeep from 'lodash/defaultsDeep';
> 
> import { TypeDisplayLanguage, TypeLocalizedString } from '@/api/config/types/map-schema-types';
> ```

We can keep this @api/config as it is the same path as @config but I do not understand why you revert all the @config you have done


<!-- Sent from Reviewable.io -->

2024-05-28 13:40 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: 43 of 47 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 284 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeni9u-V-IMBNyPHBO:-NyzJ1UIEk3rtBP1sn2i:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L284)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No , it can be only for the internal... geocore url is the same as the other. Only needed for the internal
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1061 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-Nyeu47vEzQ38KZKUCcp:-NyzJLXl9bSXYUWZC59f:b-elmzkk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1061)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We may have to do some testing, but the max record is use to query feature to display on the map.... Do we have an ESRI with thousand of features and max record?

Ok, on le garde pour Dynamic...
</blockquote></details>

Ok, we'll see. Let's keep it for the moment.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyexoOlBWP6hYR14pTS:-NyzJtuT9Z9PjftvosA5:b6tisoe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d127c0ad33839efbbf5da4d159246657e1125441/packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yeah but the esri-config cannot be a group it must be esri-feature config. Then the group is group-config.ts
</blockquote></details>

Do not confuse the GeoView layer in the listOfGeoviewLayerConfig with the ***tree*** structure in the listOfLayerEntryConfig. The input schema defines the listOfLayerEntryConfig as a ***tree*** with intermediate nodes of GroupLayerEntryConfig and leaf nodes like EsriFeatureLayerEntryConfig in this case. In addition, all the types that can be part of the listOfLayerEntryConfig have a ...EntryConfig termination, and apart from the trunk nodes of type GroupLayerEntryConfig , a GeoView layer can only contain one leaf type (EsriFeatureLayerEntryConfig in this case). The internal schema follows the same rules.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyzHqj0Ab_DUD6dNqTi:-NyzP_4p9DGB1qT10xvS:bto2862) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/99a8907f04952d9b7c8b5397f882699d3bf5a9a1/packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why have you changed this state file?
</blockquote></details>

To resolve a collision duriong the rebase.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171#-NyzHyCZ9HyidzmvxlP5:-NyzQIyDCeDGVCTK8Lgt:b1agtdq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/99a8907f04952d9b7c8b5397f882699d3bf5a9a1/packages/geoview-core/src/core/utils/config/config-validation.ts#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can keep this @api/config as it is the same path as @config but I do not understand why you revert all the @config you have done
</blockquote></details>

I did not revert them. I think the rebase did that.


<!-- Sent from Reviewable.io -->

2024-05-29 11:37 UTC, jolevesq reviewed
> Reviewed 1 of 43 files at r2, 38 of 38 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-05-29 16:20 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-05-29 16:20 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-05-29 16:21 UTC, merged