feat(events): OSDP events added
Canadian-Geospatial-Platform/geoview pull request #2221
Opened 2024-06-05 22:52 UTC by DamonU2

Closes #1931

# Description

OSDP events and functions to get status added. Still needs swiper added to demo-function-event.html. Also fixes some WMS legends.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demo-function-event.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-06-06 12:07 UTC, jolevesq reviewed
> Reviewed 9 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 9 of 18 files reviewed, 5 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 459 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhOlce2q3_QKSKEYDY:-NzhOlce2q3_QKSKEYDZ:b-9wxqfb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L459)):*
> ```XML
> 
>     // Emit event
>     MapEventProcessor.getMapViewerLayerAPI(mapId).getGeoviewLayer(layerPath)?.emitLayerOpacityChanged({ layerPath, opacity });
> ```

This emit, should it be like the other one (e.g. visibility) and be private in abstact(geoview-gc-layers? 
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 606 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhP2RoAJpEeVk_8Tpq:-NzhP2RoAJpEeVk_8Tpr:b-iupuu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L606)):*
> ```XML
>     this.setMapOrderedLayerInfo(mapId, orderedLayers);
>     // Emit event
>     this.getMapViewerLayerAPI(mapId).emitLayerReordered({ orderedLayers });
> ```

Same here for layer events
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhPdsu4XhvmWwFazZ4:-NzhPdsu4XhvmWwFazZ5:b-q7w8ow) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L60)):*
> ```XML
>   }
> 
>   static addOrRemoveCollapsedLayer(mapId: string, layerPath: string): void {
> ```

Would be more ecplicit

setLegendLayerCollapseState(mapId: string, layerPath: string, isCollapse: boolean)
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-NzhQ4kH0qvwOiJShwIX:bfd09d5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
> ```XML
>    * @returns {string | boolean | null | undefined} The requested state
>    */
>   getLayerPanelState(
> ```

All these functions are duplicated in app bar and footer bar.... Should it be n layer api? Maybe in a ui subsection. What do you think @Alex-NRCan? Because this is all related to ui, should we have ui api for such things?
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 155 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQt6r4z9xAisqbRjd:-NzhQt6r4z9xAisqbRje:bdp0ikw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L155)):*
> ```XML
>       setSelectedLayerPath: (layerPath: string): void => {
>         // Redirect to event processor
>         LegendEventProcessor.setSelectedLayersTabLayer(get().mapId, layerPath);
> ```

Can we add a button on the demo page to set this


<!-- Sent from Reviewable.io -->

2024-06-06 18:25 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 9 of 18 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 459 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhOlce2q3_QKSKEYDY:-Nziljjs3jbrz8mgUyDw:b-3zchit) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L459)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This emit, should it be like the other one (e.g. visibility) and be private in abstact(geoview-gc-layers?
</blockquote></details>

I have it that way because nothing else is happening except the emit. It is basically just a place to store the emit.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 606 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhP2RoAJpEeVk_8Tpq:-NzimCYJBJ_PKkL7XM37:buo9nmt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L606)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here for layer events
</blockquote></details>

Same here
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhPdsu4XhvmWwFazZ4:-NzimOhs2F86EqvcxF6X:blk0z1e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would be more ecplicit

setLegendLayerCollapseState(mapId: string, layerPath: string, isCollapse: boolean)
</blockquote></details>

It adds a lot of complexity if we want to add the boolean in and do it this way
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-NzimhkEB24juKFXALUP:bn2hvnv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All these functions are duplicated in app bar and footer bar.... Should it be n layer api? Maybe in a ui subsection. What do you think @Alex-NRCan? Because this is all related to ui, should we have ui api for such things?
</blockquote></details>

Yeah, I struggled with this. If this is all we're using it for, I don't think the UI api would be worth it. I initially had them in layer, but it didn't really make sense.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 155 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQt6r4z9xAisqbRjd:-NzinA6L684oZVr2L9kJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L155)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we add a button on the demo page to set this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 20:56 UTC, jolevesq reviewed
> Reviewed 3 of 18 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 14 of 21 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzjKZDyCFypalGPlwat:-NzjKZDyCFypalGPlwau:bnvb8v1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b28cf271aa3526397620eb7632c751c31cf91fba/packages/geoview-swiper/src/swiper.tsx#L140)):*
> ```XML
> 
>   useEffect(() => {
>     if (mapLoaded) setTimeout(onStop, 250);
> ```

We need a TODO for the set time out as we are not suppose to have one. We will need proper fix later

Maybe delay would be better? like handleZoom in detail


<!-- Sent from Reviewable.io -->

2024-06-06 21:12 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 14 of 21 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzjKZDyCFypalGPlwat:-NzjOKlD0eGzVzHNwHVJ:b-bjpj7a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b28cf271aa3526397620eb7632c751c31cf91fba/packages/geoview-swiper/src/swiper.tsx#L140)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need a TODO for the set time out as we are not suppose to have one. We will need proper fix later

Maybe delay would be better? like handleZoom in detail
</blockquote></details>

Better?


<!-- Sent from Reviewable.io -->

2024-06-07 15:19 UTC, Alex-NRCan requested changes
> Reviewed 6 of 18 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 8 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 459 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhOlce2q3_QKSKEYDY:-Nzmm1cjCYMVIiZWlhd3:b-vnys8b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L459)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

I have it that way because nothing else is happening except the emit. It is basically just a place to store the emit.
</blockquote></details>

I guess this goes back to the discussion we're supposed to have about LayerApi vs layer-sets vs event processor vs store states vs framework classes. That is, (1) how we communicate between them (their flow) and (2) define their respective responsibilities.

There are 3 things here:

A) Right now, it seems to be setting the opacity on the state object first, then the classes (in the recursive function) and then propagating to the store. 
In other patterns, like the layer name change, we have the layer sets which take care of updating the stores based on what happens in the layers. The layer sets call the event-processors who propagate to the store. It'd be good to standardize the flow here.

To me, the event-processor classes are just a shortcut used by the ui to do actions on the classes, actions which any developer could be doing themselves manually. It simulates what the developer would be doing. Maybe I'm wrong. Here, I'd think that to change the opacity of a layer, a dev would be saying `layerApi.getGeoviewLayer(layerPath).setOpacity()` (the same way we do a layerName change). Be it called from a ui action or via code. That being said, now, I'm assuming the opacity change is more complex due to the hierarchy of it all and so this more "indirect" function was created which makes sense too. Nonetheless, I would put this function in the LayerAPI class: LayerApi.setLayerOpacity(layerPath, opacity), that way it can also inform the layer-sets more directly. I'd prefer it in LayerApi vs now in legend-event-processor.

B) I fail to see how the children opacity (their states if they have any) are propagated to the store? Because it seems like what's propagated to the store is the `curLayers` which is only changed for the 1 layer not all children? Or is that as expected?

C) Unless very specific exceptions, emits should be have private/protected modifier (not public). In this case, it seems we only want 1 opacity changed event to be raised (even if the opacity of children might change?). So, to me, once/if the code is moved to the LayerApi, it'd be a `LayerApi.emitOpacityChanged() event` thing. Emitted by the LayerApi. So, in total, the layers themselves would have a layer opacity changed event (for each individual layer) and the LayerApi would have its own layer opacity changed event when this one function here is called (after the more complex/hierarchical logic is applied). A dev could be listening to either kind of opacity changed events to do their work.

Food for discussions..
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 432 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-Nzn0kNM9XPbvMNLKgDo:-Nzn0kNNClHotUK069sg:b-1xj38t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L432)):*
> ```XML
>    */
>   static #setOpacityInLayerAndChildren(mapId: string, layer: TypeLegendLayer, opacity: number, isChild = false): void {
>     _.set(layer, 'opacity', opacity);
> ```

Why using the lodash.set here instead of the more straightforward like layer.opacity?
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-Nzn6CUEEBCrx6DND5aC:b-4ex48s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Yeah, I struggled with this. If this is all we're using it for, I don't think the UI api would be worth it. I initially had them in layer, but it didn't really make sense.
</blockquote></details>

One quick and natural way to handle this would be to have app-bar-api and footer-bar-api inherit from a ui-api class and have those duplicated functions at one place in the mother class. However, I'm not quite sure what their "raison d'être" are. It's not that bad to have them be duplicated too seeing how they are just redirections to the event processors. An alternative would be to expose the event processors so that they are accessible like :`cgpv.api.maps.Map1.*uiEventProcessor*.getLayersCollapsedInLegend()`, but that might be exposing too much?

I agree, that I wouldn't be putting those in Layer Api.

That being said, it made me realize we might have forgotten to initialize the UIEventProcessor in `api\event-processors\index.ts`: 
I'm surprised it's even working :open_mouth:  
![image.png](https://files.reviewableusercontent.io/images/reviewable/94073946/xEG-esZ83gVYurqsQc4P3hWq/image.png)
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznBrqQ0KeMiTDnJkRh:-NznBrqQ0KeMiTDnJkRi:b-sxedna) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts#L74)):*
> ```XML
>    * @returns {string | TypeGeochartResultSetEntry[] | GeoChartStoreByLayerPath | undefined} The requested state
>    */
>   getSingleGeochartState(
> ```

Just something catching my eye... I'm not sure how I feel about having a function about a GeochartState when it's very plausible there's no Geochart plugin loaded for the majority of the footer-bar-apis we have in our maps. It seems like we might be leaking plugin logic with 'specific' functions in a totally external class.

One way to be careful about that is if we have a single more generic function named something like `getPluginState(somePluginOrKeyOrThing, state)`. That way, it's explicit that it's something that *might* be there only if you *expect it* to be there. It'd also scale a whole lot better vs having to add 'custon' functions in here, depending on where we're going with plugins in general and how many we create, etc.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-NznD31V7bfJpTOdgu2K:bhfgv32) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
> ```XML
>     logger.logTraceUseEffect('SWIPER - mapLoaded', mapLoaded);
> 
>     const clearLoading = delay(onStop, 100);
> ```

A) If `delay` is executed once after 100 milliseconds has elapsed, I don't think it's worth clearing the timeout, but it's all good too, in the very small chance that we want to cancel it from being triggered in the 100 ms window between when it's created and when it triggers. :smile: 

B) That said, a comment on why it's necessary to do that particular delay would be good [...]

2024-06-07 15:23 UTC, Alex-NRCan requested changes
> Reviewed 10 of 18 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 9 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1552 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznHQYP2iOd29r9TXI1:-NznHQYP2iOd29r9TXI2:bh0mc69) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/geo/layer/layer.ts#L1552)):*
> ```XML
>    * @param {LayerReorderedEvent} event - The event to emit
>    */
>   emitLayerReordered(event: LayerReorderedEvent): void {
> ```

private?


<!-- Sent from Reviewable.io -->

2024-06-07 17:59 UTC, jolevesq requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 459 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhOlce2q3_QKSKEYDY:-Nznnp-e1TkfYG-XGGK5:b-s0rcb0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L459)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I guess this goes back to the discussion we're supposed to have about LayerApi vs layer-sets vs event processor vs store states vs framework classes. That is, (1) how we communicate between them (their flow) and (2) define their respective responsibilities.

There are 3 things here:

A) Right now, it seems to be setting the opacity on the state object first, then the classes (in the recursive function) and then propagating to the store. 
In other patterns, like the layer name change, we have the layer sets which take care of updating the stores based on what happens in the layers. The layer sets call the event-processors who propagate to the store. It'd be good to standardize the flow here.

To me, the event-processor classes are just a shortcut used by the ui to do actions on the classes, actions which any developer could be doing themselves manually. It simulates what the developer would be doing. Maybe I'm wrong. Here, I'd think that to change the opacity of a layer, a dev would be saying `layerApi.getGeoviewLayer(layerPath).setOpacity()` (the same way we do a layerName change). Be it called from a ui action or via code. That being said, now, I'm assuming the opacity change is more complex due to the hierarchy of it all and so this more "indirect" function was created which makes sense too. Nonetheless, I would put this function in the LayerAPI class: LayerApi.setLayerOpacity(layerPath, opacity), that way it can also inform the layer-sets more directly. I'd prefer it in LayerApi vs now in legend-event-processor.

B) I fail to see how the children opacity (their states if they have any) are propagated to the store? Because it seems like what's propagated to the store is the `curLayers` which is only changed for the 1 layer not all children? Or is that as expected?

C) Unless very specific exceptions, emits should be have private/protected modifier (not public). In this case, it seems we only want 1 opacity changed event to be raised (even if the opacity of children might change?). So, to me, once/if the code is moved to the LayerApi, it'd be a `LayerApi.emitOpacityChanged() event` thing. Emitted by the LayerApi. So, in total, the layers themselves would have a layer opacity changed event (for each individual layer) and the LayerApi would have its own layer opacity changed event when this one function here is called (after the more complex/hierarchical logic is applied). A dev could be listening to either kind of opacity changed events to do their work.

Food for discussions..
</blockquote></details>

It is not working anymore but yes, parent opacity cascade to child.

Agree with comment
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhPdsu4XhvmWwFazZ4:-NznoVZP2wz-_PafDrIq:b-7v5lk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L60)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

It adds a lot of complexity if we want to add the boolean in and do it this way
</blockquote></details>

Should it be a state in the ordered array. This way by config we can set collapse or expand
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-NznoukWBVQyr0WTQKFe:b5jx2tj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

One quick and natural way to handle this would be to have app-bar-api and footer-bar-api inherit from a ui-api class and have those duplicated functions at one place in the mother class. However, I'm not quite sure what their "raison d'être" are. It's not that bad to have them be duplicated too seeing how they are just redirections to the event processors. An alternative would be to expose the event processors so that they are accessible like :`cgpv.api.maps.Map1.*uiEventProcessor*.getLayersCollapsedInLegend()`, but that might be exposing too much?

I agree, that I wouldn't be putting those in Layer Api.

That being said, it made me realize we might have forgotten to initialize the UIEventProcessor in `api\event-processors\index.ts`: 
I'm surprised it's even working :open_mouth:  
![image.png](https://files.reviewableusercontent.io/images/reviewable/94073946/xEG-esZ83gVYurqsQc4P3hWq/image.png)
</blockquote></details>

There is no protected override onInitialize so it is just static function. May be a good thing to do the new.

We should do something like state-api to have all the getter we need api.maps[id].states.getLEgendLAyerInfo()... this is only a getter class for all event processor we want to expose?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznBrqQ0KeMiTDnJkRh:-Nznq3bB7Xyxvw6Xrixo:b-8ayu6x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts#L74)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Just something catching my eye... I'm not sure how I feel about having a function about a GeochartState when it's very plausible there's no Geochart plugin loaded for the majority of the footer-bar-apis we have in our maps. It seems like we might be leaking plugin logic with 'specific' functions in a totally external class.

One way to be careful about that is if we have a single more generic function named something like `getPluginState(somePluginOrKeyOrThing, state)`. That way, it's explicit that it's something that *might* be there only if you *expect it* to be there. It'd also scale a whole lot better vs having to add 'custon' functions in here, depending on where we're going with plugins in general and how many we create, etc.
</blockquote></details>

Agree
___
*[`packages/geoview-swiper/src/swiper.tsx` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzjKZDyCFypalGPlwat:-Nznqfsd24STJ24nwp1k:b2tdv3y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b28cf271aa3526397620eb7632c751c31cf91fba/packages/geoview-swiper/src/swiper.tsx#L140)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Better?
</blockquote></details>

see comment below
___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-NznqK5b2KG-vB6SJgh6:b-q8lm0r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
<details><summary><i>Previously, Alex-NR [...]

2024-06-07 18:19 UTC, Alex-NRCan reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 8 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-NzntXGL9Eieyqhk-Vp5:b-b78wx2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no protected override onInitialize so it is just static function. May be a good thing to do the new.

We should do something like state-api to have all the getter we need api.maps[id].states.getLEgendLAyerInfo()... this is only a getter class for all event processor we want to expose?
</blockquote></details>

statesApi is another idea yeah, can think on it over the weekend too. I just think there has to be an even simpler way that I'm not seeing right now. I'm thinking, straight with the classes instead of going to the state directly.

With the overall discussion about LayerApi vs LayerSets vs processors vs states, etc, I'd think we have a similar logic with say the MapViewer and the way it uses the processors vs states (so more like a `api.maps[id].getLegendLayerInfo()` directly, kind of thing, as it's a shared state. But yeah, it looks like a StateApi at that point which has its own flow like the LayerApi does.

Food for thought..
___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-NznutW2DRyc0ZdNq-OB:b58fn8v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is the delay we have in our utils function
```
/**
 * Delay helper function.
 * @param ms number Number of milliseconds to wait for.
 * @returns Promise<void> resolves when the delay timeout expires.
 */
export const delay = (ms: number): Promise<void> => {
  return new Promise((resolve) => {
    // Wait
    setTimeout(resolve, ms);
  });
};
```
</blockquote></details>

Hmm actually no. The delay in utils is the one I created, because I wanted to work with a delayed `Promise` object to do async stuff and I've implemented it using straight JS.

The delay here is the one from lodash library.


<!-- Sent from Reviewable.io -->

2024-06-07 18:23 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-NznvnUW-YYE9QwPr1CU:b-mjcj8r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Hmm actually no. The delay in utils is the one I created, because I wanted to work with a delayed `Promise` object to do async stuff and I've implemented it using straight JS.

The delay here is the one from lodash library.
</blockquote></details>

Yeah but I wanted to say we can use this delay instead of the setTmeout


<!-- Sent from Reviewable.io -->

2024-06-07 20:06 UTC, Alex-NRCan reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 8 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-NzoIktRDJFR3Y5zNHah:b8pv1ku) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yeah but I wanted to say we can use this delay instead of the setTmeout
</blockquote></details>

Oh right, true, true


<!-- Sent from Reviewable.io -->

2024-06-10 22:56 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 6 of 27 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 459 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhOlce2q3_QKSKEYDY:-O-1nw6GD63pU3qxnNTG:b-bu91xm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L459)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is not working anymore but yes, parent opacity cascade to child.

Agree with comment
</blockquote></details>

Updated
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 432 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-Nzn0kNM9XPbvMNLKgDo:-O-1ToHE1YBuxw4eSjKg:bkg1js5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L432)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Why using the lodash.set here instead of the more straightforward like layer.opacity?
</blockquote></details>

No idea, there was also use of the lodash version of forEach in the visibility functions that I removed when I moved them. Removed
___
*[`packages/geoview-swiper/src/swiper.tsx` line 144 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznD31V7bfJpTOdgu2J:-O-3I28l4HeLFhqhk2aQ:b-l2lejh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-swiper/src/swiper.tsx#L144)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Oh right, true, true
</blockquote></details>

Back to original with comment
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhPdsu4XhvmWwFazZ4:-O-3BNmR4FOX7dL0hTuJ:b-x3abf5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be a state in the ordered array. This way by config we can set collapse or expand
</blockquote></details>

That makes sense, moved it there


<!-- Sent from Reviewable.io -->

2024-06-11 15:27 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 5 of 29 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 606 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhP2RoAJpEeVk_8Tpq:-O-6tjOw1fcq4Xo2I2Fh:b-odwz7s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L606)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Moved to state API
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1552 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznHQYP2iOd29r9TXI1:-O-6tuPx1gG9WH1LTNHI:b-odwz7s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/geo/layer/layer.ts#L1552)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Moved to state API
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-api.ts` line 210 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NzhQ4kH0qvwOiJShwIW:-O-6u3DcAODHLrGopP9u:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a696135b730314a6597709acc3e0f6b076ae3a0/packages/geoview-core/src/core/components/app-bar/app-bar-api.ts#L210)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

statesApi is another idea yeah, can think on it over the weekend too. I just think there has to be an even simpler way that I'm not seeing right now. I'm thinking, straight with the classes instead of going to the state directly.

With the overall discussion about LayerApi vs LayerSets vs processors vs states, etc, I'd think we have a similar logic with say the MapViewer and the way it uses the processors vs states (so more like a `api.maps[id].getLegendLayerInfo()` directly, kind of thing, as it's a shared state. But yeah, it looks like a StateApi at that point which has its own flow like the LayerApi does.

Food for thought..
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-NznBrqQ0KeMiTDnJkRh:-O-6u4hF9uDAOZnUewt-:b-yagwie) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f1fe4bbfb1760709113e04d578dea243a1c50e3/packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done (in state API)


<!-- Sent from Reviewable.io -->

2024-06-11 20:55 UTC, Alex-NRCan requested changes
> Reviewed 13 of 21 files at r4, 8 of 8 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: all files reviewed, 10 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 441 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-7zv_-8OqwKjIzEcNR:-O-7zv_-8OqwKjIzEcNS:b-t7bgpb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b2401684c165db801b0ae837eeadd70c78ee4045/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L441)):*
> ```XML
>     if (layer) {
>       layer.opacity = opacity;
>       MapEventProcessor.getMapViewerLayerAPI(mapId).getGeoviewLayer(layerPath)?.setOpacity(opacity, layerPath);
> ```

Not mandatory for this PR, but I'm taking note (and for the short-future).
Please use `getGeoviewLayerHybrid()` instead of `getGeoviewLayer()`. It'll be absolutely transparent for you, but it'll allow us to switch to the new layers mode and be able to test/validate that this function still works with the new layers (as part of the layers migration).
___
*[`packages/geoview-core/src/core/stores/state-api.ts` line 16 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-81lA-1Ri1xCWQ5Q_C:-O-81lA08ARTydk9N2rg:bfhd5y9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b2401684c165db801b0ae837eeadd70c78ee4045/packages/geoview-core/src/core/stores/state-api.ts#L16)):*
> ```XML
>  * API to manage states.
>  */
> export class StateApi {
> ```

This is good.
I can see the benefit of having a stateApi easily accessible which allows a dev/user to get a state of something instead of having to go through the respective EventProcessor.
___
*[`packages/geoview-core/src/core/stores/state-api.ts` line 68 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-83upd5TKCtXtHtxon:-O-83upd5TKCtXtHtxoo:b-g9o9v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b2401684c165db801b0ae837eeadd70c78ee4045/packages/geoview-core/src/core/stores/state-api.ts#L68)):*
> ```XML
>    */
>   getPluginState(
>     pluginId: 'geochart' | 'swiper' | 'time-slider',
> ```

I see what you did here. It's still enforcing knowledge of (in the case 3) specific plugins, unfortunately, but it's better than it was.
Wish we could bring this even more generic, but not sure how to do it right now. Works for me for now. Could use a TODO here eventually.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1035 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-82qdk1ADoQ9ZGFlGe:-O-82qdk1ADoQ9ZGFlGf:bkoren9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b2401684c165db801b0ae837eeadd70c78ee4045/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1035)):*
> ```XML
>     if (olLayer) {
>       olLayer.setOpacity(layerOpacity);
>       this.#emitLayerOpacityChanged({ layerPath, opacity: layerOpacity });
> ```

I think this is fantastic. Hopefully it works and we leverage this pattern.
Note to self to add this event in abstract-gv-layer.ts (the new layers).
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 486 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-83BnN10PW31uUN9PQ:-O-83BnO7T1aG-wvb1K8:bljtsmx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b2401684c165db801b0ae837eeadd70c78ee4045/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L486)):*
> ```XML
>   setOpacity(layerOpacity: number): void {
>     this.getOLLayer().setOpacity(layerOpacity);
>     this.#emitLayerOpacityChanged({ layerPath: this.getLayerPath(), opacity: layerOpacity });
> ```

No kidding! You did it already! :+1: 


<!-- Sent from Reviewable.io -->

2024-06-11 22:34 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 27 of 30 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 441 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-7zv_-8OqwKjIzEcNR:-O-8QbMB2U2SDYru9RMM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00f39b12ff455ec1d5c344e59ea8b00b40a6ca1e/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L441)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Not mandatory for this PR, but I'm taking note (and for the short-future).
Please use `getGeoviewLayerHybrid()` instead of `getGeoviewLayer()`. It'll be absolutely transparent for you, but it'll allow us to switch to the new layers mode and be able to test/validate that this function still works with the new layers (as part of the layers migration).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-12 14:19 UTC, jolevesq requested changes
> Reviewed 9 of 21 files at r4, 2 of 8 files at r5, 1 of 2 files at r7, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 28 of 30 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/legend/legend-layer.tsx` line 182 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-BoCfY3lt5M0KxpCVF:-O-BoCfY3lt5M0KxpCVG:bv0w23x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1876fb9fc3d90bc9754736f4e16b9404897e1105/packages/geoview-core/src/core/components/legend/legend-layer.tsx#L182)):*
> ```XML
>       );
>     }
>     // show sub items only when number of items are more than 1.
> ```

The single item like WMS does not expand anymore
 May be because of this


<!-- Sent from Reviewable.io -->

2024-06-12 14:25 UTC, jolevesq reviewed
> Reviewed 4 of 21 files at r4, 4 of 8 files at r5, 2 of 2 files at r6, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 29 of 30 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-12 14:39 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-layer.tsx` line 182 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-O-BoCfY3lt5M0KxpCVF:-O-BsvMzCGraT_rll-ms:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1876fb9fc3d90bc9754736f4e16b9404897e1105/packages/geoview-core/src/core/components/legend/legend-layer.tsx#L182)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The single item like WMS does not expand anymore
 May be because of this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-12 14:57 UTC, Alex-NRCan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221#-:-O-BwxtN9S5I4hXr-bri:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)



<!-- Sent from Reviewable.io -->

2024-06-12 15:21 UTC, jolevesq approved these changes
> Reviewed 2 of 8 files at r5, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-12 17:18 UTC, merged