Fetch metadata and layer tree
Canadian-Geospatial-Platform/geoview pull request #2227
Opened 2024-06-07 13:58 UTC by ychoquet

# Description

Fetch the service metadata and all the layer's metadata. Compute the layer tree.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace and debug the code.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)

2024-06-07 15:19 UTC, jolevesq requested changes
> Reviewed 2 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznGdVj8NezvZ2afhgg:-NznGdVk9ge12HtVXRjZ:b8udpao) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/public/configs/validator/04-geocore.json#L32)):*
> ```JSON
>           {
>             "layerId": "0",
>             "geometryType": "Point",
> ```

I think we should have this only in internal schema as we do not know before we read the metadata/layer


<!-- Sent from Reviewable.io -->

2024-06-07 15:19 UTC, jolevesq requested changes
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznGdVj8NezvZ2afhgg:-NznH801E_2upC4UrZna:b-1tqaun) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/public/configs/validator/04-geocore.json#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we should have this only in internal schema as we do not know before we read the metadata/layer
</blockquote></details>

I would keep lowercase.


<!-- Sent from Reviewable.io -->

2024-06-07 16:38 UTC, jolevesq requested changes
> Reviewed 5 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 8 of 19 files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 342 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWXOXBZbYJIG2xHGd:-NznWXOXBZbYJIG2xHGe:b29ofs7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L342)):*
> ```XML
>     serviceAccessString: string,
>     layerType: TypeGeoviewLayerType | 'geoCore',
>     language: TypeDisplayLanguage = 'en'
> ```

Should it be hardcoded?
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 300 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWgEG-MzoFEecpj3-:-NznWgEG-MzoFEecpj30:b-weupzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/map-schema-types.ts#L300)):*
> ```XML
> 
> /** Valid keys for the geometryType property. */
> export type TypeStyleGeometry = 'Point' | 'LineString' | 'Polygon';
> ```

Lower case?
___
*[`packages/geoview-core/src/api/config/types/classes/config-exceptions.ts` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWyfy43Laa1ogAN6a:-NznWyfy43Laa1ogAN6b:bsujqfi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/config-exceptions.ts#L26)):*
> ```XML
> }
> 
> export class GeoviewLayerMandatoryError extends ConfigError {
> ```

We continue to add classes to the file... can we have one class or split them. Is it the last class to be added? 
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 184 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznXubB0YsE6d0U1azC:-NznXubC7HKz8--0VpOl:b-vm2x45) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L184)):*
> ```XML
>    *
>    * @returns {Promise<void>} The promiseAllLayersProcessed instance.
>    * @protected
> ```

protected keywork but getter seems public while exposing a protected promise


<!-- Sent from Reviewable.io -->

2024-06-07 16:41 UTC, jolevesq reviewed
> Reviewed 6 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 14 of 19 files reviewed, 5 unresolved discussions (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-06-07 18:07 UTC, Alex-NRCan requested changes
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 20 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWlzN1VppuzuLrpA7:-NznWlzN1VppuzuLrpA8:b-kd7dqn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L19)):*
> ```XML
>   // GV: content or call the methods of the last instance created by the corresponding ConfigApi call.
>   /** Static property that contains the last object instanciated by the ConfigApi.getLayerConfig call */
>   static getLayerConfigInstance?: AbstractGeoviewLayerConfig;
> ```

A class attribute shouldn't be prefixed with 'get' it reads weirdly and dev expectations is to see a 'getter/get function' with a 'get' prefix. Lower in this class, it reads very weirdly to see something like: `ConfigApi.getMapConfigInstance = mapFeatureConfig`. Should just be `ConfigApi.mapConfig = mapFeatureConfig` - if you want to implement that pattern.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 278 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznXgcF1KXfEhk2-YF7:-NznXgcGCfGmuaMVmf5I:b-h8v26n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L278)):*
> ```XML
>   // GV: favor of their GeoView equivalent as soon as possible. Processing is based on the JSON representation of the config,
>   // GV: and requires a minimum of validation to ensure that the configuration of GeoCore layers is valid.
>   static async getMapConfig(mapConfig: string | TypeJsonObject, language: TypeDisplayLanguage): Promise<MapFeatureConfig> {
> ```

This function name should probably be changed to something that doesn't sound like a 'getter', because it's doing more processing than that. Seems more like an `initMapConfig` of sorts. The kind of function you call once.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 339 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznYt1q8L3F729SRgy_:-NznYt1q8L3F729SRgya:b2tmujg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L339)):*
> ```XML
>   // GV: GeoCore layers are processed here, well before the schema validation. The aim is to get rid of these layers in
>   // GV: favor of their GeoView equivalent as soon as possible.
>   static async getLayerConfig(
> ```

This function name should probably be changed to something that doesn't sound like a 'getter', because it's doing more processing than that. Seems more like an `initLayerConfig` of sorts. The kind of function you call once.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-NznbwC18vlhcD3B5Khz:b-3vtnc5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
> ```XML
>     // GV: been supplied by the user rather than initialized using a default value is to look
>     // GV: in the original configuration copy kept in the instance
>     const clonedJsonConfig = this.#originalgeoviewLayerConfig;
> ```

Why reassigning the cloned attribute to a local variable?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-Nzn_R9n9pbVqYeQXXcU:b65idvf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
> ```XML
>   }
> 
>   getAllServiceMetadata(): void {
> ```

Rename the function?
Also, instead of hiding a promise via a class attribute that you then access later via a public getter, can this function simply return the Promise and the call to`resolveMap()` be done more explicitly than via a 'getter'? It'd help follow the flow.
This current pattern forces a dev to really look into the code implementation to understand what's going on..
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 190 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbHuG8GvYbE9D6dz4:-NznbHuG8GvYbE9D6dz5:byh9g5g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L190)):*
> ```XML
>   }
> 
>   protected resolveMap(): void {
> ```

Why protected modifier? Are you expecting to inherit from this class and have children?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 194 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbNiWCyrHExRF0FKh:-NznbNiWCyrHExRF0FKi:b2bzm8a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L194)):*
> ```XML
>   }
> 
>   protected rejectMap(reason?: unknown): void {
> ```

Same comment
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 213 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NzndntG9bsrwl2QH-vv:-NzndntG9bsrwl2QH-vw:bbdgz3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L213)):*
> ```XML
>    * @returns {string} The json string corresponding to the map feature configuration.
>    */
>   getJsonString(): string {
> ```

Instead of having 2 functions `getJsonString` and `getIndentedJsonString`, why not just one `getJsonString` function which takes the optional 'indent' parameter? Logic seems to be reversed here where 1 function calls the other with null when it's already sort of optional on the other method.

Also, the purpose of this function seem to be to turn the current class in a json string. This is called serializing. I'd simply call this method `serialize(indent?: number = 2): string`.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzne_EL4q34g1sO-rEP:-Nzne_EMAV1AWuaxyJ1j:b-jy6xfl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L231)):*
> ```XML
>    * Methode used to propagate the error flag to the MapFeatureConfig instance.
>    */
>   propagateError(): void {
> ```

Rename this function to `setErrorDetected()` (without actual parameters) as it seems more like a setter for an attribute rather than an active function propagating anything? I know it's called many places and imo it would read better when looking at rest of the code calling this.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-Nznmkso0rCEqVVnxY7c:b8pkex6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abs [...]

2024-06-07 18:26 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 20 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 339 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznYt1q8L3F729SRgy_:-NzntDCJ-KuyJt_D9Zzi:bhg9m9x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L339)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This function name should probably be changed to something that doesn't sound like a 'getter', because it's doing more processing than that. Seems more like an `initLayerConfig` of sorts. The kind of function you call once.
</blockquote></details>

Or process like we have before
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-NzntRPj2WJyOSctGW1N:b-uc5yp1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Why reassigning the cloned attribute to a local variable?
</blockquote></details>

I think it is because the original value will be modified like in the viewer layerConfig before? For sure we need to keep a default version so we can reassign later to make sure config is apply over metadata
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznisrbCGYi6SlZyHsj:-NznurpuDEhryyutRw7V:b-rp2sf1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts#L16)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I'm guessing this additional class-parenting is to simplify some common code happening between EsriFeatureLayerConfig and EsriDynamicLayerConfig. If we do want this additional class parenting, can this class be renamed to `AbstractGeoviewEsriLayerConfig` to keep the meaning of the class. It wasn't clear to me until I saw that, that 'EsriCommon' was actually a `LayerConfig` thing class.
</blockquote></details>

Seems there is already a class of that name, @Alex-NRCan do you mean move code (use in both classes to mother class?)
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznjm8U0sotOgbyk3aM:-NznwelV2Z4AMU2ZGiv6:bbiaz24) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts#L49)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This function does more than a 'getter'. It actually 'sets' the metadata then checks if there were any errors that happened on the fetching of the metadata then creates a layer tree, then fetches more things. Those should be written more clearly. As it is, you have to know the internal implementation too much if you want to be able to follow the code. The `if (this.isValid)` notably.

`EsriCommon.fetchEsriMetadata`'s promise should resolve if it went well or reject if an error happened and the handling of the error be handled here in the `getServiceMetadata()`(to be renamed). More straightforward and easier to follow.
</blockquote></details>

I think you are right set and get should be few lines only doing this. We do not want to end in the layerstatus string assignment who start many process on the fly


<!-- Sent from Reviewable.io -->

2024-06-07 20:24 UTC, Alex-NRCan requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 20 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-NzoJAAg8x52Ifp5yGvr:b-70qlsc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think it is because the original value will be modified like in the viewer layerConfig before? For sure we need to keep a default version so we can reassign later to make sure config is apply over metadata
</blockquote></details>

Yes, I get the cloning part and keeping a copy in `this.#originalgeoviewLayerConfig`, but this value gets reassigned to `clonedJsonConfig` which is then sent to other places in this constructor. So when you read code in the constructor, one could think ` clonedJsonConfig` is just some local variable, but it's actually the same as `this.#originalgeoviewLayerConfig`. So, it could just be `this.#originalgeoviewLayerConfig` that is reused, easier to know, when reading code, that it's the actual class attribute being used instead of a local variable that you might think is different than the class attribute. The outcome is the same. Just for code readability.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznisrbCGYi6SlZyHsj:-NzoM8EH3p-TJmYf1RCN:bow165y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/esri-common.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Seems there is already a class of that name, @Alex-NRCan do you mean move code (use in both classes to mother class?)
</blockquote></details>

There's already a `AbstractGeoviewEsriLayerConfig`? (note the 'Esri')


<!-- Sent from Reviewable.io -->

2024-06-09 00:07 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 20 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznGdVj8NezvZ2afhgg:-NznvkwVCTqaBu9e1deF:b-qkga1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/public/configs/validator/04-geocore.json#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I would keep lowercase.
</blockquote></details>

When the user provides a value, it is because he wants to overwrite what is in the metadata. The user is supposed to know what he is doing.

It was lowecase before, I switch it to fit the code I extracted in the old implementation. I'll revert it to lowercase.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWlzN1VppuzuLrpA7:-Nznyd-C3CVpjw_-q1vz:btkl7pl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L19)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

A class attribute shouldn't be prefixed with 'get' it reads weirdly and dev expectations is to see a 'getter/get function' with a 'get' prefix. Lower in this class, it reads very weirdly to see something like: `ConfigApi.getMapConfigInstance = mapFeatureConfig`. Should just be `ConfigApi.mapConfig = mapFeatureConfig` - if you want to implement that pattern.
</blockquote></details>

Done. Changed to something similar.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 278 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznXgcF1KXfEhk2-YF7:-Nzo-0LyDgi51ppkY1b9:btkl7pl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L278)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This function name should probably be changed to something that doesn't sound like a 'getter', because it's doing more processing than that. Seems more like an `initMapConfig` of sorts. The kind of function you call once.
</blockquote></details>

Done. Changed to something similar.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 339 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznYt1q8L3F729SRgy_:-Nzo-5iM6-ckl8pTrcNA:btkl7pl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L339)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Or process like we have before
</blockquote></details>

Done. Changed to something similar.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 342 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWXOXBZbYJIG2xHGd:-Nzo-CodA90X3K1ef0K8:b-7mzy1o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L342)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be hardcoded?
</blockquote></details>

Done. Created a constante for geoCore. 'en' is a default value.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 300 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWgEG-MzoFEecpj3-:-Nzo1_g32KTcZkf3fcwZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/map-schema-types.ts#L300)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Lower case?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/config-exceptions.ts` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWyfy43Laa1ogAN6a:-Nzo1lQB-2z397Zv47Hs:b-vgw34d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/config-exceptions.ts#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We continue to add classes to the file... can we have one class or split them. Is it the last class to be added?
</blockquote></details>

This exception file is based on the layer-exceptions file. It has a comment at the top saying:
/\* eslint-disable max-classes-per-file \*/
// We want more than 1 Error class here to save files

I 've recently add a new exception and may add some other, we'll see.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-Nzo3XFZ6P63JlaW_-ZJ:b-3td9jf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yes, I get the cloning part and keeping a copy in `this.#originalgeoviewLayerConfig`, but this value gets reassigned to `clonedJsonConfig` which is then sent to other places in this constructor. So when you read code in the constructor, one could think ` clonedJsonConfig` is just some local variable, but it's actually the same as `this.#originalgeoviewLayerConfig`. So, it could just be `this.#originalgeoviewLayerConfig` that is reused, easier to know, when reading code, that it's the actual class attribute being used instead of a local variable that you might think is different than the class attribute. The outcome is the same. Just for code readability.
</blockquote></details>

I did this to avoid getting the ***Assignment to property of function parameter*** warning when I apply the default values to the user-supplied config. However, after verification, this trick leaks the default values in the original copy, breaking the backup.

The easiest way to correct this problem is probably to disable the generation of warnings for the line concerned. But the safest way is to make another cloneDeep to avoid leaks in the caller's object. That's what I did.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-NzpjJ7y50xadP2wQmQo:baouhdo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Rename the function?
Also, instead of hiding a promise via a class attribute that you then access later via a public getter, can this function simply return the Promise and the call to`resolveMap()` be done more explicitly than via a 'getter'? It'd help follow the flow.
This current pattern forces a dev to really look into the code implementation to understand what's going on..
</blockquote></details>

Indead, as you sugested, it is possible to simplify the code and make it more explicit. I renamed the method to fetchAllServiceMetadata. It doesn't return a promise because I don't want this method to be called in an asynchrone way.  It is cal [...]

2024-06-11 02:25 UTC, Alex-NRCan requested changes
> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 18 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWlzN1VppuzuLrpA7:-O-3N2H7804lN3ZL8ZmJ:bpvu87b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L19)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done. Changed to something similar.
</blockquote></details>

That works, though I'm not sure why the prefix 'last' is necessary? Seems redundant as it's implied since there's no other.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 300 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWgEG-MzoFEecpj3-:-O-3NT-n0yaxgpfY8ORV:b-rfdhld) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/map-schema-types.ts#L300)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment.
This is going to have an impact on the old config vs new config migration. We'll have to be cautious about later. It's adding work for us.
___
*[`packages/geoview-core/src/api/config/types/classes/config-exceptions.ts` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWyfy43Laa1ogAN6a:-O-3w5LZ50AI5E-_r5Hf:b-hd18wy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/config-exceptions.ts#L26)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This exception file is based on the layer-exceptions file. It has a comment at the top saying:
/\* eslint-disable max-classes-per-file \*/
// We want more than 1 Error class here to save files

I 've recently add a new exception and may add some other, we'll see.
</blockquote></details>

Comment.
Yeah, I think we can stack a couple redundant (in their writing) exceptions in the same file. I'm the one that started stacking some when I initialized the layers-exception file. We can always have a distinct file for each one when we want, it's just, it'd likely be a lot of files.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-3OM3C1rjValraEK65:b6m9frp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I did this to avoid getting the ***Assignment to property of function parameter*** warning when I apply the default values to the user-supplied config. However, after verification, this trick leaks the default values in the original copy, breaking the backup.

The easiest way to correct this problem is probably to disable the generation of warnings for the line concerned. But the safest way is to make another cloneDeep to avoid leaks in the caller's object. That's what I did.
</blockquote></details>

It's not an assignment to property of function parameter, it's just replacing `clonedJsonConfig` with `this.#originalgeoviewLayerConfig` in the code in this constructor.
Neither `clonedJsonConfig` nor `this.#originalgeoviewLayerConfig` is a function parameter property being reassigned. I'm not sure why you'd be getting the eslint warning?
It's also odd that you have to clone the same object twice. This might need further investigation which is hard to do via reviewable.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-O-3QD5x70AeyFdFpmxr:b-me450p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Indead, as you sugested, it is possible to simplify the code and make it more explicit. I renamed the method to fetchAllServiceMetadata. It doesn't return a promise because I don't want this method to be called in an asynchrone way.  It is called right after the map instanciation to trigger the fetch mainly because a constructor cannot be asynchronous. It will be awaited after the UI has displayed the partial map and layer information using the promise returned by the promiseAllLayersProcess method.
</blockquote></details>

It's true that a constructor cannot be asynchronous.
I still wouldn't store a promise (or an array of promises) as class attributes. It's against best practices. The constructor should create the object and the asynchronous functions (like fetchAllServiceMetadata) should return a Promise.
Furthermore, `fetchAllServiceMetadata` doesn't seem to be called in the constructor anyways?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzne_EL4q34g1sO-rEP:-O-3WPbk4XgnhutvN3tt:b-55ji1w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L231)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I renamed it to raiseErrorDetectedFlag.
</blockquote></details>

Hmmm, I personally prefer 'set', because 'raise' is a prefix typically used for methods that raise/emit events. Also, 'raise' implies an action which isn't what this 'setter' actually does.
That said, I can resolve for now..
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3Trz-3IZz0kCE4V_e:-O-3Trz-3IZz0kCE4V_f:b-g3xnn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L166)):*
> ```XML
>    * @protected
>    */
>   async promiseAllLayersProcessed(): Promise<void> {
> ```

Depending what we do with the promises as attributes, I would delete this function.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-3f5En9x3j-I_J-YHx:b-o0sl9v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I understand that in most cases, promises are created and awaited immediately afterwards in the same block of code. However, in this case, we want to trigger the asynchronous process, but wait for its resolution elsewhere in the execution sequence so that we can perform other operations (in this case, UI operations). This programming patern is perfectly functional and optimizes execution time. Of course, this optimization comes at a cost in terms of code readability, but in the present [...]

2024-06-11 13:35 UTC, jolevesq requested changes
> Reviewed 8 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 300 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWgEG-MzoFEecpj3-:-O-6T2wD5Avt_Y-C1Eec:b8bbp38) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/map-schema-types.ts#L300)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Comment.
This is going to have an impact on the old config vs new config migration. We'll have to be cautious about later. It's adding work for us.
</blockquote></details>

Ok, if it is work, we can revert and keep caps for now....
___
*[`packages/geoview-core/src/api/config/types/type-guards.ts` line 143 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-6TDi76ORLthQxn5KC:-O-6TDi76ORLthQxn5KD:bk3luhy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/type-guards.ts#L143)):*
> ```XML
>  * function.
>  *
>  * @param {EntryConfigBaseClass} verifyIfLayer Polymorphic object to test in order to determine if the type assertion is valid.
> ```

We should try to avoid renaming values inside an actual PR, It puts more work on the review.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 197 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-41HOA6X_9hZ7U9Un7:-O-6Uf9t2qnk0bKzZIyE:b-m2e9es) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L197)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

The code inside this function should be moved in a static method accepting a url and returning a Promise<TypeJsonObject>. I believe that's the function Johann expects to see? Uncoupled with the AbstractBaseLayerEntryConfig and accessible outside of all the configuration processing code.

If you want to push things further, the static method could return a Promise<LayerMetadata> where `LayerMetadata`  would be a class encapsulating the Json information and offering easily accessible 'getters' to quickly refer to the metadata information inside. The function here, `fetchEsriLayerMetadata`, could also return that object instead of a TypeJsonObject - leveraging the quick access of metadata information elsewhere in the respective config classes.
</blockquote></details>

Yes, it is what I would like. But not only related to esri.. This one may be inside a class but I want a static function

fetchLayerMetatadata(url, serviceType) *** maybe serviceMetadata
fetchLayerMetatadata(geoviewLayerConfig) *** maybe serviceMetadata

fetchLayerMetatadata(url, serviceType, [ids/layerName])
fetchLayerMetatadata(geoviewLayerConfig) ** with populated listOflayerEntryConfig


<!-- Sent from Reviewable.io -->

2024-06-11 13:40 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-6W69sEm1voEj3tf_S:b-hlz8by) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

When reading the code, I still think the promise could be returned and handled by the caller just fine. It's unfortunate that functions like `fetchServiceMetadata` and `fetchAllServiceMetadata` don't actually return promise as they do seem like a prime example of an async call and a good place to have them. As it is, the current implementation will cause issues down the road with state management and reusability (e.g. calling fetchServiceMetadata on a layer more than once). I'll leave it to Johann to decide.
</blockquote></details>

I would go with returning the promise to the caller an let him deal with the result.

Why do we have `fetchAllServiceMetadata`. Config API does not trigget the fetching of all services metadata. In fact no one does. IT is entry by entry.

The only time there is a process of all layers is to validate the config against the schema and parse geocore to an actual supported config.


<!-- Sent from Reviewable.io -->

2024-06-11 13:43 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 175 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznhZ873j7nEV8b1aDw:-O-6X-vI-xWt1tt0qCuE:b2fkzx7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L175)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I think my comment remains and eliminating asynchronous processes shouldn't be the solution, indeed.
I'm not sure I understand the complexity mentioned. It'd need more analysis than can be done by reading in reviewable. Couldn't you wait after syntactical validations to continue with the metadata afterwards? And if it's because you need to do work in between, couldn't you implement more than 1 promise, like chaining promises?
</blockquote></details>

@ychoquet  your code is not aware of a UI. It is the layers API responsibility to deal with this. The first validation against schema/geocore is the only thing layers api needs to start the process. After, it calls one by one the layers to fetchServiceMetadata for without knowing there is a UI behind


<!-- Sent from Reviewable.io -->

2024-06-11 13:47 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3sB2g5VROZy8fVnBM:-O-6XgZ63_LYW_HJIX1H:b-q7esrk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts#L23)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Was it necessary to rename this type? I ask because it's further deviating from the old implementation and causing eventual work. If we do want to rename it, I'd suggest renaming the attribute name as well, from geometryType to geometryStyle or something. This would again add additional work on our plates though..
</blockquote></details>

Let's try to minimize the changes. It is a bit my bad that I want clean stuff fast as we can. But yeah, lets make this work then do the modification. We can put TODO for the moment to say we would like to do this
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 85 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3tXFcBRpVKU0mnpMw:-O-6Y51VD7Nac-54i6NG:b-8ayu6x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L85)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This is another 'getter' that's actually a 'setter'.
The prefix could be 'set', so we can better expect what its doing, but since it's also fetching, and 'setter's are typically expected to be synchronous operations, I'd recommend naming this function `fetchAndSetMetadata()`.
</blockquote></details>

Agree
___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznGdVj8NezvZ2afhgg:-O-6YGzqD_nlT7z9M3xw:ba2ludq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/public/configs/validator/04-geocore.json#L32)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

When the user provides a value, it is because he wants to overwrite what is in the metadata. The user is supposed to know what he is doing.

It was lowecase before, I switch it to fit the code I extracted in the old implementation. I'll revert it to lowercase.
</blockquote></details>

Sorry for my comment about changing to lower case but as Alex mention, we should minimize unnecessary modification for now. We can keep old way and put a TODO for later.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3qCz69RkZD6qVkNNz:-O-6Xzru6LqadBgZozv8:b-8ayu6x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L11)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Was it necessary to rename this class? I ask because it's further deviating from the old implementation and causing eventual work for when we have to synch the configurations (like having to rename ConfigBaseClass in external classes).
</blockquote></details>

Agree


<!-- Sent from Reviewable.io -->

2024-06-12 00:10 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWlzN1VppuzuLrpA7:-O-6eJIkB2tclv8F9Car:b-nhigoo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L19)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

That works, though I'm not sure why the prefix 'last' is necessary? Seems redundant as it's implied since there's no other.
</blockquote></details>

This variable exist for **debugging purpose**. There is a comment above it to explain that. It contains the instance of the ***last feature config created*** by the call made using ***ConfigApi.createLayerConfig***. When you are in the Chrome Devtool, you can call the service like this:

***cgpv.api.configApi.createLayerConfig('https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/0', 'esriDynamic');***

and then inspect the instance like this:

***cgpv.api.configApi.lastLayerConfigCreated***
or
***cgpv.api.configApi.lastLayerConfigCreated.metadataLayerTree***
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 300 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWgEG-MzoFEecpj3-:-O-7Bn1k6z1IdMib5CgZ:b-jl522n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/map-schema-types.ts#L300)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Ok, if it is work, we can revert and keep caps for now....
</blockquote></details>

I would prefer not to make a revert, the modification is done and is functional.
___
*[`packages/geoview-core/src/api/config/types/type-guards.ts` line 143 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-6TDi76ORLthQxn5KC:-O-8Twdq0g7nTTgeWyBz:bblt5mj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/type-guards.ts#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should try to avoid renaming values inside an actual PR, It puts more work on the review.
</blockquote></details>

Totaly agree!
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-7CqMH--cGKeJPWbyq:b-frguqi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It's not an assignment to property of function parameter, it's just replacing `clonedJsonConfig` with `this.#originalgeoviewLayerConfig` in the code in this constructor.
Neither `clonedJsonConfig` nor `this.#originalgeoviewLayerConfig` is a function parameter property being reassigned. I'm not sure why you'd be getting the eslint warning?
It's also odd that you have to clone the same object twice. This might need further investigation which is hard to do via reviewable.
</blockquote></details>

I did the verification and if we do not clone twice, there is leaking in either the originalgeoviewLayerConfig or the providedMapFeatureConfig. We realy need to clone twice.

I have done the verification and if we don't clone twice, there will be a leak either in the originalgeoviewLayerConfig property or in the providedMapFeatureConfig passed as a parameter. We really need to clone twice.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-O-7DVcx3JNv4DbELZwO:b9jjx3w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It's true that a constructor cannot be asynchronous.
I still wouldn't store a promise (or an array of promises) as class attributes. It's against best practices. The constructor should create the object and the asynchronous functions (like fetchAllServiceMetadata) should return a Promise.
Furthermore, `fetchAllServiceMetadata` doesn't seem to be called in the constructor anyways?
</blockquote></details>

`fetchAllServiceMetadata` is called in ConfigApi, but we're going to remove the promises from the instance anyway.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzne_EL4q34g1sO-rEP:-O-7Izoy9s-np_j3V48Z:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L231)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Hmmm, I personally prefer 'set', because 'raise' is a prefix typically used for methods that raise/emit events. Also, 'raise' implies an action which isn't what this 'setter' actually does.
That said, I can resolve for now..
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3Trz-3IZz0kCE4V_e:-O-7E7ayAFs9LoaI67dP:bo89mrw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L166)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Depending what we do with the promises as attributes, I would delete this function.
</blockquote></details>

It will.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-7YM2bBJylF9qNvn6U:b-bjqvuq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I would go with returning the promise to the caller an let him deal with the result.

Why do we have `fetchAllServiceMetadata`. Config API does not trigget the fetching of all services metadata. In fact no one does. IT is entry by entry.

The only time there is a process of all layers is to validate the config against the schema and parse geocore to an actual supported config.
</blockquote></details>

This will be corrected to return a promise.

For your information, when we call ***fetchAllServiceMetadata***, the geocore layers no longer exist in the config. They have been eliminated during instantiation of the ***mapFeature*** or the ***geoviewLayer***, depending on the entry point used in ***ConfigApi*** (***createMapConfig*** or ***createLayerConfig***).

When the constructor returns, the config instance is partially validated. The object returned can be used to update the UI. It is up to you to call the UI or do anything else with it. ***The configApi will not make this call for you***, a [...]

2024-06-12 11:48 UTC, jolevesq requested changes
> Reviewed 1 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 14 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/esri-renderer-parser.ts` line 3 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-BGdq5AayI7hiyQI5O:-O-BGdq5AayI7hiyQI5P:bqabj96) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c3cc747492dd63c2975b7414a29c3e99352ae02f/packages/geoview-core/src/api/config/esri-renderer-parser.ts#L3)):*
> ```XML
> import { asString } from 'ol/color';
> 
> import {
> ```

Please, do not add more code to this PR. We should wait until it is merge and add this trough another PR. If we continue to improve active reviewed PR, it will be almost impossible to do the merge


<!-- Sent from Reviewable.io -->

2024-06-12 12:11 UTC, jolevesq requested changes
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 15 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-BKW_EAR3lSro_mrVe:b-re22tt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I did the verification and if we do not clone twice, there is leaking in either the originalgeoviewLayerConfig or the providedMapFeatureConfig. We realy need to clone twice.

I have done the verification and if we don't clone twice, there will be a leak either in the originalgeoviewLayerConfig property or in the providedMapFeatureConfig passed as a parameter. We really need to clone twice.
</blockquote></details>

If you never touch providedMapFeatureConfig do you reallly have to do deepClode? Why is this object modified later if it is original copy?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-O-BLdZO381zuQs3qx7V:b-f7k39m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

`fetchAllServiceMetadata` is called in ConfigApi, but we're going to remove the promises from the instance anyway.
</blockquote></details>

Like I mention in a comment on Slack, there is no AllServiceMetadata. Each call is individual and it is fetchServiceMetadata. The layers are not aware of other layers. The only time validate as a group is against the schema and at this point there is no fetch
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3Trz-3IZz0kCE4V_e:-O-BLATi5oyiRitU3Gag:b-b8626d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L166)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It will.
</blockquote></details>

There should be not such thing as AllLayers it is layer by layer and there is one promise by layer return from function call, We need to remove this test and make the function/class more streamline
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 56 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-BJzII22RPwZzV30ZT:-O-BJzII22RPwZzV30ZU:bt1s8ay) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c3cc747492dd63c2975b7414a29c3e99352ae02f/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L56)):*
> ```XML
> 
>   /** The array of promises associated with the individual layers. */
>   #promiseLayersProcessed: Promise<void>[] = [];
> ```

Class should not keep array of promise, there is one promise by layer and it is return with the function call. The promise to test geocore is return if use call static method convertGeocire or it is resolve in config api to continue process the metadata


<!-- Sent from Reviewable.io -->

2024-06-12 12:18 UTC, jolevesq reviewed
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 16 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 197 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-41HOA6X_9hZ7U9Un7:-O-BMbAfAFjhEXbXKf4o:b-b8v53r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L197)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This is one major point where my vision doesn't coincide with yours. In my implementation, code outside the config doesn't need the original metadata returned by the service call. It's only interested in the configuration resulting from metadata parsing. The result of the parsing follow the same structure, regardless of the type of geoview layer concerned.

Now, if in an exceptional case the original metadata is needed, it is still available within the geoview layer instance (service metadata) or sub-layer (layer entry metadata). It is not a promise and you don't have to await to get the metadata. Everything is in sync. All async are behind you.

So, for the exceptional cases where you would need the original metadata, you can get them using the config instance.

In the code, you can do: ***const serviceMetadata = geoviewLayerInstance.metadata***
In the debugger, you can see the metadata like this: ***cgpv.api.configApi.lastLayerConfigCreated.metadata***

In the code, you can do:
***const serviceMetadata = geoviewLayerInstance.listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].metadata***
In the debugger, you can see the metadata like this:
***cgpv.api.configApi.lastLayerConfigCreated.listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].metadata***
</blockquote></details>

I do not really care about original.... I want the parsed fetch config JSON object. The original values are in the mapConfig and I should be able to get back to it because I store in state the original config. The only thing I need is a function whho will take my input config, fetch metadata, parse and merge values, return JSON (in a form of a promise)


<!-- Sent from Reviewable.io -->

2024-06-12 12:23 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 16 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-BNcRj2QtKgZOfnB_6:btdy6kl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This will be corrected to return a promise.

For your information, when we call ***fetchAllServiceMetadata***, the geocore layers no longer exist in the config. They have been eliminated during instantiation of the ***mapFeature*** or the ***geoviewLayer***, depending on the entry point used in ***ConfigApi*** (***createMapConfig*** or ***createLayerConfig***).

When the constructor returns, the config instance is partially validated. The object returned can be used to update the UI. It is up to you to call the UI or do anything else with it. ***The configApi will not make this call for you***, as it doesn't know what you want to do.

Next, we use the instance to call (after correction) the asynchronous ***fetchAllServiceMetadata*** method, which will fetch only the metadata required to complete the validation.  And, while we're at it, we should rename the method to ***completeLayerValidation*** since we not only fetch but also parse the metadata and validate the config.

The end result is a validated static configuration that can be used to update the UI and instantiate layers via layerApi.
</blockquote></details>

It needs to be corrected before we merge the PR.
If you look at my schema, I moved the check for geocore outside schema validation so if we add other who needs to be checked it will done layer by layer when we process them.

I do not really need a constructor who return an instance. Because the schema validation is not sync, we can update UI right away and for layer validation/fetch - there is no ui to update, viewer will take care of it. It will be loading until the promise is resolve or reject


<!-- Sent from Reviewable.io -->

2024-06-12 12:24 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 16 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3qCz69RkZD6qVkNNz:-O-BP1b6Dj_2ojjgckc7:b-4jthv0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L11)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same comment as before.
</blockquote></details>

Plus previous name was better


<!-- Sent from Reviewable.io -->

2024-06-12 12:26 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 16 of 24 files reviewed, 17 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 85 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3tXFcBRpVKU0mnpMw:-O-BPA4v7L8n8omtycdO:b-yf5gib) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L85)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I already corrected it in the code that will be delivered in my next PR.
</blockquote></details>

We need to clean this PR before we merge from fetching and promise before we merge. For small thing like renaming it can be done later but major flow should be resolve now


<!-- Sent from Reviewable.io -->

2024-06-13 11:59 UTC, jolevesq reviewed
> Reviewed 5 of 23 files at r2, 4 of 11 files at r3, 9 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 23 of 25 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-06-13 16:11 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 23 of 25 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-BkYIy5Vm-GObiG93I:b-27tmyi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If you never touch providedMapFeatureConfig do you reallly have to do deepClode? Why is this object modified later if it is original copy?
</blockquote></details>

Default values are applied to the JSON provided by the user and then we use the new JSON to instaciate the class. 


<!-- Sent from Reviewable.io -->

2024-06-13 16:19 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 23 of 25 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-O-HN4BNAZvITwfEV4W3:b-1zk31a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like I mention in a comment on Slack, there is no AllServiceMetadata. Each call is individual and it is fetchServiceMetadata. The layers are not aware of other layers. The only time validate as a group is against the schema and at this point there is no fetch
</blockquote></details>

This will be alligned to the latest schema.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3Trz-3IZz0kCE4V_e:-O-HNLI61crPEmrz6qhV:b-1zk31a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L166)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There should be not such thing as AllLayers it is layer by layer and there is one promise by layer return from function call, We need to remove this test and make the function/class more streamline
</blockquote></details>

This will be alligned to the latest schema.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-HNg6b1jaVIsEX2sWh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It needs to be corrected before we merge the PR.
If you look at my schema, I moved the check for geocore outside schema validation so if we add other who needs to be checked it will done layer by layer when we process them.

I do not really need a constructor who return an instance. Because the schema validation is not sync, we can update UI right away and for layer validation/fetch - there is no ui to update, viewer will take care of it. It will be loading until the promise is resolve or reject
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 175 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznhZ873j7nEV8b1aDw:-O-HNk2a496UJ5oqZVJZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L175)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should do this now to have a clean code base before we continue to progress.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 197 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-41HOA6X_9hZ7U9Un7:-O-HNXhhBkjSZUGcPqXk:b-1zk31a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L197)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I do not really care about original.... I want the parsed fetch config JSON object. The original values are in the mapConfig and I should be able to get back to it because I store in state the original config. The only thing I need is a function whho will take my input config, fetch metadata, parse and merge values, return JSON (in a form of a promise)
</blockquote></details>

This will be alligned to the latest schema.


<!-- Sent from Reviewable.io -->

2024-06-13 16:22 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 23 of 25 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 85 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3tXFcBRpVKU0mnpMw:-O-HOyoe19I5ikyY659-:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L85)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need to clean this PR before we merge from fetching and promise before we merge. For small thing like renaming it can be done later but major flow should be resolve now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 16:24 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: 23 of 25 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3qCz69RkZD6qVkNNz:-O-HPLC9Di6VKJIRc5VN:btxdaab) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Plus previous name was better
</blockquote></details>

It was decided to keep the name as is for the moment


<!-- Sent from Reviewable.io -->

2024-06-13 17:32 UTC, Alex-NRCan requested changes
> Reviewed 9 of 11 files at r3, 9 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznWlzN1VppuzuLrpA7:-O-Gofbm-JKPaCtpSnWK:b-he3n8h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/config-api.ts#L19)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This variable exist for **debugging purpose**. There is a comment above it to explain that. It contains the instance of the ***last feature config created*** by the call made using ***ConfigApi.createLayerConfig***. When you are in the Chrome Devtool, you can call the service like this:

***cgpv.api.configApi.createLayerConfig('https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/0', 'esriDynamic');***

and then inspect the instance like this:

***cgpv.api.configApi.lastLayerConfigCreated***
or
***cgpv.api.configApi.lastLayerConfigCreated.metadataLayerTree***
</blockquote></details>

I know what it's for. The 'last' doesn't mean anything as it's implicit by the way the design of the configApi is created at the moment that there can't be others. That said, it can stay as is. It was a comment and this one (like some others) have already been a resolved a while ago.
___
*[`packages/geoview-core/src/api/config/types/type-guards.ts` line 143 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-6TDi76ORLthQxn5KC:-O-HEgqc2gabtLUyWznH:bqog80t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/type-guards.ts#L143)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Totaly agree!
</blockquote></details>

Agreed
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-H-9wfDtx6vMnd6BA-:b-vzj5bp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If you never touch providedMapFeatureConfig do you reallly have to do deepClode? Why is this object modified later if it is original copy?
</blockquote></details>

That likely means that the leak still exists and you're just patching the leak by double cloning. Maybe not the case here, but cloning too many times can lead to confusion in which object is 'the real one' down the road. Similar to what happens in current configuration with the 'parentConfig' not being trustable. I'll leave it to Johann to decide.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3sB2g5VROZy8fVnBM:-O-GrlvJ7ywDv8UNDcFZ:b-i4y15r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts#L23)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Personally, I find that a lot of energy is put into correcting variable names, to the detriment of the code's ability to function within a tight schedule.
</blockquote></details>

We'll have to change the current configurations and all the current code using it asap, before things keep deviating further. I'll create a TODO over there then for now so we don't forget..
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 149 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-HRMvU8irjulAfYSYw:-O-HRMvV-Na8J8gSWmrf:b-ljpajo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52a88b91a45a37781a2cb42d08123d3f8db6f2a8/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L149)):*
> ```XML
>     listOfLayerEntryConfig.forEach((subLayerConfig) => {
>       if (layerEntryIsGroupLayer(subLayerConfig)) {
>         listOfGroupFlag.push(true);
> ```

Question.
What is this list of flags for? Doesn't seem to have a purpose? Maybe dead code?
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznquRs9L8XusFfRis3:-O-GtAAkCZKl38LLXwrr:b-kc8p9v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts#L109)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The initial idea was to let maintainers understand that this geoviewLayerConfig contains the instance of the sublayer, hence the use of the word container. It might have been preferable to use the word parent. At this point, I'll leave the name as it is. If you want to change it, we'll put a TODO.
</blockquote></details>

That's not my point. I'm talking about the 'Instance' suffix which is just as redundant as the 'last' prefix you have elsewhere.
Typically, 'Instance' word is used to distinguish between a class name and instance name, or distinguish between a static method and instance method (of same names) or in singleton patterns, but here it's none of those. It can stay as is. It was a comment that was already resolved...


<!-- Sent from Reviewable.io -->

2024-06-13 17:32 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nzn_R9n9pbVqYeQXXcT:-O-He2stCTQZWL9bVa90:b676gw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L159)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This will be alligned to the latest schema.
</blockquote></details>

I created an issue for the fetch https://github.com/Canadian-Geospatial-Platform/geoview/issues/2253
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3Trz-3IZz0kCE4V_e:-O-He6TU3wT8fRiUvwvr:b676gw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L166)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This will be alligned to the latest schema.
</blockquote></details>

I created an issue for the fetch https://github.com/Canadian-Geospatial-Platform/geoview/issues/2253


<!-- Sent from Reviewable.io -->

2024-06-13 17:33 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 123 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-NznbwC18vlhcD3B5Khy:-O-He9Uq8Htxwe0k5Egy:b-60w09k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L123)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

That likely means that the leak still exists and you're just patching the leak by double cloning. Maybe not the case here, but cloning too many times can lead to confusion in which object is 'the real one' down the road. Similar to what happens in current configuration with the 'parentConfig' not being trustable. I'll leave it to Johann to decide.
</blockquote></details>

I have an idea to separate this a bit more.... will do a drawing and hope to be ready to present tomorrow


<!-- Sent from Reviewable.io -->

2024-06-13 17:33 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 197 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-41HOA6X_9hZ7U9Un7:-O-HeK7BAQAF37BpvpjT:b676gw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L197)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This will be alligned to the latest schema.
</blockquote></details>

I created an issue for the fetch https://github.com/Canadian-Geospatial-Platform/geoview/issues/2253


<!-- Sent from Reviewable.io -->

2024-06-13 17:33 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 38 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-Nznmkso0rCEqVVnxY7b:-O-HeNEe81PKyI6rB5DX:b676gw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba67bd749670f1cc9433c78bf425a4a24fd9aa0b/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L38)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I created an issue for the fetch https://github.com/Canadian-Geospatial-Platform/geoview/issues/2253


<!-- Sent from Reviewable.io -->

2024-06-13 17:35 UTC, Alex-NRCan reviewed
> Reviewed 1 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-06-13 17:35 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227#-O-3sB2g5VROZy8fVnBM:-O-Hea0kEC7CABN_UE0P:b-lsnupu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edb52b8a58aa4b9937524450d28fb6ce38913a05/packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts#L23)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We'll have to change the current configurations and all the current code using it asap, before things keep deviating further. I'll create a TODO over there then for now so we don't forget..
</blockquote></details>

Yes, add a TODO for this in the core.... next step is to tackle difference between old and new schema


<!-- Sent from Reviewable.io -->

2024-06-13 17:36 UTC, jolevesq approved these changes
> Reviewed 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-06-13 17:36 UTC, merged