feat(WMS): add feature info to layers
Canadian-Geospatial-Platform/geoview pull request #2249
Opened 2024-06-12 21:28 UTC by DamonU2

# Description

Adds outfields, aliases, and data types to layers that don't have them supplied by metadata, using query returns
Fixes #1470 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
https://damonu2.github.io/geoview/add-layers.html
Add: ea4c0bdb-a63f-49a4-b14a-09c1560aad0b
Run: cgpv.api.maps.mapWM.layer.redefineFeatureFields('rcs.ea4c0bdb-a63f-49a4-b14a-09c1560aad0b.en/pub:WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT', '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29', 'aliasFields')
Numbers should replace names in details

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-06-12 21:42 UTC, jolevesq requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-DOebJ4cj-QKvtnVwF:-O-DOebK2Mz7_NVweDFi:bjxbaiv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e08ef0ef0809185d10f253b11ddf93ab49939048/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L151)):*
> ```XML
>         promiseResult
>           .then((arrayOfRecords) => {
>             // Set up feature info for layers that did not include it in the metadata
> ```

Is this done in each click? If so, can we do it right on the layerset layer object?


<!-- Sent from Reviewable.io -->

2024-06-12 22:07 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-DOebJ4cj-QKvtnVwF:-O-DUGe_0V6Z-3dNCoK7:b-ywsfua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e08ef0ef0809185d10f253b11ddf93ab49939048/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L151)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this done in each click? If so, can we do it right on the layerset layer object?
</blockquote></details>

It'll only happen the first time, and we need the info from the query to set it.


<!-- Sent from Reviewable.io -->

2024-06-13 19:05 UTC, jolevesq requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 117 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-Hz6WN6b07BdZzYlkk:-O-Hz6WN6b07BdZzYlkl:bxw1yah) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cae780ceafced6d83ca61646c5c73e6a2263c3ed/packages/geoview-core/public/templates/demos/demo-function-event.html#L117)):*
> ```HTML
>         </li>
>         <li><button id="Redefine-alias-fields">Redefine alias fields for Major Projects</button><br />
>           <p>Note: this will not work until a feature from this layer has been clicked on to populate the outfields/alias fields</p>
> ```

Yeah, it should be trap before the first click or on first click if set.... looks weird to have it baddly done then call then have it ok 
___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-DOebJ4cj-QKvtnVwF:-O-HzLyQ2hZX4A_DJqUI:b-4mqcvz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e08ef0ef0809185d10f253b11ddf93ab49939048/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L151)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

It'll only happen the first time, and we need the info from the query to set it.
</blockquote></details>

We need another place for this that is done even if no click has been done.... to the layer itself maybe


<!-- Sent from Reviewable.io -->

2024-06-13 22:00 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 117 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-Hz6WN6b07BdZzYlkk:-O-IbR1M7xTJqpQ6mDIa:b-m13999) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cae780ceafced6d83ca61646c5c73e6a2263c3ed/packages/geoview-core/public/templates/demos/demo-function-event.html#L117)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yeah, it should be trap before the first click or on first click if set.... looks weird to have it baddly done then call then have it ok
</blockquote></details>

Updates, it will now keep them if set before click


<!-- Sent from Reviewable.io -->

2024-06-14 15:56 UTC, Alex-NRCan reviewed
> Reviewed 1 of 4 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-DOebJ4cj-QKvtnVwF:-O-MRfEd7Myo_zAbgiR-:bzcvhy5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e08ef0ef0809185d10f253b11ddf93ab49939048/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L151)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need another place for this that is done even if no click has been done.... to the layer itself maybe
</blockquote></details>

I understand that this has to be here, because you need the information from the query to do the work (and we might not want to 'query for nothing' just to fill this up beforehand).

I think my only minor comment would be to move the code here in an explicit function which could be named like `patchMissingMetadataIfNecessary()` or something in that vein?

Just to clarify the code being executed as part of a promise callback so it reads more smoothly like



_Code snippet:_
```XML
promiseResult
          .then((arrayOfRecords) => {
              // Use the response to possibly patch the layer config metadata
              this.patchMissingMetadataIfNecessary(layerEntryConfig, arrayOfRecords);

              // Keep the features retrieved
              // rest of the current code
          });
```


<!-- Sent from Reviewable.io -->

2024-06-14 16:23 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2249#-O-DOebJ4cj-QKvtnVwF:-O-MXHSS0EONzi_EF0rT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e08ef0ef0809185d10f253b11ddf93ab49939048/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L151)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I understand that this has to be here, because you need the information from the query to do the work (and we might not want to 'query for nothing' just to fill this up beforehand).

I think my only minor comment would be to move the code here in an explicit function which could be named like `patchMissingMetadataIfNecessary()` or something in that vein?

Just to clarify the code being executed as part of a promise callback so it reads more smoothly like
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-17 14:22 UTC, merged