refactor(layers-bounds) - Quick PR to see if calculate bounds can be simplified now
Canadian-Geospatial-Platform/geoview pull request #2260
Opened 2024-06-13 22:07 UTC by Alex-NRCan

# Description

This PR is dependent on PR #2245 
This PR replaces 5 `calculateBounds()` calls with a get bounds from the store instead.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Waiting to host..

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-06-14 14:01 UTC, jolevesq reviewed
> Reviewed 3 of 78 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: 3 of 78 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1273 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M2LMEDRy2bN4n1jfC:-O-M2LMEDRy2bN4n1jfD:b-vqvqr0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1273)):*
> ```XML
>   getExtentOfMultipleLayers(layerIds: string[] = Object.keys(this.#layerEntryConfigs)): Extent {
>     // TODO: Check - Is this function still useful now that the bounds in the store are theoretically fixed?
>     // TO.DOCONT: Maybe this is the same as bounds on the geoview layer root level?
> ```

I think so, this is use to get union of multiple extents. 
@DamonU2  can you confirm


<!-- Sent from Reviewable.io -->

2024-06-14 14:02 UTC, jolevesq approved these changes
> Reviewed 1 of 78 files at r1, 74 of 74 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-14 14:04 UTC, DamonU2 requested changes
> Reviewed 4 of 78 files at r1, 74 of 74 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1273 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M2LMEDRy2bN4n1jfC:-O-M2oc67xlbp0Gv5Njk:bbljiec) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1273)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think so, this is use to get union of multiple extents. 
@DamonU2  can you confirm
</blockquote></details>

Yep, this is still needed for that.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1278 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M1WKp6BBPtW-7kavM:-O-M1WKq47F-SZzKxUrE:bc2ifq3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1278)):*
> ```XML
>     layerIds.forEach((layerId) => {
>       // Get sublayerpaths and layerpaths from layer IDs.
>       const subLayerPaths = Object.keys(this.#layerEntryConfigs).filter((layerPath) => layerPath.includes(layerId));
> ```

Side note: Change this .includes(layerId) to .startsWith(layerId) in the unlikely chance that there is a layer that isn't a sublayer but has this ID in it's path?


<!-- Sent from Reviewable.io -->

2024-06-14 15:26 UTC, Alex-NRCan reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1273 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M2LMEDRy2bN4n1jfC:-O-MLPTe7M20yUwdfe5m:b-9sznk5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1273)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Yep, this is still needed for that.
</blockquote></details>

I'll leave it like that then and remove the TODO on the next push.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1278 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M1WKp6BBPtW-7kavM:-O-MLTX9-W3bqlQJsAGF:b-hsviy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1278)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Side note: Change this .includes(layerId) to .startsWith(layerId) in the unlikely chance that there is a layer that isn't a sublayer but has this ID in it's path?
</blockquote></details>

I can change it for sure, it was written like this though, I didn't change it.
Do we need to get this change confirmed or I just do it?


<!-- Sent from Reviewable.io -->

2024-06-14 15:29 UTC, DamonU2 requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1278 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260#-O-M1WKp6BBPtW-7kavM:-O-MMKnx5FMM0CFax3CX:bcj3m8t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3d21fb6839111cb774bdcaef7f24155614c29974/packages/geoview-core/src/geo/layer/layer.ts#L1278)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I can change it for sure, it was written like this though, I didn't change it.
Do we need to get this change confirmed or I just do it?
</blockquote></details>

Yeah, I think I wrote it like that, it just jumped out at me, you can just change it


<!-- Sent from Reviewable.io -->

2024-06-14 15:49 UTC, jolevesq reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-17 12:02 UTC, jolevesq approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-17 12:02 UTC, merged