2288-Input and internal config validation
Canadian-Geospatial-Platform/geoview pull request #2289
Opened 2024-06-21 15:21 UTC by ychoquet

# Description

Making input and internal config validation uniform.

Fixes #2288

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using chrome Devtool to trace and debug the code.

__Deploy URL:__ https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-06-25 19:53 UTC, jolevesq requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 330 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289#-O0Fw1XW31iK_70jFrng:-O0Fw1XW31iK_70jFrnh:bolfrd0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5e9ce3eec90c6d5392f249757ec42c81fe5c775/packages/geoview-core/src/api/config/types/config-validation-schema.json#L330)):*
> ```JSON
>           "type": "string"
>         },
>         "useInternalSchema": {
> ```

Should it be a flag in the schema? Should we encapsulate the internal validation inside the object? The function should always deal with validate input (user schema). The output of this call can be use to validate against internal. There should be no way to ask for internal validation from a user schema.

Lets discuss about this


<!-- Sent from Reviewable.io -->

2024-06-26 12:58 UTC, Alex-NRCan approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @ychoquet)



<!-- Sent from Reviewable.io -->

2024-06-26 14:59 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 330 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289#-O0Fw1XW31iK_70jFrng:-O0JyrGa47v2ZDxRyoPs:b98ssn3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5e9ce3eec90c6d5392f249757ec42c81fe5c775/packages/geoview-core/src/api/config/types/config-validation-schema.json#L330)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be a flag in the schema? Should we encapsulate the internal validation inside the object? The function should always deal with validate input (user schema). The output of this call can be use to validate against internal. There should be no way to ask for internal validation from a user schema.

Lets discuss about this
</blockquote></details>

Schema validation has the ability to execute conditionnal instructions ("if") using properties. We can test for existance of a property or test the value of a property to decide what kind of validation we want to apply. To my knowledge, there is no way to do that using an external flag. There must be a property in the schema to rely on.


<!-- Sent from Reviewable.io -->

2024-06-26 15:57 UTC, jolevesq reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-26 17:33 UTC, jolevesq approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-06-26 17:44 UTC, merged