2321-draft version aoi
Canadian-Geospatial-Platform/geoview pull request #2325
Opened 2024-06-27 15:47 UTC by guichoquette

# Description

Created the Area of interest package. The first version display the AOI icon in the app bar but the panel used is Data-Table Panel.

Fixes # (2321)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

With a local host I was loading the AOI page and making sure the icon was in the side panel and the page title was Area of interest. I still have a little problem, when I over above the AOI icon it says "aoiPanel.title". 

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-06-27 16:02 UTC, jolevesq reviewed
> Reviewed 10 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 10 of 17 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`.vscode/settings.json` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PPrQu9mSd5ZtZUowu:-O0PPrQu9mSd5ZtZUowv:bv4vjv8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/.vscode/settings.json#L79)):*
> ```JSON
>     }
>   ],
>   "editor.guides.indentation": false
> ```

Why this setting?
___
*[`packages/geoview-core/public/templates/area-of-interest.html` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQKSq0W8mQ6b0zT4K:-O0PQKSq0W8mQ6b0zT4L:bvfwew) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/public/templates/area-of-interest.html#L4)):*
> ```HTML
> <html lang="en">
> 
> <head>
> ```

Do not use a template, just add to configuration navigator
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQ_-6CJrzc2tlE3pT:-O0PQ_-6CJrzc2tlE3pU:b-1qjyl2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L120)):*
> ```XML
>       legend: { icon: <HubOutlinedIcon />, content: <Legend fullWidth containerType={CONTAINER_TYPE.APP_BAR} /> },
>       layers: { icon: <LayersOutlinedIcon />, content: <LayersPanel containerType={CONTAINER_TYPE.APP_BAR} /> },
>       'aoi-panel': { icon: <AoiIcon />, content: <Datapanel containerType={CONTAINER_TYPE.APP_BAR} /> },
> ```

basemap panel is not here... should be injected automatically by plugin loading


<!-- Sent from Reviewable.io -->

2024-06-27 16:05 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 10 of 17 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQmTv7GTFZCJtdFd2:-O0PQmTv7GTFZCJtdFd3:b-r4gw5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
> ```JSON
> {
>   "isOpen": false,
>   "canSwichProjection": false,
> ```

We should clean this schema, just keep isOpen
___
*[`packages/geoview-aoi-panel/schema.json` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQs8oDhsn28qXvZTY:-O0PQs8oDhsn28qXvZTZ:bn314j5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/schema.json#L8)):*
> ```JSON
>   "comments": "Configuration for GeoView basemap panel package.",
>   "additionalProperties": false,
>   "definitions": {
> ```

Clean this file, just keep isOpen
___
*[`packages/geoview-aoi-panel/src/area-of-interest-style.ts` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PR1J5A-44bdS8lBlU:-O0PR1J5A-44bdS8lBlV:b-fy1wyj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/src/area-of-interest-style.ts#L6)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export const getSxClasses = (theme): any => ({
>   basemapCard: {
> ```

You can rename basemap to aoi for class name. Style should be pretty similar


<!-- Sent from Reviewable.io -->

2024-06-28 14:29 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 10 of 17 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`.vscode/settings.json` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PPrQu9mSd5ZtZUowu:-O0Q8Zsu4aeka43n7raG:b-g114g3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/.vscode/settings.json#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this setting?
</blockquote></details>

Done. Those were personal settings that I accidentally imported
___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQmTv7GTFZCJtdFd2:-O0PwYwwAHvTMUl4zK3R:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should clean this schema, just keep isOpen
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/schema.json` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQs8oDhsn28qXvZTY:-O0Q16sF8rAWLV4KgTtJ:bs7wumx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/schema.json#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Clean this file, just keep isOpen
</blockquote></details>

Done. 
___
*[`packages/geoview-aoi-panel/src/area-of-interest-style.ts` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PR1J5A-44bdS8lBlU:-O0Q5lImDvNFT3Ti8Vby:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-aoi-panel/src/area-of-interest-style.ts#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can rename basemap to aoi for class name. Style should be pretty similar
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/area-of-interest.html` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQKSq0W8mQ6b0zT4K:-O0U0miE-meq4GErQlZJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/public/templates/area-of-interest.html#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use a template, just add to configuration navigator
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 02:47 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 7 of 21 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQ_-6CJrzc2tlE3pT:-O0lKfC4ARsbmtkgWhxI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L120)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

basemap panel is not here... should be injected automatically by plugin loading
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 13:20 UTC, jolevesq reviewed
> Reviewed 1 of 17 files at r1, 12 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 39 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0n_qklCQpajVmpvTRK:-O0n_qklCQpajVmpvTRL:b-8qku4q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-aoi-panel/src/index.tsx#L39)):*
> ```XML
>       AoiPanel: {
>         title: 'Area of Interest',
>         info: {
> ```

For translation, you can keep just the title
___
*[`packages/geoview-core/public/templates/loading-packages.html` line 123 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0na1RdE3lua-8Su1C0:-O0na1RdE3lua-8Su1C1:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/loading-packages.html#L123)):*
> ```HTML
>           cgpv.api.plugin.removePlugin('basemap-panel', 'mapWM');
>         });
>         
> ```

Remove white spaces
___
*[`packages/geoview-core/public/templates/loading-packages.html` line 141 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0na8859AAbnMfU_PKS:-O0na8859AAbnMfU_PKT:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/loading-packages.html#L141)):*
> ```HTML
>           cgpv.api.plugin.removePlugin('aoi-panel', 'mapWM');
>         });
>         
> ```

Remove white spaces
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQ_-6CJrzc2tlE3pT:-O0naHTG-Bav24OnVmOT:b-m46p22) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L120)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove aoi-panel from app-bar component. Plugins are note reference inside default app-bar core component


<!-- Sent from Reviewable.io -->

2024-07-02 13:40 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0nf7QX7c2zi_AHAW1V:-O0nf7QX7c2zi_AHAW1W:b-r1evsk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/demos-navigator.html#L125)):*
> ```HTML
>             Basemap LCC Simple-Labeled (overview map hide on zoom 7 and lower)
>           </option>
>           <option value="./configs/navigator/26-area-of-iterest">Area of Interest</option>
> ```

Put it just before package base map panel and name it Package Area of Interest


<!-- Sent from Reviewable.io -->

2024-07-02 13:59 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0nf7QX7c2zi_AHAW1V:-O0njW3SELm8EkFoa4Re:b6sf8rm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/demos-navigator.html#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put it just before package base map panel and name it Package Area of Interest
</blockquote></details>

Plus missing the .json extension and typo int he name iterest instead of interest


<!-- Sent from Reviewable.io -->

2024-07-02 14:08 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 21 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 276 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0nlaDa6xSG-r1D04ZW:-O0nlaDa6xSG-r1D04ZX:b-i0rmhv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L276)):*
> ```XML
>           .then((constructor: AbstractPlugin | ((pluginId: string, props: TypeJsonObject) => TypeJsonValue)) => {
>             Plugin.addPlugin(
>               'basemap-panel',
> ```

This should not be hard coded I think


<!-- Sent from Reviewable.io -->

2024-07-02 14:21 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 21 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 221 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0noZMiDa3Epn70Suyi:-O0noZMiDa3Epn70Suyj:b7q7173) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/src/api/config/types/config-constants.ts#L221)):*
> ```XML
>  * Definition of the default order of the tabs inside appbar
>  */
> export const CV_DEFAULT_APPBAR_TABS_ORDER = ['geolocator', 'legend', 'layers', 'details', 'data-table', 'guide', 'aoi-panel'];
> ```

Need to remove here as aoi is not a default app bar component


<!-- Sent from Reviewable.io -->

2024-07-02 18:45 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 15 of 22 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 39 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0n_qklCQpajVmpvTRK:-O0nd_LJDmw-65CTd09J:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-aoi-panel/src/index.tsx#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For translation, you can keep just the title
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0nf7QX7c2zi_AHAW1V:-O0oR3MF5C8uM6akv6uR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/demos-navigator.html#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Plus missing the .json extension and typo int he name iterest instead of interest
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/loading-packages.html` line 123 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0na1RdE3lua-8Su1C0:-O0ng-beEs5I4Ksqq_Bs:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/loading-packages.html#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/loading-packages.html` line 141 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0na8859AAbnMfU_PKS:-O0ngPMH16Q4pbRSU5AN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/public/templates/loading-packages.html#L141)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0PQ_-6CJrzc2tlE3pT:-O0njKxz5ycqpbu3DBbJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5510b3b71e86f21b8a046d362060c0a208eb9dd/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L120)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove aoi-panel from app-bar component. Plugins are note reference inside default app-bar core component
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 276 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0nlaDa6xSG-r1D04ZW:-O0oYpEc52THQLW5By7n:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L276)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This should not be hard coded I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 221 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0noZMiDa3Epn70Suyi:-O0oYUYAAQwzZWFe5Z94:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-core/src/api/config/types/config-constants.ts#L221)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Need to remove here as aoi is not a default app bar component
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 19:52 UTC, jolevesq reviewed
> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 16 of 22 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 39 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0n_qklCQpajVmpvTRK:-O0p-AeM1d2QMhz5l4g0:bpa0uz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-aoi-panel/src/index.tsx#L39)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant 
en: { title: 'Area of Interest}, fr: { title: "Région d'intérêt' }


<!-- Sent from Reviewable.io -->

2024-07-02 19:54 UTC, jolevesq reviewed
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 17 of 22 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 131 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p-W5m5O7csI-qXYi8:-O0p-W5m5O7csI-qXYi9:b-knthd1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/public/templates/demos-navigator.html#L131)):*
> ```HTML
>           <option value="./configs/navigator/07-basic-appbar.json">Basic map with app bar</option>
>           <option value="./configs/navigator/08-package-basemap.json">Package basemap panel</option>
>           <option value="./configs/navigator/26-package-area-of-interest.json">Area of Interest</option>
> ```

Should be "Package Area of interest", put it before the base map one... not in the middle of 2 basemap package demo


<!-- Sent from Reviewable.io -->

2024-07-02 19:56 UTC, jolevesq reviewed
> Reviewed 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0p03X3D0wO0J0LTW1u:b-csqmqm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
> ```XML
>             ).catch((error) => {
>               // Log
>               logger.logPromiseFailed(`api.plugin.addPlugin in useEffect in ${pluginName}`, error);
> ```

in app-bar for ${pluginName}


<!-- Sent from Reviewable.io -->

2024-07-02 20:22 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 12 of 22 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 39 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0n_qklCQpajVmpvTRK:-O0p5WV7BzNePTejL2OS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/77e24946ea0c01df9fd6ccc652af458fe4984c65/packages/geoview-aoi-panel/src/index.tsx#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I meant 
en: { title: 'Area of Interest}, fr: { title: "Région d'intérêt' }
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 131 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p-W5m5O7csI-qXYi8:-O0p1oOp3fsT5FA46Mgy:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/public/templates/demos-navigator.html#L131)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be "Package Area of interest", put it before the base map one... not in the middle of 2 basemap package demo
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0p5RXe45ePxg4XRzyE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

in app-bar for ${pluginName}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 13:29 UTC, jolevesq requested changes
> Reviewed 2 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 14 of 22 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0smHWCBBLf2vixL7Jr:busma1k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
> ```XML
>           label: {
>             name: 'with labels',
>           },
> ```

You can remove all this for en and fr



_Code quote:_
```XML
        info: {
          transport: {
            name: 'Transport',
            description: `The Canada Base Map - Transportation (CBMT). This web mapping service provides spatial reference context with an emphasis on transportation networks.
                          It is designed especially for use as a background map in a web mapping application or geographic information system (GIS).`,
          },
          simple: {
            name: 'Simple',
          },
          shaded: {
            name: 'Shaded relief',
            description: `The Canada Base Map - Elevation (CBME) web mapping services of the Earth Sciences Sector at Natural Resources Canada,
                          is intended primarily for online mapping application users and developers`,
          },
          osm: {
            name: 'Open Street Maps',
          },
          nogeom: {
            name: 'No geometry',
          },
          label: {
            name: 'with labels',
          },
```


<!-- Sent from Reviewable.io -->

2024-07-03 13:32 UTC, jolevesq requested changes
> Reviewed 5 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 19 of 22 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0smruaAb4Yz2dyp4sY:bmd2x9l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

api.plugin.addPlugin in useEffect in app-bar for ${pluginName}

If we remove the app-bar in message we will not know were the error came from


<!-- Sent from Reviewable.io -->

2024-07-03 13:32 UTC, jolevesq reviewed
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @guichoquette, and @ychoquet)



<!-- Sent from Reviewable.io -->

2024-07-03 13:57 UTC, Alex-NRCan reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2, @guichoquette, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0squfK3PJMvTDDLYsP:-O0ssY5HCo2Asq0mx-3s:bdl4kuc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-core/src/api/config/types/map-schema-types.ts#L59)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

BTW.
Maybe it'd be cool to reuse that type (or some kind of similar logic) in the Plugin.loadPlugin, Plugin.loadScript function signatures?
</blockquote></details>

On second thought, maybe we don't, because we want the loadScript/loadPlugin to be easily extensible by 3rd party developers, so working with a `string` might be easier to extend. To be determined.


<!-- Sent from Reviewable.io -->

2024-07-03 14:02 UTC, ychoquet approved these changes
> Reviewed 5 of 17 files at r1, 6 of 13 files at r2, 1 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2, @guichoquette, and @jolevesq)



<!-- Sent from Reviewable.io -->

2024-07-03 14:13 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0spqGvCYElJzoF1mug:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can remove all this for en and fr
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0susz72o8teXfqUwPk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

api.plugin.addPlugin in useEffect in app-bar for ${pluginName}

If we remove the app-bar in message we will not know were the error came from
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 14:18 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @guichoquette)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 126 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0so5iPEtYNnDvZIK_U:-O0swdU7CgkXSiNdTJbB:b-u4iur3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L126)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We should call a function on the Basemap object (e.g.: `this.mapViewer().basemap.clearBasemaps()` which clears the `basemaps` list. That way, if there are other components working on the `basemaps` array, we can make them aware of this clearing happening. (Or we use an event-processor/state thing, can let Johann decide what's best here).
</blockquote></details>

In the viewer there is the default basemap array... May be a good thing to have a centralized way of dealing with this this. I will create an issue.

@guichoquette This line can be remove as it is not part of aoi plugin


<!-- Sent from Reviewable.io -->

2024-07-03 14:18 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @guichoquette)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0sxZKHDbcWvpJwNLRn:b621227) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, object is still there


<!-- Sent from Reviewable.io -->

2024-07-03 14:19 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @guichoquette)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0squfK3PJMvTDDLYsP:-O0sxgtCBrgEbpj-WSP8:born30e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-core/src/api/config/types/map-schema-types.ts#L59)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

On second thought, maybe we don't, because we want the loadScript/loadPlugin to be easily extensible by 3rd party developers, so working with a `string` might be easier to extend. To be determined.
</blockquote></details>

I think we are right, if we do type, it will be more complicated for 3rd party


<!-- Sent from Reviewable.io -->

2024-07-03 14:21 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @guichoquette)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0sxxg484aqmMv9PbrM:b-3qyri5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, line should be : logger.logPromiseFailed(`api.plugin.addPlugin in useEffect in app-bar for ${pluginName}`, error);
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 271 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0sonAx1nNCutc4I2Lj:-O0sxrwQ1whoVo9lQfBl:bv6e9sr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L271)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Minor.
Should `pluginName` be typed 'TypeValidAppBarCoreProps` in the signature here and the 'as TypeValidAppBarCoreProps' be put at a higher level, when `processPlugin()` is called? It'd be a bit more straightforward?
</blockquote></details>

Good comment, @guichoquette you can apply


<!-- Sent from Reviewable.io -->

2024-07-03 14:36 UTC, DamonU2 requested changes
> Reviewed 5 of 17 files at r1, 6 of 13 files at r2, 1 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan, @guichoquette, and @jolevesq)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0sy_uh9FCj_qIOWUf5:-O0sy_uh9FCj_qIOWUf6:b-qyp3tf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
> ```JSON
> {
>   "isOpen": false
> }
> ```

Add blank end line - if you set up prettier to auto format on save, I think it will automatically add this
___
*[`packages/geoview-aoi-panel/package.json` line 40 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0syh9Q-HjLD6kfK9IH:-O0syh9Q-HjLD6kfK9II:b6jjx64) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/package.json#L40)):*
> ```JSON
>     "@types/react": "^18.2.0"
>   }
> }
> ```

Same here, add new line
___
*[`packages/geoview-aoi-panel/README.md` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0szI4Y3M1TzMFaiXA9:-O0szI4Y3M1TzMFaiXAA:bej4tub) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/README.md#L3)):*
> ```Markdown
> # geoview-Area-of-interest
> 
> A package that allows to display a collection of areas to visit on the map.
> ```

"A package to display..." or "A package that allows a user to display..."
___
*[`packages/geoview-aoi-panel/schema.json` line 25 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0szZoh6iwLDVLbnHTO:-O0szZoh6iwLDVLbnHTP:b-mpx163) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/schema.json#L25)):*
> ```JSON
>     "isOpen"
>   ]
> }
> ```

New line at end


<!-- Sent from Reviewable.io -->

2024-07-03 14:53 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0szbRu8ZiQJGTudojW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not done, object is still there
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 126 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0so5iPEtYNnDvZIK_U:-O0t0A3z00V36_76u4uf:b-jkcd88) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L126)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

In the viewer there is the default basemap array... May be a good thing to have a centralized way of dealing with this this. I will create an issue.

@guichoquette This line can be remove as it is not part of aoi plugin
</blockquote></details>

Do I only remove the line or the entire method? If it's only the line the comment is Done.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0squfK3PJMvTDDLYsP:-O0t1MWYB9IObNQFiD_z:b6e7etz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-core/src/api/config/types/map-schema-types.ts#L59)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we are right, if we do type, it will be more complicated for 3rd party
</blockquote></details>

I'm not sure if I have something to do here? Can I get more specifications if it's the case?
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 282 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0p03X3D0wO0J0LTW1t:-O0szUUA0egsBpAKaVRV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ccf004f123c3b12503b8dca615423200af3ff1ee/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L282)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not done, line should be : logger.logPromiseFailed(`api.plugin.addPlugin in useEffect in app-bar for ${pluginName}`, error);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 15:09 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @guichoquette)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0squfK3PJMvTDDLYsP:-O0t89Vs3Zckd9LFaElN:b57yinq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-core/src/api/config/types/map-schema-types.ts#L59)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

I'm not sure if I have something to do here? Can I get more specifications if it's the case?
</blockquote></details>

Nothing to do.


<!-- Sent from Reviewable.io -->

2024-07-03 15:10 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @guichoquette)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0t8NIb52zMIttAhJIw:b-lbsq3v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We will discuss as it is still there, cleanup of old basemap translation is not removed


<!-- Sent from Reviewable.io -->

2024-07-03 15:13 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0sy_uh9FCj_qIOWUf5:-O0t5-m8BVLUp39RvfDW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Add blank end line - if you set up prettier to auto format on save, I think it will automatically add this
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/package.json` line 40 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0syh9Q-HjLD6kfK9IH:-O0t60BF9xxaoNbKaBRL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/package.json#L40)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Same here, add new line
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/README.md` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0szI4Y3M1TzMFaiXA9:-O0t86Zh66hmTltU6YCL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/README.md#L3)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

"A package to display..." or "A package that allows a user to display..."
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/schema.json` line 25 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0szZoh6iwLDVLbnHTO:-O0t79asChTimfYtQ59f:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/schema.json#L25)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

New line at end
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 15:26 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 15 of 22 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-aoi-panel/src/index.tsx` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0smHWCBBLf2vixL7Jq:-O0tBD0r-iuynKHSiLzz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We will discuss as it is still there, cleanup of old basemap translation is not removed
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 126 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0so5iPEtYNnDvZIK_U:-O0tA8dF6ZL2zheCATrt:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/src/index.tsx#L126)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes, you can remove the line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 15:57 UTC, DamonU2 requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 15 of 22 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @guichoquette, @jolevesq, and @ychoquet)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0sy_uh9FCj_qIOWUf5:-O0tIvWe9FY93HwVFqnm:b173k6i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
<details><summary><i>Previously, guichoquette wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not there. The file should be 4 lines, with the last one blank, same with the other files with this issue


<!-- Sent from Reviewable.io -->

2024-07-03 16:28 UTC, guichoquette reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: 15 of 23 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 3 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325#-O0sy_uh9FCj_qIOWUf5:-O0tQB_30HfhwbOTpOrP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4a10e4f71b502f2efc23250782d774d7b4a1b5f0/packages/geoview-aoi-panel/default-config-area-of-interest.json#L3)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Still not there. The file should be 4 lines, with the last one blank, same with the other files with this issue
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 16:30 UTC, DamonU2 approved these changes
> Reviewed 3 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)



<!-- Sent from Reviewable.io -->

2024-07-03 17:07 UTC, jolevesq reviewed
> Reviewed 7 of 7 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-07-03 17:07 UTC, jolevesq approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-07-03 17:14 UTC, merged