fix(extent): Extent validation
Canadian-Geospatial-Platform/geoview pull request #2346
Opened 2024-07-04 20:28 UTC by DamonU2

Closes #2324

# Description

Added a utility extent validation function. Also updated all layers so that extent and bounds in initial settings config remains in lat/long.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-07-05 13:29 UTC, jolevesq reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 452 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O124Ge6A7oxOFUINpGI:-O124Ge6A7oxOFUINpGJ:bfzrchh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/utils/utilities.ts#L452)):*
> ```XML
> 
> /**
>  * Checks validity of lat long extent and updates values if invalid.
> ```

It is not only lat/long, LCC and WebMercator


<!-- Sent from Reviewable.io -->

2024-07-05 13:41 UTC, jolevesq reviewed
> Reviewed 10 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 928 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O125rQY7_un4LZ1bU73:-O125rQY7_un4LZ1bU74:b-6hsbo4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L928)):*
> ```XML
>       const metadataProjection = this.getMetadataProjection();
>       layerBounds = this.getMapViewer().convertExtentFromProjToMapProj(metadataExtent, metadataProjection);
>       layerBounds = validateExtent(layerBounds, this.getMapViewer().getProjection().getCode());
> ```

Not sure but should it be the other way around because if extent is invalid the convertExtent will fail before the validation. Should we do validate then convert?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 461 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O12682C6puw2du1Z9UX:-O12682C6puw2du1Z9UY:b-7bm4ae) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L461)):*
> ```XML
>       const metadataProjection = this.getMetadataProjection();
>       layerBounds = this.getMapViewer().convertExtentFromProjToMapProj(metadataExtent, metadataProjection);
>       layerBounds = validateExtent(layerBounds, this.getMapViewer().getProjection().getCode());
> ```

Not sure but should it be the other way around because if extent is invalid the convertExtent will fail before the validation. Should we do validate then convert?

Technically, the geoview-layers class will all be moved to configApi after refactor. We should keep this in mind when we use getMapViewer because viewer is not part of the configApi
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 206 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O126PPnAJrX0w5QnoIZ:-O126PPnAJrX0w5QnoI_:bhebys3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L206)):*
> ```XML
>             Projection.PROJECTION_NAMES.LNGLAT
>           );
>           layerConfig.initialSettings.bounds = validateExtent(latlonExtent);
> ```

Not sure but should it be the other way around because if extent is invalid the transformExtent will fail before the validation. Should we do validate then convert?
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 670 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O126zLc9izIRPJvE_a0:-O126zLd2fvClUA1UF0p:b-6hsbo4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L670)):*
> ```XML
>       const metadataProjection = this.getMetadataProjection();
>       layerBounds = this.getMapViewer().convertExtentFromProjToMapProj(metadataExtent, metadataProjection);
>       layerBounds = validateExtent(layerBounds, this.getMapViewer().getProjection().getCode());
> ```

Not sure but should it be the other way around because if extent is invalid the convertExtent will fail before the validation. Should we do validate then convert?
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts` line 252 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O1270MT0F3CbGBYFQyz:-O1270MT0F3CbGBYFQz-:b-6hsbo4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts#L252)):*
> ```XML
>       const metadataProjection = this.getMetadataProjection();
>       layerBounds = this.getMapViewer().convertExtentFromProjToMapProj(metadataExtent, metadataProjection);
>       layerBounds = validateExtent(layerBounds, this.getMapViewer().getProjection().getCode());
> ```

Not sure but should it be the other way around because if extent is invalid the convertExtent will fail before the validation. Should we do validate then convert?


<!-- Sent from Reviewable.io -->

2024-07-05 16:06 UTC, Alex-NRCan approved these changes
I like the fact that the configurations seem more standardized to all be in 4326 and the actual projection on the map projection be done only when calculating the bounds (getBounds()) :thumbsup: 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-:-O12a9zg-VVGkdjyOytp:b-iz6fkp)* status: all files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 457 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O128Otn6kRGvM6wcObd:-O128Otn6kRGvM6wcObe:b-p0f7fm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/utils/utilities.ts#L457)):*
> ```XML
>  * @returns {Extent} The validated extent
>  */
> export function validateExtent(extent: Extent, code: string = 'EPSG:4326'): Extent {
> ```

Minor
Just a general idea, because I see a lot of times when this is called code like: `if (initial.extent) initial.extent = validateExtent(initial.extent)`
How about another method next to this one that would be called like: `validateExtentWhenDefined(initial.extent)` and it just performs the validation when it's defined, otherwise it returns undefined, hence reassigning undefined to undefined in the calling methods.. but just saves a bit of overhead 'if' verifications - for minor better readability.


<!-- Sent from Reviewable.io -->

2024-07-08 16:41 UTC, ychoquet reviewed
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 8 unresolved discussions (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-07-08 16:41 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 7 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O1VJXBJ5IAuiAvM9wCi:-O1ID2BcBg9olro3rwu1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L87)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do you really have to use " as Extent"? The type of this.bounds is already Extent.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 928 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O125rQY7_un4LZ1bU73:-O1HeR97B6vEMR-t1-uy:bkivikb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L928)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not sure but should it be the other way around because if extent is invalid the convertExtent will fail before the validation. Should we do validate then convert?
</blockquote></details>

I had it that way initially, but it causes an error when the metadata projection isn't one of the three that the validation function can handle. If the extent contains invalid values, convert extent will not fail, but return NaN, which will be handled by the validate function.
___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 452 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O124Ge6A7oxOFUINpGI:-O1ID8UC1m43vEzlRWTY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2d343b4ac1a2bc886583f7f5cbce326281ff13f6/packages/geoview-core/src/geo/utils/utilities.ts#L452)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is not only lat/long, LCC and WebMercator
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 13:12 UTC, jolevesq approved these changes
> Reviewed 2 of 15 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-07-09 14:06 UTC, Alex-NRCan requested changes
> Reviewed 10 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/tile/gv-xyz-tiles.ts` line 93 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O1Mm5hK5IYQB679Rway:-O1Mm5hK5IYQB679Rwaz:b-y0t9hs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/05165c2f10961c27a31b6dff29bc61983a201678/packages/geoview-core/src/geo/layer/gv-layers/tile/gv-xyz-tiles.ts#L93)):*
> ```XML
>       // Make sure we're in the map projection
>       sourceExtent = this.getMapViewer().convertExtentFromProjToMapProj(sourceExtent, sourceProjection);
>       sourceExtent = validateExtent(sourceExtent, `EPSG:${this.getMapViewer().getProjection()}`);
> ```

Minor
Sometimes, this is called using `this.getMapViewer().getProjection().getCode()` and sometimes like here using 'EPSG:${this.getMapViewer().getProjection()}`.

Suggestion to standardize all using the former method?
___
*[`packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O1MmLjP-ps8uhU3BKn1:-O1MmLjP-ps8uhU3BKn2:bbxgkzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/05165c2f10961c27a31b6dff29bc61983a201678/packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts#L50)):*
> ```XML
>       // Make sure we're in the map projection
>       sourceExtent = this.getMapViewer().convertExtentFromProjToMapProj(sourceExtent, sourceProjection);
>       sourceExtent = validateExtent(sourceExtent, `EPSG:${this.getMapViewer().getProjection()}`);
> ```

Same comment as above


<!-- Sent from Reviewable.io -->

2024-07-09 14:18 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346#-O1MmLjP-ps8uhU3BKn1:-O1Mr0_r-KO9fJ7jvLWh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/05165c2f10961c27a31b6dff29bc61983a201678/packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts#L50)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 14:21 UTC, jolevesq reviewed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)



<!-- Sent from Reviewable.io -->

2024-07-09 14:21 UTC, jolevesq approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)



<!-- Sent from Reviewable.io -->

2024-07-09 15:34 UTC, Alex-NRCan approved these changes
> Reviewed 2 of 12 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2024-07-09 15:37 UTC, merged