2357-Code_alignment_to_last_schema
Canadian-Geospatial-Platform/geoview pull request #2381
Opened 2024-07-17 13:52 UTC by ychoquet

# Description

Adjustments to the latest drawio diagram..

Fixes #2357

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtool to trace and debug the code of config-sandbox.html.

__Deploy URL__: http://localhost:8080/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-07-17 15:28 UTC, jolevesq requested changes
> Reviewed 3 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 229 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20HLJkBkikIi2Nkrdc:-O20HLJkBkikIi2Nkrdd:b-6kkrha) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L229)):*
> ```XML
>             urlParams.keys.toString().split(',')
>           );
>           const listOfGeoviewLayerConfig = await promise;
> ```

Add blank lines between section of code and some comments... what this section is doing?
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 472 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IGyD6bxrk4fvJUbc:-O20IGyD6bxrk4fvJUbd:bdxljce) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L472)):*
> ```XML
>         const layerConfig = { geoviewLayerId: serviceAccessString, geoviewLayerType: layerType };
>         geoviewLayerConfig = (await ConfigApi.convertGeocoreToGeoview(language, Cast<TypeJsonObject>(layerConfig))) as TypeJsonObject;
>         if (!geoviewLayerConfig) return undefined;
> ```

Add blank lines and comments
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 503 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IiG6BIfSIezdDbZb:-O20IiG6BIfSIezdDbZc:beepjfe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L503)):*
> ```XML
>    * @static
>    */
>   // GV: GeoCore layers are processed here, well before the schema validation. The aim is to get rid of these layers in
> ```

There is process og geocore here... it is just a layerTree extraction. We can even remove geocore from this function as we do not want layertree for geoCore


<!-- Sent from Reviewable.io -->

2024-07-17 15:29 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 3 of 22 files reviewed, 4 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 511 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IyM_CrjJ4ZuN2tbt:-O20IyMaCjqbDkgCnrlA:b-66t9oq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L511)):*
> ```XML
>     language: TypeDisplayLanguage = 'en'
>   ): Promise<EntryConfigBaseClass[]> {
>     const geoviewLayerConfig = await ConfigApi.createLayerConfig(serviceAccessString, layerType, listOfLayerId, language);
> ```

We do not want to create a layer config here.... really just fetch metadata and create layer tree


<!-- Sent from Reviewable.io -->

2024-07-17 17:26 UTC, jolevesq requested changes
> Reviewed 7 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 10 of 22 files reviewed, 11 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 131 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20fHEy-K3KggD_P8Vv:-O20fHF85uqUsvQ3IVRE:bee54eb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a2880b2769f217887301fcfbc216855a1e17b3c/packages/geoview-core/src/api/config/uuid-config-reader.ts#L131)):*
> ```XML
>               (item): TypeJsonObject => {
>                 return Cast<TypeJsonObject>({
>                   entryType: CV_CONST_SUB_LAYER_TYPES.RASTER_IMAGE,
> ```

There is no entry type anymore or it has been moved somewhere else?
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 438 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20flEc6QMntfsO3ZfM:-O20flEc6QMntfsO3ZfN:b-8jrvyj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a2880b2769f217887301fcfbc216855a1e17b3c/packages/geoview-core/src/api/config/types/config-validation-schema.json#L438)):*
> ```JSON
>         }
>       },
>       "required": ["geoviewLayerId", "geoviewLayerName", "geoviewLayerType", "listOfLayerEntryConfig"]
> ```

and name not needed anymore?
___
*[`packages/geoview-core/src/api/config/types/classes/config-exceptions.ts` line 42 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20g8TJ1r7TKioKqA-y:-O20g8TJ1r7TKioKqA-z:b-ovuenj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a2880b2769f217887301fcfbc216855a1e17b3c/packages/geoview-core/src/api/config/types/classes/config-exceptions.ts#L42)):*
> ```XML
>   messageList: Record<string, string> = {
>     LayerTypeMandatory: 'Property geoviewLayerType is mandatory for GeoView layer <=> of type <=>.',
>     LayerIdMandatory: 'Property geoviewLayerId is mandatory for GeoView layer of type <=>.',
> ```

We do not enforce anymore?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20gXbL7YVMaLCpzoaN:-O20gXbL7YVMaLCpzoaO:b2dtudo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L14)):*
> ```XML
> import { getXMLHttpRequest } from '@/core/utils/utilities';
> import { logger } from '@/core/utils/logger';
> import { TypeJsonArray } from '@/app';
> ```

I think app is not the proper path
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20gcP07jihVkC1_XJL:-O20gcP07jihVkC1_XJM:b-awld41) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L24)):*
> ```XML
>    * @param {TypeDisplayLanguage} language The initial language to use when interacting with the map feature configuration.
>    */
>   constructor(geoviewLayerConfig: TypeJsonObject, language: TypeDisplayLanguage) {
> ```

Why we do not pass only url and list of ids as it is the only needed thing to create metadata. The rest of config will be use later in a applyUserConfig function.

Less management in the constructor
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20hVgsEugF2GglPNRz:-O20hVgt7DVf_22LGR3p:bmqh5cj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L85)):*
> ```XML
>           });
>         };
>         processListOfLayerEntryConfig(this.listOfLayerEntryConfig);
> ```

Blank line before, add some comments
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20h-SO3uWS5rFViWS8:-O20h-SP6ypemlkdMkKy:bot67pr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L87)):*
> ```XML
>         processListOfLayerEntryConfig(this.listOfLayerEntryConfig);
>         await this.#fetchListOfLayerMetadata(this.metadataLayerTree);
>         this.metadataLayerTree = this.createLayerTree();
> ```

We do not need metadata tree here, it is only needed in the configAPI getMetadataTree function? You do not need the whole tree if you have lets say 2 ids

If is it another function that does not  relate to the function getMEtadataLAyerTrtee we need better naming


<!-- Sent from Reviewable.io -->

2024-07-17 17:27 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 10 of 22 files reviewed, 12 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20inRwEQckQ6n4EY_P:-O20inRwEQckQ6n4EY_Q:bm9uci0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L23)):*
> ```XML
> 
>   /** Cloned copy of the configuration as provided by the user when the constructor was called. */
>   #geoviewLayerConfig: TypeJsonObject;
> ```

I do not think we need this... we should create config from metadata and have a function who take the piece of cofig to apply on top.... We can reuse the same object to get different config


<!-- Sent from Reviewable.io -->

2024-07-17 17:28 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 10 of 22 files reviewed, 13 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20j3Nq9eWKXAbqh7lv:-O20j3Nq9eWKXAbqh7lw:b3c27dm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L76)):*
> ```XML
>     // Keep a copy of the configuration. It will be used later in the execution flow to overwrite values obtained from the metadata.
>     this.#geoviewLayerConfig = cloneDeep(geoviewLayerConfig);
>     this.#validateGeoviewConfig();
> ```

VAlidate config is made when we validate map for layer config schema? We should then validate only in the applyUIserConfig function


<!-- Sent from Reviewable.io -->

2024-07-17 17:32 UTC, jolevesq requested changes
> Reviewed 6 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 16 of 22 files reviewed, 14 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20jbEmA3N7TYyLjGWC:-O20jbEmA3N7TYyLjGWD:b-hoe7em) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L89)):*
> ```XML
>     let jsonListOfLayerEntryConfig: TypeJsonArray;
>     switch ((geoviewLayerConfig?.listOfLayerEntryConfig as TypeJsonArray)?.length) {
>       case undefined:
> ```

 iCan t be undefined?


<!-- Sent from Reviewable.io -->

2024-07-17 18:31 UTC, Alex-NRCan requested changes
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 23 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 465 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20jgCc0DBfHYoGnzmP:-O20jgCc0DBfHYoGnzmQ:b-sisxhx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L465)):*
> ```XML
>   ): Promise<AbstractGeoviewLayerConfig | undefined> {
>     let geoviewLayerConfig: TypeJsonObject | undefined;
>     const listOfLayerEntryConfig = listOfLayerId.map((layerId) => {
> ```

Minor
This `listOfLayerEntryConfig` seem only used in the 'else' condition. Move the code below to help understand what it's used for when reading the code?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 208 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20ltcF9pzyvlJBVAwQ:-O20ltcF9pzyvlJBVAwR:b-vwnl90) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L208)):*
> ```XML
> 
>     const result = await Promise.allSettled(listOfLayerMetadata);
>     logger.logInfo('fetchListOfLayerMetadata done', result);
> ```

Isn't it `logDebug` here? Because logInfo is for everyone and the message isn't really explanatory for common folks. Maybe adjust the message if meant for everyone?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20mnjx04E2sbSXbz87:-O20mnjx04E2sbSXbz88:b8cuqhv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L61)):*
> ```XML
>    * Initial settings to apply to the GeoView layer at creation time.
>    */
>   initialSettings!: TypeLayerInitialSettings;
> ```

A bit hard to validate via reviewable, but I probably wouldn't add a `!` to bypass the EsLint error in this case.
Can it be initialized to `CV\_DEFAULT\_LAYER\_INITIAL\_SETTINGS` straight away or else be typed as `TypeLayerInitialSettings | undefined`? Relying on the override of the `applyDefaultValuesToUndefinedFields` function seems a bit "far".
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 144 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20qoOvCa-MBYlPLZI-:-O20qoOvCa-MBYlPLZI0:b7yowkl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L144)):*
> ```XML
>    *
>    */
>   applyDefaultValueToUndefinedFields(): void {
> ```

Question
Is this function used? I couldn't find where it was *called*.
Also, when reading the code, I got confused with the other functions *named exactly the same* in EntryConfigBaseClass (and its children classes) which functions receive an 'initialSettings' parameter in their signature while this one, in `AbstractGeoviewLayerConfig`, doesn't. Normal?
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts` line 20 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20tBvX8hjk1PD53AJM:-O20tBvY1M7i8tAH7YB-:b-n9k7ro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts#L20)):*
> ```XML
> 
>   /** The geometry type of the leaf node. */
>   geometryType!: TypeStyleGeometry;
> ```

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20uVXK3Y5neHotnFtt:-O20uVXK3Y5neHotnFtu:b-n9k7ro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L39)):*
> ```XML
> 
>   /** Attributions obtained from the configuration or the metadata. */
>   attributions!: string[];
> ```

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20uj2p3-Ufs7FPQbLi:-O20uj2q0ulnY6Ez4l7H:b-n9k7ro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L45)):*
> ```XML
> 
>   /** The min scale that can be reach by the layer. */
>   minScale!: number;
> ```

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20ul4p3IRGhGjixb6D:-O20ul4p3IRGhGjixb6E:b-n9k7ro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L48)):*
> ```XML
> 
>   /** The max scale that can be reach by the layer. */
>   maxScale!: number;
> ```

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20u7p2CWMAV3KWFX32:-O20u7p2CWMAV3KWFX33:b-rzilh0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L57)):*
> ```XML
>    * configuration tree.
>    */
>   initialSettings!: TypeLayerInitialSettings;
> ```

Same as other comment on initialSettings attribute


<!-- Sent from Reviewable.io -->

2024-07-18 15:54 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 22 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 229 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20HLJkBkikIi2Nkrdc:-O25Ex6h5KdHOxaqfTXE:b-cjiv02) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L229)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add blank lines between section of code and some comments... what this section is doing?
</blockquote></details>

Done.
I added the following comment:
          // The listOfGeoviewLayerConfig returned by the previous call appended 'rcs.' at the beginning and
          // '.en' or '.fr' at the end of the UUIDs. We want to restore the ids as they were before.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 465 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20jgCc0DBfHYoGnzmP:-O25GNgh70VxYUT86S4j:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L465)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Minor
This `listOfLayerEntryConfig` seem only used in the 'else' condition. Move the code below to help understand what it's used for when reading the code?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 472 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IGyD6bxrk4fvJUbc:-O25LG3SDD4ICXz29hB3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L472)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add blank lines and comments
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 503 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IiG6BIfSIezdDbZb:-O25Mv4wCKShLQbZQVbM:b-9ct8as) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L503)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is process og geocore here... it is just a layerTree extraction. We can even remove geocore from this function as we do not want layertree for geoCore
</blockquote></details>

I don't understand why you want to remove the layer tree generation for GeoCore. If you go to the config-sandbox and request the layer tree for the GeoCore sample, it works and the user could request that only layer 1 - "Strontium-90 in Milk" be added to the map. If you absolutely want to remove it, I'll do it, but why remove something that's working properly?
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 511 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IyM_CrjJ4ZuN2tbt:-O25OVZA871S9KmQWoZj:bkg39mz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L511)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not want to create a layer config here.... really just fetch metadata and create layer tree
</blockquote></details>

This is what I do. The GeoView layer instantiation just assigns the bare minimum of properties (metadataAccesPath, layerIds) and performs a few other quick tasks to select the right type of object that knows exactly how to read the metadata and create the layer tree. At the end, all we have to do is return the calculated layer tree. This approach is fully functional and encapsulates the processing linked to a layer type in an object that contains only code linked to its class. That's the beauty of object-oriented languages.

This avoids the need for a procedure containing a switch for each layer type, which connects to another sub-procedure that fetches the metadata and then connects to another sub-procedure that calculates the layer tree, thus scattering code logic everywhere.
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 131 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20fHEy-K3KggD_P8Vv:-O25TXGU33cQ-I-ZWNcj:b-nr34sp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a2880b2769f217887301fcfbc216855a1e17b3c/packages/geoview-core/src/api/config/uuid-config-reader.ts#L131)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no entry type anymore or it has been moved somewhere else?
</blockquote></details>

The entryType propriety belongs to the internal schema. Its value is derived programmatically from the GeoView layer type. Users must not provide it. We already had a problem in the past where a user provided a wrong value for this property thinking that he can force an ESRI 


<!-- Sent from Reviewable.io -->

2024-07-18 15:55 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 22 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 131 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20fHEy-K3KggD_P8Vv:-O25YW8Z0wYKrISZnRfE:boipfwg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a2880b2769f217887301fcfbc216855a1e17b3c/packages/geoview-core/src/api/config/uuid-config-reader.ts#L131)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The entryType propriety belongs to the internal schema. Its value is derived programmatically from the GeoView layer type. Users must not provide it. We already had a problem in the past where a user provided a wrong value for this property thinking that he can force an ESRI
</blockquote></details>

We already had a problem in the past where a user provided a wrong value for this property thinking that he can force an ESRI to behave like a WMS layer.


<!-- Sent from Reviewable.io -->

2024-07-18 19:11 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 20 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 503 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IiG6BIfSIezdDbZb:-O26EeAHCciCTG7yYpdo:bt675rt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L503)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I don't understand why you want to remove the layer tree generation for GeoCore. If you go to the config-sandbox and request the layer tree for the GeoCore sample, it works and the user could request that only layer 1 - "Strontium-90 in Milk" be added to the map. If you absolutely want to remove it, I'll do it, but why remove something that's working properly?
</blockquote></details>

There is no layer tree for geocore. geocore is a whole config and user cannot select or unselect withing what is set.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 511 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20IyM_CrjJ4ZuN2tbt:-O26Ew4h5k8m0cCc8E9M:bkrgj0a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/config-api.ts#L511)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This is what I do. The GeoView layer instantiation just assigns the bare minimum of properties (metadataAccesPath, layerIds) and performs a few other quick tasks to select the right type of object that knows exactly how to read the metadata and create the layer tree. At the end, all we have to do is return the calculated layer tree. This approach is fully functional and encapsulates the processing linked to a layer type in an object that contains only code linked to its class. That's the beauty of object-oriented languages.

This avoids the need for a procedure containing a switch for each layer type, which connects to another sub-procedure that fetches the metadata and then connects to another sub-procedure that calculates the layer tree, thus scattering code logic everywhere.
</blockquote></details>

Good, as long as there is no unneeded call to fetch stuff specific to layer I am good.


<!-- Sent from Reviewable.io -->

2024-07-18 20:46 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 20 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20inRwEQckQ6n4EY_P:-O26_FlP7VhNFKpJPKoY:bxlx0dt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I do not think we need this... we should create config from metadata and have a function who take the piece of cofig to apply on top.... We can reuse the same object to get different config
</blockquote></details>

I think we still need it because the user can provide its config in the map template or in a config file processed programmaticaly. This doesn't eliminate the fact that we want to apply a user config using another method. The two method will be available and well documented when we come to it.


<!-- Sent from Reviewable.io -->

2024-07-19 02:48 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 20 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20mnjx04E2sbSXbz87:-O26gLx_BtlGjp2j_MBC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L61)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

A bit hard to validate via reviewable, but I probably wouldn't add a `!` to bypass the EsLint error in this case.
Can it be initialized to `CV\_DEFAULT\_LAYER\_INITIAL\_SETTINGS` straight away or else be typed as `TypeLayerInitialSettings | undefined`? Relying on the override of the `applyDefaultValuesToUndefinedFields` function seems a bit "far".
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20j3Nq9eWKXAbqh7lv:-O27rvWU2bgZmUJdaugk:b-vq6ju4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

VAlidate config is made when we validate map for layer config schema? We should then validate only in the applyUIserConfig function
</blockquote></details>

We must validate the properties used in the instanciation to make sure we can proceed with the metadata fetch. The validation cost is only a tiny fraction of a second and it simplify the error managment that must be done later.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20jbEmA3N7TYyLjGWC:-O26iEGoCsu3Vu8M1BRg:be937ds) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

iCan t be undefined?
</blockquote></details>

geoviewLayerConfig is a flat json object comming from the users and the constructor is used to instanciate a GeoView layer in many situations. There is no guarantee that the user provided a valid structure since it has never been validated before.. This is why we use ?. in the switch variable so if geoviewLayerConfig?.listOfLayerEntryConfig?.length cannot be evaluated, we get undefined.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 144 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20qoOvCa-MBYlPLZI-:-O26m8Hj7QSsDM0gnJUf:bciasaw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L144)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Question
Is this function used? I couldn't find where it was *called*.
Also, when reading the code, I got confused with the other functions *named exactly the same* in EntryConfigBaseClass (and its children classes) which functions receive an 'initialSettings' parameter in their signature while this one, in `AbstractGeoviewLayerConfig`, doesn't. Normal?
</blockquote></details>

It will be in the next phase. Johann specification says that the default is applied after the metadata has been read and processed. That's the point we are now.

It's also worth noting that sublayers inherit the initialSettings from the parent container as default values. The abstractGeoviewLayerConfig is at the top of this inheritance and these initialSettings are propagated as new default values  to the sublayers, which explains the presence of the parameter only for descendants of the EntryConfigBaseClass.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts` line 20 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20tBvX8hjk1PD53AJM:-O27cwvGAvBYTc2KTsJx:b-xzqckt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts#L20)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
</blockquote></details>

Done. The geometryType may be undefined for some GeoView layers.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20uVXK3Y5neHotnFtt:-O27dPyC5wkVzo7D6xYH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L39)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20uj2p3-Ufs7FPQbLi:-O27rTLa8GwED7AWu0nn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L45)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20ul4p3IRGhGjixb6D:-O27rVjF--9xJyxZJEaI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L48)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I wouldn't add a `!` suffix on this attribute. Especially since I can't find *where* this attribute is defined/used in this class. Seems misleading.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20u7p2CWMAV3KWFX32:-O27rXN80MuzJFl5TT2v:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L57)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i [...]

2024-07-19 16:23 UTC, jolevesq reviewed
> Reviewed 2 of 22 files at r1, 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 21 of 22 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-07-19 16:50 UTC, Alex-NRCan approved these changes
> Reviewed 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 144 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O20qoOvCa-MBYlPLZI-:-O2AnXkF0t5CM6QrYNc4:b-jpdipw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9110d228c76df60a48e2acf6037fb4a7aa77c48f/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L144)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It will be in the next phase. Johann specification says that the default is applied after the metadata has been read and processed. That's the point we are now.

It's also worth noting that sublayers inherit the initialSettings from the parent container as default values. The abstractGeoviewLayerConfig is at the top of this inheritance and these initialSettings are propagated as new default values  to the sublayers, which explains the presence of the parameter only for descendants of the EntryConfigBaseClass.
</blockquote></details>

I'd prefer to have a distinct function name to differentiate them from the overridable functions of the same name (if they're meant to be called differently), to remove possible confusion, but I can mark this as resolved.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 113 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O2AswtGAVRelT8bZW25:-O2AswtGAVRelT8bZW26:b-kykv92) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/94fb882161b3d3408bb6d650902e7bb0f6b89bf3/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L113)):*
> ```XML
>    */
>   applyDefaultValueToUndefinedFields(initialSettings: TypeLayerInitialSettings): void {
>     this.initialSettings = defaultsDeep(this.initialSettings, initialSettings);
> ```

This comment relates to my other couple comments about the '!' suffix.

I see you've added this section, which helps understand when those attributes are meant to be set/defaulted - which is great. Unfortunately, you're saying the code calling this function is only coming "in the next phase". Therefore, right now, it's hard to validate if your reasoning for bypassing the EsLint is "worth it". Until I can see when and how this method is called it's a grey area. I can resolve this for now.


<!-- Sent from Reviewable.io -->

2024-07-19 18:50 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 113 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381#-O2AswtGAVRelT8bZW25:-O2BK4JF4wLnu9zVljyt:bogxi14) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/94fb882161b3d3408bb6d650902e7bb0f6b89bf3/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L113)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This comment relates to my other couple comments about the '!' suffix.

I see you've added this section, which helps understand when those attributes are meant to be set/defaulted - which is great. Unfortunately, you're saying the code calling this function is only coming "in the next phase". Therefore, right now, it's hard to validate if your reasoning for bypassing the EsLint is "worth it". Until I can see when and how this method is called it's a grey area. I can resolve this for now.
</blockquote></details>

Maybe add a TODO to validate when next phase is done


<!-- Sent from Reviewable.io -->

2024-07-19 19:17 UTC, jolevesq approved these changes
> Reviewed 1 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2381)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-07-19 19:54 UTC, merged