2410-ESRI_layer_metadata_parsing
Canadian-Geospatial-Platform/geoview pull request #2424
Opened 2024-08-01 19:55 UTC by ychoquet

# Description

Complete implementation of the config API that process  esri feature and dynamic configuration. The temporal dimension, source, stype, extent properties are operationnal. The apply user config is implemented. The config is generated starting with the default values, over which we apply the metadata settings and finally the user settings.

Fixes #2410 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the Chrome Devtool and the config-sandbox template to trace and debbug the code.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-08-01 22:04 UTC, Alex-NRCan requested changes
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424)* status: all files reviewed, 12 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/api/config/esri-renderer-parser.ts` line 600 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3E_AJ79DrHCouwu1w_:-O3E_AJ8DDhVK8Z-iTyp:b-7s6l2k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/esri-renderer-parser.ts#L600)):*
> ```XML
>   if (esriRendererIsSimple(renderer)) return processSimpleRenderer(renderer);
>   if (esriRendererIsClassBreaks(renderer)) return processClassBreakRenderer(renderer);
>   logger.logInfo(`Handling of ESRI renderer '${renderer.type}' is not coded, default GeoView settings will be used instead.`);
> ```

Unrelated to the PR itself, but this should maybe be a logWarning()?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3E_zj81mwoCVBq7vf-:-O3E_zj81mwoCVBq7vf0:b-yj0s1l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L373)):*
> ```XML
>     });
> 
>     const promiseSettledResult = await Promise.allSettled(promiseLayersProcessed);
> ```

Here it awaits for all the promises, sets the errorDetectedFlag after, and returns a Promise<void>.

Suggestion, wouldn't it be more useful to return the Promise.allSettled() promise with all the results of the promises instead of Promise<void>? The caller could better track what happened with the service metadata promises.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 137 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3ExgZw8t4e_JklM4nP:-O3ExgZw8t4e_JklM4nQ:bgrhsvr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L137)):*
> ```XML
> 
>   // #region GETTER/SETTER
>   // GV: The benifit of using a setter/getter with a private #property is that it is invisible to the schema
> ```

Same comment here as others
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3EcFAF5DecUkJckqvb:-O3EcFAF5DecUkJckqvc:b-t0mfkh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts#L12)):*
> ```XML
> export type TypeEsriDynamicLayerNode = EsriGroupLayerConfig | EsriDynamicLayerEntryConfig;
> 
> // #region CLASS HEADER
> ```

Here and many other places in this PR.
Make sure that for each `#region` tag that you open, you have a corresponding `#endregion` tag.
https://code.visualstudio.com/docs/editor/codebasics#_folding
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3EbpQa2s5TZA_xbrMA:-O3EbpQa2s5TZA_xbrMB:b-uixdfw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts#L27)):*
> ```XML
> 
>   // #region GETTER/SETTER
>   // GV: The benifit of using a setter/getter with a private #property is that it is invisible to the schema
> ```

Is this comment still relevant? I'm not seeing any private #property here
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Ecb-T294FVsHfDXiO:-O3Ecb-U5ErZtK3j26BB:bbxgkzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts#L23)):*
> ```XML
> 
>   // #region GETTER/SETTER
>   // GV: The benifit of using a setter/getter with a private #property is that it is invisible to the schema
> ```

Same comment as above
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 191 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Ed8-G1bZCpWs9lDlY:-O3Ed8-G1bZCpWs9lDlZ:b-ku153l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L191)):*
> ```XML
>    * @protected @abstract
>    */
>   protected abstract getSchemaPath(): string;
> ```

Personal opinion.
I think we should group (in a region?) the must-override methods such as this one together (and probably up top). They are "more important" methods than others. Especially when inheriting. They should have some sort of "focus" on them instead of listed between other methods.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts` line 83 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Edtm4BBU9HQT-dQfG:-O3Edtm4BBU9HQT-dQfH:b-m059z1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts#L83)):*
> ```XML
>    * The same method signature is used by layer group nodes and leaf nodes (layers).
>    */
>   override async fetchLayerMetadata(): Promise<void> {
> ```

This function is a bit hard to follow. It doesn't help that not all code paths return an _explicit_ Promise (only an implicit Promise is returned here (one on the `return` line and one at the end of the function)). Personally, I wish we would have an ESLint rule to that effect, to prevent accidents/unintentional behavior when chaining promises..

Anyways, I guess this comment is more for clarity. IMO, this function could use more comments with regard to context with the process of things in general.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Ey-uP-7Vr2wqqx_a5:-O3Ey-uP-7Vr2wqqx_a6:bkt4gh0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts#L115)):*
> ```XML
>    * The same method signature is used by layer group nodes and leaf nodes (layers).
>    */
>   override async fetchLayerMetadata(): Promise<void> {
> ```

See other comment about adding more contextualized comments in this function as well.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/esri-dynamic-layer-entry-config.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3EbQEV4EQcyOb53gc8:-O3EbQEV4EQcyOb53gc9:b-2tgl5o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/esri-dynamic-layer-entry-config.ts#L66)):*
> ```XML
>     };
> 
>     const renderer =  [...]

2024-08-02 14:58 UTC, DamonU2 requested changes
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424)* status: all files reviewed, 14 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3INKuH9Rup14iznHay:-O3INKuIAtopdgK6badX:baob137) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/map-schema-types.ts#L327)):*
> ```XML
>   singleHandle: boolean;
> };
> */
> ```

Does this need to stay here?
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/group-layer-entry-config.ts` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3I_7H_8OOF9JxAuPCI:-O3I_7H_8OOF9JxAuPCJ:b-u9z8z9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/group-layer-entry-config.ts#L41)):*
> ```XML
>         if (layerEntryIsGroupLayer(subLayerConfig))
>           return geoviewLayerConfig.createLeafNode(subLayerConfig, language, geoviewLayerConfig, this);
>         return geoviewLayerConfig.createLeafNode(subLayerConfig, language, geoviewLayerConfig, this);
> ```

These two returns are identical, should the first one be returning a group layer, or do we not need the if statement?


<!-- Sent from Reviewable.io -->

2024-08-02 22:13 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424)* status: all files reviewed, 14 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/config/esri-renderer-parser.ts` line 600 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3E_AJ79DrHCouwu1w_:-O3G8otU9ir2pHOPUtLB:b-grmhy9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/esri-renderer-parser.ts#L600)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Unrelated to the PR itself, but this should maybe be a logWarning()?
</blockquote></details>

Done. There were 5 logInfo that should be logWarning. I changed them.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3INKuH9Rup14iznHay:-O3K5DT58Xqnj7UddfRF:b-s9ewq5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/map-schema-types.ts#L327)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Does this need to stay here?
</blockquote></details>

Done. I removed it.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3E_zj81mwoCVBq7vf-:-O3GCAkQEe87AFseheaL:bsitw19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L373)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here it awaits for all the promises, sets the errorDetectedFlag after, and returns a Promise<void>.

Suggestion, wouldn't it be more useful to return the Promise.allSettled() promise with all the results of the promises instead of Promise<void>? The caller could better track what happened with the service metadata promises.
</blockquote></details>

This method was created to compare the metadata fetch of all geoview layers with the metadata fetch using a loop to process the list layer by layer. I'm not sure it will be retained. Johann plans to process geoview layers one by one rather than as a block. Also, I think that if this method is kept, it's better to return a simple promise<void> and process the Promise.allSettled here in order to set the errorDetectedFlag on the layers that fail mainly because the API logic is to raise this flag every time a layer is unusable. If we don't raise this flag inside the ConfigApi boundary, we transfer the responsibility for doing so outside the API, with the risk that the user won't be aware that they need to do so.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 137 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3ExgZw8t4e_JklM4nP:-O3Jfif1EzSiMcFuVDzS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L137)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same comment here as others
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3EcFAF5DecUkJckqvb:-O3ILXiC2-g-Xxh5-PZJ:bot7bdk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts#L12)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here and many other places in this PR.
Make sure that for each `#region` tag that you open, you have a corresponding `#endregion` tag.
https://code.visualstudio.com/docs/editor/codebasics#_folding
</blockquote></details>

Done. Interesting, I thought that #region was only used to display a marker in the Minimap.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3EbpQa2s5TZA_xbrMA:-O3IMMYo6Ql86E96sQJD:b-74bepi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts#L27)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Is this comment still relevant? I'm not seeing any private #property here
</blockquote></details>

Done. Removed it.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Ecb-T294FVsHfDXiO:-O3IMWAv3_dBsvfsu1Qy:b-74bepi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts#L23)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done. Removed it.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 191 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Ed8-G1bZCpWs9lDlY:-O3Jfuld-aVBC1Ugd63Z:b-hhpq4p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L191)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Personal opinion.
I think we should group (in a region?) the must-override methods such as this one together (and probably up top). They are "more important" methods than others. Especially when inheriting. They should have some sort of "focus" on them instead of listed between other methods.
</blockquote></details>

Good idea! I created regions in this order when they exist: abstract, override, private, protected and public.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts` line 83 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Edtm4BBU9HQT-dQfG:-O3JrCCp9OEhe1iaAHIC:bubyrh7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts#L83)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This function is a bit hard to follow. It doesn't help that not all code paths return an _explicit_ Promise (only an implicit Promise is returned here (one on the `return` line and one at the end of the function)). Personally, I wish we would have an ESLint rule to that effect, to prevent accidents/unintentional behavior when chaining promises..

Anyways, I guess this comment is more for clarity. IMO, this function could use more comments with regard to context with the process of things in general.
</blockquote></details>

I've added a few comments and restructured the code. There is no promise chaining in this method. We use either the service metadata that have been fetched previously or the layer metadat [...]

2024-08-02 22:22 UTC, DamonU2 approved these changes
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424)* status: all files reviewed, 12 unresolved discussions (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-08-05 13:08 UTC, Alex-NRCan requested changes
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424)* status: all files reviewed, 10 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3E_zj81mwoCVBq7vf-:-O3XaI502zhiVSR2noYg:b2ykqd4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L373)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This method was created to compare the metadata fetch of all geoview layers with the metadata fetch using a loop to process the list layer by layer. I'm not sure it will be retained. Johann plans to process geoview layers one by one rather than as a block. Also, I think that if this method is kept, it's better to return a simple promise<void> and process the Promise.allSettled here in order to set the errorDetectedFlag on the layers that fail mainly because the API logic is to raise this flag every time a layer is unusable. If we don't raise this flag inside the ConfigApi boundary, we transfer the responsibility for doing so outside the API, with the risk that the user won't be aware that they need to do so.
</blockquote></details>

We could still set the flag here, for processing reasons, and return the whole Promise.allSettled for convenience.
Was a suggestion.
Up to you/Johann.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 187 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Xa2FZ4Cr0s0IiSjAl:-O3Xa2FZ4Cr0s0IiSjAm:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L187)):*
> ```XML
> 
>   /**
>    * @private
> ```

Same as above
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 226 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Xa53ZDVVQRqyslOHj:-O3Xa53ZDVVQRqyslOHk:bnx2vld) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L226)):*
> ```XML
> 
>   /**
>    * @private
> ```

Same as above, it seems you've moved them all on purpose?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Xda3k0NX1a8KJmY88:-O3Xda3k0NX1a8KJmY89:b-huu3an) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L55)):*
> ```XML
>   // #region OVERRIDE
>   /**
>    * @override
> ```

Same comment for jsdocs
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3XbaCLB7hy5K1F3Vrz:-O3XbaCLB7hy5K1F3Vs-:bl93sp8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L152)):*
> ```XML
>    */
>   // ================
>   // #region ABSTRACT
> ```

I like that the abstract functions were moved up top in the file, to give them some importance :thumbsup: 
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts` line 123 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3XdmGb-6WuPp9XVTqJ:-O3XdmGb-6WuPp9XVTqK:b-kfc00f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts#L123)):*
> ```XML
>    */
>   // ================
>   // #region ABSTRACT
> ```

I like this region ABSTRACT :thumbsup: 
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts` line 83 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Edtm4BBU9HQT-dQfG:-O3XcfC7ErZdAiM_ZyOf:b-rbf6eo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/36c8bf1366e69a843b267f911ed08fa0159b7b83/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts#L83)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I've added a few comments and restructured the code. There is no promise chaining in this method. We use either the service metadata that have been fetched previously or the layer metadata obtained by a new fetch.

The logic behind the config api is as follows: when a config object's asychronous method is called, the Promise<void> will always terminate successfully. If this is not the case, the ConfigApi is badly coded. To find out whether the config is usable, we consult the error flag returned by the getErrorDetectedFlag method.
</blockquote></details>

I meant chaining from the caller of this function.
IMO, my comment remains, but up to you/Johann at this point.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3XcL1JE1QRg7FbFEfy:-O3XcL1KECQcjKY-DAFJ:b150pal) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts#L27)):*
> ```XML
>   // #region OVERRIDE
>   /** ***************************************************************************************************************************
>    * @override
> ```

Same comment about jsdocs
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts` line 98 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3XdRfJ5N73ndj4N9NQ:-O3XdRfJ5N73ndj4N9NR:bu8gz1o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts#L98)):*
> ```XML
> 
>   /** ***************************************************************************************************************************
>    * @protected
> ```

Same comment as other jsdocs
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-layer-entry-config.ts` line 30 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2424#-O3Xdfyz8L4x0_B7sTCi:-O3Xdfyz8L4x0_B7sTCj:b-huu3an) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d5f9c4875c1dae52675aef58c4c070bf65d67d15/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-layer-entry-config.ts#L30)):*
> ```XML
>   // #region ABSTRACT
>   /**
>    * @protected @abstract
> ```

Same comment for jsdocs


<!-- Sent from Reviewable.io -->

2024-08-27 16:40 UTC, merged