2608 geo core initial settings
Canadian-Geospatial-Platform/GeoView pull request #2651
Opened 2024-12-11 15:05 UTC by MatthewMuehlhauserNRCan

# Description

Added the ability to apply initial settings to GeoCore layers. Only applies to the top most layers currently.

Fixes # 2608

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Test the following configuration in the sandbox map. Only tested visibility, but other properties could work as well, assuming they are valid.

{
"geoviewLayerId": "21b821cf-0f1c-40ee-8925-eab12d357668",
"geoviewLayerType": "geoCore",
'initialSettings': {'states': {'visible': false}}
}

[Sandbox](https://matthewmuehlhausernrcan.github.io/geoview/sandbox.html)

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-12-11 20:44 UTC, jolevesq requested changes
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-ODrS2ZI6tWAPT3BWQOK:-ODrS2ZJAcBHmvfLKkzh:bcn9koi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6607a85f0ddd6d4f20f128e9da42cdec5da80f82/packages/geoview-core/src/geo/layer/other/geocore.ts#L60)):*
> ```XML
>         for (let i = 0; i < response.layers.length; i++) {
>           response.layers[i].initialSettings = { ...response.layers[i].initialSettings, ...layerConfig.initialSettings };
>           // Need to set the initial settings of the LayerConfigs. Only applies to top layers.
> ```

We should be able to apply to any layers?


<!-- Sent from Reviewable.io -->

2025-01-15 15:13 UTC, MatthewMuehlhauserNRCan reviewed
> Reviewed 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-ODrS2ZI6tWAPT3BWQOK:-OGe6XGJ3Asbp93TBaHP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6607a85f0ddd6d4f20f128e9da42cdec5da80f82/packages/geoview-core/src/geo/layer/other/geocore.ts#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should be able to apply to any layers?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-15 16:29 UTC, jolevesq requested changes
> Reviewed 3 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 4 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGempbTC9-mG9g6RG66:-OGempbTC9-mG9g6RG67:bywjylk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/geo/layer/other/geocore.ts#L4)):*
> ```XML
> 
> import { UUIDmapConfigReader } from '@/core/utils/config/reader/uuid-config-reader';
> // import { UUIDmapConfigReader } from '@/api/config/uuid-config-reader';
> ```

Do you need dead import
___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 46 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGekr0K0mvfIuAlSct8:-OGekr0K0mvfIuAlSct9:b-7xqt5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L46)):*
> ```JSON
>                 "hoverable": true,
>                 "legendCollapsed": false,
>                 "opacity": 0.7,
> ```

Can you put .3, .7 is hard to notice
___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelgXX6UKh-TZ5Ouuc:-OGelgXX6UKh-TZ5Ouud:bu7qj7m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L57)):*
> ```JSON
>         "geoviewLayerType": "geoCore",
>         "geoviewLayerId": "03ccfb5c-a06e-43e3-80fd-09d4f8f69703",
>         "initialSettings": {
> ```

Is this section suppose to do something?
___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 71 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelm076QgDkYsl0a2B:-OGelm076QgDkYsl0a2C:b-sov6jd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L71)):*
> ```JSON
>               },
>               "controls": {
>                 "highlight": false,
> ```

The control is disable on layers but not on legend. If it is a quick fix you can do. If not, please create an issue
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 887 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGemErL-u4bcK0rafQZ:-OGemErM16AkKMxKhwYV:b-qr3c89) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L887)):*
> ```XML
>         (layerEntries as TypeGeoviewLayerConfig[]).forEach((geoviewLayerConfig) => {
>           if (layerName !== geoviewLayerConfig.geoviewLayerName) {
>             const tempConfig = geoviewLayerConfig;
> ```

I tested this uuid cf21aa0c-b76c-4f1f-96c1-4ef4b085b647  and set a name. Instead of giving the name to the group it gave it to the first layer

![image.png](https://files.reviewableusercontent.io/images/reviewable/3472990/MrovYaXyul4vdVi2nqu-VbZ-/image.png)
___
*[`packages/geoview-core/src/core/utils/config/config.ts` line 58 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGemUZA74-j70VCh-kB:-OGemUZA74-j70VCh-kC:bu6rg0t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/core/utils/config/config.ts#L58)):*
> ```XML
>         if (mapConfigLayerEntryIsGeoCore(geoviewLayerEntry)) {
>           //  Skip it, because we don't validate the GeoCore configuration anymore. Not the same way as typical GeoView Layer Types at least.
>           // ? Why not do GeoCore request here? Then could easily replace listOfLayerEntries and validate / process along with other layers?
> ```

Put TODO: refactor - so we will track it in the refactor
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 412 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGen4XeCw0t087l2om8:-OGen4XeCw0t087l2om9:b33d2c1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/geo/map/map-schema-types.ts#L412)):*
> ```XML
> 
>   /** The layer entries to use from the GeoCore layer. */
>   listOfLayerEntryConfig?: TypeLayerEntryConfig[];
> ```

This file is depecrated, we should use ma-schema type in api config


<!-- Sent from Reviewable.io -->

2025-01-15 17:47 UTC, DamonU2 approved these changes
> Reviewed 3 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @MatthewMuehlhauserNRCan)



<!-- Sent from Reviewable.io -->

2025-01-15 17:53 UTC, MatthewMuehlhauserNRCan reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 887 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGemErL-u4bcK0rafQZ:-OGf4BGw4N5Qxf_UXowh:b-gqn0zy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L887)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I tested this uuid cf21aa0c-b76c-4f1f-96c1-4ef4b085b647  and set a name. Instead of giving the name to the group it gave it to the first layer

![image.png](https://files.reviewableusercontent.io/images/reviewable/3472990/MrovYaXyul4vdVi2nqu-VbZ-/image.png)
</blockquote></details>

Looking at this, I think it's because of how the layers are handled. There is one layer with two indexes in the layerEntries returned from GeoCore, but there is no Group layer, so the name is applied to the first layer entry and not the created group entry. I'll look a bit closer to see if there's any way I can make the name apply to the group that is created later.
___
*[`packages/geoview-core/src/core/utils/config/config.ts` line 58 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGemUZA74-j70VCh-kB:-OGf2A-r9Qoacyd-trkw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/core/utils/config/config.ts#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put TODO: refactor - so we will track it in the refactor
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 4 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGempbTC9-mG9g6RG66:-OGf1xK20jUNGKUrFnKK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/geo/layer/other/geocore.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you need dead import
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 412 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGen4XeCw0t087l2om8:-OGf1VCp9qmvndUN92cu:bc7hqh9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/geo/map/map-schema-types.ts#L412)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This file is depecrated, we should use ma-schema type in api config
</blockquote></details>

I don't think type GeoCoreLayerConfig exists in the new map-schema-types. I'm guessing it won't be necessary after the refactor? Including this use case.


<!-- Sent from Reviewable.io -->

2025-01-15 17:59 UTC, Alex-NRCan approved these changes
> Reviewed 2 of 5 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 8 unresolved discussions (waiting on @jolevesq and @MatthewMuehlhauserNRCan)



<!-- Sent from Reviewable.io -->

2025-01-15 18:22 UTC, MatthewMuehlhauserNRCan reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 46 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGekr0K0mvfIuAlSct8:-OGfAWrIEBFje0MUvomP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put .3, .7 is hard to notice
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelgXX6UKh-TZ5Ouuc:-OGfAYi55XCsfFibg0uz:bf6uwfc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this section suppose to do something?
</blockquote></details>

I was trying to see if I could get it to highlight from the config, but it didn't seem to work.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 887 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGemErL-u4bcK0rafQZ:-OGfACpDBECTXw_S7emt:b-rvcoe3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L887)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

Looking at this, I think it's because of how the layers are handled. There is one layer with two indexes in the layerEntries returned from GeoCore, but there is no Group layer, so the name is applied to the first layer entry and not the created group entry. I'll look a bit closer to see if there's any way I can make the name apply to the group that is created later.
</blockquote></details>

This should be handled now


<!-- Sent from Reviewable.io -->

2025-01-15 18:31 UTC, jolevesq requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelgXX6UKh-TZ5Ouuc:-OGfCtXm9Lg5jt7isSbQ:b-fp5ss2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L57)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

I was trying to see if I could get it to highlight from the config, but it didn't seem to work.
</blockquote></details>

Can you remove from config if itis not working
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 409 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGfDj8KEOPdtTYT6K6d:-OGfDj8L-fnBnW_PUOOD:b561c6i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9e2d32bb0b4f951479298e0a4d99b9583105914/packages/geoview-core/src/geo/map/map-schema-types.ts#L409)):*
> ```XML
> 
>   /** Initial settings to apply to the GeoCore layer at creation time. */
>   initialSettings?: TypeLayerInitialSettings;
> ```

You said this is not working at the root level. Can we remove from the type file


<!-- Sent from Reviewable.io -->

2025-01-15 18:35 UTC, MatthewMuehlhauserNRCan reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelgXX6UKh-TZ5Ouuc:-OGfEPAK-6c_gwHaAWO1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you remove from config if itis not working
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json` line 71 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGelm076QgDkYsl0a2B:-OGfET5i8Ogv1fRaXkT0:b-2ua5bq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ffef81706060155723581a2f97d1d313ac950115/packages/geoview-core/public/configs/navigator/28-geocore-custom-inline-config.json#L71)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The control is disable on layers but not on legend. If it is a quick fix you can do. If not, please create an issue
</blockquote></details>

This happens with non-geocore layers too, so I'll create an issue.


<!-- Sent from Reviewable.io -->

2025-01-15 18:41 UTC, MatthewMuehlhauserNRCan commented
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 409 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-OGfDj8KEOPdtTYT6K6d:-OGfFB4M-z4nshUz23SN:b-3yjzrq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9e2d32bb0b4f951479298e0a4d99b9583105914/packages/geoview-core/src/geo/map/map-schema-types.ts#L409)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You said this is not working at the root level. Can we remove from the type file
</blockquote></details>

I just tested, it does work at the root level too, but I was testing the controls to see if maybe I needed to set it somewhere else to disable the highlight function, but it didn't seem to matter. I just tested the controls now too, and they seem to work there as well. So I guess it's just the highlight not behaving correctly in the legend.


<!-- Sent from Reviewable.io -->

2025-01-15 18:55 UTC, jolevesq reviewed
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651)* status: all files reviewed, 3 unresolved discussions (waiting on @MatthewMuehlhauserNRCan)



<!-- Sent from Reviewable.io -->

2025-01-15 18:55 UTC, jolevesq approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2651#-:-OGfJaMq0-FtEe6JoV0c:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MatthewMuehlhauserNRCan)



<!-- Sent from Reviewable.io -->

2025-01-15 18:56 UTC, merged