fix(details): Display detail fields when service returns alias instea…
Canadian-Geospatial-Platform/geoview pull request #2658
Opened 2024-12-12 17:35 UTC by DamonU2

…d of field name

Fixes some of #2596, info is displayed properly, but icons are not fixed.

# Description

Fixes issue with some layers returning the field alias instead of the field name when fetching feature properties. Icons remain broken.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/add-layers.html

4baa66ad-aa29-4233-a6a8-7f5cbefb5ea8
8ad80782-d468-44dc-af4f-ddf8ed44ce0a
dbe22a3d-0f34-40f5-a40b-83e68f9c3c37
4efad8d5-b7c7-4ea8-b95c-f41f76f24e63
a88f1437-f93f-42e8-9b44-6cdc2213a172
9edee77a-4cb9-4e64-bb37-c5e66a82108d
0b88062f-ebbe-46c6-ab19-54fd226e9aa7

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-12-12 21:38 UTC, jolevesq requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 587 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658#-ODwnj5Y79waDmbA3kwV:-ODwnj5Y79waDmbA3kwW:bueav8d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e84c5aad82a0d271633a967b31fbf98c31a2597b/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L587)):*
> ```XML
>                 fieldKey: fieldKeyCounter++,
>                 value:
>                   this.getFieldValue(feature, fieldName, fieldEntry!.type as 'string' | 'number' | 'date') ||
> ```

CAn you add a comment why we this ||


<!-- Sent from Reviewable.io -->

2024-12-13 15:32 UTC, DamonU2 reviewed
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 587 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658#-ODwnj5Y79waDmbA3kwV:-OE-dbz18iklC6iSYeBX:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e84c5aad82a0d271633a967b31fbf98c31a2597b/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L587)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you add a comment why we this ||
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-13 15:42 UTC, jolevesq reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-12-13 15:42 UTC, jolevesq approved these changes
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2658)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)



<!-- Sent from Reviewable.io -->

2024-12-13 15:54 UTC, merged