feature(layer-proj) - Better layer projection and extent densification support
Canadian-Geospatial-Platform/geoview pull request #2659
Opened 2024-12-12 21:47 UTC by Alex-NRCan

# Description

- Improves support for layer projections once more.
- Improves extent densification, to make sure the generated extent bbox adequately follows the curvature of the earth.

Fixes #2591

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted Dec 12th @ 17h : https://alex-nrcan.github.io/geoview/add-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

2024-12-12 22:40 UTC, jolevesq requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/projection.ts` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659#-ODx0q8v6ryaknJP0QBi:-ODx0q8v6ryaknJP0QBj:b-synayz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e8136839046fdf9ba1b1dbfa6e6a8204bfaa036d/packages/geoview-core/src/geo/utils/projection.ts#L37)):*
> ```XML
>     LCC: 'EPSG:3978',
>     3979: 'EPSG:3979',
>     102100: 'EPSG:102100', // TODO: Minor - This is technically supposed to be ESRI:102100, but some things would need to change in order to support this, works now
> ```

What do you mean by this comment?


<!-- Sent from Reviewable.io -->

2024-12-13 17:57 UTC, Alex-NRCan reviewed
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/utils/projection.ts` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659#-ODx0q8v6ryaknJP0QBi:-OE08J1g0p_E3B-dgxLC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e8136839046fdf9ba1b1dbfa6e6a8204bfaa036d/packages/geoview-core/src/geo/utils/projection.ts#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What do you mean by this comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-13 18:19 UTC, jolevesq approved these changes
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-12-13 18:49 UTC, jolevesq reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @Alex-NRCan and @DamonU2)



<!-- Sent from Reviewable.io -->

2024-12-13 18:50 UTC, jolevesq approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)



<!-- Sent from Reviewable.io -->

2024-12-13 18:50 UTC, merged