Geo view layers and class hierarchy
Canadian-Geospatial-Platform/GeoView pull request #509
Opened 2022-08-31 03:58 UTC by ychoquet

Let's start with this restructuration!

2022-08-31 13:39 UTC, jolevesq requested changes
> Reviewed 114 of 188 files at r1, 6 of 14 files at r2, 11 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 131 of 197 files reviewed, 28 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`README.md` line 210 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjlI53vd42T99gibf:-NAnjlI53vd42T99gibg:b89aa61) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/README.md#L210)):*
> ```Markdown
>         ]
>       },
>       'suportedLanguages': ['en-CA']
> ```

Should we only keep en (remove -CA) for consistency
___
*[`README.md` line 276 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjj1BCFGS9fAn7jqy:-NAnjj1BCFGS9fAn7jqz:b7zf2ir) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/README.md#L276)):*
> ```Markdown
> 	                  {
> 	                    'index': 6
> 	                  }                  
> ```

Trailing white spaces
___
*[`README.md` line 282 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjtlV59W3xQ9LmzVv:-NAnjtlV59W3xQ9LmzVw:b89aa61) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/README.md#L282)):*
> ```Markdown
> 	          },
> 	          'theme': 'dark',
> 	          'suportedLanguages': ['en-CA']
> ```

Should we only keep en (remove -CA) for consistency
___
*[`docs/app/loading-maps.md` line 74 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnk8C558hheNsMLmef:-NAnk8C558hheNsMLmeg:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/loading-maps.md#L74)):*
> ```Markdown
>   ],
>   "externalPackages": [],
>   "suportedLanguages": ["en-CA", "fr-CA"]
> ```

Same comment for -CA
___
*[`docs/app/loading-maps.md` line 141 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnk6002T5hHcGsawmU:-NAnk6002T5hHcGsawmV:b7zf2ir) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/docs/app/loading-maps.md#L141)):*
> ```Markdown
>                     'corePackages': ['overview-map', 'basemap-switcher', 'layers-panel', 'details-panel', 'geolocator'],
>                     'externalPackages': [],
>                     'languages': ['en-CA', 'fr-CA']                                    
> ```

Trailing white spaces
___
*[`docs/app/loading-maps.md` line 188 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkB0O8OwMfLPnPy-v:-NAnkB0O8OwMfLPnPy-w:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/loading-maps.md#L188)):*
> ```Markdown
>         corePackages: ['overview-map', 'basemap-switcher', 'layers-panel', 'details-panel', 'geolocator'],
>         externalPackages: [],
>         suportedLanguages: ['en-CA', 'fr-CA'],
> ```

Same comment for -CA
___
*[`docs/app/packages.md` line 202 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkDDg6inPKLWJXnY1:-NAnkDDg6inPKLWJXnY2:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/packages.md#L202)):*
> ```Markdown
>         'corePackages': ['details-panel', 'layers-panel', 'basemap-panel', 'overview-map'],
>         'theme': 'dark',
>         'suportedLanguages': ['en-CA']
> ```

Same comment for -CA
___
*[`packages/geoview-basemap-panel/default-config-basemap-panel.json` line 78 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkHLA-nIfCqtDKdVz:-NAnkHLA-nIfCqtDKdW-:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-basemap-panel/default-config-basemap-panel.json#L78)):*
> ```JSON
>     }
>   ],
>   "suportedLanguages": ["en-CA", "fr-CA"]
> ```

Same comment for -CA
___
*[`packages/geoview-core/schema.json` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlij4DDP7ZxQztpem:-NAnlij4DDP7ZxQztpen:b-85io2v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema.json#L2)):*
> ```JSON
> {
>   "$schema": "http://json-schema.org/draft-07/schema#",
> ```

Is this file can be removed?
___
*[`packages/geoview-core/schema-default-config.json` line 27 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlS_R16tce3DTS6Yy:-NAnlS_R16tce3DTS6Yz:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema-default-config.json#L27)):*
> ```JSON
>     "keys": "https://geocore.api.geo.ca"
>   },
>   "suportedLanguages": ["en-CA", "fr-CA"],
> ```

Same comment for -CA
___
*[`packages/geoview-core/schemav2.json` line 1096 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnmRWg6EsvRvSqZpRJ:-NAnmRWg6EsvRvSqZpRK:b-g9gajm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schemav2.json#L1096)):*
> ```JSON
> 
>     "TypeLocalizedLanguages": {
>       "enum": ["en-CA", "fr-CA"],
> ```

Same comment for -CA
___
*[`packages/geoview-core/public/geojson/points.json` line 34 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnnB6R84MwCZcb-znK:-NAnnB6R84MwCZcb-znL:b-sgksx3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/packages/geoview-core/public/geojson/points.json#L34)):*
> ```JSON
>       "geometry": {
>         "type": "Point",
>         "coordinates": [-100, 45]
> ```

Why the minus is removed?
___
*[`packages/geoview-core/public/templates/add-panels.html` line 53 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnnbVJBuj_EslM1vZT:-NAnnbVJBuj_EslM1vZU:b6axj9k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/add-panels.html#L53)):*
> ```HTML
>         'map': {
>           'interaction': 'dynamic',
>           'viewSettings': {
> ```

In schema-default, the property is call view. Here it is viewSettings. What is the good one?
___
*[`packages/geoview-core/public/templates/languages.html` line 53 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAno7qA5Meq21ADZd_J:-NAno7qA5Meq21ADZd_K:bubu8xm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/languages.html#L53)):*
> ```HTML
>         id="LNG1"
>         class="llwp-map"
>         data-lang="en-CA"
> ```

Are we suppose to remove -ca on data-lang in the div element?
___
*[`packages/geoview-core/public/templates/layers.html` line 343 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnoUKIE1kPrcGTHxY0:-NAnoUKIE1kPrcGTHxY1:btzhlsa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/layers.html#L343)):*
> ```HTML
> 
>       <div>
>         <h3 id="HLYR6">6. WFS Layer</h3>
> ```

Layer 6 header is duplicate
___
*[`packages/geoview-core/public/templates/layers.html` line 492 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnocxbDoPV3xODpXpB:-NAnocxbDoPV3xODpXpC:b-66f6s4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/pac [...]

2022-08-31 15:31 UTC, jolevesq requested changes
> Reviewed 56 of 188 files at r1, 5 of 14 files at r2, 3 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 195 of 197 files reviewed, 39 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 182 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoRM8Z70NkNxessiXu:-NAoRM8Z70NkNxessiXv:b3ajtfz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L182)):*
> ```XML
>   private createVectorSource(layerEntry: TypeBaseVectorLayerEntryConfig): VectorSource<Geometry> {
>     // eslint-disable-next-line no-var
>     var vectorSource: VectorSource<Geometry>;
> ```

Why var instead of const or let?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoRmVVA9JeRYVcCAwv:-NAoRmVVA9JeRYVcCAww:b-cxrhjk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L4)):*
> ```XML
> import axios from 'axios';
> 
> import { Icon as StyleIcon } from 'ol/style';
> ```

Question... this is the esri feature layer but I do not see import EsriJSON from 'ol/format/EsriJSON'; Where do you create this object?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 172 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoS35E1v5Q51ywhS74:-NAoS35E1v5Q51ywhS75:bhud6di) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L172)):*
> ```XML
>               height: symbolInfo.symbol.height as number,
>               width: symbolInfo.symbol.width as number,
>               rotation: ((symbolInfo.symbol.angle as number) * Math.PI) / 180.0, // convert to dadians
> ```

Typo dadian
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 187 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoS7Qm5j25q6luxJMk:-NAoS7Qm5j25q6luxJMl:b-j5ymmf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L187)):*
> ```XML
>             src: `data:${symbolInfo.contentType};base64,${symbolInfo.imageData}`,
>             scale: (symbolInfo.height as number) / (symbolInfo.width as number),
>             // anchor: [Math.round((symbolInfo.width as number) / 2), Math.round((symbolInfo.height as number) / 2)],
> ```

Do we still need this line?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 19 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoSLHE547bKk-TwLKM:-NAoSLHE547bKk-TwLKN:b-mfdnht) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L19)):*
> ```XML
> 
> // constant to define default style if not set by renderer
> // TODO: put somewhere to reuse for all vector layers + maybe array so if many layer, we increase the choice
> ```

Good comments, seems this section is duplicated in all vector layer file
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 69 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoSi8NEGX5zROAeJo0:-NAoSi8NEGX5zROAeJo1:b2s0hge) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L69)):*
> ```XML
>  * @returns {Style} the new style with the custom renderer
>  */
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> ```

There no var, is this still needed

Create style from renderer should not be the same for all layer and put in the abstract class?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 112 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoT-2S7gkux41w0zpz:-NAoT-2S7gkux41w0zq-:b-ucld8x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L112)):*
> ```XML
>  * verifyIfLayer parameter is WFS. The type ascention applies only to the true block of the if clause that use this function.
>  *
>  * @param {TypeGeoviewLayerConfig} verifyIfLayer Polymorphic object to test in order to determine if the type ascention is valid
> ```

Can you just explain the difference of those 3 type Gard from a config point of view. Do we have this explanation somewhere to help understand?
___
*[`packages/geoview-core/src/geo/map/map.ts` line 253 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoTeMR1u7JIiclHSN2:-NAoTeMR1u7JIiclHSN3:b-hrfmub) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/map/map.ts#L253)):*
> ```XML
>             ),
>         extent: mapView.extent,
>         // resolution: mapView.resolution,
> ```

Do we need to keep?
___
*[`packages/geoview-core/src/ui/stepper/custom-stepper.tsx` line 1 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoVgJfA2uZFfhWSvJs:-NAoVgJfA2uZFfhWSvJt:b-2qjmi1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/stepper/custom-stepper.tsx#L1)):*
> ```XML
> /* eslint-disable react/require-default-props */
> ```

Why this file as type inside the component and the Snackbar as one file for type and another one for the component?
___
*[`packages/geoview-core/src/ui/text-field/text-field.tsx` line 10 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoWC2XDbbBFZjAIGIk:-NAoWC2XDbbBFZjAIGIl:bafkaa6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/text-field/text-field.tsx#L10)):*
> ```XML
>  */
> // eslint-disable-next-line react/require-default-props
> type TypeTextFieldProps = TextFieldProps & { mapId?: string };
> ```

Sometime you define the the typeProps with extend and here with &.... what is the difference?
___
*[`packages/geoview-core/src/ui/tooltip/tooltip.tsx` line 8 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoWMY19_qchA4WqEes:-NAoWMY19_qchA4WqEet:ba682c8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/tooltip/tooltip.tsx#L8)):*
> ```XML
>  * Custom MUI Tooltip properties
>  */
> interface TypeTooltipProps extends TooltipProps {
> ```

Here extend, file before &, curious to know why


<!-- Sent from Reviewable.io -->

2022-08-31 21:14 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 195 of 197 files reviewed, 39 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`README.md` line 210 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjlI53vd42T99gibf:-NAoA84s7yrvVkepQxVM:b-ppkur2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/README.md#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we only keep en (remove -CA) for consistency
</blockquote></details>

We could. If it is what you want, I can do the changes in the next PR.
___
*[`README.md` line 276 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjj1BCFGS9fAn7jqy:-NAoAO2Q1WDGTfm-yovr:bp6r4tu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/README.md#L276)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

The README.md has not be adjusted to the new schemav2 file. should we adjust it now or in a future PR?
___
*[`README.md` line 282 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjtlV59W3xQ9LmzVv:-NAoB00D44euINRP2_VU:bunxano) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/README.md#L282)):*
> We could. If it is what you want, I can do the changes in the next PR.
___
*[`docs/app/loading-maps.md` line 74 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnk8C558hheNsMLmef:-NAoB4q0A-l3MPGmbfvc:b-ppkur2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/loading-maps.md#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment for -CA
</blockquote></details>

We could. If it is what you want, I can do the changes in the next PR.
___
*[`docs/app/loading-maps.md` line 141 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnk6002T5hHcGsawmU:-NAoBAvEECY1tU-XGpzA:b-rxnlwy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/docs/app/loading-maps.md#L141)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

All ***file.md*** need to be adjusted to the new schema. Should we create an issue on this topic and postpone the work to later?
___
*[`docs/app/loading-maps.md` line 188 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkB0O8OwMfLPnPy-v:-NAoBzS5AIO_gQxx1xCc:b-qu3nwp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/loading-maps.md#L188)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment for -CA
</blockquote></details>

Same comment as before.
___
*[`docs/app/packages.md` line 202 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkDDg6inPKLWJXnY1:-NAoC5ctBRhaPNQkI6Rg:b-qu3nwp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/docs/app/packages.md#L202)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment for -CA
</blockquote></details>

Same comment as before.
___
*[`packages/geoview-basemap-panel/default-config-basemap-panel.json` line 78 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnkHLA-nIfCqtDKdVz:-NAoCEdpAq4Rd8eIDWQB:byfb9qt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-basemap-panel/default-config-basemap-panel.json#L78)):*
> Same comment as before.
___
*[`packages/geoview-core/schema.json` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlij4DDP7ZxQztpem:-NAoCIbU-0s676VYAkCW:b-rr2qxp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema.json#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this file can be removed?
</blockquote></details>

I think we should. The new code can not process it anymore. 
___
*[`packages/geoview-core/schema-default-config.json` line 27 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlS_R16tce3DTS6Yy:-NAoCd0g0f1vraZtu9bq:b-qu3nwp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema-default-config.json#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment for -CA
</blockquote></details>

Same comment as before.
___
*[`packages/geoview-core/schemav2.json` line 1096 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnmRWg6EsvRvSqZpRJ:-NAoCf9YBf1oWiotqBLr:b-qu3nwp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schemav2.json#L1096)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment for -CA
</blockquote></details>

Same comment as before.
___
*[`packages/geoview-core/public/geojson/points.json` line 34 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnnB6R84MwCZcb-znK:-NAoCp_R87jLzCg2dGI2:b-mwz7uo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/packages/geoview-core/public/geojson/points.json#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why the minus is removed?
</blockquote></details>

I can not say. I do not remember removing it. I made the correction. It will be restored in the next PR.
___
*[`packages/geoview-core/public/templates/add-panels.html` line 53 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnnbVJBuj_EslM1vZT:-NAoF-ED6bJgsRSRWnac:bajhxpc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/add-panels.html#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

In schema-default, the property is call view. Here it is viewSettings. What is the good one?
</blockquote></details>

It is viewSettings. The only ***file.html*** that was adjusted to the new code is ***layers.html***. We should create an issue to revise all the ***html*** files and make the corrections needed.
___
*[`packages/geoview-core/public/templates/languages.html` line 53 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAno7qA5Meq21ADZd_J:-NAoFoM64csDORGI5JQI:b54z7s3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/languages.html#L53)):*
> The only ***file.html*** that was adjusted to the new code is ***layers.html***. We should create an issue to revise all the ***html*** files and make the corrections needed.
___
*[`packages/geoview-core/public/templates/layers.html` line 343 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnoUKIE1kPrcGTHxY0:-NAoGXHjE97-xdJ9oJyg:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates [...]

2022-09-01 03:07 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 195 of 197 files reviewed, 38 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoRmVVA9JeRYVcCAwv:-NAqpp8_7lZL1QbV9d_l:b81s5xu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Question... this is the esri feature layer but I do not see import EsriJSON from 'ol/format/EsriJSON'; Where do you create this object?
</blockquote></details>

This behavior is coded in the parent class ***AbstractGeoViewVector*** that is in the ***abstract-geoview-vector.ts*** file.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts` line 187 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoS7Qm5j25q6luxJMk:-NAqqidL-NtQIzMrVGl9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need this line?
</blockquote></details>

Done.



_Code quote:_
```XML
anchor: [Math.round((symbolInfo.width as number) / 2)
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 19 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoSLHE547bKk-TwLKM:-NAqr3MF2vvHvqO_hHRa:b-b9c16f) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Good comments, seems this section is duplicated in all vector layer file
</blockquote></details>

This will be corrected by the renderer work I'm currently doing.



_Code quote:_
```XML
TODO: put somewhere to reuse for all vector layers + maybe array so if man
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 69 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoSi8NEGX5zROAeJo0:-NAqrgdz5fhkjyvPPPHR:b-mb2qrl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L69)):*
> This will be corrected by the renderer work I'm currently doing.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 112 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoT-2S7gkux41w0zpz:-NAqrp_OCc--OV5-3MPk:b-p81b2o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L112)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just explain the difference of those 3 type Gard from a config point of view. Do we have this explanation somewhere to help understand?
</blockquote></details>

I think that we should create an issue related to documenting this topic and some other things like the notion of map features, geoview layer and layer entry configuration.
___
*[`packages/geoview-core/src/geo/map/map.ts` line 253 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoTeMR1u7JIiclHSN2:-NAqsTrmBKQKLXL5OGR6:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/map/map.ts#L253)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need to keep?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/stepper/custom-stepper.tsx` line 1 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoVgJfA2uZFfhWSvJs:-NAqtIcy-Pc7X4GrQn2S:b-tq16ir) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/stepper/custom-stepper.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this file as type inside the component and the Snackbar as one file for type and another one for the component?
</blockquote></details>

I tried to avoid a large proliferation of files by keeping the types in the file they are related to, especially for the ***UI*** part. Most of the time, these types are only used by the ***UI*** code. So, logically, the snackbar types should be in the header of the ***snackbar.tsx*** file. Should we merge the snackbar files?
___
*[`packages/geoview-core/src/ui/text-field/text-field.tsx` line 10 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoWC2XDbbBFZjAIGIk:-NAqwrWF7SAKqLEsOxst:b-dlwl8y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/text-field/text-field.tsx#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Sometime you define the the typeProps with extend and here with &.... what is the difference?
</blockquote></details>

This define the type ***TypeTextFieldProps*** as being a ***TextFieldProps*** and also an object with an optional ***mapId*** attribute of type string. This being said, I'm not sure it is needed in this context. For more information, see [intersection-types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types)
___
*[`packages/geoview-core/src/ui/tooltip/tooltip.tsx` line 8 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoWMY19_qchA4WqEes:-NAr-DBf-NsH13AZcJEJ:bqkv4zd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/tooltip/tooltip.tsx#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Here extend, file before &, curious to know why
</blockquote></details>

Not sure to understand the question. what do you mean by *file before &* ? The extend allows to have a ***mapId*** in the ***TooltipProps*** type defined by ***MUI***.


<!-- Sent from Reviewable.io -->

2022-09-01 14:10 UTC, jolevesq requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 181 of 197 files reviewed, 38 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`README.md` line 210 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjlI53vd42T99gibf:-NAtNvda0avf-JqbuFJo:b570j8p) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/README.md#L210)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

We could. If it is what you want, I can do the changes in the next PR.
</blockquote></details>

Created issues 511 for this


<!-- Sent from Reviewable.io -->

2022-09-01 14:14 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 181 of 197 files reviewed, 37 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`README.md` line 276 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnjj1BCFGS9fAn7jqy:-NAtO3AF8HAn94KjXeJK:b-8wuv4y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c810d2e4cc5733f128194fe550b35b3dd7197be/README.md#L276)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

The README.md has not be adjusted to the new schemav2 file. should we adjust it now or in a future PR?
</blockquote></details>

Futur PR, created issue 512


<!-- Sent from Reviewable.io -->

2022-09-01 14:19 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 181 of 197 files reviewed, 27 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlij4DDP7ZxQztpem:-NAtPSF9AlLP-3L8vVbz:bned0w6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema.json#L2)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

I think we should. The new code can not process it anymore. 
</blockquote></details>

Please remove the file and push a new version
___
*[`packages/geoview-core/public/templates/add-panels.html` line 53 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnnbVJBuj_EslM1vZT:-NAtPs43ChzYeGqbDWvZ:bhuby4z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/public/templates/add-panels.html#L53)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

It is viewSettings. The only ***file.html*** that was adjusted to the new code is ***layers.html***. We should create an issue to revise all the ***html*** files and make the corrections needed.
</blockquote></details>

Created issue 513


<!-- Sent from Reviewable.io -->

2022-09-01 14:23 UTC, jolevesq requested changes
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 182 of 197 files reviewed, 21 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/api.ts` line 8 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAo-6mY2xyafoR66U49:-NAtQnwxAsBLCzTk6Bl2:b-j6u9bs) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/api/api.ts#L8)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

Yes, it is. The first ***plugin*** is a folder that gather all the plugin related files. The second ***plugin*** is the typescript file that contains the plugin code. We have done the same with ***../geo/map/map***.
</blockquote></details>

Perfect


<!-- Sent from Reviewable.io -->

2022-09-01 14:26 UTC, jolevesq requested changes
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 183 of 197 files reviewed, 19 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 119 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAo14Cs48wAoqZHFeTG:-NAtRRlnC2LmPPEnL2Se:blnw5ak) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L119)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

I don't know. If I touched this code, it was only to eliminate error messages. I inserted this question in the file using **// ?**.
</blockquote></details>

Issue 514


<!-- Sent from Reviewable.io -->

2022-09-01 14:35 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 188 of 197 files reviewed, 13 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 102 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAo6muQCQ8MjFF9eQK0:-NAtTT8m1t-FyUtpuGsN:b-bh7uaa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L102)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

Ok, I see. When the layer is not specified, we get a memory error. I think we need to think a little bit before tackling this problem. We should create an issue so that we don't forget it.
</blockquote></details>

issue 516


<!-- Sent from Reviewable.io -->

2022-09-01 14:47 UTC, jolevesq requested changes
> Reviewed 2 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: 190 of 197 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts` line 112 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoT-2S7gkux41w0zpz:-NAtUZ3hBJ11RsvzFWj0:b-p8emfl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts#L112)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

I think that we should create an issue related to documenting this topic and some other things like the notion of map features, geoview layer and layer entry configuration.
</blockquote></details>

Added to issue 512
___
*[`packages/geoview-core/src/ui/stepper/custom-stepper.tsx` line 1 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAoVgJfA2uZFfhWSvJs:-NAtWEVj0CCT1IfWtWho:b-bh7ua9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/ui/stepper/custom-stepper.tsx#L1)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

I tried to avoid a large proliferation of files by keeping the types in the file they are related to, especially for the ***UI*** part. Most of the time, these types are only used by the ***UI*** code. So, logically, the snackbar types should be in the header of the ***snackbar.tsx*** file. Should we merge the snackbar files?
</blockquote></details>

issue 517


<!-- Sent from Reviewable.io -->

2022-09-01 14:56 UTC, jolevesq reviewed
> Reviewed 2 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2022-09-01 15:09 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAnlij4DDP7ZxQztpem:-NAtVabOAdkVJPY0OaDb:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/schema.json#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Please remove the file and push a new version
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 116 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-NAo6UJQ7WibwT-tcOJH:-NAtWlTFAg1bgFwoRHBO:bp5esuz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1a57ac131988fa0f6abb4c2ac15b87d9ce6f64c0/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L116)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I mean when you put `show...' in your request, the layer will be visible by default I think. We should just make sure that is user set visible=false in initialSettings, the show is overwitted
</blockquote></details>

Your right, I will cover this point at the same time I code the renderer.


<!-- Sent from Reviewable.io -->

2022-09-01 15:18 UTC, jolevesq approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/509#-:-NAtcKb6AX2bJBJzG6Am:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)



<!-- Sent from Reviewable.io -->

2022-09-01 15:18 UTC, merged