534 core legend
Canadian-Geospatial-Platform/geoview pull request #599
Opened 2022-10-26 17:37 UTC by dayc-mapdev

Its still forcing legend into a footer tab, but I will look at changing that next

2022-10-26 17:47 UTC, dayc-mapdev commented
Demo site w/ @ychoquet's latest PR => https://dayc-mapdev.github.io/geoview/legend.html

2022-10-26 20:36 UTC, ychoquet requested changes
> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKwIT02wZ6TnGKWMYc:-NFKwIT02wZ6TnGKWMYd:b-fvsb33) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L129)):*
> ```XML
>                   if (styleSettings.styleType === 'classBreaks') {
>                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
>                       return styleInfo.label;
> ```

We have type gard functions named ***isSimpleStyleConfig***, ***isUniqueValueStyleConfig*** and ***isClassBreakStyleConfig*** in ***geoview-core\src\geo\map\map-schema-types.ts*** that perform a type ascention for ***simple***, ***uniqueValue*** and ***classBreaks*** style types. In the CODE QUOTE bellow, when the condition is met, the ***styleSettings*** type is automatically changed to ***TypeClassBreakStyleConfig***.

You can replace the CODE QUOTE with: 
 ***if (isClassBreakStyleConfig(styleSettings) {
&nbsp;&nbsp;&nbsp;&nbsp;const iconLabelList = styleSettings.classBreakStyleInfos.map((styleInfo) => {***



_Code quote:_
```XML
                  if (styleSettings.styleType === 'classBreaks') {
                    const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
```
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 135 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKtk9UC1Hsi5i1-kDN:-NFKtk9UC1Hsi5i1-kDO:b-3d8y04) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L135)):*
> ```XML
>                   if (styleSettings.styleType === 'uniqueValue') {
>                     const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
>                       return styleInfo.label;
> ```

We have a type gard function named ***isUniqueValueStyleConfig*** in ***geoview-core\src\geo\map\map-schema-types.ts*** that perform a type ascention for ***uniqueValue***. When the condition is met, the ***styleSettings*** type is automatically changed to ***TypeUniqueValueStyleConfig***.

You can replace the CODE QUOTE with: 
 ***if (isUniqueValueStyleConfig(styleSettings) {
&nbsp;&nbsp;&nbsp;&nbsp;const iconLabelList = styleSettings.uniqueValueStyleInfo.map((styleInfo) => {***



_Code quote:_
```XML
                  if (styleSettings.styleType === 'uniqueValue') {
                    const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
```
___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFL-0nJ09pSdiRcXKdt:-NFL-0nJ09pSdiRcXKdu:b-vb79tc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/ui/list/list-item.tsx#L15)):*
> ```XML
>     //   color: theme.palette.primary.dark,
>     // },
>   },
> ```

Is this commented section of code temporay or permanent? If it is permanent, we normaly delete it to avoid keeping dead code in the sources. If we need to retrieve the old code, github has it.



_Code quote:_
```XML
    // flexDirection: 'column',
    // padding: 0,
    // color: theme.palette.primary.contrastText,
    // '&:hover': {
    //   backgroundColor: theme.palette.primary.main,
    //   color: theme.palette.primary.dark,
    // },
```


<!-- Sent from Reviewable.io -->

2022-10-26 21:01 UTC, ychoquet requested changes
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFL1iu62XZLxvtKM4_q:-NFL1iu7DH1elW4f2wuf:b-6cnuu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L129)):*
> ```XML
>                   if (styleSettings.styleType === 'classBreaks') {
>                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
>                       return styleInfo.label;
> ```

We have type gard functions named ***isSimpleStyleConfig***, ***isUniqueValueStyleConfig*** and ***isClassBreakStyleConfig*** in ***geoview-core\src\geo\map\map-schema-types.ts*** that perform a type ascention for ***simple***, ***uniqueValue*** and ***classBreaks*** style types. In the following CODE QUOTE, when the condition is met, a type ascention to ***TypeUniqueValueStyleConfig*** is performed on the ***styleSettings*** property.

You can replace the CODE QUOTE with:
***if (isClassBreakStyleConfig(styleSettings) {
&nbsp;&nbsp;&nbsp;&nbsp;const iconLabelList = styleSettings.classBreakStyleInfos.map((styleInfo) => {***



_Code quote:_
```XML
                  if (styleSettings.styleType === 'classBreaks') {
                    const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
```


<!-- Sent from Reviewable.io -->

2022-10-27 12:31 UTC, jolevesq requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: all files reviewed, 18 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/schema.json` line 1096 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOKurg5y23rvWIjpJd:-NFOKurg5y23rvWIjpJe:bwn88lc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/schema.json#L1096)):*
> ```JSON
>       "uniqueItems": true,
>       "items": {
>         "enum": ["app-bar", "nav-bar", "overview-map", "north-arrow", "legend"]
> ```

We will not add legend as a component in the schema. This is something always available when needed
___
*[`packages/geoview-core/public/templates/legend.html` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLzKm8wOtjZQ2UC2F:-NFOLzKm8wOtjZQ2UC2G:b50hk9x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

I see all sample use the footer-tabs. Can you in one of them send the constructed legend component to a custom div on the page instead of the footer-tabs.
___
*[`packages/geoview-core/public/templates/legend.html` line 132 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLmsr6BZ9KbiTiZH7:-NFOLmsr6BZ9KbiTiZH8:b-vr1xy9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L132)):*
> ```HTML
>           },
>           'theme': 'dark',
>           'components': ['legend'],
> ```

Do not use legend in component
___
*[`packages/geoview-core/public/templates/legend.html` line 175 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLkAY7smSNnRV3dua:-NFOLkAY7smSNnRV3dub:b-vr1xy9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L175)):*
> ```HTML
>           },
>           'theme': 'dark',
>           'components': ['legend'],
> ```

Do not use legend in component
___
*[`packages/geoview-core/public/templates/legend.html` line 217 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLg3sCluUe-Oe40fZ:-NFOLg3sCluUe-Oe40f_:b-vr1xy9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L217)):*
> ```HTML
>             ]
>           },
>           'components': ['legend', 'nav-bar'],
> ```

Do not use legend in component
___
*[`packages/geoview-core/public/templates/legend.html` line 295 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLXoj8cOXbNMSU0T4:-NFOLXoj8cOXbNMSU0T5:b357lvr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L295)):*
> ```HTML
>       'components': [
>         'nav-bar',
>         'legend'
> ```

We do not use legend in component
___
*[`packages/geoview-core/public/templates/legend.html` line 307 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLJNb4tNpy1zykmK_:-NFOLJNb4tNpy1zykmKa:bg5katn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L307)):*
> ```HTML
>   <pre id="UC4CS" class="panel"></pre>
> 
>   <!--
> ```

Remove commented piece of code
___
*[`packages/geoview-core/public/templates/legend.html` line 399 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLOJWDhJkw65ZbsUL:-NFOLOJWDhJkw65ZbsUM:b2e33hl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L399)):*
> ```HTML
>   <script src="codedoc.js"></script>
>   <script>
>     function addPolyline(map) {
> ```

Remove unneeded piece of code
___
*[`packages/geoview-core/src/core/components/legend/legend.tsx` line 38 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFON8Fx9qWboI1_tDoL:-NFON8Fx9qWboI1_tDoM:b-mawqht) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend.tsx#L38)):*
> ```XML
>   };
> 
>   const { footerTabs } = api.map(mapId);
> ```

We should not force the component to go to footer-tabs as many component or outside package may want to get the legend item.
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 58 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOK1Z9Ez_zyXUbhWr5:-NFOK1Z9Ez_zyXUbhWr6:b-v76hn0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L58)):*
> ```XML
>   layerConfigEntry?: TypeLayerEntryConfig;
> }
> /**
> ```

Carriage return before comment block
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 66 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOK6ao3e1lsPJyC279:-NFOK6ao3e1lsPJyC27A:b-gi4dc6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L66)):*
> ```XML
>   const { layerId, rootGeoViewLayer, subLayerId, layerConfigEntry } = props;
> 
>   const unknownLayerName = 'Unknown Layer Title';
> ```

Use translation module for text. Text is different in English and French and needs to be stored in the locale i18n files. Let me know if you need help with this.
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 282 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFONkCV-XCNgh-2_1zZ:-NFONkCV-XCNgh-2_1z_:b-5s1m3o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/map/map.tsx#L282)):*
> ```XML
>           {deviceSizeMedUp && components !== undefined && components.indexOf('overview-map') > -1 && <OverviewMap />}
>           {deviceSizeMedUp && <Footerbar />}
>           {deviceSizeMedUp && components !== undefined && components.indexOf('legend') > -1 && <Legend />}
> ```

We will not add Legend here. We will create the ReactElement on the fly when needed.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 987 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFONtaXB2QyhzfdNzgn:-NFONtaXB2QyhzfdNzgo:b-pzasjo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/geo/map/map-schema-types.ts#L987)):*
> ```XML
>  * Core components to initialize on viewer load. Default = ['app-bar', 'nav-bar', 'north-arrow', 'overview-map'].
>  */
> export type TypeMapComponents = Array<'app-bar' | 'nav-bar' | 'north-arrow' | 'overview-map' | 'legend'>;
> ```

No need for legend here
___
*[`packages/geoview-core/src/ui/avatar/index.ts` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOOOtX7nQhUs1U7YOT:-NFOOOtX7nQhUs1U7YOU:b-qt5hse) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/ui/avatar/index.ts#L1)):*
> ```XML
> export * from './avatar';
> ```

To export the avatar, use the index.ts file one level upper where  [...]

2022-10-31 13:49 UTC, dayc-mapdev commented
> Is this commented section of code temporay or permanent? If it is permanent, we normaly delete it to avoid keeping dead code in the sources. If we need to retrieve the old code, github has it.

Permanent, I will delete

2022-10-31 13:52 UTC, dayc-mapdev commented
> > Reviewed 17 of 18 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)_ status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)
> 
> _[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKwIT02wZ6TnGKWMYc:-NFKwIT02wZ6TnGKWMYd:b-fvsb33) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L129)):_
> 
> > ```
> >                   if (styleSettings.styleType === 'classBreaks') {
> >                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
> >                       return styleInfo.label;
> > ```
> 
> We have type gard functions named _**isSimpleStyleConfig**_, _**isUniqueValueStyleConfig**_ and _**isClassBreakStyleConfig**_ in _**geoview-core\src\geo\map\map-schema-types.ts**_ that perform a type ascention for _**simple**_, _**uniqueValue**_ and _**classBreaks**_ style types. In the CODE QUOTE bellow, when the condition is met, the _**styleSettings**_ type is automatically changed to _**TypeClassBreakStyleConfig**_.
> 
> You can replace the CODE QUOTE with: _**if (isClassBreakStyleConfig(styleSettings) {     const iconLabelList = styleSettings.classBreakStyleInfos.map((styleInfo) => {**_
> 
> _Code quote:_
> 
> ```
>                   if (styleSettings.styleType === 'classBreaks') {
>                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
> ```
> 
> _[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 135 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKtk9UC1Hsi5i1-kDN:-NFKtk9UC1Hsi5i1-kDO:b-3d8y04) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L135)):_
> 
> > ```
> >                   if (styleSettings.styleType === 'uniqueValue') {
> >                     const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
> >                       return styleInfo.label;
> > ```
> 
> We have a type gard function named _**isUniqueValueStyleConfig**_ in _**geoview-core\src\geo\map\map-schema-types.ts**_ that perform a type ascention for _**uniqueValue**_. When the condition is met, the _**styleSettings**_ type is automatically changed to _**TypeUniqueValueStyleConfig**_.
> 
> You can replace the CODE QUOTE with: _**if (isUniqueValueStyleConfig(styleSettings) {     const iconLabelList = styleSettings.uniqueValueStyleInfo.map((styleInfo) => {**_
> 
> _Code quote:_
> 
> ```
>                   if (styleSettings.styleType === 'uniqueValue') {
>                     const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
> ```
> 
> _[`packages/geoview-core/src/ui/list/list-item.tsx` line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFL-0nJ09pSdiRcXKdt:-NFL-0nJ09pSdiRcXKdu:b-vb79tc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/ui/list/list-item.tsx#L15)):_
> 
> > ```
> >     //   color: theme.palette.primary.dark,
> >     // },
> >   },
> > ```
> 
> Is this commented section of code temporay or permanent? If it is permanent, we normaly delete it to avoid keeping dead code in the sources. If we need to retrieve the old code, github has it.
> 
> _Code quote:_
> 
> ```
>     // flexDirection: 'column',
>     // padding: 0,
>     // color: theme.palette.primary.contrastText,
>     // '&:hover': {
>     //   backgroundColor: theme.palette.primary.main,
>     //   color: theme.palette.primary.dark,
>     // },
> ```



> > Reviewed 17 of 18 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)_ status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)
> 
> _[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKwIT02wZ6TnGKWMYc:-NFKwIT02wZ6TnGKWMYd:b-fvsb33) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L129)):_
> 
> > ```
> >                   if (styleSettings.styleType === 'classBreaks') {
> >                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
> >                       return styleInfo.label;
> > ```
> 
> We have type gard functions named _**isSimpleStyleConfig**_, _**isUniqueValueStyleConfig**_ and _**isClassBreakStyleConfig**_ in _**geoview-core\src\geo\map\map-schema-types.ts**_ that perform a type ascention for _**simple**_, _**uniqueValue**_ and _**classBreaks**_ style types. In the CODE QUOTE bellow, when the condition is met, the _**styleSettings**_ type is automatically changed to _**TypeClassBreakStyleConfig**_.
> 
> You can replace the CODE QUOTE with: _**if (isClassBreakStyleConfig(styleSettings) {     const iconLabelList = styleSettings.classBreakStyleInfos.map((styleInfo) => {**_
> 
> _Code quote:_
> 
> ```
>                   if (styleSettings.styleType === 'classBreaks') {
>                     const iconLabelList = (styleSettings as TypeClassBreakStyleConfig).classBreakStyleInfos.map((styleInfo) => {
> ```
> 
> _[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 135 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKtk9UC1Hsi5i1-kDN:-NFKtk9UC1Hsi5i1-kDO:b-3d8y04) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L135)):_
> 
> > ```
> >                   if (styleSettings.styleType === 'uniqueValue') {
> >                     const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
> >                       return styleInfo.label;
> > ```
> 
> We have a type gard function named _**isUniqueValueStyleConfig**_ in _**geoview-core\src\geo\map\map-schema-types.ts**_ that perform a type ascention for _**uniqueValue**_. When the condition is met, the _**styleSettings**_ type is automatically changed to _**TypeUniqueValueStyleConfig**_.
> 
> You can replace the CODE QUOTE with: _**if (isUniqueValueStyleConfig(styleSettings) {     const iconLabelList = styleSettings.uniqueValueStyleInfo.map((styleInfo) => {**_
> 
> _Code quote:_
> 
> ```
>                   if (styleSettings.styleType === 'uniqueValue') {
>                     const iconLabelList = (styleSettings as TypeUniqueValueStyleConfig).uniqueValueStyleInfo.map((styleInfo) => {
> ```
> ```

I saw these type guards, but I get an error when I try to use them:
```
plugin.ts:26 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
```

2022-11-01 17:02 UTC, dayc-mapdev reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 17 of 24 files reviewed, 19 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/legend.html` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLzKm8wOtjZQ2UC2F:-NFnnj794fy4q3jGSj-0:b2bp0eo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I see all sample use the footer-tabs. Can you in one of them send the constructed legend component to a custom div on the page instead of the footer-tabs.
</blockquote></details>

One example now uses app panel
___
*[`packages/geoview-core/public/templates/legend.html` line 132 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLmsr6BZ9KbiTiZH7:-NFnoNRoAIbPG_eJ_VlP:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use legend in component
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/legend.html` line 175 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLkAY7smSNnRV3dua:-NFnoOw76x1Mq6vGQv2S:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L175)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use legend in component
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/legend.html` line 217 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLg3sCluUe-Oe40fZ:-NFnoPixEzBYrvhe5idU:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L217)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use legend in component
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/legend.html` line 295 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLXoj8cOXbNMSU0T4:-NFnoQxh6bAuSVibvwlY:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L295)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not use legend in component
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/legend.html` line 307 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLJNb4tNpy1zykmK_:-NFnoSDXEZqc83X4-PpD:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L307)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove commented piece of code
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/legend.html` line 399 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOLOJWDhJkw65ZbsUL:-NFnoSZb4XVmcYWu_1S9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/public/templates/legend.html#L399)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove unneeded piece of code
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend/legend.tsx` line 38 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFON8Fx9qWboI1_tDoL:-NFnoUbFAMMkmuRPnBLj:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend.tsx#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not force the component to go to footer-tabs as many component or outside package may want to get the legend item.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend/legend-api.ts` line 28 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFnnFLz0lyNWl3YIHff:-NFo5WhQ5vQowv-G7SOS:b-8sa3sv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/b3323c8bc8c816e8390f4e58b462e3eec983b9d0/packages/geoview-core/src/core/components/legend/legend-api.ts#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of returning the whole Legend object, can it return the legend-item for the requested layer? It would give more flexibility. Then the Layers-Panel-Package can create the overall legend object by requesting all layers?
</blockquote></details>

I'll do both options. I think I'll need to export ReactDOM so I can create the component with hooks
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 58 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOK1Z9Ez_zyXUbhWr5:-NFnqpwtDsD2d6Rf3BLM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment block
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 66 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOK6ao3e1lsPJyC279:-NFnqrrt9mgWf0fvHYrV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use translation module for text. Text is different in English and French and needs to be stored in the locale i18n files. Let me know if you need help with this.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/list/index.ts` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFOPpD23mAJdgGzQ45f:-NFnr3j0CiBvjcupAxzV:b1zi8w6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/ui/list/index.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I created an issue #517 to standardize the ui component export. You can solve it here or wait until we do it when we solve that issue
</blockquote></details>

I will leave it
___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFL-0nJ09pSdiRcXKdt:-NFnr6ia5OvtU_bZhqw7:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/ui/list/list-item.tsx#L15)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

Is this commented section of code temporay or permanent? If it is permanent, we normaly delete it to avoid keeping dead code in the sources. If we need to retrieve the old code, github has i [...]

2022-11-01 17:15 UTC, jolevesq reviewed
> Reviewed 1 of 8 files at r2, 1 of 6 files at r3, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-core/src/core/components/legend/legend-api.ts` line 28 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFnnFLz0lyNWl3YIHff:-NFo9mIz4Hm9N614tQf2:b-b2lv7u) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/b3323c8bc8c816e8390f4e58b462e3eec983b9d0/packages/geoview-core/src/core/components/legend/legend-api.ts#L28)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

I'll do both options. I think I'll need to export ReactDOM so I can create the component with hooks
</blockquote></details>

You are right, I did this in my PR too (add ReactDOM). 


<!-- Sent from Reviewable.io -->

2022-11-01 18:26 UTC, ychoquet requested changes
> Reviewed 1 of 8 files at r2, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: all files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 135 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFKtk9UC1Hsi5i1-kDN:-NFoQ8yq8N5-HvoekRbi:bx7zd32) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6ac2c5c55199e28c39ee0dd05a3a4e5d4dca4f89/packages/geoview-core/src/core/components/legend/legend-item.tsx#L135)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

I saw these type guards, but I get an error when I try to use them:
```
plugin.ts:26 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
    at Module.isClassBreakStyleConfig (plugin.ts:26:1)
    at Module.isClassBreakStyleConfig (i18n.ts:34:1)
```

</blockquote></details>

I'll try to see why. On my side (in my code) it works seamlessly. I'll checkout your repo for testing.


<!-- Sent from Reviewable.io -->

2022-11-02 15:40 UTC, dayc-mapdev reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 21 of 24 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 179 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFszGCA9GHGxfh2zud9:-NFszGCA9GHGxfh2zudA:bkbix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5e5a5f9807de88c50d9fa8cd219e1c4a5707b346/packages/geoview-core/src/core/components/legend/legend-item.tsx#L179)):*
> ```XML
>   };
> 
>   useEffect(() => {
> ```

This works same the as before, I had some problems using the legend events described below. Need some advice @ychoquet @jolevesq 


<!-- Sent from Reviewable.io -->

2022-11-02 17:19 UTC, ychoquet reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: 21 of 24 files reviewed, 4 unresolved discussions (waiting on @dayc-mapdev and @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 179 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599#-NFszGCA9GHGxfh2zud9:-NFtLUO0DQzocL8gWIt1:bgk8f04) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5e5a5f9807de88c50d9fa8cd219e1c4a5707b346/packages/geoview-core/src/core/components/legend/legend-item.tsx#L179)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

This works same the as before, I had some problems using the legend events described below. Need some advice @ychoquet @jolevesq 
</blockquote></details>

I think the best is to accept the PR as it is now and debug it once your code is entirely integrated to the new base.


<!-- Sent from Reviewable.io -->

2022-11-02 18:31 UTC, ychoquet reviewed
> Reviewed 5 of 8 files at r2, 3 of 6 files at r3, 2 of 5 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: all files reviewed, 4 unresolved discussions (waiting on @dayc-mapdev and @jolevesq)



<!-- Sent from Reviewable.io -->

2022-11-02 19:00 UTC, ychoquet approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)



<!-- Sent from Reviewable.io -->

2022-11-02 19:00 UTC, ychoquet approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)



<!-- Sent from Reviewable.io -->

2022-11-02 19:00 UTC, merged