feat(basemap) add the ability to load more than one basemap for each projection
Canadian-Geospatial-Platform/GeoView pull request #63
Opened 2021-02-04 20:09 UTC by melzeiny1980

closes #49

2021-02-04 20:13 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 56 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSif8SYEY4lMsfqUhab:-MSif8SZ09KMjQSeDqwe:b-qkn4c1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L56)):*
> ```HTML
>                 id="mapWM"
>                 class="llwp-map"
>                 data-leaflet="{ 'name': 'Web Mercator', 'projection': 3857, 'zoom': 4, 'center': [60,-100], 'language': 'en-CA','basemapID':'3857-CBMT','shaded':false,'labeled':true,
> ```

Instead of multiple paramters, It would be better to have one object with parameter inside
```
basemap: {
id: "transport",
label: true,
shaded: true
}
```



<!-- Sent from Reviewable.io -->

2021-02-04 20:45 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 3 files reviewed, 26 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 88 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSih5kF0_8q5kNV3Cu9:-MSih5kF0_8q5kNV3CuA:brhgnjo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L88)):*
> ```HTML
>                 id="mapLCC"
>                 class="llwp-map"
>                 data-leaflet="{ 'name': 'LCC', 'projection': 3978, 'zoom': 12, 'center': [45,-75], 'language': 'fr-CA','basemapID':'3978-SIMPLE','shaded':false,'labeled':true,
> ```

Same thing as above for object
Can you put CBMT with label french and shaded under. Label from CBMt and CBCT should be define by language parameter
___
*[public/index.html, line 111 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSihPSN32z1G3nM9dyw:-MSihPSN32z1G3nM9dyx:bxwinvz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L111)):*
> ```HTML
>                 id="mapLCC"
>                 class="llwp-map"
>                 data-leaflet="{ 'name': 'LCC_SHADED', 'projection': 3978, 'zoom': 12, 'center': [45,-75], 'language': 'fr-CA','basemapID':'3978-SIMPLE','shaded':true,'labeled':true,
> ```

For this map, you can remove what is inside the layers array and use simple as id basemap, no label = false and shaded = true
___
*[src/common/basemap.ts, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSij1LK1xWLILD8iXii:-MSij1LK1xWLILD8iXij:b-1tl611) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L11)):*
> ```XML
> export class Basemap {
>     private language = '';
>     private basemapID='';
> ```

Basemap object type of the interface. Space before and after =
___
*[src/common/basemap.ts, line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiuwvDi0R8ppQSKta:-MSiiuwvDi0R8ppQSKtb:b-4fsa3s) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L15)):*
> ```XML
>     private labeled: boolean;
> 
>     constructor(language: string , basemapID:string , shaded:boolean , labeled:boolean) {
> ```

Receive the object instead. Space after :
___
*[src/common/basemap.ts, line 22 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSijqYX52fAMiyT-yCt:-MSijqYY4-pd-X2_wWfF:b-nzpimb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L22)):*
> ```XML
>     };
> 
>     private lccShadedUrls:Basemapurl[] =   [      
> ```

All the url for all the base should become string element, not array. Because we can mix them up all the way we want we will not group them. The grouping we can do is by projection
```
basemap: {
3978: [{ id: url:}, {id:, url: }],
3857: [{ id: url:}, {id:, url: }]
}

Remove trailing white space

We should have id: transport, simple, shaded (LCC) and transport (WM)

We should then create a function who will construct the basemap array
```

___
*[src/common/basemap.ts, line 40 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiKwO96bppfWDUn5u:-MSiiKwO96bppfWDUn5v:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L40)):*
> ```XML
>     ];
>     // Web Mercator url arrays {'ID', 'WMTS Geometry URL', 'WMTS Label URL'}
>     private wbLabelUrls: Basemapurl[] = [      
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 42 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiJAIASOA7Py-oUxF:-MSiiJAIASOA7Py-oUxG:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L42)):*
> ```XML
>     private wbLabelUrls: Basemapurl[] = [      
>         { 'id': '3857-LBL', 'url':  'https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/xxxx_TXT_3857/MapServer/WMTS/tile/1.0.0/BaseMaps_xxxx_TXT_3857/default/default028mm/{z}/{y}/{x}.jpg' }
>     ];                        
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 44 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiJxQDbN-1gHPia_W:-MSiiJxQDbN-1gHPia_X:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L44)):*
> ```XML
>     ];                        
>     // Web Mercator url arrays {'ID', 'WMTS Geometry URL', 'WMTS Label URL'}
>     private wbShadedUrls: Basemapurl[] = [      
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 57 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSikxAM8NXTlzCjaG12:-MSikxAM8NXTlzCjaG13:b-zcx56o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L57)):*
> ```XML
> 
>     // LCC basemap options
>     private lccParamCBMT: BasemapOptions[] = [
> ```

Should become one function for any projection. It was done this way because at first it was not suppose to have any other basemap or configuration. Because we have this now we should have a function to grab the right basic url from projection value and basemap.id value. The we check if we need to add label, then shaded. It will make this class much more smaller.
___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MSiiGo45U6KdRSd-tBu:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
> ```XML
> 
>     get lccCBMT(): BasemapOptions[] {
>         
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 116 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiC7T2SvySFdOhX4m:-MSiiC7T2SvySFdOhX4n:b-2vyyv6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L116)):*
> ```XML
>             this.lccParamCBMT[1].opacity=0.5;
>         }
>         else{
> ```

Remove empty else condition
___
*[src/common/basemap.ts, line 119 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiBGj7_rZsqxMIW09:-MSiiBGj7_rZsqxMIW0A:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L119)):*
> ```XML
>             
>         }
>         
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 126 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiAes6QBq7woBY_Qn:-MSiiAes6QBq7woBY_Qo:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L126)):*
> ```XML
>                     ? this.lccParamCBMT[2].url=this.lccLabelUrls[0].url.replaceAll('xxxx', 'CBMT')
>                     : this.lccParamCBMT[2].url=this.lccLabelUrls[0].url.replaceAll('xxxx', 'CBCT')
>          
> ```

Remove trailing white space
___
*[src/common/basemap.ts, line 127 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiA1DEEC8kOxX8GFZ:-MSiiA1DEEC8kOxX8GF_:b-7wm6e6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L127)):*
> ```XML
>                     : this.lccParamCBMT[2].url=this.lccLabel [...]

2021-02-04 20:59 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 3 files reviewed, 27 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/common/basemap.ts, line 9 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiprjVDOBBALs3nvPY:-MSiprjVDOBBALs3nvPZ:b-4374b7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L9)):*
> ```XML
>  * @class Basemap
>  */
> export class Basemap {
> ```

Add JSDOC to all interface and fucntion


<!-- Sent from Reviewable.io -->

2021-02-08 13:36 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 4 files reviewed, 35 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 56 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSif8SYEY4lMsfqUhab:-MT0kXXtBMoOW5DkPC6V:biks136) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L56)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of multiple paramters, It would be better to have one object with parameter inside
```
basemap: {
id: "transport",
label: true,
shaded: true
}

</blockquote></details>

You didn't make the object. For the id, it should be: transport, simple or 
___
*[src/common/basemap.ts, line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiuwvDi0R8ppQSKta:-MT0mmml5cfv-rdj_0xS:brvsxzl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Receive the object instead. Space after :
</blockquote></details>

Should receive the basemap configuration object. You do not have to explicitly define all the object component. Just reuse it. 
___
*[src/common/basemap.ts, line 42 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiJAIASOA7Py-oUxF:-MT0n5R27V3bKIzUBLQg:b-g956kd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

The id can be the key. Because you will have it from configuration, you will be able to do basemapSetting[projection] to get all the available basemap. We can even do if it is not an array os basemap but 

basemaps {
3978: {
    transport: url,
    simple: url,
    shaded: url,
   label: url
},
3857: { transport: url, label: url }
}

You access now like basemaps[projection][congif.id]. You now have the url
___
*[src/common/basemap.ts, line 3 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0l9MMDe99xw5EZA8W:-MT0l9MMDe99xw5EZA8X:b1irdjx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L3)):*
> ```XML
> /* eslint-disable lines-between-class-members */
> /**
>  * A class to get a BasemapGroup for a define projection. For the moment, we a  Web Mercator and a LCC basemap.
> ```

Would keep Basemap for class name. Like Layer is the class who works on layers

Typo, we a Web... we have Web ...
___
*[src/common/basemap.ts, line 37 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oAUf9QCzxKF3QOxw:-MT0oAUgEmH2kfhpgOtp:b-6r5wo6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L37)):*
> ```XML
>             basemaps: [
>                 {
>                     id: 'SHADED',
> ```

id = shaded
___
*[src/common/basemap.ts, line 42 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oCPhEnZdouKdZLH0:-MT0oCPhEnZdouKdZLH1:b-rtnzsf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L42)):*
> ```XML
>                 },
>                 {
>                     id: 'LBL',
> ```

id = label
___
*[src/common/basemap.ts, line 47 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oNu7CJERdZrJKKoI:-MT0oNu7CJERdZrJKKoJ:b-z68wev) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L47)):*
> ```XML
>                 },
>                 {
>                     id: 'CBMT',
> ```

id transport
___
*[src/common/basemap.ts, line 52 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oRGnBK9Og9LoRP7U:-MT0oRGnBK9Og9LoRP7V:b-t7ewi6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L52)):*
> ```XML
>                 },
>                 {
>                     id: 'SIMPLE',
> ```

id simple
___
*[src/common/basemap.ts, line 82 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0qhFw6Ol8ilGfeRan:-MT0qhFw6Ol8ilGfeRao:b-dkfkzl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L82)):*
> ```XML
>     };
> 
>     get basemps(): BasemapOptions[] {
> ```

Typo basemps  => basemaps
___
*[src/common/basemap.ts, line 108 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0pCGB1Fp0pv7JmTf9:-MT0pCGB1Fp0pv7JmTfA:b-5ptzn7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L108)):*
> ```XML
>         }
>         basemapgroup.push({
>             id: basemaps.filter((basemap) => basemap.id === this.basemapID)[0]?.id || 'SIMPLE',
> ```

You already have the id from the configuration (transport, simple, shaded, label). Because they can be combine we can have label use more than once so we need to build a unique ID.  The first map of a group is the main basemap then the other one are secondary basemap. The id can be main base - second base e.g.

[ transport, transport-label, transport-shaded]
[shaded, shaded-label]
[simple, simple-shaded, simple-label] ...
___
*[src/common/basemap.ts, line 129 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0qZO73Z6fwVzdPnv8:-MT0qZO73Z6fwVzdPnv9:b-n7isdj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L129)):*
> ```XML
>                       url: basemaps.filter((basemap) => basemap.id === 'LBL')[0].url.replaceAll('xxxx', 'CBCT'),
>                       options: this.basemapConfig,
>                       opacity: 1,
> ```

Do you have to specify opacity: 1, is it not the default value?


<!-- Sent from Reviewable.io -->

2021-02-08 14:50 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 4 files reviewed, 36 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/common/basemap.ts, line 105 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT16iIz6Rh0CN-h7gPz:-MT16iIz6Rh0CN-h7gQ-:bfpp25y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L105)):*
> ```XML
>                 opacity: 1,
>             });
>             mainBasemapOpacity = 0.5;
> ```

0.5 is to low, use .8 or .7 instead


<!-- Sent from Reviewable.io -->

2021-02-09 02:39 UTC, melzeiny1980 reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 4 files reviewed, 36 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 56 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSif8SYEY4lMsfqUhab:-MT38s6C0wcr6_-oCBwX:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L56)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You didn't make the object. For the id, it should be: transport, simple or 
</blockquote></details>

Done.
___
*[public/index.html, line 88 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSih5kF0_8q5kNV3Cu9:-MT3HpaC58897EZlBdwL:b-2fnkdf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same thing as above for object
Can you put CBMT with label french and shaded under. Label from CBMt and CBCT should be define by language parameter
</blockquote></details>

Done. However, we need to have a deeper discussion about the basemap class,  the basemap class constructor misses both Language and Coordinate system id in . which makes it tricky to use the same class in the call in the index.html file. this has been mitigated previously by adding a setter in the map.tsx , which makes  them tightly coupled together. 
___
*[public/index.html, line 111 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSihPSN32z1G3nM9dyw:-MT3K3i68W1x-TeQRFkZ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L111)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For this map, you can remove what is inside the layers array and use simple as id basemap, no label = false and shaded = true
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 9 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiprjVDOBBALs3nvPY:-MT3K79Z0fhPTA_SmZpk:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add JSDOC to all interface and fucntion
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSij1LK1xWLILD8iXii:-MT3LaFk8MzwznIsIVpW:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Basemap object type of the interface. Space before and after =
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiuwvDi0R8ppQSKta:-MT3MC0h5XoZxkzVZYY8:byovluh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should receive the basemap configuration object. You do not have to explicitly define all the object component. Just reuse it. 
</blockquote></details>

language is not part of the configuration , related to how the class is structured
___
*[src/common/basemap.ts, line 22 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSijqYX52fAMiyT-yCt:-MT3MbXV0Qe2caSnQ1gs:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All the url for all the base should become string element, not array. Because we can mix them up all the way we want we will not group them. The grouping we can do is by projection
```
basemap: {
3978: [{ id: url:}, {id:, url: }],
3857: [{ id: url:}, {id:, url: }]
}

Remove trailing white space

We should have id: transport, simple, shaded (LCC) and transport (WM)

We should then create a function who will construct the basemap array
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 40 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiKwO96bppfWDUn5u:-MT3Mce26wk7KmbOBYbe:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT3dj6h2DJh9kmCB490:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 116 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiC7T2SvySFdOhX4m:-MT3dk0353z1XojHx3pl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L116)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove empty else condition
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 119 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiBGj7_rZsqxMIW09:-MT3duGdBHATRWR0GTR5:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L119)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 126 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiAes6QBq7woBY_Qn:-MT3duz9DFr4pC9_zw7t:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L126)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 127 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiA1DEEC8kOxX8GFZ:-MT3dvNU5ZY-lqZS8zLH:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L127)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 143 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSii39nDm7RH0XZ_aNG:-MT3dz2Y3AfiZLKjFoAd:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 144 at r1](https:// [...]

2021-02-09 13:23 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 4 files reviewed, 36 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 42 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiJAIASOA7Py-oUxF:-MT5xKeV7nk9iDYYAbcy:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The id can be the key. Because you will have it from configuration, you will be able to do basemapSetting[projection] to get all the available basemap. We can even do if it is not an array os basemap but 

basemaps {
3978: {
    transport: url,
    simple: url,
    shaded: url,
   label: url
},
3857: { transport: url, label: url }
}

You access now like basemaps[projection][congif.id]. You now have the url
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 44 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiJxQDbN-1gHPia_W:-MT5xMvc-26sqohcan7B:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 57 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSikxAM8NXTlzCjaG12:-MT5xS7jBT902qxQ9Pl-:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should become one function for any projection. It was done this way because at first it was not suppose to have any other basemap or configuration. Because we have this now we should have a function to grab the right basic url from projection value and basemap.id value. The we check if we need to add label, then shaded. It will make this class much more smaller.
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 37 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oAUf9QCzxKF3QOxw:-MT5xTmk7wYOBSkCiz-0:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

id = shaded
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 42 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0oCPhEnZdouKdZLH0:-MT5xUO9AmUks_tVIF31:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

id = label
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 41 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiil3cDuiFMQnhp4JF:-MT5xYvSDcj65U1170B6:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/components/map/map.tsx#L41)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Basemap object type = the interface in basemap.tsx
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiPym9Mns3vYMOQq1:-MT5xWGp2NJ42Lkh_4p3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/components/map/map.tsx#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Pass basemap object not parameters
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 61 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiTyQ9ASXY1mGEJFq:-MT5xWjhC9ujnM5xWL78:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/components/map/map.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here, the whole object
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiia742NEQ7KD2B8HT:-MT5xXyI9NEod360aF9p:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/components/map/map.tsx#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Base opacity should only be applied if shaded is true
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 163 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiihUZEzxjcPlpy5GW:-MT5xYZw59m-tBq0GGyE:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/components/map/map.tsx#L163)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Basemap object
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 13:56 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 0 of 4 files reviewed, 23 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 88 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSih5kF0_8q5kNV3Cu9:-MT5t7gzAT3ewCPgjKbs:bmcq160) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/public/index.html#L88)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done. However, we need to have a deeper discussion about the basemap class,  the basemap class constructor misses both Language and Coordinate system id in . which makes it tricky to use the same class in the call in the index.html file. this has been mitigated previously by adding a setter in the map.tsx , which makes  them tightly coupled together. 
</blockquote></details>

Yes, we should. Before we only passed the language to the class constructor and we had 2 function (one for LCC and one for WB). It was before they decided to add many options and basemaps. Now the basemap class should receive language, projection and basemap config object. From this we only need one function e.g. getBasemap who will use the language, config and projection to get the array of layer to create the basemap-layers.

Shaded should be true
___
*[src/common/basemap.ts, line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiuwvDi0R8ppQSKta:-MT63YJECu04oITSp-Dn:b-sq8roe) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L15)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

language is not part of the configuration , related to how the class is structured
</blockquote></details>

Maybe language and projection should only be pass to the getBasemap function. Maybe even the basemap config. This way the constructor is empty and there is no use a bunch of private const. We only keep the array of basemap and from getBasemap function (language, projection and config) we build everything. This way the class is simple and may be reuse to other purpose later.
___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT6-vCB23Nj9qSi2uX-:b-q5zzur) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Would be a function not a property. Use to be a property because they where no code inside, only returns the basemap value for a projection. Now it is changes, it is a real function. Add JSDOC

Name the function getBasemap
___
*[src/common/basemap.ts, line 3 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0l9MMDe99xw5EZA8W:-MT5ziRD-YP5ZVfYX5L4:briz08n) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L3)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

i considered that, then the array inside it would be basemap.layers ?
</blockquote></details>

The function getBasemap should return the array, You do not need to have basemap.layers. 
___
*[src/common/basemap.ts, line 82 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0qhFw6Ol8ilGfeRan:-MT62Rr7EB5o0WxB3n_c:b-yf2xpy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L82)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we really need this?
___
*[src/common/basemap.ts, line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5ztJa9-1MQA9gMQhB:-MT5ztJa9-1MQA9gMQhC:b-24tt3k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L4)):*
> ```XML
> /**
>  * A class to get a BasemapGroup for a define projection. For the moment, we a  Web Mercator and a LCC basemap.
>  * We intend to have only one basemap per projection to avoid the need of a basemap switcher.
> ```

We should modify the description because it is not true anymore
___
*[src/common/basemap.ts, line 10 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-L8k7zPdpHbsn7j-:-MT6-L8k7zPdpHbsn7j0:b-t7rxc1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L10)):*
> ```XML
>  * @class Basemap
>  */
> /**
> ```

Carriage return between class description and interface description
___
*[src/common/basemap.ts, line 11 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5rxqYCYFzo6kM2HWR:-MT5rxqYCYFzo6kM2HWS:btq66kn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L11)):*
> ```XML
>  */
> /**
>  *basemap basic properties
> ```

Space after *
___
*[src/common/basemap.ts, line 18 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-SMF04regACYOYuf:-MT6-SMF04regACYOYug:b-g2tekp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L18)):*
> ```XML
>     attribution: boolean;
>     noWrap: boolean;
> }
> ```

Carriage return
___
*[src/common/basemap.ts, line 20 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5s19OEalq57r6YX1c:-MT5s19OEalq57r6YX1d:btq66kn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L20)):*
> ```XML
> }
> /**
>  *single basemap layer
> ```

Space after *
___
*[src/common/basemap.ts, line 27 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-UNa8C4a3spWFry6:-MT6-UNa8C4a3spWFry7:b-g2tekp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L27)):*
> ```XML
>     options: BasemapConfig;
>     opacity: number;
> }
> ```

Carriage return
___
*[src/common/basemap.ts, line 29 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5sISg-wGozwnr8KGe:-MT5sISg-wGozwnr8KGf:btq66kn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L29)):*
> ```XML
> }
> /**
>  *Attribution value
> ```

Space after *
___
*[src/common/basemap.ts, line 34 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-XpJ5euJH-1d63gX:-MT6-XpJ5euJH-1d63gY:b-g2tekp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L34)):*
> ```XML
>     'en-CA': string;
>     'fr-CA': string;
> }
> ```

Carriage return
___
*[src/common/basemap.ts, line 36 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5sLGS5mx3Fk9lGJxt:-MT5sLGS5mx3Fk9lGJxu:btq66kn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L36)):*
> ```XML
> }
> /**
>  *basemap constructor properties
> ```

Space after *
___
*[src/common/basemap.ts, line 42 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-_ef-5xZScIZX5oz:-MT6-_ef-5xZScIZX5p-:b-g2tekp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L42)):*
> ```XML
>   [...]

2021-02-09 18:01 UTC, jolevesq requested changes
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 21 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT6xAM1AWS3x7P7pxv1:b-65m55h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would be a function not a property. Use to be a property because they where no code inside, only returns the basemap value for a projection. Now it is changes, it is a real function. Add JSDOC

Name the function getBasemap


</blockquote></details>

Add JSDOC
___
*[src/common/basemap.ts, line 3 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0l9MMDe99xw5EZA8W:-MT6wQ-EBBy2sQ38rzkx:b-qqwg1d) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The function getBasemap should return the array, You do not need to have basemap.layers. 
</blockquote></details>

Typo avaible and viable
___
*[src/common/basemap.ts, line 76 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT62UsgDT1qyCdPhSJ5:-MT6x5qF2LHo47Km4FAZ:b-65m55h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You do not need a reference to this, should only be the output of getBasemap function
</blockquote></details>

Add JSDOC
___
*[src/common/basemap.ts, line 6 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wryA4peOEIvGq3xp:-MT6wryA4peOEIvGq3xq:b-2uygmn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/src/common/basemap.ts#L6)):*
> ```XML
>  * can be filtered by projection (currently only WM and LCC projections are listed,
>  *  in case other projections needed, they need to be added to the list)
>  * * @export
> ```

Just below you shoould the start of the class. The interface should be inside the class
___
*[src/common/map.ts, line 2 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6w7tU5vvXYa25hJXN:-MT6w7tU5vvXYa25hJXO:bwf76kr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L2)):*
> ```XML
> import { LatLngBounds } from 'leaflet';
> ```

Can you put back all removed carriage return
___
*[src/common/map.ts, line 4 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wDR0AGGaSeIAfPQG:-MT6wDR0AGGaSeIAfPQH:b-35aq2x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L4)):*
> ```XML
> 
> import screenfull from 'screenfull';
> ```


carriage return
___
*[src/common/map.ts, line 12 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wF9-64zsCC8sACHO:-MT6wF9-64zsCC8sACHP:bes55j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L12)):*
> ```XML
>     maxZooom: 19,
> };
> ```

carriage return
___
*[src/common/map.ts, line 21 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wFj1-HZqA9e3nFB6:-MT6wFj23UH1b5__xw9M:bes55j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L21)):*
> ```XML
>     maxBoundsViscosity: 0.0,
> };
> ```

carriage return
___
*[src/common/map.ts, line 25 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wGPQ3kpYQ3xCDn-N:-MT6wGPQ3kpYQ3xCDn-O:bes55j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L25)):*
> ```XML
>     return epsgCode === 3978 ? lccMapOptionsParam : wmMapOptionsParam;
> }
> ```

carriage return
___
*[src/common/map.ts, line 33 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wHHJExs5YgFKWIqL:-MT6wHHJExs5YgFKWIqM:bes55j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L33)):*
> ```XML
>     maxBoundsViscosity?: number;
> }
> ```

carriage return


<!-- Sent from Reviewable.io -->

2021-02-09 18:22 UTC, yass0016 requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 22 unresolved discussions (waiting on @melzeiny1980)

___
*[public/index.html, line 109 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT70qOw3IRVJoXquqKM:-MT70qOx6_1ZAnTF4DpA:b-g6xqdc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/public/index.html#L109)):*
> ```HTML
>             <h3>L'Atlas du Canada - Ressources et projets d'énergie propre (RPEP)</h3>
>             <div
>                 id="mapLCC"
> ```

Can you change the map ID? we can't have a duplicate IDs because we make API calls per map using the ID


<!-- Sent from Reviewable.io -->

2021-02-09 18:29 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 22 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 109 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT70qOw3IRVJoXquqKM:-MT71uEz1Fd2cRwwyDc7:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/public/index.html#L109)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Can you change the map ID? we can't have a duplicate IDs because we make API calls per map using the ID
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 15 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiuwvDi0R8ppQSKta:-MT6yrg47MUJ69zFEYYr:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe language and projection should only be pass to the getBasemap function. Maybe even the basemap config. This way the constructor is empty and there is no use a bunch of private const. We only keep the array of basemap and from getBasemap function (language, projection and config) we build everything. This way the class is simple and may be reuse to other purpose later.
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 3 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT0l9MMDe99xw5EZA8W:-MT7-GNa67NEBqQoGdua:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fce226396c9476c06243eded7dc62158c45cd3a2/src/common/basemap.ts#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo avaible and viable
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5ztJa9-1MQA9gMQhB:-MT7-Fbt6_VANhpbdGpm:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should modify the description because it is not true anymore
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 29 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5sISg-wGozwnr8KGe:-MT6ykJj4XH4lrqOVE4T:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after *
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 34 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-XpJ5euJH-1d63gX:-MT6yoFW8Y4DdIi9VDNX:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 36 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5sLGS5mx3Fk9lGJxt:-MT6yorC9Qi9K_sIhIMv:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after *
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 42 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-_ef-5xZScIZX5oz:-MT6yqAPEaqs_Y0Lmc-Q:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 76 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT62UsgDT1qyCdPhSJ5:-MT6zCggCPygttgqkvS3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add JSDOC
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 18:29 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 22 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 10 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-L8k7zPdpHbsn7j-:-MT72XjsDl2pRP-eFbTm:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return between class description and interface description
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 11 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5rxqYCYFzo6kM2HWR:-MT72Vc_1mvonO6npCkl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after *
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 18 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-SMF04regACYOYuf:-MT72Y-32g9eXDOjP9Tg:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 20 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT5s19OEalq57r6YX1c:-MT72WES0jS0ABw2no6s:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after *
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 27 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6-UNa8C4a3spWFry6:-MT72YQL3vuF_34XSKEq:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8191360dc853db016111009643d3b5d2e4a8d8f8/src/common/basemap.ts#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 2 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6w7tU5vvXYa25hJXN:-MT72_FfEdgJWCre55pz:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put back all removed carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 4 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wDR0AGGaSeIAfPQG:-MT72_YZ3F7vaD-RQZRl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 12 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wF9-64zsCC8sACHO:-MT72a029me15Km4rbu3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 21 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wFj1-HZqA9e3nFB6:-MT72aEl16o6yLhTY6qy:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 25 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wGPQ3kpYQ3xCDn-N:-MT72a_36MWyLqqqmosU:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

carriage return
</blockquote></details>

Done.
___
*[src/common/map.ts, line 33 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wHHJExs5YgFKWIqL:-MT72aoBDkvMMCmOKYVj:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e43fc37b39de129bc49008a1bee6f2c6e77cadd1/src/common/map.ts#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

carriage return
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 18:37 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 22 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 6 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wryA4peOEIvGq3xp:-MT73qEk01_4oI65rsWn:b-rl851y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/src/common/basemap.ts#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Just below you shoould the start of the class. The interface should be inside the class
</blockquote></details>

according  to my understanding , in order to move the interface inside the class , i need to declare a name space to put it under. which is not recommended in typescript  do you want me to do that? 


<!-- Sent from Reviewable.io -->

2021-02-09 19:09 UTC, jolevesq requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jolevesq, @melzeiny1980, @return, and @yass0016)

___
*[public/index.html, line 109 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT70qOw3IRVJoXquqKM:-MT7B_Ti-Ktg5aoCBg39:b91rjk6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/public/index.html#L109)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should change this basemap, not the second one. The second is already used in part of the code. The third one, the one you will add needs a different id
___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT7AItMDhubraiBXB9F:btcznpr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add JSDOC
</blockquote></details>

For JSDOC

/**
 * Build basemap ...
 *
 * @param {string} language the language for the map
 * @param {number} csrID the projection id
 * @return {BasemapLayer[]} basemapLayers the array of basemap layer
 */
___
*[src/common/basemap.ts, line 6 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT6wryA4peOEIvGq3xp:-MT79OmMEXEfWrNjnL5a:bw4nf7x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/src/common/basemap.ts#L6)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

according  to my understanding , in order to move the interface inside the class , i need to declare a name space to put it under. which is not recommended in typescript  do you want me to do that? 
</blockquote></details>

Ok, Let like this
___
*[src/common/basemap.ts, line 101 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7A6m60B17nw0tedYf:-MT7A6m60B17nw0tedYg:b-aji36o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L101)):*
> ```XML
>         const basemapLayers: BasemapLayer[] = [];
>         let mainBasemapOpacity = 1;
>         if (this.basemapOptions.shaded !== false) {
> ```

Put carriage return before and after if statement
___
*[src/common/basemap.ts, line 116 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7ADS3AfAIMQQPslco:-MT7ADS3AfAIMQQPslcp:bcuhysz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L116)):*
> ```XML
>             opacity: mainBasemapOpacity,
>         });
>         if (this.basemapOptions.labeled !== false) {
> ```

Put carriage return before if statement
___
*[src/common/basemap.ts, line 132 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7AGPtDAlBgkoYHhwB:-MT7AGPtDAlBgkoYHhwC:bckpcue) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L132)):*
> ```XML
>                   });
>         }
>         return basemapLayers;
> ```

Put carriage return before return statement


<!-- Sent from Reviewable.io -->

2021-02-09 19:16 UTC, melzeiny1980 reviewed
> Dismissed @jolevesq from a discussion.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 109 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT70qOw3IRVJoXquqKM:-MT7CPgY1GfBO7wAeY-d:bwgo259) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51b23bf4c054e4f4651d6e1fee902ce638fcf9df/public/index.html#L109)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should change this basemap, not the second one. The second is already used in part of the code. The third one, the one you will add needs a different id
</blockquote></details>

sorry , i actually thought i was changing the 3rd one , but since i removed all the layers i keep missing it for the second map
___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT7Csna12WnziFuvF6k:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For JSDOC

/**
 * Build basemap ...
 *
 * @param {string} language the language for the map
 * @param {number} csrID the projection id
 * @return {BasemapLayer[]} basemapLayers the array of basemap layer
 */
</blockquote></details>

Done
___
*[src/common/basemap.ts, line 101 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7A6m60B17nw0tedYf:-MT7D7PvCsm72qhP6Vp7:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L101)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put carriage return before and after if statement
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 116 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7ADS3AfAIMQQPslco:-MT7D7uq--jTTvebD35E:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L116)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put carriage return before if statement
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 132 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7AGPtDAlBgkoYHhwB:-MT7DFwq-h4SvdH4Zg5V:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6f9d238682745208524b846aa34e92ec9b8768c1/src/common/basemap.ts#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put carriage return before return statement
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 19:26 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT7F30Q8SizOp6UIHib:b15ie8q) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done
</blockquote></details>

Have you deploy this new code? Should not work.....  I think you copy paste my comment but in my comment, * was replace by Reviewable by a bullet. The comment is not good anymore. Plus I start description just to show you. You should keep the description you have
___
*[src/common/basemap.ts, line 9 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EyIZ-QpdcniIi5Rd:-MT7EyIZ-QpdcniIi5Re:bebe2h3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L9)):*
> ```XML
>  * @class Basemap
>  */
> /**
> ```

Carriage return before comment
___
*[src/common/basemap.ts, line 51 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EqWVCOOdNA5fX66X:-MT7EqWVCOOdNA5fX66Y:bhmfsy4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L51)):*
> ```XML
> export class Basemap {
>     private basemapOptions: BasemapOptions;
>     /**
> ```

Carriage return before comments
___
*[src/common/basemap.ts, line 141 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EhDo2hs7qBwVtqEN:-MT7EhDo2hs7qBwVtqEO:b6xn2mg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L141)):*
> ```XML
>         return basemapLayers;
>     }
>     /**
> ```

Carriage return between functions - interface - property


<!-- Sent from Reviewable.io -->

2021-02-09 19:40 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/basemap.ts, line 108 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MSiiGo45U6KdRSd-tBt:-MT7G0Ok-gn9kfCzyPtT:b-j5hchn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0ea6527a407e37c12826d85addc2753e4d2bf2c0/src/common/basemap.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Have you deploy this new code? Should not work.....  I think you copy paste my comment but in my comment, * was replace by Reviewable by a bullet. The comment is not good anymore. Plus I start description just to show you. You should keep the description you have
</blockquote></details>

i removed the bullets, as for my original comment it is was build map using language and projection which seemed moot since they are listed as parameters right after
___
*[src/common/basemap.ts, line 9 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EyIZ-QpdcniIi5Rd:-MT7HGe-88U_rqBLn34C:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comment
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 51 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EqWVCOOdNA5fX66X:-MT7HFYW49qRoW3RlljB:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return before comments
</blockquote></details>

Done.
___
*[src/common/basemap.ts, line 141 at r6](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-MT7EhDo2hs7qBwVtqEN:-MT7Ikeg9AJFl9VaYHIW:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/f531a39ea9c485b4b44be5a0521b9658332cfdb6/src/common/basemap.ts#L141)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return between functions - interface - property
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 20:20 UTC, jolevesq reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)



<!-- Sent from Reviewable.io -->

2021-02-09 20:20 UTC, jolevesq approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63#-:-MT7RzJz-10Qwj5Kt950:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yass0016)



<!-- Sent from Reviewable.io -->

2021-02-09 20:22 UTC, yass0016 approved these changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-09 20:24 UTC, merged