69samplepagestartup
Canadian-Geospatial-Platform/GeoView pull request #79
Opened 2021-02-15 14:50 UTC by melzeiny1980

creating startup with one use case page

2021-02-15 15:05 UTC, jolevesq requested changes
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaAiMa9IsrW21Nykha:bduj0sg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
> ```JavaScript
> const path = require('path');
> const HtmlWebpackPlugin = require('html-webpack-plugin');
> const CopyPlugin = require('copy-webpack-plugin');
> ```

Start with lower case letter
___
*[webpack.common.js, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAoeT940S8VjTsgdN:-MTaAoeT940S8VjTsgdO:b51elpy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L54)):*
> ```JavaScript
>             scriptLoading: 'blocking',
>         }),
>         new HtmlWebpackPlugin({
> ```

You should use wildcard so we do not have to modify this file every time we add a new sample page
___
*[public/index.html, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaB7sO6Gb2aKWMfX_v:-MTaB7sP0KAFQXB7027w:byugnga) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c247ad55b0c3b6c48b14b3ef1928e84f8da6852b/public/index.html#L6)):*
> ```HTML
>         <meta charset="UTF-8" />
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
> ```

You should keep the title, if not it uses the url
___
*[public/index.html, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBEgO57UR9IaQOLfy:-MTaBEgO57UR9IaQOLfz:by36jzc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L11)):*
> ```HTML
> <div style="text-align: left;margin: 0 auto;">
> <table cellpadding="1" cellspacing="1" style="width:1180px; margin:auto;">
> 	<tbody>
> ```

Do not use tab, use spaces... check whole file
___
*[public/index.html, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBSbg4bnRvLqiHPeB:-MTaBSbg4bnRvLqiHPeC:bdg7med) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L13)):*
> ```HTML
> 	<tbody>
> 		<tr>
> 			<td style="width:186px"><img alt="logo" src="./img/Logo.png" style="height:120px; width: 120px; text-align: center;" /></td>
> ```

For this index file only, put the logo bigger and center
___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBKub1wBkrnYF0WvI:-MTaBKub1wBkrnYF0WvJ:b-uqcd9a) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L14)):*
> ```HTML
> 		<tr>
> 			<td style="width:186px"><img alt="logo" src="./img/Logo.png" style="height:120px; width: 120px; text-align: center;" /></td>
> 			<td style="width:979px">
> ```

Do not use inline style, use a style block on top
___
*[public/index.html, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBXNk7G-CPJzjC24E:-MTaBXNk7G-CPJzjC24F:bd9e6wr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L16)):*
> ```HTML
> 			<td style="width:979px">
> 			<h1>&nbsp;</h1>
> 			<h1><strong>Plateforme Géospatiale Canadienne (PGC) / Canadian Geospatial Platform (CGP)</strong></h1>
> ```

Put the French and English title on their own line center above the logo
___
*[public/index.html, line 17 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBdjw4Bjle_nYOtrW:-MTaBdjw4Bjle_nYOtrX:b-bxcofs) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L17)):*
> ```HTML
> 			<h1>&nbsp;</h1>
> 			<h1><strong>Plateforme Géospatiale Canadienne (PGC) / Canadian Geospatial Platform (CGP)</strong></h1>
>             <h1><strong>GeoView project</strong></h1>
> ```

Put this center below the logo
___
*[public/templates/usecases.html, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCA9mDB2EjgN2GrX4:-MTaCA9mDB2EjgN2GrX5:b-3k15dw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L6)):*
> ```HTML
>         <meta charset="UTF-8" />
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title>GeoView</title>
> ```

Should be page title
___
*[public/templates/usecases.html, line 46 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCFJH3yApEtNpG-Zq:-MTaCFJH3yApEtNpG-Zr:bljm7j1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L46)):*
> ```HTML
>             }
> 
>             body{         
> ```

Trailing white spaces... /use prettier to reformat the file as there is many trailing white spaces
___
*[public/templates/usecases.html, line 53 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCRfu-7DiD00iUOT8:-MTaCRfu-7DiD00iUOT9:b-vvqotd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L53)):*
> ```HTML
>     </head>
>     <body>
>         <div style="text-align: left;margin: 0 auto;">
> ```

Do not use inline style, put style at the top with classes
___
*[public/templates/usecases.html, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCa1bEUwvaaLVlTLT:-MTaCa1bEUwvaaLVlTLU:bf4vcnq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L87)):*
> ```HTML
>                 id="UC1"
>                 class="llwp-map"
>                 data-leaflet="{ 'name': 'LCC', 'projection': 3978, 'zoom': 4, 'center': [60,-100], 'language': 'fr-CA', 'basemapOptions':{'id':'transport','shaded':true,'labeled':true} ,  
> ```

Space after : and after and before { }
Space after ,

Check syntax for the whole file
___
*[public/templates/usecases.html, line 103 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaDFpb4vdQdQ-MZ0-l:-MTaDFpb4vdQdQ-MZ0-m:bvj30uc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L103)):*
> ```HTML
>             <p> <strong>Code Snippet:</strong> </p>
>             <div class="panel">
>             function addPolyline(map) {<br>
> ```

Would it be a better way to create those config snippet?
___
*[public/templates/usecases.html, line 248 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaD10KCITKg86S4Wya:-MTaD10KCITKg86S4Wyb:b-8pa3se) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L248)):*
> ```HTML
>                 console.log('api is ready');
>                 addPolygon('UC1');
>                 });
> ```

Cehck indentation
___
*[public/templates/usecases.html, line 249 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaD3vb4LLUM6PV8LN9:-MTaD3vb4LLUM6PV8LNA:bco1vgc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L249)):*
> ```HTML
>                 addPolygon('UC1');
>                [...]

2021-02-15 15:24 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaG15W72gaT_PFAnA_:bj69v6z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Start with lower case letter
</blockquote></details>

my understanding that this is type , thus it should be pascal case , no ? actually when i tried to change it to a camel case i got an prettier violation 
"A constructor name should not start with a lowercase letter.eslintnew-cap"


<!-- Sent from Reviewable.io -->

2021-02-15 15:34 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 14 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaJter9CcahICEo5Ct:bhdbb9i) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

my understanding that this is type , thus it should be pascal case , no ? actually when i tried to change it to a camel case i got an prettier violation 
"A constructor name should not start with a lowercase letter.eslintnew-cap"


</blockquote></details>

Ok, my bad


<!-- Sent from Reviewable.io -->

2021-02-15 15:44 UTC, melzeiny1980 commented
___
*[public/index.html, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaB7sO6Gb2aKWMfX_v:-MTaIC_u4zcJJp-K1uZO:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c247ad55b0c3b6c48b14b3ef1928e84f8da6852b/public/index.html#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should keep the title, if not it uses the url
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 15:49 UTC, yass0016 requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaI57zEUG4xMOzTLmM:bonal8i) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
> ```
> copy-webpack-plugin
> ```
it's better to be renamed to CopyWebpackPlugin to follow convention 
___
*[webpack.common.js, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaN0QC4vN0t70tXjJh:-MTaN0QC4vN0t70tXjJi:b-urw0ut) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L74)):*
> ```JavaScript
>                 { from: './public/locales', to: 'locales' },
>                 { from: './public/locales', to: 'css' },
>                 { from: './public/locales', to: 'geojson' },
> ```

why do you copy locals to css and geojson?


<!-- Sent from Reviewable.io -->

2021-02-15 15:56 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaN0QC4vN0t70tXjJh:-MTaP33rEweFZ9_QjkR6:b-74b9ww) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L74)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

why do you copy locals to css and geojson?
</blockquote></details>

this way i do not have to manually copy them to the dist folder


<!-- Sent from Reviewable.io -->

2021-02-15 15:58 UTC, yass0016 requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[webpack.common.js, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaN0QC4vN0t70tXjJh:-MTaPRhUBJx26Xpu5G4d:beecn0k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L74)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

this way i do not have to manually copy them to the dist folder
</blockquote></details>

no I mean should it not be public/css to css and public/geojson to geojson?


<!-- Sent from Reviewable.io -->

2021-02-15 15:59 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaPbSQCheHpsXiWVMW:b-yu7y27) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

> ```
> copy-webpack-plugin
> ```
it's better to be renamed to CopyWebpackPlugin to follow convention 
</blockquote></details>

i do not understand ? this is the name coming node module 
module "C:/Users/Mazen Elzeiny/AppData/Local/Microsoft/TypeScript/4.1/node_modules/@types/copy-webpack-plugin/index"


<!-- Sent from Reviewable.io -->

2021-02-15 16:01 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaN0QC4vN0t70tXjJh:-MTaQ-pF99UQYjsBkbnS:b-k3b5xu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L74)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

no I mean should it not be public/css to css and public/geojson to geojson?
</blockquote></details>

you are right , i do not understand how did this happen! i already changed it and tested it for each folder


<!-- Sent from Reviewable.io -->

2021-02-15 16:01 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaN0QC4vN0t70tXjJh:-MTaQFHn2WNal039QjlE:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L74)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

you are right , i do not understand how did this happen! i already changed it and tested it for each folder
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 16:02 UTC, melzeiny1980 commented
___
*[public/index.html, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBEgO57UR9IaQOLfy:-MTaN7894vjqK7F7KOs5:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use tab, use spaces... check whole file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 16:06 UTC, yass0016 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaRI0S5H7jcWaVT28X:b-hpb1ea) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
> ```
> const CopyPlugin = require('copy-webpack-plugin');
> ```
const CopyWebpackPlugin = require('copy-webpack-plugin');


<!-- Sent from Reviewable.io -->

2021-02-15 16:19 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAiMa9IsrW21Nykh_:-MTaUGMl8VcYFGzcZggn:bipt4mi) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L6)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

> ```
> const CopyPlugin = require('copy-webpack-plugin');
> ```
const CopyWebpackPlugin = require('copy-webpack-plugin');
</blockquote></details>

sorry i misunderstood. sure


<!-- Sent from Reviewable.io -->

2021-02-15 17:47 UTC, melzeiny1980 commented
___
*[public/templates/usecases.html, line 103 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaDFpb4vdQdQ-MZ0-l:-MTanPIn3ST-3ekTLixV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would it be a better way to create those config snippet?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 18:37 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAoeT940S8VjTsgdN:-MTayc6rCzKg6NfDWKR-:b7amafy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should use wildcard so we do not have to modify this file every time we add a new sample page
</blockquote></details>

can't think of a way to do this off the top of my head. the typical use of the htmlwebpack plugin requires the file name and the chunk of code to be injected. it might need more time to look at


<!-- Sent from Reviewable.io -->

2021-02-15 18:44 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBSbg4bnRvLqiHPeB:-MTaUeCp3WubD13eQCBK:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For this index file only, put the logo bigger and center
</blockquote></details>

Done.
___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBKub1wBkrnYF0WvI:-MTaUgaH9MjfguZZVbaR:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use inline style, use a style block on top
</blockquote></details>

Done.
___
*[public/index.html, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBXNk7G-CPJzjC24E:-MTaUq2gAZBJ_Av59ah5:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put the French and English title on their own line center above the logo
</blockquote></details>

Done.
___
*[public/index.html, line 17 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBdjw4Bjle_nYOtrW:-MTaWEThECK6UQUrS90k:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this center below the logo
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCA9mDB2EjgN2GrX4:-MTaWT01ABcqCP45IVce:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be page title
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 46 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCFJH3yApEtNpG-Zq:-MTaYrg5EmmsasECRHni:bb7f2mf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces... /use prettier to reformat the file as there is many trailing white spaces
</blockquote></details>

done
___
*[public/templates/usecases.html, line 53 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCRfu-7DiD00iUOT8:-MTaqvN_7jXR195mXMct:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not use inline style, put style at the top with classes
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCa1bEUwvaaLVlTLT:-MTanOXr95MMe_ta1z5-:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after : and after and before { }
Space after ,

Check syntax for the whole file
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 248 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaD10KCITKg86S4Wya:-MTaqwmd3TWv03JsPO9E:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L248)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Cehck indentation
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 249 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaD3vb4LLUM6PV8LN9:-MTaqxA87aE16LSpfbyl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L249)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank lines
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 19:48 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 17 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaBdjw4Bjle_nYOtrW:-MTbD3pm8ApcvlsenU4b:b-4nf6bt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/index.html#L17)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you put it below the logo
___
*[public/index.html, line 36 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDE6S2Dq02f2YYWAS:-MTbDE6S2Dq02f2YYWAT:by9bn3z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L36)):*
> ```HTML
>             <img class="center logo" alt="logo" src="./img/Logo.png" />
>         </tr>
>             <h3>Accessing map center from outside of the core viewer using api event listeners</h3>
> ```

Remove this line
___
*[public/index.html, line 37 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDHVj9IBXEa2uUELr:-MTbDHVj9IBXEa2uUELs:by9bn3z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L37)):*
> ```HTML
>         </tr>
>             <h3>Accessing map center from outside of the core viewer using api event listeners</h3>
>             <h3>L'Atlas du Canada - Ressources et projets d'énergie propre (RPEP)</h3>
> ```

Remove this line
___
*[public/index.html, line 39 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDJcW237r7j-OJPU9:-MTbDJcW237r7j-OJPUA:bn473ot) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L39)):*
> ```HTML
>             <h3>L'Atlas du Canada - Ressources et projets d'énergie propre (RPEP)</h3>
>         <tr>
>             <td><a href="./usecases.html">Use Cases</a></td>
> ```

Apply left margin (40px)
___
*[public/templates/usecases.html, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCa1bEUwvaaLVlTLT:-MTbDjym8wQ6-eg8VLgc:brr4dm8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L87)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Trailing white space


<!-- Sent from Reviewable.io -->

2021-02-15 20:59 UTC, melzeiny1980 commented
___
*[webpack.common.js, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaAoeT940S8VjTsgdN:-MTbU8F-DCKGJznjDKus:bh61sdb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/webpack.common.js#L54)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

can't think of a way to do this off the top of my head. the typical use of the htmlwebpack plugin requires the file name and the chunk of code to be injected. it might need more time to look at
</blockquote></details>

Done. Thanks to Saleh , got the code to generate the html file . then added some code to create the file names from the template folder


<!-- Sent from Reviewable.io -->

2021-02-15 21:15 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 36 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDE6S2Dq02f2YYWAS:-MTbXawu54WDp5jKxcks:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove this line
</blockquote></details>

Done.
___
*[public/index.html, line 37 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDHVj9IBXEa2uUELr:-MTbXaiu93Ow0UhImqP4:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove this line
</blockquote></details>

Done.
___
*[public/index.html, line 39 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTbDJcW237r7j-OJPU9:-MTbXaRC-ENxjGQm7iq7:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/335f7462460703e94fd59b1f60c890fc830bfc86/public/index.html#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Apply left margin (40px)
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTaCa1bEUwvaaLVlTLT:-MTbY-O176Sqol88h2bJ:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0855e725dbf550763babdb59524add831ff7d1d8/public/templates/usecases.html#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white space
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-02-15 21:32 UTC, jolevesq reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[webpack.common.js, line 10 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTb_oh9AmQHj1D3jf1y:-MTb_oh9AmQHj1D3jf1z:b4h0qv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2bf6cd04f7bc6c59343acc3b8676d527fb9bf7e2/webpack.common.js#L10)):*
> ```JavaScript
> const glob = require('glob');
> const package = require('./package.json');
> // get version numbers and the hash of the current commit
> ```

Need a carriage return before a comment
___
*[webpack.common.js, line 13 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTba7dI-vT6wTtFLGVn:-MTba7dI-vT6wTtFLGVo:b-f8oir6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2bf6cd04f7bc6c59343acc3b8676d527fb9bf7e2/webpack.common.js#L13)):*
> ```JavaScript
> const [major, minor, patch] = package.version.split('.');
> const hash = JSON.stringify(childProcess.execSync('git rev-parse HEAD').toString().trim());
> const multipleHtmlPlugins = glob.sync('./public/templates/*.html').map((name) => {
> ```

Here, you put your const inside a group of const and the console that shows version

It should be in is own block separate by carriage return 

We will push like this, next issue will still be on sample page, you may do the modification at this time. Please take a note.


<!-- Sent from Reviewable.io -->

2021-02-16 14:09 UTC, jolevesq requested changes
Don't know why but we have lost favicon

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-:-MTfA7qT1X-qGx9tdB67:b-g8tnhn)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 24 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTf9TKk3Kz550-mt6RT:-MTf9TKk3Kz550-mt6RU:brr4dm8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2feb8f0a8a142d7dfc764b474d2fac7da4389dc2/public/index.html#L24)):*
> ```HTML
>                             margin-left: 80px;
>                     }
>                     
> ```

Trailing white space
___
*[public/index.html, line 28 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTf9dcd1yjMFrDt2pMC:-MTf9dcd1yjMFrDt2pMD:bhkyf8k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2feb8f0a8a142d7dfc764b474d2fac7da4389dc2/public/index.html#L28)):*
> ```HTML
>     </head>
>     <body>
> <div style="text-align: left;margin: 0 auto;">
> ```

No inline style


<!-- Sent from Reviewable.io -->

2021-02-16 14:38 UTC, melzeiny1980 reviewed
my bad, i was testing the build for the HTML webpack , so i deleted the dist folder and used the newly generated one. which is missing the icon since it is the only artifact now that needs to placed manually 

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-:-MTfGThPBzY8NzItO3pZ:bt1o7j3)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)



<!-- Sent from Reviewable.io -->

2021-02-16 14:38 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 24 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTf9TKk3Kz550-mt6RT:-MTfGu3mEsuzW7ZOnjJ9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2feb8f0a8a142d7dfc764b474d2fac7da4389dc2/public/index.html#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white space
</blockquote></details>

Done.
___
*[public/index.html, line 28 at r5](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTf9dcd1yjMFrDt2pMC:-MTfGuYEAjJs0QPSk-ZN:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2feb8f0a8a142d7dfc764b474d2fac7da4389dc2/public/index.html#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No inline style
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 15:54 UTC, yass0016 approved these changes
> Reviewed 5 of 8 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)



<!-- Sent from Reviewable.io -->

2021-02-16 15:55 UTC, jolevesq approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-:-MTfYJ6o49BbXOoDJQ_u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-16 18:57 UTC, jolevesq requested changes
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 29 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgBvpSDSvPrcDcpRrj:-MTgBvpSDSvPrcDcpRrk:b1mfv8g) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L29)):*
> ```HTML
> <div style="text-align: left;margin: 0 auto;">
> <table cellpadding="1" cellspacing="1" style="width:1180px; margin:auto;">
> 	<tbody>
> ```

Replace tab by spaces for this line and 5 line below
___
*[public/index.html, line 36 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC334DYNVpmuAbjwX:-MTgC334DYNVpmuAbjwY:bezcxyc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L36)):*
> ```HTML
> 			<h1><strong>Plateforme Géospatiale Canadienne (PGC) / Canadian Geospatial Platform (CGP)</strong></h1>
>             <h1><strong>GeoView project</strong></h1>
> 			</td>
> ```

Replace tab
___
*[public/index.html, line 38 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC4XE3bLoAbsEQtOB:-MTgC4XE3bLoAbsEQtOC:bezcxyc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L38)):*
> ```HTML
> 			</td>
> 		</tr>
> 		<tr>
> ```

Replace tab
___
*[public/index.html, line 39 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC6jWBeooPs78pGuR:-MTgC6jWBeooPs78pGuS:bezcxyc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L39)):*
> ```HTML
> 		</tr>
> 		<tr>
> 			<td><a href="./usecases.html">Use Cases</a></td>
> ```

Replace tab


<!-- Sent from Reviewable.io -->

2021-02-16 19:58 UTC, melzeiny1980 reviewed
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 29 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgBvpSDSvPrcDcpRrj:-MTgPzGSAOekmU7LrPcf:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces for this line and 5 line below
</blockquote></details>

Done.
___
*[public/index.html, line 36 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC334DYNVpmuAbjwX:-MTgQ1O4Bk4aR0D2Oc9Y:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab
</blockquote></details>

Done.
___
*[public/index.html, line 38 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC4XE3bLoAbsEQtOB:-MTgQ0vG6XQ1DLi1yUbx:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab
</blockquote></details>

Done.
___
*[public/index.html, line 39 at r7](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79#-MTgC6jWBeooPs78pGuR:-MTgQ19k5tPp19uwtI91:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d2a7a2e6cd4c9bc045d37eab3406af94bc6aa452/public/index.html#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 20:02 UTC, jolevesq approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/79)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-16 20:02 UTC, merged